"""Appended-conversation proposals; terminology is advisory, relations authored.

Keep positions, fit, optical transmission, finish, support and viewpoint separate.
No source establishes attractiveness, identity or a measured audience effect.
"""

NEW_SPECS = [
    ("lateral_chest", "의복 옆 경계의 가슴 측면", ["사이드부브", "sideboob", "side breast exposure"],
     "outer breast contour beside the same garment arm opening", "garment_detail", ["appearance"],
     ["a bounded outer breast contour is visible beside the adult garment's arm opening",
      "the same opaque bodice covers the central breast surface and retains a continuous side edge",
      "the exposed lateral contour remains distinguishable from the upper arm and back"],
     ["central cleavage alone", "an open back without a lateral breast contour", "the upper arm beside a closed side seam", "a dark printed patch"],
     ["S19"], "측면 위치를 판별하는 좁은 설계다. 크기·노출 깊이·중앙 골·성적 반응은 독립이며, 광범위한 sideboob 사용 전체를 이 구조로 환원하지 않는다."),
    ("lower_chest", "상의 하단 경계의 가슴 하부", ["언더부브", "underboob", "lower breast edge exposure"],
     "lower breast contour beside an opaque top's lower edge", "garment_detail", ["appearance"],
     ["a bounded lower breast contour is visible below the adult top's lower edge",
      "the same opaque top covers the central breast surface with an identifiable textile hem",
      "the lower breast contour remains distinct from the abdominal surface below it"],
     ["an exposed midriff with fully covered breasts", "central cleavage", "a fold in the top hem", "a painted crescent on fabric"],
     ["S20"], "가슴 하부와 복부를 구분한다. 특정 크기·자세·젖꼭지 노출·노출 면적을 요구하지 않으며 사전 속어를 해부학의 공식 명칭으로 취급하지 않는다."),
    ("navel", "의복 사이에서 식별되는 배꼽", ["배꼽 노출", "navel-baring", "visible navel", "umbilicus"],
     "navel on abdominal skin between separate garment edges", "garment_detail", ["appearance"],
     ["the adult subject's identifiable navel is visible on continuous abdominal skin",
      "a separate upper garment hem and lower waistband leave that navel uncovered",
      "the navel remains distinguishable from a printed dot piercing or cast fabric shadow"],
     ["midriff skin with the navel covered", "a dark button on fabric", "a waist cutout away from the navel", "navel orange"],
     ["S21"], "이 좁은 프로필은 상하의 사이 배꼽 관계다. 배꼽의 돌출·함몰 정도나 아랫배 체형을 고정하지 않으며 모든 navel-baring 의상을 이 형태로 제한하지 않는다."),
    ("opaque_fit", "불투명 의복의 몸 윤곽을 따르는 핏", ["불투명 밀착 실루엣", "opaque figure-hugging silhouette", "form-fitting", "bodycon", "skin-tight", "second-skin fit"],
     "continuous opaque garment surface along the torso and hips", "wardrobe_style", ["appearance", "material"],
     ["an opaque garment closely follows the adult torso waist and hip outline",
      "continuous fabric covers those regions without transmitting underlying skin detail",
      "visible hems seams and local folds identify a textile surface separate from skin"],
     ["body paint substituted for clothing", "a sheer panel exposing skin detail", "a loose sack silhouette", "a digitally narrowed body substituted for garment fit"],
     ["S07", "S29"], "밀착과 비침의 독립성을 보여주는 선택안이다. 모든 bodycon이 불투명하거나 압박성이 강하다는 뜻이 아니며 기존 인물의 체형 변경을 지시하지 않는다."),
    ("mesh_skin", "비친 복부 피부와 연속된 망눈", ["메쉬 너머 피부", "visible mesh pattern over abdominal skin", "fine mesh", "fitted semi-sheer mesh"],
     "mesh panel over the abdomen and adjacent opaque garment coverage", "texture", ["material", "appearance"],
     ["an interconnected mesh pattern remains visible across the adult abdominal panel",
      "the abdominal skin surface remains visible through that same mesh's openings",
      "attached opaque garment panels retain continuous edges beside the mesh region"],
     ["a mesh pattern printed on opaque fabric", "an empty cutout without threads", "a smooth sheer panel without visible mesh", "a fishnet backdrop behind the subject"],
     ["S07", "S14", "S28"], "복부라는 지정 부위의 관찰 관계다. 망눈 크기·압박·소재·안감 유무·노출 부위는 독립 선택이며 모든 mesh가 피부를 비치게 한다는 뜻이 아니다."),
    ("illusion_panel", "불투명 몸판에 연결된 착시 목선 패널", ["일루전 네크라인", "illusion neckline", "illusion panel"],
     "fine net panel between upper neckline edge and opaque bodice", "garment_detail", ["appearance", "material"],
     ["a fine net panel spans between the adult garment's upper neckline edge and opaque bodice",
      "visible net threads or attached decoration identify fabric across the apparently open region",
      "the panel's lower join remains continuous with the same opaque bodice"],
     ["an empty neckline cutout", "a necklace floating above a strapless bodice", "opaque skin-tone fabric without a readable net layer", "beads painted onto bare skin"],
     ["S28"], "메쉬 기반 착시 패널의 좁은 설계다. 일부 상품의 fully lined 문구로 목선까지 불투명하다고 단정하지 않으며 실제 원단·안감 구성은 제작 정보와 구분한다."),
    ("hosiery_sheer", "피부색이 비치는 다리의 스타킹 층", ["시어 타이츠", "sheer hosiery", "sheer tights", "semi-sheer stockings"],
     "translucent hosiery surface on a continuous adult leg", "texture", ["material", "appearance"],
     ["the adult leg's skin tone remains visible through a continuous hosiery layer",
      "a readable hosiery boundary or fabric texture identifies the layer on that same leg",
      "the hosiery surface follows the connected knee calf and ankle without replacing their anatomy"],
     ["a bare leg with no hosiery evidence", "opaque tights without transmitted skin tone", "a detached extra leg", "a patterned background mistaken for leg fabric"],
     ["S23", "S27"], "투과의 가시적 결과만 요구한다. 색·광택·데니어·허벅지형 또는 허리형·고정 방식은 자동 결정하지 않는다."),
    ("hosiery_opaque", "피부 세부를 가리는 불투명 타이츠", ["불투명 타이츠", "opaque tights", "opaque hosiery"],
     "opaque hosiery covering a connected adult leg", "texture", ["material", "appearance"],
     ["opaque hosiery covers the adult leg without transmitting underlying skin detail",
      "the fabric follows the continuous knee calf and ankle contour",
      "a readable fabric boundary or surface texture distinguishes the hosiery from bare skin"],
     ["a dark bare leg", "a translucent stocking showing skin detail", "loose trousers substituted for hosiery", "a boot covering the entire declared region"],
     ["S23", "S27"], "색이 검다는 것과 불투명함은 동의어가 아니다. 픽셀에서 정확한 데니어를 요구하지 않으며 광택과 지지 방식은 독립이다."),
    ("hosiery_sheen", "스타킹 표면을 따라 이어지는 광택", ["광택 스타킹", "glossy hosiery", "high-shine tights", "wet-look finish", "soft sheen"],
     "directional highlights on hosiery following the same leg surface", "texture", ["material", "lighting"],
     ["directional highlights follow the adult leg's curved hosiery surface",
      "visible fabric evidence locates those highlights on hosiery rather than bare skin",
      "the same continuous leg contour remains readable beside the highlight bands"],
     ["oiled bare skin without hosiery", "a flat painted white stripe", "a wet pavement reflection", "a clipped white patch hiding the leg contour"],
     ["S23"], "광택 강도는 별도 선택이다. wet-look은 외관 표현이며 실제 물·젖음·특정 섬유·비침을 증명하지 않는다."),
    ("hosiery_backline", "스타킹 뒤면의 이어진 세로선", ["백심 스타킹", "back-seam stockings", "faux backseam", "knitted-in back seam"],
     "posterior decorative or constructed line on the hosiery layer", "garment_detail", ["appearance"],
     ["a posterior line follows the same adult hosiery leg from the heel region upward",
      "the line stays attached to the curved hosiery surface through the calf region",
      "visible surrounding fabric distinguishes the line from a mark on bare skin"],
     ["a tattoo on a bare calf", "a line on the front of unrelated trousers", "a background pole behind the leg", "a broken floating stripe"],
     ["S25"], "시각적인 뒤 세로선과 실제 봉제 접합은 구분한다. knitted-in 또는 faux 선도 이 관찰 관계를 구현할 수 있고 봉제 방식은 픽셀에서 확정하지 않는다."),
    ("garter_path", "벨트에서 스타킹 상단으로 이어진 지지 끈", ["가터벨트 연결", "garter belt", "suspender straps", "stocking support path"],
     "visible strap path between waist support and hosiery welt", "garment_detail", ["appearance"],
     ["a visible strap descends from the adult waist support to a stocking's upper band",
      "the strap's lower fastener visibly attaches to that same hosiery welt",
      "the belt strap and stocking retain separate continuous textile boundaries"],
     ["a thigh-high stocking with no visible strap", "an unattached hanging ribbon", "an ordinary shoulder suspender", "a tattoo mimicking a garter strap"],
     ["S27", "S06"], "한 연결 경로의 가시성만 요구한다. 숨은 접합·실제 하중·실리콘 유무는 추정하지 않고 thigh-high 길이가 가터 지지를 자동 의미하지 않는다."),
    ("thigh_skin_band", "짧은 밑단과 긴 양말 사이의 허벅지 피부 띠", ["절대영역", "絶対領域", "zettai ryōiki", "zettai ryoiki", "hem-to-stocking skin band"],
     "thigh skin between an outer hem and above-knee hosiery boundary", "garment_detail", ["appearance"],
     ["a short outer garment hem ends above the adult leg's above-knee hosiery boundary",
      "a visible band of thigh skin lies between those two garment edges on the same leg",
      "both textile edges remain identifiable beside the continuous uncovered skin band"],
     ["background space between the inner thighs", "continuous tights covering the thigh", "a knee-high sock ending below the knee", "underwear fabric substituted for the skin band"],
     ["S32"], "일본어 커뮤니티의 용례를 바탕으로 한 경계 설계다. 길이 비율·매력·현행 유행·용어의 기원을 주장하지 않으며 기존 절대공역의 다리 사이 배경 공간과 구분한다."),
    ("covered_underlayer_relief", "겉옷이 덮고 있는 기반층 가장자리의 요철", ["겉옷 위 속옷선", "visible panty line", "VPL", "covered underlayer edge relief"],
     "local relief on an opaque outer garment over an underlayer edge", "garment_detail", ["appearance", "material"],
     ["a localized edge-shaped ridge or depression reads across the adult outer garment surface",
      "continuous opaque outer fabric covers the declared underlayer edge across that relief",
      "the relief stays distinguishable from an outer seam printed stripe or ordinary drape fold"],
     ["exposed underwear fabric beyond a hem", "a transparent panel showing the underlayer itself", "the outer garment's own seam", "a printed stripe"],
     ["S30", "S33"], "VPL 가운데 불투명 겉옷 표면 요철이라는 좁은 방식이다. 사전의 through clothes는 투과 방식도 포괄할 수 있다. 픽셀만으로 안쪽 의복 종류를 확정하지 않는다."),
    ("mini_outer_leg", "짧은 치마 바깥의 연결된 다리", ["미니 치마 다리 구도", "mini hemline and outer leg silhouette", "thigh-baring", "micro-mini"],
     "outer skirt hem and connected legs below that visible hem", "subject_framing", ["appearance", "framing"],
     ["the adult skirt's outer hem ends visibly above the knee region",
      "connected legs continue below that outer hem to the declared footwear",
      "the visible skirt panel and leg contours remain readable in one coherent frame"],
     ["a long skirt with only a side slit", "a floating cropped leg", "footwear removed by the requested full-leg crop", "underwear substituted for the outer skirt panel"],
     ["S08"], "짧은 밑단의 위치와 바깥 실루엣을 조합한 설계다. micro-mini의 보편적 길이·로우앵글·속옷 보임·실제 다리 길이 증가를 강제하지 않는다.")
]

NEW_EXTRA = [
    ("v_waistband", "V자 하의 허리밴드의 연속 경계", "garment_detail", ["appearance"],
     ["two sloping waistband edges join into a visible V on the same adult lower garment", "the waistband remains a constructed textile boundary rather than a drawn abdominal line"], ["S07"]),
    ("lower_abdomen", "하의 허리선 위의 한정된 아랫배 피부", "garment_detail", ["appearance"],
     ["a bounded lower-abdominal skin region remains visible above the adult lower garment waistband", "the lower garment continues to cover the pelvic intimate region while retaining its own waistband edge"], ["S22", "S31"]),
    ("lace_welt", "스타킹 상단의 연결된 레이스 밴드", "garment_detail", ["appearance", "material"],
     ["a lace-patterned upper band joins continuously to the adult leg's hosiery layer", "open lace threads remain distinct from the underlying skin and stocking panel"], ["S27"]),
    ("plain_welt", "스타킹 상단의 단순한 직물 밴드", "garment_detail", ["appearance", "material"],
     ["a plain textile upper band joins continuously to the adult leg's hosiery layer", "the band remains distinct from a lace pattern or unattached strap"], ["S24"]),
    ("high_angle_face_clavicle", "높은 시점에 함께 보이는 얼굴과 쇄골", "composition", ["composition", "framing"],
     ["a modest downward view includes the same adult face and shoulder-clavicle region", "the garment's open neckline and connected neck remain readable beside the facial expression"], ["S08"]),
    ("low_angle_outer_silhouette", "낮은 시점의 의복 바깥 실루엣", "composition", ["composition", "framing"],
     ["a modest upward view includes the adult garment's outer silhouette and connected legs", "the composition keeps the outer hem footwear and readable face within the declared frame"], ["S08", "S26"]),
    ("supported_s_curve", "접지된 체중 이동과 완만한 S자 축", "body_pose", ["pose"],
     ["one planted adult foot supports a weight shift with the pelvis and shoulders offset", "connected knees torso and head form a restrained curved body axis without altering body proportions"], ["S08"]),
    ("torso_twist", "골반과 상체 방향의 연결된 차이", "body_orientation", ["pose"],
     ["the adult shoulder direction differs from the pelvis direction through a continuous torso turn", "the planted feet and connected neck retain plausible support and joint continuity"], ["S08"])
]

NEW_BUNDLES = [
    ("navel_face", ["navel", "face_garment"], ["navel", "face_garment"], ["an abdominal band with the navel hidden", "face removed by crop"]),
    ("opaque_curve", ["opaque_fit", "supported_s_curve"], ["opaque_fit"], ["pose used to substitute for the declared opaque fabric", "changed body proportions"]),
    ("mesh_boundary", ["mesh_skin", "illusion_panel"], ["mesh_skin", "illusion_panel"], ["an empty cutout substituted for mesh threads", "opaque bodice coverage confused with the separate abdominal mesh panel"]),
    ("hosiery_light", ["hosiery_sheer", "hosiery_sheen"], ["hosiery_sheer", "hosiery_sheen"], ["shine mistaken for optical transparency", "bare skin substituted for hosiery"]),
    ("thigh_band", ["thigh_skin_band", "lace_welt"], ["thigh_skin_band"], ["lace-top alone substituted for the skin band", "inter-thigh background gap"]),
    ("garter_line", ["garter_path", "hosiery_backline"], ["garter_path", "hosiery_backline"], ["a posterior decorative line substituted for a support strap", "unattached strap"]),
    ("mini_low_view", ["mini_outer_leg", "low_angle_outer_silhouette"], ["mini_outer_leg"], ["viewpoint substituted for garment length", "inside-garment view inferred from camera height"]),
    ("high_view_neckline", ["face_garment", "high_angle_face_clavicle"], ["face_garment", "clavicle_supraclavicular_hollow"], ["camera height treated as a guarantee of cleavage", "disconnected neck"])
]
