"""Author the bounded research pack. Writes only this documentation directory.

Examples, variants and expected relations are research drafts authored for this
project. They are not extracted quotations, independent human ratings, model
outputs or new runtime activation rules.
"""
from pathlib import Path
from datetime import datetime, timezone, timedelta
import hashlib
import json

OUT = Path(__file__).resolve().parent
SNAPSHOT = json.loads((OUT / "source-snapshot.json").read_text())
BY_ID = {r["profile"]["id"]: r for r in SNAPSHOT["profiles"]}


def dump(name, value):
    (OUT / name).write_text(json.dumps(value, ensure_ascii=False, indent=2) + "\n")


def source(ident, title, publisher, url, access, locator, facts, limits):
    return dict(id=ident, title=title, publisher=publisher, url=url,
                checked_on="2026-10-02", source_type="primary",
                access_status=access, inspected_location=locator,
                supported_facts=facts, does_not_establish=limits)


SOURCES = [
    source("mw-pilot", "Pilot: dictionary senses", "Merriam-Webster",
           "https://www.merriam-webster.com/dictionary/pilot", "definition_read",
           "noun and adjective definition sections",
           ["항공기 조종자 외에 선박 안내자, 시험적 운영, 방송의 시범 제작물, 점화용 불꽃 등의 뜻이 있다."],
           ["현재 프로젝트의 비행 단계 일치·손의 조작·가시성 조건을 보편적 사전 정의로 확정하지 않는다."]),
    source("collins-one-piece", "One-piece: clothing scope", "Collins",
           "https://www.collinsdictionary.com/us/dictionary/english/one-piece", "definition_read",
           "British/American adjective and noun definitions",
           ["의복이 분리된 상하의 대신 하나의 단위라는 형용사 뜻과 수영복을 가리키는 명사 뜻이 있다.",
            "하나의 의복 단위는 드레스만으로 제한되지 않는다."],
           ["한국어 원피스의 국어사전 뜻이나 일본어 외래어의 전체 범위를 대신 검증하지 않는다.",
            "한 장의 천으로 재단했음을 의미하지 않는다."]),
    source("mw-cowl", "Cowl: neckline and other senses", "Merriam-Webster",
           "https://www.merriam-webster.com/dictionary/cowl", "definition_read",
           "noun definition section",
           ["늘어뜨린 의복 목둘레뿐 아니라 두건·두건 달린 의복·굴뚝 덮개·기계 덮개 등의 뜻이 있다."],
           ["모든 의복 카울을 낮은 드레스 목둘레로 제한하지 않는다."]),
    source("mw-corruption", "Corruption: domain distinctions", "Merriam-Webster",
           "https://www.merriam-webster.com/dictionary/corruption", "definition_read",
           "noun senses 1a–1d; editorial definitions, not automatically collected news examples",
           ["권력자의 부정행위, 부정한 수단에 의한 유도, 원문·파일의 변질, 부패·분해 등 다른 분야의 뜻이 있다."],
           ["창작물의 인물 변화가 반드시 검은 신체 경계로 나타남을 입증하지 않는다."]),
    source("mw-sheer", "Sheer: textile sense", "Merriam-Webster",
           "https://www.merriam-webster.com/dictionary/sheer", "definition_read",
           "adjective senses",
           ["직물 맥락의 얇고 투명한 성질과, 순전한·완전한·가파른 등의 다른 뜻이 구별된다."],
           ["실제 구멍의 모양·섬유 성분·아래층·노출 수준을 결정하지 않는다."]),
    source("mw-ruche", "Ruche/ruching: trim sense", "Merriam-Webster",
           "https://www.merriam-webster.com/dictionary/ruche", "definition_read",
           "noun definition and ruching variant",
           ["주름지거나 모인 천 띠를 장식에 쓰는 뜻도 있다."],
           ["일반 용어 전체가 현재 프로필의 한 패널 안 국소 모음 구조와 일치하지는 않는다."]),
    source("faa-flight-controls", "PHAK chapter 6: flight controls", "Federal Aviation Administration",
           "https://www.faa.gov/regulationspolicies/handbooksmanuals/aviation/phak/chapter-6-flight-controls",
           "landing_page_read_pdf_unavailable", "official chapter title and linked 08_phak_ch6.pdf",
           ["공식 항공 교재에 비행 조종 장치를 다루는 장이 있다."],
           ["이 실행에서 PDF 본문은 읽지 못했다. 구체적인 체크리스트 절차나 운항 판단의 근거로 사용하지 않는다."]),
    source("flight-kuudere", "Official application release: kuudere note", "FLIGHT",
           "https://www.flight.co.jp/uploaded_files/c_news/106_detail.pdf", "primary_index_excerpt_only",
           "Japanese search-index excerpt of definition footnote; PDF text encoding damaged; browser rendering unavailable",
           ["당시 앱 설명은 차분한 외면과 좋아하는 상대 앞에서의 호의적 태도를 결합하여 설명한다."],
           ["제품의 성별·상대 관계 설정을 모든 캐릭터의 필수 조건으로 일반화하지 않는다.",
            "실용적 도움 행동을 원어의 보편적 필수 조건으로 확인하지 못했다."]),
    source("togashi-kuudere", "Tsundere attributes and language: author-hosted handout", "Junichi Togashi, Daito Bunka University",
           "https://www2.ic.daito.ac.jp/jtogashi/t09a.html", "landing_read_pdf_index_excerpt_only",
           "author's 2009 handout landing page; indexed excerpt of linked togashi2009a.pdf",
           ["저자 호스팅 자료의 발췌에서는 강한 거부 표면을 cool로 바꾸는 관련 유형으로 쿠데레를 논의한다."],
           ["PDF 전체를 확인하지 못했다. 개념의 기원·최초 사용 연도·모든 유형 분류를 확정하지 않는다.",
            "저자의 원문 변형·재배포 조건이 있어 원문 파일을 복제하지 않았다."]),
    source("kadokawa-yami", "Publisher's original synopsis using 闇堕ち", "KADOKAWA",
           "https://www.kadokawa.co.jp/product/201208000042/", "publisher_synopsis_read",
           "publisher synopsis above reader reviews, ISBN 9784829147221",
           ["공식 줄거리는 인물들이 어둠과의 싸움 중 다른 상태로 넘어가는 서사 용례를 제공한다."],
           ["한 작품의 용례이며 흑화·타락·corruption·闇堕ち 전체의 완전 번역 등가성을 확정하지 않는다.",
            "독자 리뷰는 근거로 사용하지 않았다. 작품의 학생 설정을 성인 프로필에 이식하지 않는다."]),
    source("cotton-mesh", "Mesh: open textile construction", "Cotton Incorporated / CottonWorks",
           "https://cottonworks.com/encyclopedia-item/mesh/", "article_read",
           "mesh encyclopedia entry",
           ["메시는 실 또는 루프 사이에 열린 공간이 있는 직물 구조로 설명된다."],
           ["튤의 특정 셀 형태나 모든 메시의 규칙성·투명도·섬유 성분을 결정하지 않는다."]),
    source("va-corset", "Corsets, crinolines and bustles", "Victoria and Albert Museum",
           "https://www.vam.ac.uk/articles/corsets-crinolines-and-bustles-fashionable-victorian-underwear",
           "article_read", "inserted busk, loop-and-stud fastening and split busk historical sections",
           ["내부에 넣는 버스크와, 앞에서 고리·돌기를 맞물려 여닫는 분할 버스크의 역사적 사례가 구별된다.",
            "앞면 잠금과 뒤쪽 끈 여밈을 함께 가진 변형이 있다."],
           ["모든 코르셋에 같은 앞면 잠금이 있거나 외관만으로 보정 기능을 확인할 수 있다는 뜻이 아니다."]),
    source("seamwork-gathering", "Gathering: author's construction tutorial", "Seamwork / Colette Media",
           "https://www.seamwork.com/sewing-tutorials/gathering", "article_and_primary_index_read",
           "introductory gathering explanation and indexed tutorial text",
           ["천을 모아 봉제선 부근에 여유와 작은 주름을 만드는 제작 용례가 있다."],
           ["모든 구김을 루싱으로 분류하거나 한 가지 제작 방식만 필수로 정하지 않는다."]),
    source("seamwork-shirring", "A Guide to Shirring", "Katie Whittle / Seamwork",
           "https://www.seamwork.com/sewing-tutorials/a-guide-to-elastic-shirring", "article_read_reference_viewed",
           "2017 tutorial, machine shirring vs smocking section, three blue swatches in page header",
           ["이 튜토리얼의 기계 셔링은 여러 봉제 줄과 탄성 밑실을 사용해 천을 모은다.",
            "스모킹의 장식 자수와 이 기계 셔링 방식은 구별된다."],
           ["외관만으로 탄성 실을 확정할 수 없다. 특정 줄 간격을 모든 루싱의 기준으로 이식하지 않는다."]),
    source("met-cowl", "Elizabeth Hawes evening dress, ca. 1935", "The Metropolitan Museum of Art",
           "https://www.metmuseum.org/art/collection/search/155680", "catalog_read_reference_viewed",
           "object 2009.300.1011a,b, catalog description and normal page image",
           ["소장품 설명은 비대칭의 스카프 같은 카울 목둘레를 명시한다."],
           ["스카프 같은 외관 자체가 별도 스카프라는 뜻은 아니다. 보이지 않는 재단·내부 부착은 사진으로 확정하지 않는다.",
            "이 페이지의 이미지는 확대·다운로드 제한이 명시되어 있다. 이미지 파일을 수집하거나 재게시하지 않았다."]),
    source("met-wrap", "Chuquibamba wrap, 14th–early 16th century", "The Metropolitan Museum of Art",
           "https://www.metmuseum.org/art/collection/search/317736", "catalog_read_image_not_inspected",
           "catalog description of rectangular cloth pinned at one shoulder and belted",
           ["한쪽 어깨에 고정하는 직사각형 감싸기 의복의 특정 역사적 착용 용례가 있다."],
           ["착용 중인 지지 경로를 실제 사진에서 확인한 것이 아니다. 역사적 무늬·문화·소재는 현대 디자인의 필수 요소가 아니다.",
            "해당 페이지는 이미지를 public domain으로 표시했지만 이번 작업은 이미지 파일을 수집하지 않았다."]),
    source("schneider-split", "Split Diopter GEN2 fact sheet", "Schneider-Kreuznach",
           "https://schneiderkreuznach.com/application/files/5717/0142/0920/Fact_Sheet_Diopter_Split_GEN2_Schneider-Kreuznach.pdf",
           "pdf_text_read", "two-page manufacturer fact sheet",
           ["반쪽 광학 요소가 전경 쪽 초점을 바꾸고 나머지 영역에서 배경 초점을 유지하여 두 초점 면을 다루는 제품이다."],
           ["화면 중앙의 흐린 띠가 모든 사용에서 반드시 눈에 띄어야 하는 것은 아니다.",
            "완성 이미지의 두 선명 구역만으로 실제 렌즈 사용이나 단일 촬영을 확정하지 않는다."]),
    source("kodak-halation", "Essential Reference Guide for Filmmakers", "Eastman Kodak",
           "https://www.kodak.com/content/products-brochures/Film/kodak-essential-reference-guide-for-filmmakers.pdf",
           "relevant_pdf_text_read", "PDF page index 32, emulsion/base reflection and antihalation explanation",
           ["필름 내부 반사에 의한 추가 노출이 밝은 대상 주변에 생기며 반할레이션 층은 이를 줄인다."],
           ["모든 할레이션이 붉은색·특정 폭·동일 강도라는 결론은 지지하지 않는다.",
            "비슷한 외관의 디지털 효과를 실제 필름으로 촬영했다고 판정할 근거가 아니다."]),
    source("profoto-face-light", "John Russo reveals his character portrait lighting secrets", "Profoto / Clare Gillsäter with John Russo",
           "https://www.profoto.com/lv/en/still-photography/profoto-stories/character-portraits-with-john-russo-and-profoto-d2",
           "primary_index_article_text_read", "Patterns of light and Classic covers sections, original 2018 article",
           ["쇼트는 카메라에 가까운 얼굴 면이 주로 그림자이고 먼 면이 주광을 받는 관계로 설명된다.",
            "브로드는 카메라 쪽으로 향한 면이 주로 밝은 관계로 설명된다."],
           ["고정된 화면 왼쪽·오른쪽만으로 종류를 정하지 않는다. 미적 평가나 실제 성격 추론은 채택하지 않는다.",
            "일반 페이지 직접 열기는 시간 초과였고 검색 색인의 원문 텍스트를 확인했다. 사진은 직접 관찰하지 않았다."]),
    source("nikon-broad", "Photography glossary: broad lighting", "Nikon",
           "https://www.nikonusa.com/learn-and-explore/photography-glossary", "primary_index_definition_read",
           "Broad Lighting indexed glossary entry; direct response did not expose this term",
           ["브로드 조명은 카메라를 향한 얼굴 면에 주광을 두는 뜻으로 설명된다."],
           ["검색 발췌로 확인했으며 전체 글로서리 탐색 결과가 아니다. 쇼트 조명의 정의 근거로 사용하지 않는다."]),
]


def pair(ko, en):
    return {"ko": ko, "en": en}


def invariant(ident, owner, relation, basis="project_selected_scope"):
    return dict(id=ident, owner=owner, relation=relation, basis=basis)


def variant(ident, ko, en, status="authored_scope_preserving_draft"):
    return dict(id=ident, description=pair(ko, en), status=status,
                verification="not independently reviewed or image tested")


def case(ko, en, relation, why):
    return dict(request=pair(ko, en), semantic_relation=relation, rationale_ko=why)


def card(ident, family, profiles, title, meaning, scope, source_ids, invariant_rows,
         short, detailed, variants, positives, negatives, limits, gaps):
    assert len(variants) == len(positives) == len(negatives) == 3
    return dict(id=ident, family=family, profile_ids=profiles, title_ko=title,
                research_status="authored_draft_not_runtime_applied",
                contextual_meaning=meaning, selected_scope_ko=scope,
                source_ids=source_ids, invariants=invariant_rows,
                neutral_descriptions={"short": short, "detailed": detailed},
                variants=variants, positive_contexts=positives,
                contrast_contexts=negatives, claim_limits_ko=limits,
                remaining_evidence_gaps_ko=gaps)


CARDS = [
    card("pilot-aircraft", "pilot", ["aircraft_pilot_operation"], "항공 운항 중의 조종자",
         pair("항공기 문맥의 pilot는 비행 조종자다. 방송·시험 운영·선박·점화 불꽃 문맥과 구별한다.",
              "In an aircraft context, pilot denotes a flight operator; television, trial-operation, ship and ignition senses differ."),
         "현재 프로필은 일반 직업 사진보다 좁은, 조종석·손의 조작 또는 점검·비행 단계의 관계가 보이는 성인 장면이다.",
         ["mw-pilot", "faa-flight-controls"],
         [invariant("operator", "adult operator", "occupies the aircraft pilot station"),
          invariant("control", "same operator's hand", "contacts flight controls or follows a cockpit checklist"),
          invariant("phase", "instruments and outside view", "agree with the explicitly requested operation phase")],
         pair("성인이 항공기 조종석에서 체크리스트를 짚으며 계기와 창밖 상태를 확인한다. 두 상태는 요청한 비행 단계와 맞는다.",
              "An adult at the aircraft controls follows a checklist and checks the instruments against the outside view, with both agreeing with the requested flight phase."),
         pair("성인 조종자가 항공기의 조종사 좌석에 앉아 있다. 손가락은 조종석 체크리스트의 한 항목을 따라가거나 주 조종 장치에 닿는다. 보이는 계기와 창밖 기준물은 사용자가 지정한 운항 단계와 서로 모순되지 않는다. 좌석, 손, 계기, 창밖이 한 장면 안에서 읽힌다.",
              "An adult occupies the aircraft's control station. A finger follows a cockpit checklist item or a hand contacts a primary control. The visible instruments and outside anchors consistently depict the operation phase named in the request. The station, hand, instruments and outside view remain legible in one scene."),
         [variant("preflight", "정지된 항공기에서 비행 전 점검을 하는 장면. 손·계기·외부 정지 상태를 함께 보인다.", "A preflight check in a stationary aircraft, with hand, instruments and stationary outside state visible."),
          variant("taxi", "지상 이동 문맥에서 조종 장치와 외부 지상 경로를 함께 읽을 수 있는 장면.", "A taxi-context scene with readable control contact and outside ground route."),
          variant("airborne", "비행 중 문맥에서 조종자·계기·창밖 수평선의 일관성을 보이는 장면.", "An airborne-context scene showing consistent operator, instrument and outside horizon relationships.")],
         [case("비행 전 점검 중인 성인 파일럿을 조종석 안에서 보여줘. 체크리스트를 짚는 손과 계기, 정지된 외부 상태가 함께 보여야 해.", "Show an adult pilot performing a preflight check, with a hand following the cockpit checklist, instruments and the stationary outside view all visible.", "matches_selected_scope", "항공기·점검·정지 상태가 같은 운항 문맥을 이룬다."),
          case("택시 중인 항공기 조종석의 성인 조종자와 조작 중인 손, 계기, 외부 지상 경로를 일관되게 보여줘.", "Show an adult at the controls of a taxiing aircraft, with control contact, instruments and the outside ground route in agreement.", "matches_selected_scope", "정복만이 아니라 운항 관계가 명시된다."),
          case("성인이 비행 중 항공기의 조종간을 잡고 계기와 창밖 수평선을 교차 확인하는 모습을 담아줘.", "Depict an adult holding an aircraft control and cross-checking the instruments against the outside horizon during flight.", "matches_selected_scope", "라벨 없이 조종자와 장치·외부 상태 관계를 요구한다.")],
         [case("새 드라마의 pilot episode 촬영 현장을 보여줘.", "Show the set where a new television pilot episode is being filmed.", "different_sense", "방송 시범 제작물이며 항공 조종자가 아니다."),
          case("가스 기기의 작은 pilot light를 접사로 찍어줘.", "Make a close-up of a gas appliance's small pilot light.", "different_sense", "점화 불꽃 의미다."),
          case("공항 카페에서 쉬는 파일럿의 인물 사진을 만들어줘.", "Create a portrait of a pilot resting in an airport cafe.", "outside_selected_scope", "직업 의미는 맞지만 현재의 운항 중 관계를 요청하지 않는다.")],
         ["운항 장면의 가시 조건과 일반적인 직업 정의를 구별한다.", "항공기 종류별 장치·계기 내용은 별도 전문 자료가 필요하다. 이 데이터는 운항 절차 안내가 아니다."],
         ["실제 기종·단계별 참고 장면과 장치의 일관성은 아직 항공 전문가가 확인하지 않았다."]),

    card("dress-one-unit", "one_piece", ["one_piece_dress_construction"], "한 벌로 이어진 드레스",
         pair("이 프로젝트에서 원피스는 상체 부분과 치마 부분이 한 벌인 드레스다. 영어 one-piece는 의복 일반과 수영복까지 더 넓게 쓰인다.",
              "This project selects a dress whose bodice and skirt form one garment. English one-piece has a wider clothing scope, including swimsuits."),
         "드레스의 연속 단위를 선택한다. 한 장의 천, 바지 다리가 있는 의복, 수영복, 작품명은 현재 선택 범위와 다르다.",
         ["collins-one-piece"],
         [invariant("unit", "bodice and skirt", "form one garment from neckline to hem"),
          invariant("silhouette", "same garment", "has a dress lower outline rather than separate trouser legs"),
          invariant("construction", "seams, closure and drape", "belong to and articulate that same garment")],
         pair("상체 부분과 치마 부분이 하나의 옷으로 이어지며, 목둘레부터 밑단까지 연속된 윤곽 안에 봉제선과 여밈이 보인다.",
              "The bodice and skirt form one garment, with seams and a closure inside a continuous outline from neckline to hem."),
         pair("목둘레에서 상체를 지나 치마 밑단까지 한 벌로 이어진 의복을 보여준다. 허리 절개선이나 여러 패널이 있어도 위와 아래는 서로 분리된 옷이 아니다. 봉제선, 겹치는 여밈, 천의 낙하가 같은 드레스의 구조로 읽히며 하부에는 별도의 바지 다리가 없다.",
              "Show one garment continuing from neckline through bodice to skirt hem. A waist seam or multiple panels may be present while upper and lower parts remain one dress. Seams, overlapping closure and fabric drape read as its construction, and the lower section does not divide into trouser legs."),
         [variant("waist-seam", "허리 절개가 있는 A라인 한 벌 드레스.", "An A-line dress with a waist seam that remains one garment."),
          variant("wrap", "여밈이 겹쳐지는 한 벌의 랩 형태 드레스.", "A one-garment dress with an overlapping wrap closure."),
          variant("shirt", "앞 중심의 단추가 목둘레부터 치마 쪽까지 이어지는 셔츠 형태 드레스.", "A shirt-shaped dress with a center-front button closure continuing toward the skirt.")],
         [case("허리 절개가 있지만 상체와 스커트가 한 벌로 이어지는 A라인 원피스를 보여줘.", "Show an A-line dress with a waist seam whose bodice and skirt remain one garment.", "matches_selected_scope", "봉제선은 분리된 옷을 뜻하지 않는다."),
          case("한 벌로 연결된 랩 드레스의 겹치는 여밈과 밑단을 함께 보여줘.", "Show the overlap closure and hem of a wrap dress constructed as one garment.", "matches_selected_scope", "겹침 여밈과 한 벌 구조가 공존한다."),
          case("목둘레부터 치마 밑단까지 이어지는 셔츠 형태 의복을 전체 길이로 찍어줘.", "Photograph a shirt-shaped garment continuously from neckline to skirt hem at full length.", "matches_selected_scope", "라벨 대신 연속성과 드레스 하부 형태를 명시한다.")],
         [case("one-piece swimsuit의 앞뒤 상품 사진을 만들어줘.", "Create front and back product views of a one-piece swimsuit.", "outside_selected_scope", "영어 의복 뜻으로는 맞지만 선택한 드레스 변형과 다르다."),
          case("원피스처럼 색이 맞는 블라우스와 스커트 두 벌을 찍어줘.", "Photograph a matching blouse and skirt that remain two separate garments.", "contradicts_required_relation", "같은 색은 한 벌 구조를 대신하지 않는다."),
          case("ONE PIECE라는 작품의 책 표지를 자료로 찾아줘.", "Find reference information for a book cover from the work titled ONE PIECE.", "different_sense", "작품명이지 의복 구조가 아니다. 실제 표지 생성 요청이나 반영을 수행하지 않는다.")],
         ["한 벌이라는 말은 한 장의 천이나 무봉제라는 뜻이 아니다.", "한국어 단어 범위는 현재 프로젝트의 드레스 문맥으로 한정하였다. 국립국어원 개별 항목의 직접 확인은 완료하지 못했다."],
         ["한국어·일본어 외래어 사전의 직접 교차 확인과 언어 전문가 검토가 필요하다."]),

    card("character-transition", "corruption", ["embodied_corruption_transition"], "몸 위에 변화 경계가 남는 인물 전환",
         pair("창작물의 어두운 상태로 넘어가는 인물 변화 문맥을 다룬다. 부정부패, 파일 손상, 우아하고 어두운 분위기와 구별한다.",
              "This concerns a fictional character changing into a darker state, distinct from institutional corruption, damaged files or a dark aesthetic."),
         "현재 프로필은 옛 상태와 아직 끝나지 않은 변화 경계가 몸 위에서 함께 보이는 시각적 변형이다. 도덕적·서사적 변화 일반보다 좁다.",
         ["mw-corruption", "kadokawa-yami"],
         [invariant("former", "same adult fictional character", "retains readable markers of the earlier state"),
          invariant("boundary", "same character's body surface", "carries an unfinished advancing boundary between former and darkened regions")],
         pair("성인 창작 인물의 몸 표면에서 짙어진 영역과 이전 모습 사이의 변화 경계가 아직 남아 있고, 옛 복장이나 상징도 함께 읽힌다.",
              "An adult fictional character retains an unfinished boundary between darkened and former body-surface regions while the earlier costume or emblem remains readable."),
         pair("한 성인 창작 인물의 같은 몸에서 이전 상태와 짙게 변한 영역이 나란히 보인다. 변화의 가장자리는 팔이나 몸 표면에서 멈춰 있어 완료되지 않은 전환으로 읽힌다. 옛 복장 또는 상징이 남아 이전 상태를 식별할 수 있고, 변한 영역과 그대로인 영역의 경계가 이어진다.",
              "The same adult fictional character shows both an earlier state and a darkened body-surface region. The advancing edge stops visibly on an arm or body surface, making the transition unfinished. An earlier costume or emblem remains identifiable, alongside the continuing boundary between changed and unchanged regions."),
         [variant("wrist-stop", "손목에서 멈춘 짙은 표면 변화와 옛 소매 상징.", "A darkened surface change stopping at the wrist beside an earlier sleeve emblem."),
          variant("arm-spread", "팔 일부를 따라 번지는 변화와 아직 그대로인 몸 영역.", "A change advancing along part of an arm beside a body region that retains the earlier state."),
          variant("emblem-choice", "몸 위의 미완료 변화가 남은 채 옛 배지를 놓으려는 장면.", "An unfinished on-body transition remains visible while the character prepares to release an earlier badge.")],
         [case("성인 주인공의 표면 변화가 손목에서 멈추고 옛 제복 상징은 남아 있는 전환 장면을 보여줘.", "Show an adult protagonist whose body-surface transition stops at the wrist while the old uniform emblem remains.", "matches_selected_scope", "몸 위 경계와 옛 상태가 공존한다."),
          case("성인 창작 인물의 팔 일부만 짙게 변하고 나머지는 이전 상태인 순간을 담아줘.", "Depict an adult fictional character with a partly darkened arm and the rest still in its earlier state.", "matches_selected_scope", "미완료 경계가 같은 인물에 있다."),
          case("흑화가 끝나지 않은 성인이 몸 위 변화 경계를 드러낸 채 옛 배지를 내려놓으려는 장면을 원해.", "I want an adult with an unfinished on-body darkening boundary preparing to put down the old badge.", "matches_selected_scope", "선택 행동은 경계를 대체하지 않고 추가된다.")],
         [case("손상된 파일의 corruption 오류 메시지 화면을 보여줘.", "Show a file-corruption error message on a screen.", "different_sense", "파일 변질의 뜻이다."),
          case("정부 corruption을 주제로 한 비폭력 풍자 일러스트를 원해.", "I want a nonviolent editorial illustration about government corruption.", "different_sense", "정치적 부정행위다."),
          case("이제 어두운 조직에 가담한 인물이 검은 새 옷을 입은 모습을 보여줘. 몸의 변화는 없어.", "Show a character who has joined a darker faction wearing a new black outfit, with no body transformation.", "outside_selected_scope", "서사적 변화로는 가능하지만 현재의 몸 위 경계 변형은 요구하지 않는다.")],
         ["타락·흑화·corruption·闇堕ち를 모든 문맥에서 완전 동의어로 묶지 않는다.", "검은 옷이나 어두운 색조만으로 인물 전환의 경계를 대신하지 않는다."],
         ["다른 창작 매체의 성인 인물 용례와 변화가 없는 서사 변형을 더 수집할 필요가 있다."]),

    card("reserved-help", "kuudere", ["kuudere_composed_warmth_relation"], "절제된 표면과 특정 상대를 향한 작은 도움",
         pair("일본어 캐릭터 용례에서 차분한 외면과 상대를 향한 호의가 결합된다. 실제 사람의 성격이나 감정을 표정으로 진단하는 범주가 아니다.",
              "Japanese fictional-character usage combines a cool surface with affiliation toward another person. It is not a diagnosis of a real person's personality from facial appearance."),
         "현재 프로젝트는 성인 인물의 차분한 기준선, 특정 성인 상대, 조용한 실용적 도움, 작은 표정 완화, 같은 상대의 가시적 이득을 모두 요구한다. 도움 행동은 구체화 방식이다.",
         ["flight-kuudere", "togashi-kuudere"],
         [invariant("baseline", "adult fictional character", "retains a composed low-expression baseline"),
          invariant("target", "same identifiable adult counterpart", "is the target of understated practical help"),
          invariant("warmth", "helper's face", "shows one localized softening while remaining composed"),
          invariant("consequence", "same counterpart", "visibly benefits from that practical help")],
         pair("차분하고 표정 변화가 적은 성인 인물이 특정 성인 동료에게 필요한 도구를 조용히 건넨다. 그 동료가 작업을 재개할 때 인물의 입매만 조금 풀린다.",
              "A composed adult with little facial movement quietly hands a needed tool to one specific adult companion. The companion resumes the task as only the helper's mouth corners soften slightly."),
         pair("두 성인 중 한 인물은 안정된 자세와 거의 변하지 않는 표정을 유지한다. 그 인물이 한 명의 신뢰하는 동료에게 필요한 도구를 먼저 건네고, 같은 동료가 그 도구로 작업을 다시 시작한다. 도움을 준 인물은 차분한 기준선을 유지한 채 입가나 눈가 한 곳만 작게 부드러워진다. 도움의 대상과 결과가 같은 동료에게 이어진다.",
              "Of two adults, one maintains a stable posture and a low-expression face. That character quietly supplies a needed tool to one trusted companion, who uses it to resume the task. The helper remains composed while one small area around the mouth or eyes softens. The target and visible consequence of the help belong to that same companion."),
         [variant("tool", "필요한 도구를 건네고 같은 동료가 작업을 재개할 때 입가만 완화.", "A needed tool is supplied; the same companion resumes work as the helper's mouth softens."),
          variant("dry-cloth", "젖은 책상에 수건을 건네 동료가 작업 공간을 회복할 때 눈가만 완화.", "A cloth helps the companion restore a wet workspace as only the helper's eyes soften."),
          variant("steady-box", "동료가 든 상자를 잠깐 받쳐 동료가 문을 열 수 있게 하며 입가만 완화.", "The helper steadies a companion's box, allowing that person to open a door, with a slight mouth softening.")],
         [case("성인 쿠데레가 말없이 필요한 공구를 건네고, 같은 성인 동료가 작업을 재개할 때 입가만 조금 풀리는 장면을 보여줘.", "Show an adult kuudere quietly handing over a needed tool and slightly softening the mouth as the same adult companion resumes work.", "matches_selected_scope", "표면·대상·행동·작은 변화·같은 대상의 이득이 연결된다."),
          case("담담한 성인이 젖은 책상의 수건을 성인 동료에게 건네고 그 동료가 작업 공간을 되찾는 동안 눈가만 부드러워지게 해줘.", "Have a reserved adult pass a cloth to an adult companion at a wet desk, softening only the eyes as that companion restores the workspace.", "matches_selected_scope", "큰 표정 전환 없이 도움의 결과가 보인다."),
          case("성인이 성인 동료의 상자를 조용히 받쳐 문을 열 수 있게 도와줘. 동료가 문을 열 때 돕는 사람은 침착한 표정을 유지하며 입가만 살짝 풀려.", "An adult quietly steadies an adult companion's box so that companion can open a door; the helper stays composed with only a slight softening of the mouth.", "matches_selected_scope", "한 문장 안에서 행동의 소유자와 결과의 대상이 일치한다.")],
         [case("표정 없는 성인 인물을 혼자 정면으로 찍어줘.", "Photograph an expressionless adult alone, facing the camera.", "insufficient_evidence", "무표정만으로 특정 상대에게 향한 호의를 읽을 수 없다."),
          case("모든 고객에게 똑같이 도구를 건네는 차분한 직원의 모습을 보여줘.", "Show a composed employee handing tools to every customer in exactly the same manner.", "insufficient_evidence", "직무 서비스만으로 선택적 관계의 뜻을 확정하지 않는다."),
          case("상대에게 큰 소리로 거절하다가 얼굴 전체가 밝아져 크게 웃는 성인 캐릭터를 보여줘.", "Show an adult character who loudly rejects another person and then changes into a broad full-face smile.", "outside_selected_scope", "큰 반전과 넓은 표정 변화는 이 절제된 기준선 변형과 다르다.")],
         ["실용적 도움을 모든 원어 용례의 필수 조건으로 일반화하지 않는다.", "도움을 준 사람, 도움을 받은 사람, 작은 변화와 결과를 구별한다. 실존 인물의 감정·성격·동의는 외관만으로 확정하지 않는다."],
         ["두 원어 1차 자료의 PDF 전체·정확한 발췌 위치를 직접 확인해야 한다.", "독립적인 원어 전문가의 검토와 라벨 없는 장면 식별 평가는 아직 없다."]),

    card("cowl-draped-opening", "cowl", ["pfe_cowl", "clothing_ct037_v1"], "같은 옷의 목둘레에 처지는 천",
         pair("의복 목둘레의 느슨한 드레이프 뜻을 선택한다. 두건과 기계 덮개의 뜻, 올라온 두꺼운 칼라 변형은 구별한다.",
              "The selected sense is a loosely draped garment neckline, distinguished from a hood, a machinery cover and an upright thick collar variant."),
         "두 프로필의 공통 드레이프 뜻을 연결한다. pfe_cowl은 부착점·같은 목둘레의 연속성·겹 그림자를 더 상세히 요구한다.",
         ["mw-cowl", "met-cowl"],
         [invariant("attachment", "neckline fabric", "hangs between attachment points of the same garment opening"),
          invariant("edge", "folded opening edge", "continues into that garment rather than a separate accessory"),
          invariant("depth", "fabric folds", "show hanging depth and overlap/contact shadows")],
         pair("같은 옷의 목둘레 부착점 사이에서 천이 느슨하게 처진다. 접힌 가장자리는 그 목둘레에 이어지고, 겹친 주름 아래에 그림자가 남는다.",
              "Fabric hangs loosely between attachment points of the same garment opening. Its folded edge continues into that neckline, with overlap shadows under the hanging folds."),
         pair("상의의 목둘레 가장자리를 따라가면 양쪽 부착점 사이의 여분 천이 아래로 처지는 모습을 볼 수 있다. 곡선으로 접힌 가장자리는 별도 장신구가 아니라 같은 옷의 연속된 천이다. 겹의 깊이와 주름 아래 그림자가 천의 표면과 아래층을 구별한다. 대칭 여부와 처짐의 깊이는 요청에서 정한다.",
              "Following the top's neckline reveals surplus fabric hanging between its attachment points. The curved folded edge belongs to the same continuous garment, rather than an independent accessory. Fold depth and shadows distinguish fabric from the underlying layer. Symmetry and drape depth follow the request."),
         [variant("shallow", "얕고 느슨한 목둘레 처짐. 같은 옷과의 연결과 겹 그림자를 유지.", "A shallow loose drape with continuous garment attachment and fold shadows."),
          variant("deep", "깊은 여러 겹의 처짐. 겹 수와 폭은 선택 값이며 연결 구조를 유지.", "A deeper multi-fold drape; count and width vary while attachment remains."),
          variant("asymmetric", "한쪽으로 치우친 스카프 같은 처짐. 같은 목둘레에 속함을 확인.", "An off-center scarf-like drape that still belongs to the same neckline.")],
         [case("카울넥의 천이 같은 목둘레 양쪽에서 느슨하게 처지고 접힌 겹 아래 그림자가 보이게 해줘.", "Show cowl-neck fabric hanging loosely from both sides of the same neckline, with shadows beneath its folds.", "matches_selected_scope", "이름과 부착·연속·깊이 관계를 함께 요구한다."),
          case("별도 스카프 없이 같은 상의 목둘레의 천이 한쪽으로 비대칭 처지는 모습을 원해.", "I want an asymmetrical drape made from the same top's neckline fabric, with visible folds and no independent scarf.", "matches_selected_scope", "비대칭도 같은 옷에 속하면 가능한 변형이다."),
          case("목둘레 사이로 얕게 늘어진 천의 곡선 가장자리와 겹 그림자를 가까이 보여줘.", "Show the curved edge and overlap shadows of fabric hanging shallowly between neckline attachment points.", "matches_selected_scope", "이름 없이 같은 구조를 지시한다.")],
         [case("평평한 목둘레 위에 독립된 스카프를 둘러줘.", "Place an independent scarf over a flat neckline.", "contradicts_required_relation", "같은 의복 목둘레의 연속된 천이 아니다."),
          case("수도사의 cowl hood를 자료로 설명해줘.", "Explain a monk's cowl hood as a reference concept.", "different_sense", "두건 뜻이며 드레이프된 목둘레 뜻과 다르다."),
          case("목 위로 올라오는 두꺼운 니트 카울 칼라를 보여줘.", "Show a thick knitted cowl collar rising around the neck.", "outside_selected_scope", "틀린 카울이 아니라 현재 낮게 처지는 목둘레와 다른 변형이다.")],
         ["스카프 같은 형태와 실제 별도 스카프를 단어만으로 구별하지 않는다.", "접힌 외관만으로 바이어스 재단이나 내부 봉제 방식을 확정하지 않는다."],
         ["서로 다른 각도에서 같은 목둘레 연결을 확인하는 추가 참고 이미지가 필요하다."]),

    card("single-shoulder-support", "one_shoulder", ["pfe_one_shoulder"], "한 어깨를 지나는 지지 구조",
         pair("한쪽 어깨에서 지지되는 의복 목둘레 구조다. 단순한 비대칭, 끈 하나, 양쪽 어깨 아래 목둘레와 동의어가 아니다.",
              "This is a neckline supported over one shoulder, not a synonym for any asymmetry, one strap or a neckline below both shoulders."),
         "성인 의복의 한 어깨 지지, 반대 어깨와 비대칭 경계, 같은 옷의 연속된 연결을 선택한다.",
         ["met-wrap"],
         [invariant("support", "same garment", "is supported over one adult shoulder"),
          invariant("opposite", "opposite shoulder", "lies outside that same asymmetrical neckline"),
          invariant("continuity", "diagonal neckline edge", "connects continuously to the declared support")],
         pair("같은 상의는 한쪽 어깨 위에서 지지되고 반대 어깨는 목둘레 경계 밖에 있다. 비스듬한 가장자리가 그 지지점으로 연속해서 이어진다.",
              "The same top is supported over one shoulder while the opposite shoulder lies outside its neckline. A diagonal edge continues into that support."),
         pair("성인 상의의 지지 경로는 한쪽 어깨 위를 지나 같은 몸판으로 이어진다. 반대 어깨는 그 비대칭 목둘레 바깥에 남는다. 목둘레의 비스듬한 천 가장자리와 어깨의 연결이 함께 읽힌다. 어깨 위의 지지 천이 갈라지더라도 모든 지지 조각은 같은 한쪽 어깨와 몸판에 이어진다.",
              "The adult top's support passes over one shoulder and continues into the same bodice. The opposite shoulder remains outside its asymmetrical opening. The diagonal fabric edge and shoulder connection are readable together. If the support divides into narrow pieces, they all continue over that same shoulder into the same bodice."),
         [variant("wide-band", "한쪽 어깨 위의 넓은 천 지지와 비스듬한 목둘레.", "A wide fabric support on one shoulder with a diagonal neckline."),
          variant("single-side-straps", "여러 가는 끈이 모두 같은 한쪽 어깨를 지지하는 구조.", "Several narrow supports all passing over the same one shoulder."),
          variant("pinned-wrap", "같은 감싸기 천이 한쪽 어깨에서 고정되는 연결.", "The same wrap fabric fastened at one shoulder.")],
         [case("성인 원숄더 상의의 한쪽 어깨 지지와 반대쪽 목둘레 경계를 함께 보여줘.", "Show an adult one-shoulder top's supported shoulder and opposite neckline boundary together.", "matches_selected_scope", "한 어깨의 지지와 동일 목둘레의 관계다."),
          case("가는 끈 두 개가 모두 오른쪽 한 어깨에 이어지고 왼쪽은 같은 목둘레 밖에 있는 상의를 원해.", "I want a top with two thin supports both over the right shoulder and the left shoulder outside the same neckline.", "matches_selected_scope", "끈 개수가 아니라 지지하는 어깨를 센다."),
          case("천이 한 어깨에 고정되고 반대쪽으로 비스듬히 이어지는 성인 의복을 보여줘.", "Show an adult garment fastened over one shoulder with a fabric edge continuing diagonally toward the opposite side.", "matches_selected_scope", "라벨 없이 부착 구조를 기술한다.")],
         [case("양쪽 어깨 아래로 목둘레가 내려오는 상의를 보여줘.", "Show a top whose neckline sits below both shoulders.", "contradicts_required_relation", "두 어깨 바깥 구조이며 한 어깨 위 지지가 없다."),
          case("한쪽 끈은 머리카락에 가려진 두 끈 상의를 원해.", "I want a two-strap top with one strap hidden by hair.", "contradicts_required_relation", "숨겨진 양쪽 지지를 한 어깨 지지로 바꾸지 않는다."),
          case("대칭 상의 위로 머리만 한쪽에 늘어뜨려 비대칭으로 보여줘.", "Make a symmetric top look asymmetrical by draping hair to one side.", "insufficient_evidence", "머리카락의 비대칭은 의복 지지 구조를 증명하지 않는다.")],
         ["한쪽 어깨 구조는 성별·체형·매력의 주장과 별개다.", "가려진 지지점을 실제로 확인했다고 기록하지 않는다. 역사적 용례의 소재·문양을 일반 요구로 옮기지 않는다."],
         ["현대 제작자의 앞뒤 도해와 다양한 한 어깨 지지 방식의 확인이 필요하다."]),

    card("local-gathered-folds", "ruching", ["pfe_ruching"], "선택 위치로 모이는 국소 천 주름",
         pair("여분 천을 모아 주름을 만드는 의복 문맥이다. 일반 구김·플리츠·셔링 제작 방식·장식 띠와 범위가 겹치지만 모두 같은 것은 아니다.",
              "This garment context concerns gathered surplus fabric; ordinary wrinkles, pleats, elastic shirring and ruched trim overlap in scope without being identical."),
         "현재 프로필은 한 성인 의복 패널의 지정 봉제선 또는 고정점으로 모이는 작은 반복 주름과 주변 천의 연속성을 선택한다.",
         ["mw-ruche", "seamwork-gathering", "seamwork-shirring"],
         [invariant("convergence", "small repeated fabric folds", "converge at the requested seam or attachment"),
          invariant("owner", "gathered region", "stays within the same garment panel"),
          invariant("surround", "surrounding fabric", "continues through the gathered region")],
         pair("같은 옷 패널의 지정 봉제선으로 작은 천 주름들이 반복해 모인다. 모인 부분과 주변의 비교적 평평한 천이 끊기지 않고 이어진다.",
              "Small repeated folds in the same garment panel converge at the requested seam. The gathered area continues into the surrounding, flatter fabric."),
         pair("요청한 패널 위치의 고정선으로 여분 천이 모여 작은 주름을 반복해서 만든다. 주름들은 그 선이나 부착점을 향하고, 주위의 덜 모인 천까지 같은 패널로 연속된다. 반복되는 작은 주름 마루와 골의 그림자가 모임의 위치와 방향을 읽을 수 있게 한다.",
              "Surplus fabric forms repeated small folds toward a fixed line at the requested panel position. The folds converge on that seam or attachment and continue into less-gathered fabric in the same panel. Small repeating fold ridges and valley shadows make the location and direction of gathering readable."),
         [variant("side-seam", "한쪽 옆 봉제선으로 수렴하는 작은 가로 주름.", "Small transverse folds converging on one side seam."),
          variant("center-seam", "앞 중심 고정선으로 모이는 양쪽 천 주름.", "Fabric folds from both sides gathering into a center-front fixed line."),
          variant("waist-zone", "허리 영역의 고정선에 모이되 같은 패널의 주변 천과 이어지는 반복 주름.", "Repeated folds gathering at fixed lines in a waist region and continuing into the same panel.")],
         [case("성인 드레스의 왼쪽 옆선으로 루싱이 모이고 주변 천은 같은 패널로 이어지게 해줘.", "Have ruching converge into the left side seam of an adult dress while surrounding fabric remains the same panel.", "matches_selected_scope", "주름 방향·위치·소속을 명시한다."),
          case("앞 중심 봉제선으로 양쪽의 작은 주름이 모이는 의복 상세 사진을 원해.", "I want a garment detail with small folds from both sides gathering into the center-front seam.", "matches_selected_scope", "유효한 다른 위치 변형이다."),
          case("허리의 고정선에 작은 천 주름이 반복되고 위아래 천과 연속해서 이어지게 해줘.", "Show repeated small folds at fixed waist lines continuously connected to the fabric above and below.", "matches_selected_scope", "천 주름의 국소 모임을 지시한다.")],
         [case("고정점 없이 드레스 전체가 불규칙하게 구겨진 모습을 보여줘.", "Show irregular wrinkles across a whole dress with no gathering attachment.", "contradicts_required_relation", "국소 모임과 고정 관계가 없다."),
          case("국소 모임 없이 일정한 폭의 접힌 플리츠가 늘어서는 치마를 보여줘.", "Show a skirt with evenly spaced folded pleats and no localized gathering.", "outside_selected_scope", "접힌 주름은 이 모임 구조와 다른 변형이다."),
          case("요청한 옆선 대신 독립된 장식 주름 띠를 목둘레에 달아줘.", "Add a separate ruched trim around the neckline instead of gathering the requested side seam.", "outside_selected_scope", "사전의 ruche 용례일 수 있으나 요청한 소속·위치를 바꾼다.")],
         ["루싱·셔링·스모킹을 모든 문맥에서 완전 동의어로 묶지 않는다.", "탄성·신축 성능은 보이는 주름만으로 확정할 수 없다."],
         ["사이드 모임·장식 띠·탄성 줄 모임의 실제 앞뒤 사진을 비교하는 독립 검토가 필요하다."]),

    card("textile-transmission", "sheer_mesh", ["sheer_garment_optical_layering"], "천 층과 빛 투과의 관계",
         pair("직물의 부분적 빛 투과를 다룬다. 열린 구멍의 조직인 메시와 다른 차원이며 어느 아래층이 보이는지 별도로 기술한다.",
              "This concerns partial light transmission through a textile, a different dimension from mesh's open-cell construction. The transmitted underlayer must be specified."),
         "직조·가장자리·봉제선·주름으로 천 층이 존재하면서 빛과 아래층 또는 배경 일부가 통과하는 변형을 선택한다. 본 묶음의 예시는 불투명 의복 아래층이다.",
         ["mw-sheer", "cotton-mesh"],
         [invariant("surface", "outer textile", "retains visible weave or textile surface"),
          invariant("transmission", "same outer textile", "transmits some light and part of the explicitly specified underlayer or background"),
          invariant("layer-order", "textile seam, edge and folds", "identify a distinct cloth layer above that underlayer")],
         pair("바깥 천의 직조·봉제선·가장자리가 보이면서 빛과 불투명한 안감의 색이 일부 통과한다. 겹친 주름에서는 그 투과가 줄어든다.",
              "The outer fabric's weave, seam and edge remain visible while some light and color from an opaque lining pass through; overlapping folds transmit less."),
         pair("불투명한 안감 위에 얇은 직물 층이 놓인다. 바깥 층의 실 조직과 봉제선, 끝단, 주름이 읽히며 안감의 색은 일부만 통과한다. 겹쳐 두꺼워진 주름은 주변의 단일 층보다 덜 비친다. 겉감 가장자리는 안감보다 앞에 있고 빛이 얇은 층을 통과하는 방향도 읽힌다.",
              "A thin textile layer sits above an opaque lining. Its yarn structure, seams, edge and folds remain legible while the lining's color partly transmits. Overlapping folds transmit less than the single layer beside them. The outer fabric edge lies in front of the lining, and the direction of light through the thin layer remains readable."),
         [variant("lined-overlay", "불투명 안감 위의 부분 투과 겉감.", "A partly transmitting outer textile above an opaque lining."),
          variant("backlit-sleeve", "불투명한 안쪽 소매 위의 겉 소매에 역광이 통과하는 변형.", "A backlit outer sleeve transmitting light over an opaque inner sleeve."),
          variant("folded-overlay", "안감은 유지하고 같은 겉감의 단일 층과 겹친 주름을 비교하는 변형.", "An unchanged lining beneath both a single outer layer and its overlapping folds.")],
         [case("불투명 안감 위의 시어 겉감에서 직조와 봉제선을 남기고 안감 색이 조금 통과하게 해줘.", "Show a sheer outer layer over an opaque lining, retaining weave and seams while a little lining color transmits.", "matches_selected_scope", "직물 존재와 아래층 순서를 함께 명시한다."),
          case("성인 의복의 안쪽 소매는 불투명하게 두고 바깥 얇은 소매에는 역광이 통과하게 해줘.", "Keep an adult garment's inner sleeve opaque while backlight transmits through its thin outer sleeve.", "matches_selected_scope", "빛 투과와 다른 층의 소속이 구별된다."),
          case("같은 안감 위의 천이 단일 층에서는 조금 비치고 겹친 주름에서는 덜 비치는 모습을 보여줘.", "Show cloth over the same lining transmitting slightly through one layer and less through overlapping folds.", "matches_selected_scope", "투과 정도의 변형을 같은 천 관계로 기술한다.")],
         [case("직물 대신 투명한 유리판을 앞에 놓아줘.", "Place a transparent glass pane in front instead of a textile.", "contradicts_required_relation", "직물의 조직·봉제선·주름 관계가 사라진다."),
          case("불투명 천에 망사 격자만 인쇄하고 빛은 통과하지 않게 해줘.", "Print a mesh grid on opaque cloth without any transmitted light.", "contradicts_required_relation", "무늬는 투과 관계를 대신하지 않는다."),
          case("sheer cliff의 가파른 수직 지형을 보여줘.", "Show the vertical terrain of a sheer cliff.", "different_sense", "직물 아닌 형용사 뜻이다.")],
         ["시어의 광학 성질과 메시의 실제 구멍은 동의어가 아니다.", "아래층의 소유자가 달라지면 같은 표현의 등가 치환이 아니다. 불투명 안감 예시는 별도 선택 변형이다.", "투과 정도·섬유 성분·제작법은 실제 재료·조명 자료가 있어야 확정할 수 있다."],
         ["같은 천의 층수·역광·각도별 직접 비교 자료와 재료 전문가 검토가 필요하다."]),

    card("fine-open-cells", "sheer_mesh", ["clothing_ct090_v2"], "실 사이에 실제 열린 작은 셀이 있는 천",
         pair("메시는 실·루프 사이의 열린 공간을 가진 조직이다. 현재 프로필은 작고 일정하게 반복되는 튤 메시의 특정 외관을 선택한다.",
              "Mesh has spaces between yarns or loops. This profile selects the visible variant of fine, evenly repeated tulle mesh cells."),
         "fine tulle mesh의 작고 일정한 실제 열린 셀을 선택한다. 셀 모양·색·아래층을 용어 하나로 고정하지 않는다. 금속 링 메시 프로필과 별개다.",
         ["cotton-mesh"],
         [invariant("cells", "outer fabric's yarn network", "surrounds small real openings repeated at even spacing"),
          invariant("not-print", "openings", "are gaps between fibers rather than printed marks")],
         pair("미세한 실들이 일정한 간격의 작은 열린 셀을 이루고, 그 실제 틈을 통해 뒤의 층이 보인다. 실과 빈 틈을 각각 구별할 수 있다.",
              "Fine yarns form small real open cells at even intervals, revealing the layer behind through the gaps. Yarns and empty spaces remain distinguishable."),
         pair("가느다란 실 조직이 작은 열린 셀을 일정하게 반복해 둘러싼다. 그 실제 틈을 통해 아래에 놓인 불투명한 천이 보인다. 셀을 둘러싼 실의 윤곽과 교차, 그 사이의 빈 공간, 전체 천 가장자리가 각각 구별된다. 작은 열린 셀의 반복은 주름 주변에서도 같은 겉감에 이어진다.",
              "A fine yarn network encloses small real open cells at even intervals, revealing opaque cloth beneath through the gaps. Yarn boundaries and intersections, empty spaces between them, and the overall fabric edge remain separately legible. The repeated small openings continue in the same outer fabric around its folds."),
         [variant("flat", "불투명 천 위에 평평하게 놓인 미세 셀 조직.", "Fine open-cell fabric laid flat over opaque cloth."),
          variant("folded", "같은 미세 셀 조직에 주름이 생겨 겹쳐 보이는 변형.", "The same fine open-cell fabric with folds producing overlapping layers."),
          variant("edge", "일정한 작은 열린 셀과 천 가장자리가 함께 보이는 상세 뷰.", "A detail showing evenly repeated small open cells together with the textile edge.")],
         [case("불투명 천 위에 일정한 작은 실제 셀이 있는 미세 튤 메시를 보여줘.", "Show fine tulle mesh with evenly repeated small real openings over opaque cloth.", "matches_selected_scope", "선택 조직과 예시 아래층이 명시된다."),
          case("얇은 실들이 작은 빈 셀을 반복해서 둘러싸는 천을 접사로 찍어줘.", "Make a close-up of cloth whose fine yarns repeatedly enclose small empty cells.", "matches_selected_scope", "라벨 대신 실과 빈 틈의 관계를 요구한다."),
          case("미세 메시의 주름 가장자리에서도 작은 열린 셀과 실을 구별할 수 있게 해줘.", "Keep fine mesh yarns and small open cells distinguishable along a folded fabric edge.", "matches_selected_scope", "폴딩 변형에서도 선택 조직을 유지한다.")],
         [case("실제 구멍 없이 불투명 천에 작은 격자를 인쇄해줘.", "Print a small grid on opaque cloth without real openings.", "contradicts_required_relation", "프린트는 열린 셀 구조를 대신하지 않는다."),
          case("연결된 금속 고리로 된 링 메시를 보여줘.", "Show a mesh made of linked metal rings.", "outside_selected_scope", "넓은 mesh 용어에는 포함될 수 있으나 이 섬유 셀 변형과 다르다."),
          case("촘촘한 셀 대신 옷에 큰 원형 절개 구멍 세 개를 만들어줘.", "Give the garment three large circular cutouts instead of fine cells.", "contradicts_required_relation", "셀 크기·반복·실 조직을 바꾼다.")],
         ["일정한 셀은 현재 선택 변형의 조건이다. 모든 메시는 동일하게 규칙적이지 않다.", "CottonWorks의 일반 메시 정의는 이 셀을 튤로 확정하거나 섬유 성분을 입증하지 않는다."],
         ["튤 제조자의 셀 구조 도해와 현미경·접사 자료를 직접 대조해야 한다."]),

    card("paired-front-fastening", "corset", ["clothing_ct023_v2"], "몸판 앞 중심의 쌍을 이룬 금속 잠금",
         pair("코르셋은 구조가 다양한 상위 의복 개념이다. 이 프로필은 앞 중심에서 쌍을 이룬 버스크 잠금으로 닫히는 변형만 선택한다.",
              "Corset is a broader garment category with varied construction. This profile selects a front closed with paired busk fasteners."),
         "한 몸판의 좌우 앞판을 따라 고리·돌기 쌍이 맞물리는 앞면 여밈이다. 단단한 내부 버스크나 뒤 끈 여밈만으로 대체하지 않는다.",
         ["va-corset"],
         [invariant("front", "left and right panels of the same structured garment", "meet at center front"),
          invariant("paired", "metal loops/hooks and studs", "form corresponding pairs along the two front edges"),
          invariant("closure", "same paired fasteners", "join and close those front panels")],
         pair("구조적인 의복의 좌우 앞판이 중심에서 만나고, 양쪽 가장자리의 작은 금속 고리와 돌기가 쌍으로 맞물려 앞면을 닫는다.",
              "The two front panels of a structured garment meet at the center, where small paired metal loops and studs interlock along the edges to close it."),
         pair("같은 구조적인 의복의 앞면 좌우 가장자리에 연속된 잠금 부품이 놓인다. 한쪽의 작은 고리 또는 훅과 다른 쪽의 대응하는 돌기가 쌍을 이루어 맞물리고, 그 연결이 두 앞판을 닫는다. 각 부품은 대응하는 앞 가장자리에 붙어 있고 금속과 천 사이의 연결이 읽힌다.",
              "A sequence of fasteners lies along the two front edges of the same structured garment. Small loops or hooks on one side interlock with corresponding studs on the other, joining and closing the two front panels. Each component is attached to its corresponding front edge, with the metal-to-fabric connection readable."),
         [variant("closed-front", "닫힌 앞면에서 대응 잠금 쌍과 두 패널의 연결이 보이는 변형.", "A closed front displaying corresponding fastener pairs joining both panels."),
          variant("back-lacing-also", "같은 앞면 잠금을 유지하며 뒤에 끈 여밈도 있는 변형.", "The same front fasteners with additional rear lacing."),
          variant("color-change", "색과 표면 마감은 달라도 앞면 잠금 쌍과 연결은 같은 변형.", "Different color or surface finish with the same paired front-closure relationship.")],
         [case("성인 의복의 코르셋 앞판이 짝을 이룬 버스크 훅으로 닫히고 그 연결이 보이게 해줘.", "Show an adult garment's corset front closed by visibly paired busk fasteners.", "matches_selected_scope", "앞판과 대응 잠금 쌍을 명시한다."),
          case("뒤에 끈 여밈이 있어도 앞 중심은 대응하는 금속 고리와 돌기로 닫힌 구조를 보여줘.", "Show a garment with rear lacing whose center front is still closed by corresponding metal loops and studs.", "matches_selected_scope", "뒤 끈은 앞 잠금을 대체하지 않는 추가 변형이다."),
          case("좌우 앞판 가장자리의 작은 금속 잠금들이 쌍으로 맞물리는 상세를 원해.", "I want a detail of small paired metal fasteners interlocking along the left and right front edges.", "matches_selected_scope", "이름 없이 동일 앞면 연결을 기술한다.")],
         [case("여밈 없이 잘록한 실루엣의 상의만 보여줘.", "Show a fitted narrow-waist top without a visible closure.", "insufficient_evidence", "체형이나 윤곽은 앞 잠금 구조가 아니다."),
          case("코르셋의 뒤 끈만 보이고 앞면은 가려지게 해줘.", "Show only a corset's rear lacing with the front hidden.", "insufficient_evidence", "코르셋일 수 있지만 선택한 앞면 연결을 볼 수 없다."),
          case("한 장의 단단한 버스크를 내부에 넣고 앞면은 평평하게 닫아줘.", "Use a single solid busk inside the garment with a plain closed front.", "outside_selected_scope", "내부 단단한 버스크와 앞에서 쌍으로 여닫는 분할 잠금은 다르다.")],
         ["버스크라는 단어만으로 분할 앞면 잠금을 확정하지 않는다.", "코르셋 전체·잘록한 허리·내부 지지 성능을 이 앞면 여밈과 동일시하지 않는다."],
         ["잠금의 대응 부품을 확인할 제조자 접사·앞뒤 도해와 복식 전문가 검토가 필요하다."]),

    card("separated-focus-zones", "split_diopter", ["split_diopter_dual_focus_planes"], "두 거리의 선명한 초점 구역",
         pair("광학 제조사 자료는 가까운 대상과 먼 대상을 두 초점 면으로 다루는 반쪽 렌즈 요소를 설명한다.",
              "The optical manufacturer's source describes a half-lens element used to maintain near and far subjects in separate focus planes."),
         "현재 프로젝트는 동시에 선명한 근·원거리 기준물, 더 부드러운 사이 깊이 또는 광학 전환, 연속된 빛·원근·가림을 보이는 변형이다.",
         ["schneider-split"],
         [invariant("near", "near foreground anchor", "is critically sharp"),
          invariant("far", "clearly distant anchor", "is critically sharp at the same time"),
          invariant("middle", "intervening depth or optical transition", "remains visibly softer"),
          invariant("continuity", "lighting, perspective and occlusion", "remain visually continuous across the focus zones")],
         pair("가까운 물체와 분명히 먼 물체가 동시에 선명하고, 사이 깊이의 좁은 영역은 더 부드럽다. 빛·원근·가림은 두 구역을 가로질러 연속된다.",
              "A near object and a clearly distant object are sharp simultaneously, with a softer intervening depth region and continuous light, perspective and occlusion across both zones."),
         pair("전경 가까이에 놓인 물체의 세부와 멀리 있는 대상의 세부가 한 화면에서 동시에 또렷하다. 두 거리 사이의 중간 깊이 또는 절제된 광학 전환은 상대적으로 흐려 보인다. 두 선명 영역의 조명 방향, 원근선, 가림 순서는 서로 이어지며 하나의 공간을 이룬다.",
              "Fine detail on a close foreground object and a clearly distant subject stays sharp in the same frame. The intervening depth or restrained optical transition appears softer. Lighting direction, perspective lines and occlusion order continue across both sharp zones as one coherent space."),
         [variant("left-near", "왼쪽 가까운 기준물과 오른쪽 먼 대상이 선명한 변형.", "A sharp near anchor on the left and distant subject on the right."),
          variant("right-near", "오른쪽 가까운 기준물과 왼쪽 먼 대상이 선명한 변형.", "A sharp near anchor on the right and distant subject on the left."),
          variant("object-person", "가까운 소품과 먼 성인이 선명하고 사이 깊이는 부드러운 변형.", "A sharp close object and distant adult with softer intervening depth.")],
         [case("split diopter 느낌으로 가까운 꽃병과 먼 성인을 동시에 선명하게 하고 중간 깊이는 부드럽게 해줘. 조명과 원근은 이어져야 해.", "Use a split-diopter-like relation with a close vase and distant adult sharp together, softer intervening depth, and continuous lighting and perspective.", "matches_selected_scope", "현재 선택한 두 선명 구역과 부드러운 사이 영역을 요구한다."),
          case("왼쪽 가까운 시계와 오른쪽 먼 문이 동시에 선명하고 가림과 원근이 연속되게 해줘. 사이 깊이는 흐리게 해줘.", "Keep a close clock on the left and distant door on the right sharp together with continuous occlusion and perspective, and a softer middle depth.", "matches_selected_scope", "화면 위치를 달리해도 거리 관계가 유지된다."),
          case("오른쪽 전경 물체와 왼쪽 멀리 있는 대상을 동시에 또렷하게, 사이 깊이는 부드럽게 한 장면으로 보여줘.", "Show a right foreground object and left distant subject sharp simultaneously, with softer intervening depth in one visually continuous scene.", "matches_selected_scope", "고정된 좌우 방향을 개념 필수로 만들지 않는다.")],
         [case("가까운 곳부터 먼 곳까지 모든 깊이가 똑같이 선명하게 해줘.", "Make every depth from foreground to background equally sharp.", "outside_selected_scope", "일반 깊은 초점이며 선택한 부드러운 사이 영역이 없다."),
          case("좌우 두 사진을 분할 화면으로 붙여줘.", "Join two photographs as a left-right split screen.", "contradicts_required_relation", "광학 거리 관계를 두 패널로 대체한다."),
          case("가까운 성인만 선명하게 하고 먼 배경은 전부 흐리게 해줘.", "Keep only the close adult sharp and blur the whole distant background.", "contradicts_required_relation", "먼 기준물의 동시 선명도를 요구하지 않는다.")],
         ["부드러운 사이 영역은 현재 프로필의 선택 조건이지 모든 반쪽 보조 렌즈 사용의 필수 외관이 아니다.", "렌즈·단일 촬영·합성 여부는 최종 픽셀만으로 확정하지 않는다."],
         ["조건을 충족하는 권리 확인 참고 장면과 일반 깊은 초점·합성의 비교 자료가 필요하다."]),

    card("warm-highlight-halo", "halation", ["film_halation_highlight_edge_relation"], "밝은 경계 바로 밖의 국소 따뜻한 번짐",
         pair("필름 할레이션 일반은 밝은 대상 주변의 추가 노출 현상이다. 현재 프로필은 그중 얇고 따뜻하거나 붉은 편향의 가장자리 번짐을 선택한다.",
              "Film halation generally concerns additional exposure around bright objects. This profile selects a thin warm or red-biased edge halo."),
         "매우 밝은 경계 바로 바깥의 얇은 국소 따뜻한 번짐, 국소 감쇠, 읽을 수 있는 밝은 코어와 비하이라이트 세부를 선택한다.",
         ["kodak-halation"],
         [invariant("anchor", "genuinely bright highlight boundary", "anchors the effect"),
          invariant("halo", "immediate exterior of that boundary", "carries a thin warm/red-biased halo"),
          invariant("local", "halo width and intensity", "fall off locally rather than covering the frame"),
          invariant("detail", "highlight core and nearby nonhighlight detail", "remain structured"),
          invariant("separation", "flare ghosts and paired colored edges", "remain distinct from the local halo")],
         pair("아주 밝은 가장자리 바로 밖에 얇고 따뜻한 번짐이 국소적으로 줄어든다. 밝은 코어와 주변 세부는 읽히며 전역 안개나 유령 광점과 구별된다.",
              "A thin warm halo falls off locally just outside very bright edges. Highlight cores and nearby detail remain readable, distinct from global haze, ghost orbs or paired colored fringes."),
         pair("아주 밝은 창이나 반사광의 경계 바로 바깥에 얇은 따뜻한 색 테두리가 나타난다. 번짐의 폭과 강도는 가까운 영역에서 줄어들고 화면 전체로 퍼지지 않는다. 밝은 대상 자체의 모양과 근처의 어둡거나 중간 밝기 세부는 유지된다. 렌즈 유령 광점, 넓은 안개, 서로 반대색의 이중 가장자리와 구별되는 하나의 국소 번짐으로 읽힌다.",
              "A thin warm-colored rim appears immediately outside a very bright window or reflection boundary. Its width and strength decrease nearby instead of spreading across the frame. The bright object's core shape and neighboring midtone or dark detail remain readable. The halo stays distinct from ghost orbs, broad veiling haze and opposed colored edge pairs."),
         [variant("window", "매우 밝은 창 경계의 얇은 따뜻한 국소 번짐.", "A thin local warm halo at a very bright window edge."),
          variant("reflection", "작은 강한 반사광 경계에서 국소적으로 줄어드는 번짐.", "A halo falling off locally around a small intense reflection."),
          variant("light-source", "밝은 광원 경계에 국한되고 주변 세부를 유지하는 번짐.", "A halo confined to a bright light-source edge with neighboring detail retained.")],
         [case("필름 할레이션 느낌으로 아주 밝은 창 가장자리 바로 밖에만 얇은 따뜻한 번짐을 두고 주변 세부는 남겨줘.", "Use a film-halation-like effect with a thin warm halo only just outside a very bright window edge, retaining nearby detail.", "matches_selected_scope", "현재 색 편향과 국소 경계를 지정한다."),
          case("강한 반사광의 코어는 선명하게 두고 바로 바깥 붉은 번짐은 가까운 곳에서 줄어들게 해줘.", "Keep an intense reflection's core structured while a thin red-biased halo just outside it falls off nearby.", "matches_selected_scope", "코어·외부 경계·감쇠 관계가 있다."),
          case("작은 밝은 광원에 얇은 따뜻한 테두리만 더하고 어두운 배경 세부와 유령 광점은 구별되게 해줘.", "Add only a thin warm rim to a small bright light source, keeping dark background detail and any ghost orbs distinct.", "matches_selected_scope", "라벨 없이 국소 광학 외관을 요구한다.")],
         [case("전체 사진을 붉게 색 보정해줘.", "Apply a red color grade to the entire photograph.", "contradicts_required_relation", "밝은 경계에 붙은 국소 번짐이 아니다."),
          case("모든 영역에 똑같은 뿌연 glow를 덮어줘.", "Cover every region with the same hazy glow.", "contradicts_required_relation", "국소 감쇠와 세부 유지가 사라진다."),
          case("고대비 가장자리 양쪽에 반대색 색수차를 만들어줘.", "Create opposed colored aberration fringes on both sides of high-contrast edges.", "outside_selected_scope", "색 쌍의 가장자리 이동은 선택한 단일 따뜻한 번짐과 다르다.")],
         ["따뜻함과 붉은 편향은 이 프로젝트의 선택 조건이다. 모든 필름 할레이션의 보편적 색을 입증한 것이 아니다.", "이 외관은 실제 필름 사용이나 필름 제품 종류를 확정하지 않는다."],
         ["같은 광원에서 할레이션·블룸·색수차를 분리하는 권리 확인 비교 이미지가 필요하다."]),

    card("broad-cheek-lit", "broad_short", ["broad_face_light_orientation_relation"], "카메라에 넓게 보이는 뺨의 주광",
         pair("머리를 돌려 카메라에 넓게 보이는 얼굴 면이 주광을 받는 조명 관계다.",
              "With the head turned, the cheek plane presenting more visible area to the camera receives the dominant light."),
         "머리 방향·넓게 보이는 뺨의 주광·좁은 반대 면의 그림자와 읽을 수 있는 얼굴 단서를 선택한다.",
         ["profoto-face-light", "nikon-broad"],
         [invariant("turn", "turned face", "presents a broader near cheek and narrower far cheek to the camera"),
          invariant("lit", "camera-broad cheek", "receives the dominant illumination"),
          invariant("shadow", "narrower far cheek", "carries the primary shadow"),
          invariant("orientation", "nose, eyes and jaw", "keep head direction and light ownership readable")],
         pair("고개를 돌려 카메라에 넓게 보이는 뺨이 주광을 받고 좁게 보이는 반대 뺨에는 그림자가 남는다. 코·눈·턱의 방향이 읽힌다.",
              "On a turned face, the cheek showing more area to the camera receives the main light while the narrower opposite cheek stays in shadow; nose, eye and jaw direction remain readable."),
         pair("얼굴을 돌려 한쪽 뺨은 카메라에 넓게, 반대쪽은 좁게 보이게 한다. 주된 빛은 넓게 보이는 가까운 뺨을 비추고 좁은 먼 뺨에는 모델링된 그림자가 남는다. 코의 방향과 눈·턱 윤곽은 읽을 수 있다. 화면의 좌우가 바뀌어도 넓게 보이는 면이 밝다는 관계는 유지한다.",
              "Turn the face so one cheek occupies more camera-visible area and the opposite cheek less. The dominant light illuminates the broad near cheek, leaving modeled shadow on the narrow far cheek. Nose direction, eyes and jaw remain legible. Mirroring the frame preserves which camera-visible plane is lit."),
         [variant("left-turn", "고개가 한쪽으로 돌아도 넓게 보이는 면이 밝은 변형.", "A head turn to one side with the camera-broad cheek lit."),
          variant("right-turn", "반대 방향의 머리 회전에서도 넓게 보이는 면이 밝은 변형.", "The opposite head turn with the camera-broad cheek still lit."),
          variant("softer-key", "주광의 부드러움이 달라도 넓은 뺨이 주로 밝고 좁은 뺨이 어두운 변형.", "A softer key retaining the broad-lit and narrow-shadow relation.")],
         [case("성인 얼굴을 돌려 브로드 조명으로 찍어줘. 카메라에 더 넓게 보이는 뺨이 밝고 반대의 좁은 뺨은 그림자여야 해.", "Photograph a turned adult face with broad lighting: the camera-broad cheek lit and the narrower opposite cheek in shadow.", "matches_selected_scope", "라벨과 카메라 기준 얼굴 면이 일치한다."),
          case("고개가 왼쪽을 향해도 넓게 보이는 가까운 뺨에 주광을 두고 좁은 먼 뺨은 어둡게 해줘.", "Even with the head turned left, light the broad near cheek and leave the narrow far cheek in shadow.", "matches_selected_scope", "방향보다 밝아야 하는 면의 관계를 고정한다."),
          case("반대 방향으로 얼굴을 돌리고 부드러운 빛을 써도 더 넓게 보이는 뺨이 주로 밝도록 해줘.", "Turn the face the other way and use softer light while keeping the camera-broad cheek predominantly illuminated.", "matches_selected_scope", "회전·광원 부드러움은 변할 수 있다.")],
         [case("얼굴을 돌리고 좁게 보이는 먼 뺨을 밝게, 넓은 가까운 뺨을 어둡게 해줘.", "Turn the face and light the narrow far cheek, leaving the broad near cheek in shadow.", "contradicts_required_relation", "정반대인 쇼트 관계다."),
          case("얼굴 방향은 정하지 않고 왼쪽 조명이라고만 써줘.", "Specify only light from the left, without defining the head turn.", "insufficient_evidence", "고정 좌우로는 어느 카메라 면이 밝은지 결정되지 않는다."),
          case("정면 얼굴의 양쪽을 동일하게 밝게 해줘.", "Light both sides of a front-facing face equally.", "outside_selected_scope", "돌아간 얼굴의 넓은 면·좁은 면 관계가 없다.")],
         ["브로드는 얼굴 폭·미적 평가·성격의 주장이 아니라 카메라에 보이는 면과 빛의 관계다.", "고정된 화면 왼쪽·오른쪽만으로 라벨을 결정하지 않는다."],
         ["같은 얼굴·카메라를 유지하고 머리 방향만 달리한 권리 확인 참고 사진이 필요하다."]),

    card("short-cheek-lit", "broad_short", ["short_face_light_orientation_relation"], "카메라에 좁게 보이는 뺨의 주광",
         pair("머리를 돌려 카메라에 좁게 보이는 먼 얼굴 면이 주광을 받고 넓게 보이는 가까운 면이 그림자인 관계다.",
              "With the head turned, the narrow far cheek receives dominant light and the broad camera-facing cheek remains in shadow."),
         "좁은 먼 뺨의 주광·넓은 가까운 뺨의 그림자·읽을 수 있는 얼굴 방향을 선택한다.",
         ["profoto-face-light"],
         [invariant("turn", "turned face", "presents a narrow far cheek and broader near cheek to the camera"),
          invariant("lit", "camera-narrow far cheek", "receives the dominant light"),
          invariant("shadow", "camera-broad near cheek", "carries modeled shadow"),
          invariant("orientation", "face contour, eyes and nose", "remain readable through the shadow")],
         pair("고개를 돌려 카메라에 좁게 보이는 먼 뺨이 주광을 받고 넓게 보이는 가까운 뺨에는 그림자가 남는다. 그림자 속 눈·코·얼굴 윤곽도 읽힌다.",
              "On a turned face, the narrow far cheek receives the main light and the broad near cheek stays in shadow, with eyes, nose and contour still readable."),
         pair("머리 회전으로 먼 뺨의 카메라 가시 면적은 작고 가까운 뺨의 면적은 크게 만든다. 주광은 좁게 보이는 먼 뺨에 닿으며 넓게 보이는 가까운 뺨은 형태가 읽히는 그림자에 둔다. 눈의 위치, 코의 방향과 얼굴 윤곽은 사라지지 않는다. 좌우를 뒤집어도 좁은 면이 밝고 넓은 면이 그림자인 관계를 유지한다.",
              "The head turn makes the far cheek occupy less camera-visible area than the near cheek. Place the dominant light on that narrow far plane, leaving modeled shadow on the broad near plane. Eye position, nose direction and face contour remain legible. Mirroring preserves the narrow-lit and broad-shadow relation."),
         [variant("left-turn", "한쪽으로 고개를 돌리고 좁은 먼 면에 주광을 두는 변형.", "A head turn to one side with the narrow far plane lit."),
          variant("right-turn", "반대 방향으로 돌려도 좁은 먼 면을 밝게 두는 변형.", "The opposite head turn with the narrow far plane still lit."),
          variant("gentle-fill", "넓은 면의 그림자 속 윤곽을 약한 보조광으로 읽게 하되 주광 관계는 유지.", "Gentle fill reveals contour in the broad plane's shadow while preserving the dominant-light relation.")],
         [case("성인 얼굴을 돌려 쇼트 조명으로 찍어줘. 좁은 먼 뺨이 밝고 넓은 가까운 뺨은 읽을 수 있는 그림자여야 해.", "Photograph a turned adult face with short lighting: the narrow far cheek lit and the broad near cheek in readable shadow.", "matches_selected_scope", "주광과 그림자의 소유자가 브로드와 반대다."),
          case("고개를 오른쪽으로 돌려도 먼 쪽의 좁게 보이는 면에 주광을 두고 가까운 넓은 면을 어둡게 해줘.", "With the head turned right, put the main light on the narrow far plane and leave the broad near plane in shadow.", "matches_selected_scope", "좌우 변화에도 관계가 유지된다."),
          case("약한 보조광으로 눈과 코는 읽히게 하면서 주된 빛은 좁게 보이는 뺨에만 두어줘.", "Use gentle fill to keep the eyes and nose readable while the main light stays on the narrow cheek of the turned face.", "matches_selected_scope", "그림자 세부를 유지하는 변형이다.")],
         [case("돌아간 얼굴의 넓게 보이는 가까운 뺨을 밝게 비춰줘.", "Illuminate the broad near cheek of the turned face.", "contradicts_required_relation", "브로드 관계로 바뀐다."),
          case("얼굴 면은 전부 어둡게 하고 뒤에서 윤곽선만 밝혀줘.", "Leave the facial planes dark and light only the outline from behind.", "outside_selected_scope", "좁은 얼굴 면의 주광이 아니라 림 관계다."),
          case("넓은 가까운 뺨을 완전히 검게 지워 눈과 얼굴 방향도 안 보이게 해줘.", "Make the broad near cheek solid black so the eyes and face direction disappear.", "contradicts_required_relation", "현재 프로필이 요구하는 그림자 속 얼굴 방향 단서가 사라진다.")],
         ["쇼트는 얼굴이 짧다는 뜻이나 체형 보정 효과의 입증이 아니다.", "그림자의 밝기와 주광 방향을 구별한다. 검은 면만으로 쇼트 관계를 대신하지 않는다."],
         ["한 독립 1차 출처에 의존한다. 별도 전문 광학·사진 교육 자료의 교차 확인이 필요하다."]),
]


def main():
    stamp = datetime.now(timezone(timedelta(hours=9))).isoformat()
    dump("sources.json", {
        "schema_version": 1, "assembled_at_kst": stamp,
        "items": SOURCES,
        "reuse_limits": "Paraphrased research facts and links only; no remote image files or full copyrighted texts redistributed.",
        "unsuccessful_access": [
            {"url": "https://krdict.korean.go.kr/eng/dicSearch/search?mainSearchWord=%EC%9B%90%ED%94%BC%EC%8A%A4", "outcome": "tool fetch failed", "fact_status": "not used as a verified Korean definition"},
            {"url": "https://one-piece.com/", "outcome": "403", "fact_status": "not used as source evidence"},
            {"url": "https://www2.ic.daito.ac.jp/jtogashi/articles/togashi2009a.pdf", "outcome": "timeout/internal error", "fact_status": "indexed excerpt only; exact PDF wording needs review"},
            {"url": "https://www.flight.co.jp/uploaded_files/c_news/106_detail.pdf", "outcome": "text encoding damaged; browser viewport blank", "fact_status": "indexed excerpt only; not visual PDF verification"},
        ],
    })
    dump("concept-cards.json", {
        "schema_version": 1, "authored_at_kst": stamp,
        "baseline_head": SNAPSHOT["head"],
        "baseline_loaded_profiles": SNAPSHOT["loaded_profile_count"],
        "status": "research_drafts_unapplied",
        "scope": "12 agreed concept families; sheer/mesh and broad/short split into separate cards; two cowl profiles share one card",
        "provenance": "Context requests, neutral descriptions, variants and invariants are authored proposals grounded in linked sources and the frozen project profiles. They are not external quotations or independent evaluation results.",
        "cards": CARDS,
    })
    cases = []
    proposals = []
    for c in CARDS:
        for label, examples in [("positive", c["positive_contexts"]), ("contrast", c["contrast_contexts"])]:
            for number, ex in enumerate(examples, 1):
                cases.append(dict(
                    id=f"{c['id']}-{label}-{number:02d}", card_id=c["id"],
                    source_ids=c["source_ids"], candidate_profile_ids=c["profile_ids"],
                    request=ex["request"], semantic_relation=ex["semantic_relation"],
                    rationale_ko=ex["rationale_ko"],
                    expected_profile_ids=c["profile_ids"] if label == "positive" else [],
                    expected_relation_basis="authored comparison to frozen selected project scope; not measured activation",
                    split="authoring_development_examples_not_blind_holdout",
                    model_result="NOT_RUN", pixel_result="NOT_RUN"))
        neutral = [c["neutral_descriptions"][size][lang] for size in ("short", "detailed") for lang in ("ko", "en")]
        contrasts = [ex["request"][lang] for ex in c["contrast_contexts"] for lang in ("ko", "en")]
        for ident in c["profile_ids"]:
            p = BY_ID[ident]["profile"]
            proposals.append(dict(
                profile_id=ident, card_id=c["id"], source_ids=c["source_ids"],
                source_file=BY_ID[ident]["source_file"],
                baseline_compiled_profile_sha256=hashlib.sha256(json.dumps(p, ensure_ascii=False, sort_keys=True, separators=(",", ":")).encode()).hexdigest(),
                status="unapplied_append_only_review_proposal",
                operations=[
                    {"operation": "append_unique", "path": "semantics.paraphrase_examples", "values": neutral},
                    {"operation": "append_unique", "path": "semantics.contrast_examples", "values": contrasts},
                    {"operation": "append_unique", "path": "semantics.claim_limits", "values": c["claim_limits_ko"]},
                ],
                unchanged_contracts=["semantics.definition", "activation", "runtime_expression", "authored_components", "required_evidence_fields", "evidence_requirements", "render_gates", "composition_instruction"],
                boundary="Paraphrase additions alone do not update literal evidence requirements, hard activation, frozen core choices or output wording. No change has been applied."))
    (OUT / "context-cases.jsonl").write_text("".join(json.dumps(c, ensure_ascii=False) + "\n" for c in cases))
    dump("profile-data-proposals.json", {
        "schema_version": 1, "baseline_head": SNAPSHOT["head"],
        "status": "NOT_APPLIED", "apply_script_included": False,
        "policy": "Review artifacts for existing data fields, not runtime schema or skill logic changes. An appendix may preserve additional source/variant metadata outside the runtime registry.",
        "proposals": proposals,
    })
    dump("reference-observations.json", {
        "schema_version": 1, "checked_on": "2026-10-02",
        "method": "Read-only normal page screenshot through Codex in-app browser; no remote image download, crop, enlargement or rehosting",
        "items": [
            {"id": "cowl-page-view", "source_id": "met-cowl", "card_id": "cowl-draped-opening",
             "observation_type": "normal_viewport_observation",
             "observed": ["밝은 색의 긴 의복에서 목둘레 주변의 천이 겹쳐 처지는 형태가 보인다.", "목둘레 부근의 처짐과 허리 아래 세로 천 주름은 위치가 구별된다."],
             "not_resolved": ["낮은 해상도에서 내부 부착 봉제선이나 재단 방향은 확정할 수 없다."],
             "catalog_facts_separate": ["비대칭의 스카프 같은 카울 목둘레는 소장품 설명의 사실이다."],
             "image_rights": "page explicitly restricts enlargement/full-screen/download; reference link and own observations only",
             "image_file_collected": False, "qualification": "reference observation, not generated-image acceptance"},
            {"id": "shirring-swatches-view", "source_id": "seamwork-shirring", "card_id": "local-gathered-folds",
             "observation_type": "normal_viewport_observation",
             "observed": ["세 파란 천 조각에서 여러 가로 줄 주변의 작은 세로 주름이 반복되어 보인다.", "모인 영역과 그 위의 더 넓게 펼쳐진 영역이 각각 같은 천 조각 안에서 이어진다."],
             "not_resolved": ["외관만으로 밑실의 탄성 재료나 인장 성능을 확인하지 못한다."],
             "catalog_facts_separate": ["탄성 밑실과 여러 봉제 줄의 제작 설명은 작성자의 튜토리얼 사실이다."],
             "image_rights": "copyrighted tutorial; no reuse license established; reference link and own observations only",
             "image_file_collected": False, "qualification": "related construction reference, not a universal ruching template"},
        ],
    })
    by_source = {s["id"]: s for s in SOURCES}
    lines = ["# 개념별 보강 자료", "", "이 문서는 concept-cards.json의 읽기용 표현이다. 모든 예문·변형은 출처와 현재 프로필을 바탕으로 작성한 연구 초안이다. 모델·픽셀 평가나 독립 전문가 검토는 실행하지 않았다.", ""]
    for number, c in enumerate(CARDS, 1):
        lines.extend([f"## {number}. {c['title_ko']}", "",
                      "대상 프로필: " + ", ".join(f"`{p}`" for p in c["profile_ids"]), "",
                      "**문맥상 뜻:** " + c["contextual_meaning"]["ko"], "",
                      "**현재 프로필의 선택 범위:** " + c["selected_scope_ko"], "",
                      "**근거:** " + ", ".join(f"[{by_source[s]['title']}]({by_source[s]['url']}) — {by_source[s]['access_status']}" for s in c["source_ids"]), "",
                      "**관계와 소유자:**", ""])
        lines.extend(f"- {i['owner']}: {i['relation']} (현재 프로젝트의 선택 조건)" for i in c["invariants"])
        for size, label in (("short", "짧은 묘사"), ("detailed", "상세 묘사")):
            lines.extend(["", f"**이름 없는 {label}:**", "",
                          "한국어: " + c["neutral_descriptions"][size]["ko"], "",
                          "English: " + c["neutral_descriptions"][size]["en"]])
        lines.extend(["", "**변형 초안:**", ""])
        lines.extend("- " + v["description"]["ko"] for v in c["variants"])
        lines.extend(["", "**선택 범위에 맞는 문맥 예시:**", ""])
        lines.extend("- " + v["request"]["ko"] + " / " + v["request"]["en"] for v in c["positive_contexts"])
        lines.extend(["", "**혼동 경계 예시:**", ""])
        lines.extend("- " + v["request"]["ko"] + " / " + v["request"]["en"] + f" — `{v['semantic_relation']}`: " + v["rationale_ko"] for v in c["contrast_contexts"])
        lines.extend(["", "**한계:**", ""])
        lines.extend("- " + v for v in c["claim_limits_ko"])
        lines.extend(["", "**추가 근거 공백:**", ""])
        lines.extend("- " + v for v in c["remaining_evidence_gaps_ko"])
        lines.append("")
    (OUT / "CONCEPTS.md").write_text("\n".join(lines))
    print(json.dumps({"sources": len(SOURCES), "families": len({c["family"] for c in CARDS}),
                      "cards": len(CARDS), "profiles": len(proposals), "variants": sum(len(c["variants"]) for c in CARDS),
                      "bilingual_cases": len(cases), "utterances": len(cases) * 2,
                      "neutral_texts": len(CARDS) * 4, "reference_observations": 2}, ensure_ascii=False))


if __name__ == "__main__":
    main()
