#!/usr/bin/env python3
"""Anchor catalog for reverse-image-prompt module coverage checks."""

from __future__ import annotations

LEGACY_ANCHOR_IDS = [
    "standalone_reference_ban",
    "visible_evidence_only",
    "aspect_ratio_drift_major",
    "normalized_coordinates",
    "primary_visual_concept",
    "concept_spec",
    "output_sections",
    "prompt_contract_16",
    "negative_primary_concept",
    "recommended_settings_aspect",
    "face_fidelity",
    "aesthetic_upgrade",
    "symmetric_large_body_lock",
    "symmetric_moderate_body_lock",
    "band_height_drift",
    "garment_geometry",
    "face_exposure_budget",
    "screenshot_ui_split",
    "absent_ui_controls",
    "low_legibility_text",
    "miniature_scale",
    "endpoint_sensitive",
    "polish_amplifying",
    "maturity_anti_collapse",
    "coordinate_contradictions",
    "secondary_detail_budget",
]

CORE_ANCHOR_IDS = [
    "standalone_reference_ban",
    "visible_evidence_only",
    "aspect_ratio_drift_major",
    "normalized_coordinates",
    "primary_visual_concept",
    "concept_spec",
    "output_sections",
    "prompt_contract_16",
    "negative_primary_concept",
    "recommended_settings_aspect",
    "coordinate_contradictions",
    "secondary_detail_budget",
    "anti_polish",
    "broad_label_discipline",
    "fidelity_ceiling",
    "output_gate",
    "prompt_only_limits",
    "background_zoning",
    "low_legibility_background",
    "color_mood",
]

ANCHORS = {
    "standalone_reference_ban": "Never write `same as the image`, `as shown`, `based on the reference`, `like the provided image`, `from the uploaded image`",
    "visible_evidence_only": "Do not infer hidden anatomy, hidden objects, hidden clothing structure, hidden context",
    "aspect_ratio_drift_major": "Treat aspect-ratio drift as a major fidelity failure",
    "normalized_coordinates": "`x=0%` is the far left edge; `x=100%` is the far right edge",
    "primary_visual_concept": "Primary visual concept, perceived intent, and perceptual relationships",
    "concept_spec": "In the Concept Spec, name the relationship type, contributing surfaces/elements and their visual roles",
    "output_sections": "Write only the required output sections",
    "prompt_contract_16": "16. Critical fidelity locks",
    "negative_primary_concept": "Primary-concept drift and concept-lock failure modes",
    "recommended_settings_aspect": "- Aspect ratio:",
    "face_fidelity": "Prevent the generated person from drifting into a different face type",
    "aesthetic_upgrade": "Before finalizing portrait prompts, check for aesthetic-upgrade risks",
    "symmetric_large_body_lock": "If a visible adult body feature is large or very large, preserve it against reduction",
    "symmetric_moderate_body_lock": "If it is moderate, moderate-to-full, slight, flat, broad, secondary, softened, low-detail, or obscured",
    "band_height_drift": "Treat band-height drift as a major fidelity failure",
    "garment_geometry": "Prefer visible garment geometry over broad fashion-category labels",
    "face_exposure_budget": "create a face exposure budget",
    "screenshot_ui_split": "audit the exact UI/content split before emitting",
    "absent_ui_controls": "home indicators, heart/reaction buttons, share buttons, profile avatars",
    "low_legibility_text": "preserve location, size, contrast, and readability level over exact transcription",
    "miniature_scale": "treat the scale relationship as a first-order concept lock",
    "endpoint_sensitive": "endpoint-sensitive appendage",
    "polish_amplifying": "audit for polish-amplifying phrases",
    "maturity_anti_collapse": "Do not let `cute`, `doll-like`, `toy-scale`, `large eyes`, `small mouth`, or `youthful` automatically collapse",
    "coordinate_contradictions": "audit internal contradictions before emitting",
    "secondary_detail_budget": "receives more words than its visible importance supports",
    "anti_polish": "Cap generated polish to the source.",
    "broad_label_discipline": "Weaken broad portrait, fashion, garment, product, genre, and body-region labels",
    "fidelity_ceiling": "Treat source fidelity ceiling as an affirmative requirement",
    "output_gate": "Confirm that `PROMPT:` contains the primary visual concept",
    "prompt_only_limits": "Report prompt-only limits honestly",
    "background_zoning": "Analyze background zoning as image-plane structure",
    "low_legibility_background": "keep them as low-detail background massing",
    "color_mood": "Preserve color mood, palette, color cast, saturation, contrast, shadow color, highlight color, and local color relationships",
    "unspecified_visual_medium": "When no specific medium is clear, preserve only visible medium evidence without forcing a photographic or rendered style.",
    "generic_subject_fallback": "When no specific subject module fits, preserve the main visible object or ordinary scene as a generic object/scene without inventing a category.",
}
