#!/usr/bin/env python3
"""Owned invariant phrases for reverse-image-prompt coverage checks."""

from __future__ import annotations

REQUIRED_ANCHOR_IDS = [
    "standalone_reference_ban",
    "visible_evidence_only",
    "causal_origin_attribution",
    "aspect_ratio_drift_major",
    "normalized_coordinates",
    "subject_environment_balance",
    "major_region_hierarchy",
    "primary_visual_concept",
    "concept_spec",
    "major_component_relation_graph",
    "major_component_topology",
    "interaction_geometry_sentence",
    "image_scene_space_distinction",
    "dominant_fidelity_axis",
    "aesthetic_invariants",
    "flexible_dimensions",
    "appeal_render_separation",
    "invariant_salience_ledger",
    "output_sections",
    "negative_primary_concept",
    "recommended_settings_aspect",
    "aesthetic_salience_gate",
    "aesthetic_signature_early",
    "detail_not_sharpness",
    "attractiveness_polish_separation",
    "aesthetic_causal_signature",
    "direct_perceptual_appeal",
    "aggregate_prior_cluster_audit",
    "background_legibility_ceiling",
    "color_causality",
    "sharpness_topology",
    "contrast_topology",
    "photographic_causal_decomposition",
    "color_light_decomposition",
    "light_to_form_strength",
    "face_fidelity",
    "broad_person_gestalt_anchor",
    "aesthetic_upgrade",
    "symmetric_large_body_lock",
    "symmetric_moderate_body_lock",
    "band_height_drift",
    "garment_geometry",
    "material_role",
    "category_prior_disambiguation",
    "human_body_form_signature",
    "muscle_lighting_separation",
    "skin_surface_signature",
    "body_region_hierarchy",
    "persistent_induced_form_split",
    "face_exposure_budget",
    "human_detail_hierarchy",
    "face_anchor_budget",
    "expression_gaze_hair_geometry",
    "screenshot_ui_split",
    "absent_ui_controls",
    "low_legibility_text",
    "miniature_scale",
    "endpoint_sensitive",
    "polish_amplifying",
    "maturity_anti_collapse",
    "coordinate_contradictions",
    "secondary_detail_budget",
    "semantic_salience_amplification",
    "semantic_claim_merge",
    "net_salience_audit",
    "replacement_correction",
    "module_evidence_not_prose",
    "clause_ownership",
    "diagnostic_render_separation",
    "detail_role_ceiling",
]

CORE_ANCHOR_IDS = [
    "standalone_reference_ban",
    "visible_evidence_only",
    "causal_origin_attribution",
    "aspect_ratio_drift_major",
    "normalized_coordinates",
    "subject_environment_balance",
    "major_region_hierarchy",
    "primary_visual_concept",
    "concept_spec",
    "major_component_relation_graph",
    "major_component_topology",
    "interaction_geometry_sentence",
    "image_scene_space_distinction",
    "dominant_fidelity_axis",
    "aesthetic_invariants",
    "flexible_dimensions",
    "appeal_render_separation",
    "invariant_salience_ledger",
    "output_sections",
    "negative_primary_concept",
    "recommended_settings_aspect",
    "coordinate_contradictions",
    "secondary_detail_budget",
    "semantic_salience_amplification",
    "semantic_claim_merge",
    "net_salience_audit",
    "replacement_correction",
    "anti_polish",
    "broad_label_discipline",
    "fidelity_ceiling",
    "aesthetic_salience_gate",
    "aesthetic_signature_early",
    "detail_not_sharpness",
    "attractiveness_polish_separation",
    "aesthetic_causal_signature",
    "direct_perceptual_appeal",
    "aggregate_prior_cluster_audit",
    "module_evidence_not_prose",
    "clause_ownership",
    "diagnostic_render_separation",
    "output_gate",
    "prompt_only_limits",
    "background_zoning",
    "low_legibility_background",
    "color_mood",
    "color_causality",
    "background_legibility_ceiling",
]

# Compatibility for callers created before the runtime legacy excerpts were retired.
LEGACY_ANCHOR_IDS = REQUIRED_ANCHOR_IDS

ANCHORS = {
    "standalone_reference_ban": "Never refer to the source image in the final prompt.",
    "visible_evidence_only": "Describe visible evidence only; do not invent hidden structure or context.",
    "causal_origin_attribution": "Before treating an observed contour, scale, color, surface, or definition as intrinsic, separate effects caused by pose or deformation, perspective, lighting or shadow, material interaction or occlusion, and capture or processing.",
    "aspect_ratio_drift_major": "Treat aspect-ratio drift as a major fidelity failure.",
    "normalized_coordinates": "Use normalized coordinates only for concept-critical anchors.",
    "subject_environment_balance": "Lock subject frame share and negative-space share before adding face or object micro-detail.",
    "major_region_hierarchy": "Map the few largest visually coherent regions as a major-region hierarchy before local detail.",
    "primary_visual_concept": "State the primary visual concept and perceptual relationship before inventory details.",
    "concept_spec": "Name each concept-critical element, its image-plane role, and its relationship.",
    "major_component_relation_graph": "Give each major component or coherent group at least one explicit spatial relation to another major component or stable reference zone.",
    "major_component_topology": "Preserve the side-of-boundary, containment, contact, support, and depth order of concept-critical elements.",
    "interaction_geometry_sentence": "For each concept-critical interaction, write one explicit relation sentence naming both elements, their relevant parts, the side or zone, any contact point, and what provides support when visible.",
    "image_scene_space_distinction": "Distinguish image-plane overlap from scene-space containment, contact, and support.",
    "dominant_fidelity_axis": "Classify the dominant fidelity axis as `relationship-led`, `appearance-led`, `information-led`, or `mixed` before deciding prompt order.",
    "aesthetic_invariants": "Separate aesthetic invariants from flexible dimensions before drafting.",
    "flexible_dimensions": "An invariant would materially weaken or change the proposition if altered; a flexible dimension may vary without losing it.",
    "appeal_render_separation": "Keep the direct appeal reading separate from the render contract",
    "invariant_salience_ledger": "Build an invariant salience ledger.",
    "output_sections": "Emit only sections required by the selected output mode.",
    "negative_primary_concept": "When a negative prompt is supported, reject only likely concept and fidelity drift.",
    "recommended_settings_aspect": "Separate source dimensions from the requested target size.",
    "aesthetic_salience_gate": "Use three to six mutually supporting look anchors only when the source aesthetic is high-salience; otherwise use one or two ordinary cues.",
    "aesthetic_signature_early": "When the source look materially differs from a clean default, place a compact Aesthetic Signature near the beginning of `PROMPT:`.",
    "detail_not_sharpness": "Treat descriptive detail and rendered sharpness as independent controls.",
    "attractiveness_polish_separation": "Treat subject attractiveness and image polish as separate controls.",
    "aesthetic_causal_signature": "Build a sparse Aesthetic Causal Signature from only the form, surface, light-to-form, color, sharpness, and hierarchy axes that materially create the image's perceptual proposition.",
    "direct_perceptual_appeal": "In diagnostic mode, name the source-supported perceptual appeal directly before decomposing it into visible mechanisms.",
    "aggregate_prior_cluster_audit": "Audit prior-heavy cues as a combined cluster, not only as isolated labels.",
    "background_legibility_ceiling": "Treat background legibility and information density as part of the source aesthetic.",
    "color_causality": "Separate intrinsic surface color from illumination color, global color cast, and exposure.",
    "sharpness_topology": "Map sharpness separately across the primary subject, secondary details, foreground, and background.",
    "contrast_topology": "Map contrast topology separately at the global scene, major subject masses, local form transitions, and surface/material boundaries.",
    "photographic_causal_decomposition": "Decompose photographic appearance into intrinsic subject evidence, pose or deformation, perspective, illumination and shadow, material interaction or occlusion, and capture or processing.",
    "color_light_decomposition": "Record important color relationships as intrinsic surface hue, illumination color, global cast, and exposure response.",
    "light_to_form_strength": "Set light-to-form strength source-relatively as flattening, subtle revelation, moderate separation, or strong sculpture.",
    "face_fidelity": "Prevent the generated person from drifting into a different visible face type.",
    "broad_person_gestalt_anchor": "Describe each non-identifying fictional person coarse-to-fine: use one compact broad person-gestalt anchor when it materially reduces ambiguity, then constrain it with visible geometry and source-specific corrections.",
    "aesthetic_upgrade": "Check portrait prompts for aesthetic-upgrade drift.",
    "symmetric_large_body_lock": "Preserve a clearly visible large-scale body silhouette without exaggeration or reduction.",
    "symmetric_moderate_body_lock": "Keep a moderate or obscured body silhouette secondary rather than promoting it.",
    "band_height_drift": "Treat visible band-height drift as a composition failure.",
    "garment_geometry": "Prefer visible garment geometry over broad fashion-category labels.",
    "material_role": "Assign each visible garment or accessory a material role: primary subject, silhouette boundary, frame, texture support, or low-legibility mass.",
    "category_prior_disambiguation": "Before using a garment category label, specify the visible opacity, thickness, weight, weave or knit scale, finish, and construction cues that must override its default prior.",
    "human_body_form_signature": "Build a visible human-body form signature from source-supported proportion, contour, tissue, tension, and region hierarchy rather than from a body-type label.",
    "muscle_lighting_separation": "Separate visible muscle or skeletal definition from contour created by pose, perspective, garment pressure, highlight, self-shadow, and cast shadow.",
    "skin_surface_signature": "Describe skin as a surface system: lightness, hue family, saturation, undertone, tonal variation, finish, texture, and response to light only where visible.",
    "body_region_hierarchy": "Assign each visible body region a hierarchy role—primary form, structural connector, supporting mass, edge crop, or low-legibility background evidence.",
    "persistent_induced_form_split": "Split persistent body-form evidence from induced appearance before selecting prompt controls.",
    "face_exposure_budget": "Define a face visibility budget before choosing a broad person-gestalt anchor or local face detail.",
    "human_detail_hierarchy": "Allocate human detail by visible face scale and legibility.",
    "face_anchor_budget": "For a prominent legible face, choose six to ten likeness-bearing visible anchors instead of listing every facial field.",
    "expression_gaze_hair_geometry": "Preserve expression, gaze, and hair-to-face occlusion as likeness-critical geometry.",
    "screenshot_ui_split": "Audit the exact UI/content split before emitting.",
    "absent_ui_controls": "Do not invent absent UI controls.",
    "low_legibility_text": "Preserve location, size, contrast, and readability level before exact transcription.",
    "miniature_scale": "Treat the scale relationship as a first-order concept lock.",
    "endpoint_sensitive": "Treat a cropped or obscured appendage as endpoint-sensitive.",
    "polish_amplifying": "Audit for polish-amplifying phrases.",
    "maturity_anti_collapse": "Do not let cute or doll-like cues automatically collapse an adult-looking stylized subject into a childlike one.",
    "tight_selfie_hierarchy": "When tight selfie framing makes the face and hair the primary anchors",
    "accessory_torso_budget": "Treat accessories and cropped torso regions as measured support budgets",
    "partial_cheek_hand_budget": "Keep cheek-hand contact as a partial edge-cropped support gesture",
    "coordinate_contradictions": "Audit coordinate contradictions before emitting.",
    "secondary_detail_budget": "Check whether a secondary element receives more words than its visible importance supports.",
    "semantic_salience_amplification": "Audit semantic salience amplification across exact repeats, synonyms, paraphrases, labels, negatives, and settings; a repeatedly described dimension gains visual priority even when no sentence is duplicated verbatim.",
    "semantic_claim_merge": "Merge candidate claims by semantic slot before writing prose; each emitted slot has one clause owner.",
    "net_salience_audit": "Compare each slot's aggregate direction and strength with its source target.",
    "replacement_correction": "Correct an overstrong draft by replacing or deleting the amplifying language, not by appending a negative counterweight.",
    "anti_polish": "Cap generated polish to the source.",
    "broad_label_discipline": "Weaken broad portrait, fashion, garment, product, genre, and body-region labels",
    "fidelity_ceiling": "Treat source fidelity ceiling as an affirmative requirement",
    "module_evidence_not_prose": "Selected modules contribute evidence candidates, not mandatory prose.",
    "clause_ownership": "Assign one clause owner to each emitted semantic slot.",
    "diagnostic_render_separation": "Keep diagnostic appeal language separate from render instructions",
    "output_gate": "Confirm that `PROMPT:` contains the primary visual concept",
    "prompt_only_limits": "Report prompt-only limits honestly",
    "background_zoning": "Analyze background zoning as image-plane structure",
    "low_legibility_background": "keep them as low-detail background massing",
    "color_mood": "Preserve color mood, palette, color cast, saturation, contrast, shadow color, highlight color, and local color relationships",
    "detail_role_ceiling": "Cap material and construction detail to the garment's hierarchy role",
    "unspecified_visual_medium": "When no specific medium is clear, preserve only visible medium evidence without forcing a photographic or rendered style.",
    "generic_subject_fallback": "When no specific subject module fits, preserve the main visible object or ordinary scene as a generic object/scene without inventing a category.",
}
