"""Bind the coordinator's direct native-pixel observations to the first images.

This records human-readable observations, not an automatic image scorer. No
generated image is edited, enlarged, or regenerated by this script.
"""
from pathlib import Path
import hashlib
import json

ROOT = Path(__file__).resolve().parent


def digest(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def gate(keyword, status, evidence):
    return {"keyword": keyword, "status": status, "native_pixel_evidence": evidence}


rows = [
    {
        "arm": "arm-1",
        "image": "generated_image-1.png",
        "review_basis": "Original 1024 x 1536 image and unchanged-resolution cuff, necklace and pleat inspection crops; parent recorded an independent observation set.",
        "keyword_gates": [
            gate("princess seam", "PASS", "Curving continuous panel joins descend from the upper bodice across its shaped sides into the fitted waist; they belong to the teal dress."),
            gate("sweetheart neckline", "PASS", "The attached upper bodice edge has two rounded lobes and a distinct central dip."),
            gate("gigot sleeve", "PASS", "Both upper sleeves have large gathered shoulder and upper-arm volume, then narrow substantially below the elbows to the cuffs."),
            gate("welt pocket", "PASS", "Both hip sites show horizontal dark openings framed by slim fabric lips, continuous with the dress panels."),
            gate("piping", "PARTIAL", "Ivory edging is present at neckline and cuffs, but the cuff crop shows a strip whose raised cord section cannot be separated reliably from flat binding at native resolution."),
            gate("inverted box pleat", "PASS", "Two front panel fold edges converge above and open over an inset cloth panel below; recessed cloth and edge shadows establish the inward-facing fold arrangement."),
            gate("pendant bail", "PARTIAL", "A rectangular pendant hangs from the chain, but the tiny connector does not resolve an independently open loop and the chain's passage through it."),
            gate("Derby", "PASS", "The near shoe shows eyelet-bearing quarters layered above the vamp and open edges around a visible tongue; both shoes are in frame."),
        ],
        "additional_observations": [
            {"status": "PASS", "evidence": "One wearer, connected limbs and both floor-contacting shoes are visible in the library entrance. The standing geometry is coherent."},
            {"status": "PARTIAL", "evidence": "All eight target sites are in frame, but simultaneous full visibility of the tiny bail relation and raised piping section is insufficient."},
        ],
    },
    {
        "arm": "arm-2",
        "image": "first-native.png",
        "review_basis": "Original first native image directly inspected before receiving the arm's final pixel verdict; no other arm's result was given to this agent.",
        "keyword_gates": [
            gate("Henley", "PASS", "A collarless round neck connects to a short chest button placket, with several distinct button shapes and no full-length front opening."),
            gate("raglan", "PASS", "Diagonal shoulder joins descend from the neckline toward the underarm fields, independently of the vertical body cables."),
            gate("cable knit", "PASS", "Repeated raised yarn braids visibly cross on the ochre pullover body and sleeves."),
            gate("rib knit", "PASS", "Fine parallel ribs finish the cuffs and free lower hem, contrasting with the crossed body cables."),
            gate("cargo pocket", "PASS", "The near trouser thigh has an attached rectangular patch pocket, flap and projecting side/fold wall."),
            gate("drawstring", "PASS", "Two cord paths emerge at the trouser waist and form a tied loop with dangling ends there."),
            gate("half tuck", "PASS", "One front sector meets and disappears into the waistband while the opposite near-side ribbed hem hangs below and outside it."),
            gate("layer order", "PASS", "A cream inner jersey neck edge is visible beneath the open ochre neck and placket boundaries."),
        ],
        "additional_observations": [
            {"status": "PASS", "evidence": "Connected arms reach the board; the near hand wraps its edge and the other hand reaches its far corner. Board contact with the tabletop and bowls' contact with the board are visible."},
            {"status": "PASS", "evidence": "Both boots meet the floor. The forward body lean, bent elbows and foot spacing are consistent with moving the supported board."},
        ],
    },
    {
        "arm": "arm-3",
        "image": "generated-first.png",
        "review_basis": "Original 1024 x 1536 first native image directly inspected; agent verdict was also available and is kept separately.",
        "keyword_gates": [
            gate("jeogori", "PASS", "A sage short jacket has connected long sleeves, a crossing front and a hem ending above the blue skirt."),
            gate("dongjeong", "PASS", "A distinct white strip follows the jacket's crossing collar edge; it belongs to that collar."),
            gate("goreum", "PASS", "An attached cream front tie has a visible knot, lateral loop and two descending tails."),
            gate("norigae", "PARTIAL", "Decorative knots, an oval pendant and a long tassel are visible, but the upper attachment disappears behind the tie; its loop-to-goreum path cannot be traced."),
            gate("chima", "PASS", "The navy high-waist skirt shows a horizontal top band above repeated gathered or pleated fabric spreading below."),
            gate("layer order", "PASS", "The short jacket hem lies outside and above the visible chima band and skirt; separate boundaries establish their order."),
            gate("bezel setting", "PASS", "A continuous light metallic rim surrounds the green oval center and retains it around its visible perimeter."),
            gate("pendant bail", "PARTIAL", "The pendant's upper connector is too small and merges with the decorative knot to resolve a separate open bail bridging the cord and pendant."),
        ],
        "additional_observations": [
            {"status": "FAIL", "evidence": "The black case is held on screen-left by the actor's right hand; the frozen case requested actor-left."},
            {"status": "PARTIAL", "evidence": "The norigae upper connection and bail topology are not visible enough for whole-case qualification, although larger garment boundaries are clear."},
        ],
    },
]

for row in rows:
    arm_root = ROOT / row["arm"]
    image_path = arm_root / row.pop("image")
    row["result_image"] = str(image_path)
    row["result_sha256"] = digest(image_path)
    row["test_case_sha256"] = digest(arm_root / "test_case.json")
    row["keyword_counts"] = {
        status: sum(g["status"] == status for g in row["keyword_gates"])
        for status in ("PASS", "PARTIAL", "FAIL")
    }
    row["keyword_qualification"] = (
        "PASS" if all(g["status"] == "PASS" for g in row["keyword_gates"]) else "FAIL"
    )
    row["whole_case_qualification"] = (
        "PASS" if row["keyword_qualification"] == "PASS" and
        all(g["status"] == "PASS" for g in row["additional_observations"]) else "FAIL"
    )
    row["reference_scope"] = "Visible face and dark short bob/fringe appearance only. Explicit adult generation is a scenario choice, not an inference about the reference person's actual age. No identity or body correspondence asserted."

payload = {
    "contract_version": "clothing-coordinator-native-pixel-review/v1",
    "reviewer": "root coordinator",
    "source_data_freeze_sha256": digest(ROOT / "data-freeze.json"),
    "policy": "partial_is_fail",
    "automated_pixel_scoring": False,
    "user_acceptance": "pending",
    "causal_improvement_over_baseline": "not_established; no matched baseline render",
    "arms": rows,
}
(ROOT / "coordinator-review.json").write_text(
    json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
)
print(json.dumps({row["arm"]: row["whole_case_qualification"] for row in rows}))
