import pathlib,json,hashlib
b=pathlib.Path(__file__).resolve().parent;repo=pathlib.Path('/Users/chasoik/Projects/image-prompt');p=json.loads((b/'candidate_pack.json').read_text())[0];c=json.loads((b/'composed_prompt.json').read_text());result=json.loads((b/'qualification_result.json').read_text());a=json.loads((b/'composition_audit.json').read_text());runtime=json.loads((b/'runtime_audit.json').read_text());review=json.loads((b/'render_review_audit.json').read_text());binding=json.loads((b/'render_input_hashes.json').read_text());meta=json.loads((b/'native_attempt03_success.json').read_text());ledger=json.loads((b/'cumulative_attempt_provenance.json').read_text());source=json.loads((b/'source_manifest.json').read_text())
assert a['status']=='pass' and runtime['status']=='pass' and not a['failures'] and not runtime['failures'];assert review['schema_failures']==[] and review['technical_qualified'] is False and len(review['failed_hard_gates'])==2
for path,sha in binding['files'].items(): assert hashlib.sha256(pathlib.Path(path).read_bytes()).hexdigest()==sha,path
assert hashlib.sha256(pathlib.Path(meta['preserved_original_path']).read_bytes()).hexdigest()==meta['image_sha256'];assert hashlib.sha256(pathlib.Path(meta['returned_original_path']).read_bytes()).hexdigest()==meta['image_sha256'];ref=json.loads((b/'render_request.json').read_text())['references'][0];assert hashlib.sha256(pathlib.Path(ref['path']).read_bytes()).hexdigest()==ref['sha256']
for path,sha in ledger['v1_artifacts_hash_only_inventory'].items():assert hashlib.sha256(pathlib.Path(path).read_bytes()).hexdigest()==sha,path
expected={'authorial_core.json':'411436e1cf894d91af673f4c235a24e9e8cced4b3d8efbe40f6e7a53ef30687d','creative_controls.json':'cb43e2fb4a04a5d3d7adabc463e6effab735df89c9f75f01dedb5cf986e1f02f','request_envelope.json':'6363571a23798ee6104c62e278243f22b67b7a7596600458b7580ed00927c62c'}
for f,sha in expected.items():assert hashlib.sha256((b/f).read_bytes()).hexdigest()==sha
assert p['authorial_core']['canonical_sha256']=='a7aff6a3462a015b8a5c985d13dbdc48160493ef9a67b395ea477a0e8fcbff51' and p['authorial_core']['intent_lock']['canonical_sha256']=='7a26d10876c1f9502c89381a46295016eb8a2787739e3e1daad485a50eb6446a'
post=json.loads((b/'keyword_target_ledger.json').read_text());post.update({'pre_render':False,'pre_render_ledger_unchanged':True,'result_image':meta['preserved_original_path'],'result_sha256':meta['image_sha256'],'effect_results':result['effects'],'all_of_verdict':result['strict_all_of_verdict'],'review_audit_path':str(b/'render_review_audit.json')});(b/'keyword_target_ledger_post_render.json').write_text(json.dumps(post,ensure_ascii=False,indent=2)+'\n')
result.update({'composition_audit_status':a['status'],'runtime_audit_status':runtime['status'],'composition_warning_count':len(a['warnings']),'render_review_schema_failures':review['schema_failures'],'render_review_technical_qualified':review['technical_qualified'],'render_review_qualification_status':review['qualification_status'],'ledger_run_id':ledger['new_run_id'],'prompt_id':ledger['new_prompt_id'],'selected_candidate_ids':c['chosen_candidate_ids'],'selected_visual_concept_ids':c['chosen_visual_concept_ids'],'effective_visual_contract_sha256':a['effective_visual_contract_sha256'],'source_dictionary_sha256':source['dictionary_sha256'],'source_registry_sha256':source['registry_sha256'],'source_pack_sha256':json.loads((b/'selected_candidate_details.json').read_text())['source_pack_sha256'],'core_canonical_sha256':p['authorial_core']['canonical_sha256'],'intent_lock_sha256':p['authorial_core']['intent_lock']['canonical_sha256'],'prompt_sha256':hashlib.sha256(c['prompt_en'].encode()).hexdigest(),'prompt_words':binding['word_count'],'v1_preserved':True,'artifacts':{'prompt':str(b/'prompt_en.txt'),'negative':str(b/'negative_en.txt'),'pack':str(b/'candidate_pack.json'),'runtime_request':str(b/'render_request.json'),'pre_render_tests':str(b/'pre_render_test_cases.json'),'target_ledger':str(b/'keyword_target_ledger.json'),'target_ledger_post_render':str(b/'keyword_target_ledger_post_render.json'),'image_runs':str(b/'image_runs.ndjson'),'manifest':str(b/'run_manifest.json'),'native_diagnostics':str(b/'native_read_only_diagnostics.json'),'pixel_review':str(b/'moe_render_review.json'),'pixel_review_audit':str(b/'render_review_audit.json'),'reference_scope_review':str(b/'reference_scope_review.json')}})
(b/'qualification_result.json').write_text(json.dumps(result,ensure_ascii=False,indent=2)+'\n')
text=f'''Arm C v2는 후보 노출·조합·런타임 감사에 통과했으나, 실제 픽셀의 엄격 전체 판정은 **FAIL (효과 1/3 통과)** 입니다. PARTIAL은 FAIL로 처리했습니다. 사용자 수용 판단은 pending입니다.

| 테스트 | 원본 픽셀 결과 | 근거 |
| --- | --- | --- |
| 붉은 문진 컬러 스플래시 | FAIL | 문진은 붉지만 나머지 화면에 넓은 따뜻한/세피아 색조가 남음. 문진 마스크 외 RGB 채널차 중앙값 7/255; 88.36%가 3 초과. |
| 상승 검정 계조 | FAIL | 어두운 세부는 읽히지만 가장 깊은 머리뿌리와 선반 안쪽에 충분히 명백한 soft-charcoal floor가 유지되지 않음. 뿌리 p01 휘도 21.82, p05 28.07; 선반 p01 24.07. |
| 피부결 보존 국부 톤 정리 | PASS | 원래 해상도에서 볼의 국부 톤 전환과 미세 모공/자연스러운 피부 변화가 함께 읽히며, 참조 얼굴의 가시적 구성이 유지됨. |

선택 프로필 게이트 4/6, 물리 게이트 5/5, 결합 게이트 9/11입니다. `vo_pe_red_object_splash_relation_2`와 `vo_pe_lifted_black_floor_relation_1`이 실패했습니다. 형태·소유·관절/도달·지지·접촉·가시성의 물리 조건과 얼굴/헤어 범위의 참조 가이드는 통과했습니다. 픽셀 감사 레코드의 schema_failures는 빈 목록이며 technical_qualified는 false입니다. 감사기는 사람이 작성한 픽셀 근거를 검증하며 픽셀을 독립 추론하지 않습니다.

원래 secrets 랜덤 seed `8f0040ca75299371254dbda8c32957fd`와 theater-repair 컨셉을 그대로 사용했습니다. 마지막 공연 직후 극장 소품 수리실에서, 가상의 성인 여성이 붉은 에나멜 문진과 반대 손으로 말리는 무대 도면을 펴면서 사진가를 잠깐 바라봅니다. 새 장면·새 core·새 controls resolver·requester lock 승격은 없습니다. 이전 안전한 retry의 단추 잠긴 면 작업셔츠와 neutral engaged expression을 유지하는 open authorial repair를 적용했습니다. 가장 낮은 계조의 45/255 표현은 렌더 안내이며 새로운 requester 수치 조건이나 독립 판정 임계값이 아닙니다.

v2 source로 정확히 한 팩 `{p['pack_id']}`을 생성했고 compact composer view를 먼저 읽은 뒤 전체 선택 상세를 읽었습니다. 실제 선택 후보는 `slot:color_grading:pe_red_object_splash`, `slot:color_grading:pe_lifted_black_floor`, `slot:skin_finish:pe_texture_preserving_tone_evening`입니다. 실제 선택 opt-in 프로필은 `visual-concept:pe_red_object_splash_relation`, `visual-concept:pe_lifted_black_floor_relation`, `visual-concept:pe_texture_preserving_tone_evening_relation`입니다. 세 슬롯의 모든 concept unit/relation과 세 프로필의 모든 literal component/게이트를 보존했습니다. 관련 없는 optional bundle은 선택하지 않았습니다.

최종 prompt는 {binding['word_count']} 단어입니다. composed/runtime PASS, negative 원문 일치, reference 파일 해시 일치입니다. 조합의 일반 anchor 후보 미노출 경고 4개는 literal free description으로 보존된 원래 네 anchor에 대한 경고이며 실패는 없습니다. 이 결과는 올바른 후보 노출이 실제 픽셀 성공을 보장하지 않는다는 증거입니다.

builtin `image_gen.imagegen`을 v2에서 1회 호출했습니다. arm 누적 호출은 3회이며 v1의 최초 safety block은 unscored로, 성공 retry와 모든 원문/ledger/image를 그대로 보존했습니다. 새 성공 run `{ledger['new_run_id']}`은 v1의 마지막 run `598e8c9471e7c156`에 연결했습니다. 추가 생성이나 CLI/provider 전환은 없었습니다. v2 누적 ledger는 v1 두 행을 정확한 byte prefix로 보존하고 세 번째 행만 추가합니다.

원본 경로: `{meta['preserved_original_path']}`

원본 SHA256: `{meta['image_sha256']}`; 1237×1272. 반환된 원래 파일과 보존본이 byte-identical입니다. 검사 crop은 정수 좌표의 원래 해상도 잘라보기만 수행했으며 색·톤·필터·크기 변경은 없습니다. 모든 결과는 같은 저장 이미지에서 판정했습니다.

source dictionary SHA `{source['dictionary_sha256']}`; registry SHA `{source['registry_sha256']}`; pack object SHA `{result['source_pack_sha256']}`; core canonical SHA `{result['core_canonical_sha256']}`; intent-lock SHA `{result['intent_lock_sha256']}`; effective visual contract SHA `{a['effective_visual_contract_sha256']}`; prompt SHA `{result['prompt_sha256']}`. 파일별 원본 SHA는 `render_input_hashes.json`과 `artifact_hashes.json`에 있습니다.

재현·검토 근거는 `pre_render_test_cases.json`, `keyword_target_ledger.json`, `keyword_target_ledger_post_render.json`, `moe_render_review.json`, `render_review_audit.json`, `native_read_only_diagnostics.json`, `reference_scope_review.json`, `image_runs.ndjson`, `run_manifest.json`, `cumulative_attempt_provenance.json`입니다. 참조는 성인 가상 인물의 가시적 얼굴·헤어에만 적용했으며 신원·생체·성향·체형이나 사용자 수용을 주장하지 않습니다.
'''
(b/'qualification_report.md').write_text(text,encoding='utf-8')
inv={str(x.resolve()):hashlib.sha256(x.read_bytes()).hexdigest() for x in sorted(b.rglob('*')) if x.is_file() and x.name!='artifact_hashes.json'};(b/'artifact_hashes.json').write_text(json.dumps({'schema_version':'photo-artifact-hashes/v1','revision':'v2','files':inv,'original_and_reference_unchanged':True,'pre_render_bindings_unchanged':True,'v1_preservation_verified':True},ensure_ascii=False,indent=2)+'\n')
print(json.dumps({'strict_verdict':result['strict_all_of_verdict'],'effects':result['effect_pass_count'],'source_exposure':'3 targets and corresponding 3 profiles present/selected','core_controls_envelope_bytes_unchanged':True,'v1_ledger_byte_prefix_preserved':True,'artifact_file_count':len(inv),'result_path':str(b/'qualification_result.json'),'report_path':str(b/'qualification_report.md'),'run_id':ledger['new_run_id']},indent=2))
