import pathlib,json,hashlib,sys,re,datetime
repo=pathlib.Path('/Users/chasoik/Projects/image-prompt');b=pathlib.Path(__file__).resolve().parent;sys.path.insert(0,str(repo/'skills/photo-prompt-image-generator/scripts'));import audit_composed_prompt,photo_embodiment
p=json.loads((b/'candidate_pack.json').read_text())[0];c=json.loads((b/'composed_prompt.json').read_text());a=json.loads((b/'composition_audit.json').read_text());assert a['status']=='pass' and not a['failures']
effective,failures=audit_composed_prompt.derive_effective_visual_obligation_contract(p,c);assert not failures;assert audit_composed_prompt.effective_visual_obligation_sha256(effective)==a['effective_visual_contract_sha256'];body_gates,failures=photo_embodiment.render_gate_ids(p,c);assert not failures
ref=pathlib.Path('/Users/chasoik/Downloads/0CB25F47-BB90-4DBD-8993-733BA8282851(20260927-041323).jpeg');refsha=hashlib.sha256(ref.read_bytes()).hexdigest();assert refsha=='06d6c6feeed0d2397ec9562d46113cd221ac54a0e190295f0aa7f7868c22ece7'
runtime=c['prompt_en']+'\n\nAvoid: '+c['negative_en']
r={'schema_version':'photo-image-render-request/v2','pack_id':p['pack_id'],'runtime_prompt_en':runtime,'runtime_negative_en':c['negative_en'],'source_intent_lock_sha256':p['authorial_core']['intent_lock']['canonical_sha256'],'source_embodiment_preflight_sha256':p['embodiment_preflight']['canonical_sha256'],'effective_visual_contract_sha256':a['effective_visual_contract_sha256'],'references':[{'path':str(ref),'sha256':refsha,'role':'Visible adult face and hair appearance guidance for the fictional adult woman; no identity, biometric, trait or body inference.'}],'audit_boundary':{'composed_prompt_audit_status':a['status'],'runtime_prompt_audit_status':'not_run','inherits_composed_prompt_pass':False}}
args={'prompt':runtime,'referenced_image_paths':[str(ref)],'transparent_background':False}
source=json.loads((b/'source_manifest.json').read_text());rawcore=json.loads((b/'authorial_core.json').read_text());details=json.loads((b/'selected_candidate_details.json').read_text())
checklist={'contract_version':'photo-qualification-pre-render/v1','created_at':datetime.datetime.now(datetime.timezone.utc).isoformat(),'arm_id':'arm-c-tonal-skin','revision':'v2','random_seed_hex':'8f0040ca75299371254dbda8c32957fd','same_frozen_core':True,'same_frozen_controls':True,'same_frozen_request_envelope':True,'source_dict_sha256':source['dictionary_sha256'],'source_registry_sha256':source['registry_sha256'],'pack_id':p['pack_id'],'source_pack_sha256':details['source_pack_sha256'],'effective_visual_contract_sha256':a['effective_visual_contract_sha256'],'prompt_sha256':hashlib.sha256(c['prompt_en'].encode()).hexdigest(),'negative_sha256':hashlib.sha256(c['negative_en'].encode()).hexdigest(),'runtime_prompt_sha256':hashlib.sha256(runtime.encode()).hexdigest(),'reference_sha256':refsha,'target_authority':'agent-authored advisory test goals; explicit composer profile opt-in adds hard visual gates without changing requester locks','test_cases':[],'required_selected_profile_gates':effective['required_hard_gates'],'required_physical_gates':body_gates,'required_reference_review':'visible face/hair guidance only','strict_all_of':True,'partial_is_fail':True,'blocked_calls':'unscored','user_acceptance':'pending','diagnostic_rules':{'color_splash':'Native visual review must show the existing crimson paperweight as sole colored region and every remaining region achromatic. Read-only RGB spread outside a generous prop mask can corroborate visual tint; tolerance diagnostics do not waive the contract.','lifted_blacks':'Inspect deepest roots and shelf recesses at native scale for clearly visible neutral-charcoal floor and preserved strand/wood distinctions. The authorial approximately 45/255 cue is a rendering guide, not a new requester lock or substitute for visible gray.','skin_detail':'Inspect cheeks at native scale for locally smooth tonal transitions plus independent fine pores/natural variations; preserved face/hair configuration and no artificial facial-geometry alteration are separate checks.'}}
for ob in effective['obligations']:
 row={'profile_id':ob['id'],'selected_visual_concept_id':'visual-concept:'+ob['id'],'component_semantics':ob['component_semantics'],'render_gates':ob['render_gates'],'literal_component_evidence':c['visual_obligation_evidence'][ob['id']],'reject_substitutes':ob['reject_substitutes'],'same_image_required':True};checklist['test_cases'].append(row)
ledger={'schema_version':'photo-keyword-target-ledger/v1','revision':'v2','pre_render':True,'targets':rawcore['semantic_assertions'],'target_source':'unchanged original frozen core advisory assertions','required_requester_assertions_added':False,'selected_candidate_ids':c['chosen_candidate_ids'],'selected_visual_concept_ids':c['chosen_visual_concept_ids'],'selected_candidate_interpretations':c['candidate_interpretations'],'selected_profile_components':c['visual_obligation_evidence'],'selected_effective_contract_sha256':a['effective_visual_contract_sha256'],'pre_render_gate_checklist_path':str(b/'pre_render_test_cases.json'),'test_grading':'all targets, all opted-in gates, physical gates and scoped reference guidance in this single saved image; partial_is_fail'}
for f,x in [('render_request.json',r),('native_tool_args.json',args),('effective_visual_contract.json',effective),('pre_render_test_cases.json',checklist),('keyword_target_ledger.json',ledger)]: (b/f).write_text(json.dumps(x,ensure_ascii=False,indent=2)+'\n')
(b/'runtime_prompt_en.txt').write_text(runtime,encoding='utf-8')
keys=['authorial_core.json','creative_controls.json','request_envelope.json','candidate_pack.json','composer_view.json','selected_candidate_details.json','composed_prompt.json','prompt_en.txt','negative_en.txt','render_request.json','native_tool_args.json','runtime_prompt_en.txt','effective_visual_contract.json','pre_render_test_cases.json','keyword_target_ledger.json','source_manifest.json']
binding={'schema_version':'photo-render-input-hashes/v1','pack_id':p['pack_id'],'source_authorial_core_sha256':p['authorial_core']['canonical_sha256'],'source_intent_lock_sha256':p['authorial_core']['intent_lock']['canonical_sha256'],'effective_visual_contract_sha256':a['effective_visual_contract_sha256'],'files':{str(b/f):hashlib.sha256((b/f).read_bytes()).hexdigest() for f in keys},'word_count':len(re.findall(r"[A-Za-z]+(?:[-'][A-Za-z]+)*",c['prompt_en'])),'actual_prior_image_calls':2,'authorized_new_image_calls':1,'expected_cumulative_image_calls_after_invocation':3}
(b/'render_input_hashes.json').write_text(json.dumps(binding,ensure_ascii=False,indent=2)+'\n');print(json.dumps({'pack_id':p['pack_id'],'word_count':binding['word_count'],'effective_visual_contract_sha256':a['effective_visual_contract_sha256'],'prompt_sha256':checklist['prompt_sha256'],'gate_count':len(effective['required_hard_gates'])+len(body_gates)},indent=2))
