import pathlib,hashlib,json,shutil,subprocess,sys
repo=pathlib.Path('/Users/chasoik/Projects/image-prompt');b=pathlib.Path(__file__).resolve().parent;arm=b.parent
c=json.loads((b/'composed_prompt.json').read_text());p=json.loads((b/'candidate_pack.json').read_text())[0];a=json.loads((b/'composition_audit.json').read_text());r=json.loads((b/'render_request.json').read_text());meta=json.loads((b/'native_attempt03_success.json').read_text())
old=arm/'image_runs.ndjson';oldbytes=old.read_bytes();expected_oldsha=hashlib.sha256(oldbytes).hexdigest();ledger=b/'image_runs.ndjson';assert not ledger.exists();shutil.copyfile(old,ledger)
# Copy is a byte preservation operation, not candidate/prompt consultation.
assert ledger.read_bytes()==oldbytes
source_ref='source-snapshot-v2:sha256:'+hashlib.sha256((b/'source_manifest.json').read_bytes()).hexdigest()
generator_argv=['.venv/bin/python','skills/photo-prompt-image-generator/scripts/generate_photo_prompt.py','--request-envelope-json',str(b/'request_envelope.json'),'--authorial-core-json',str(b/'authorial_core.json'),'--creative-controls-json',str(b/'creative_controls.json'),'--embodiment-review-json',str(b/'embodiment_review.json'),'--candidate-pack-version','v6','--emit-candidate-pack','--n','1']
cmd=[str(repo/'.venv/bin/python'),str(repo/'skills/photo-prompt-image-generator/scripts/record_image_run.py'),'--ts',meta['started_at'],'--concept','Theater prop repair immediately after final curtain; red enamel paperweight flattens curling scenery plan as the adult worker looks toward the photographer.','--prompt-en',c['prompt_en'],'--negative-en',c['negative_en'],'--prompt-id',hashlib.sha256(c['prompt_en'].encode()).hexdigest()[:16],'--seed',str(p['provenance']['seed']),'--attempt','3','--retry-of','598e8c9471e7c156','--status','success','--image-path',meta['preserved_original_path'],'--tool','image_gen.imagegen','--generation-environment','codex_native','--argv-json',json.dumps(generator_argv),'--pack-id',p['pack_id'],'--chosen-candidate-ids-json',json.dumps(c['chosen_candidate_ids']),'--chosen-visual-concept-ids-json',json.dumps(c['chosen_visual_concept_ids']),'--effective-visual-contract-sha256',a['effective_visual_contract_sha256'],'--composer','agent','--audit-status','pass','--arm-id','arm-c-tonal-skin','--worktree-id',str(repo)+'::isolated-artifact-directory='+str(b),'--skill-sha256',hashlib.sha256((b/'SKILL.snapshot.md').read_bytes()).hexdigest(),'--source-ref',source_ref,'--candidate-pack-version','v6','--authorial-core-sha256',p['authorial_core']['canonical_sha256'],'--intent-lock-sha256',p['authorial_core']['intent_lock']['canonical_sha256'],'--reference-sha256',r['references'][0]['sha256'],'--image-call-count','3','--independent-no-cross-arm-inputs','--manifest',str(b/'run_manifest.json'),'--ledger',str(ledger)]
(b/'recorder_invocation.json').write_text(json.dumps({'shell':False,'argv':cmd,'image_call_count_scope':'arm cumulative; v1=2 and v2=1','previous_ledger_sha256':expected_oldsha,'previous_ledger_byte_count':len(oldbytes),'revision_generation_argv':generator_argv},ensure_ascii=False,indent=2)+'\n')
res=subprocess.run(cmd,cwd=repo,text=True,capture_output=True);(b/'recorder_output.json').write_text(json.dumps({'exit_code':res.returncode,'stdout':res.stdout,'stderr':res.stderr},ensure_ascii=False,indent=2)+'\n');print(res.stdout);assert res.returncode==0,res.stderr
assert old.read_bytes()==oldbytes;newbytes=ledger.read_bytes();assert newbytes.startswith(oldbytes);rows=newbytes.splitlines();assert len(rows)==3
last=json.loads(rows[-1]);assert last['attempt']==3 and last['status']=='success' and last['prompt_en']==c['prompt_en'] and last['negative_en']==c['negative_en'] and last['image_call_count']==3
preserved={str(x.resolve()):hashlib.sha256(x.read_bytes()).hexdigest() for x in sorted(arm.rglob('*')) if x.is_file() and b not in x.parents}
summary={'schema_version':'photo-cumulative-attempt-provenance/v1','previous_v1_ledger_sha256':expected_oldsha,'v2_cumulative_ledger_sha256':hashlib.sha256(newbytes).hexdigest(),'inherited_rows':2,'new_rows':1,'actual_cumulative_calls':3,'actual_v2_calls':1,'new_run_id':last['run_id'],'new_prompt_id':last['prompt_id'],'retry_of':last['retry_of'],'v1_ledger_unchanged':True,'v1_rows_preserved_as_exact_byte_prefix':True,'v1_artifacts_hash_only_inventory':preserved,'scope_note':'No v1 candidate inventories or optional prose consulted; this inventory records byte preservation. Original whitelist core/controls/envelope, defect evidence and safe portrayal governed this v2 revision.'}
(b/'cumulative_attempt_provenance.json').write_text(json.dumps(summary,ensure_ascii=False,indent=2)+'\n')
print(json.dumps({k:v for k,v in summary.items() if k!='v1_artifacts_hash_only_inventory'},indent=2))
