import pathlib,json,hashlib,datetime
b=pathlib.Path(__file__).resolve().parent;p=json.loads((b/'candidate_pack.json').read_text())[0];c=json.loads((b/'composed_prompt.json').read_text());e=json.loads((b/'effective_visual_contract.json').read_text());m=json.loads((b/'native_read_only_diagnostics.json').read_text());meta=json.loads((b/'native_attempt03_success.json').read_text())
gates={
 'vo_pe_red_object_splash_relation_1':{'status':'pass','evidence':'At overall and native contact scale, the existing domed enamel paperweight beneath the right fingertips carries distinctly red paint; its circular base sits on the scenery paper. This is the declared colored carrier.','review_scale_observed':['overall','native'],'pixel_regions':['contacts_native.png']},
 'vo_pe_red_object_splash_relation_2':{'status':'fail','evidence':'PARTIAL maps to FAIL: the environment and person are desaturated but broadly warm/sepia rather than achromatic. Native cheeks, paper, shirt and wood retain a systematic red-over-blue tint. Outside the generous prop mask, median RGB channel spread is 7/255, mean RGB 110.27/106.14/103.55, and 88.36% of pixels exceed spread 3. The true-grayscale remainder does not coexist with the red carrier.','review_scale_observed':['overall','native'],'pixel_regions':['generated-original.png','face_native.png','contacts_native.png'],'observation':'partial'},
 'vo_pe_lifted_black_floor_relation_1':{'status':'fail','evidence':'PARTIAL maps to FAIL: larger dark surfaces are gray and some shadow separation improves, but the deepest root troughs still read near black rather than a consistently visible soft-charcoal floor; dark shelf recesses also sink well below the main charcoal level. The native root crop has p01 luminance 21.82 and p05 28.07, with 13.39% below 35, and the shelf crop p01 24.07. These diagnostics corroborate the visible compressed lower endpoint; the authorial approximate 45/255 guide is not treated as a requester lock or independent numeric gate.','review_scale_observed':['overall','native'],'pixel_regions':['hair_roots_native.png','shelf_recess_native.png'],'observation':'partial'},
 'vo_pe_lifted_black_floor_relation_2':{'status':'pass','evidence':'Native hair-root inspection resolves separate dark strands and lighter strand boundaries around the part; shelving remains distinguishable from objects and shelf edges. Dark subject information is retained even though the globally lifted endpoint is incomplete.','review_scale_observed':['overall','native'],'pixel_regions':['hair_roots_native.png','shelf_recess_native.png']},
 'vo_pe_texture_preserving_tone_evening_relation_1':{'status':'pass','evidence':'At native cheek scale, the broad transitions from nose highlight through both cheek planes remain continuous and locally even. Small tonal variation persists rather than blotchy or posterized patches; this supports the requested visible result, not proof of a specific editing operation.','review_scale_observed':['native'],'pixel_regions':['face_native.png','cheeks_native.png']},
 'vo_pe_texture_preserving_tone_evening_relation_2':{'status':'pass','evidence':'Native face and cheek crops retain fine pores and tiny irregular skin variations, distinct from the coarse textile and hair detail. Comparing the original reference with the generated face shows the guided bob, divided bangs, soft oval face, dark almond eyes, small nose and full lips without an obvious introduced facial-geometry distortion. This is a visible-appearance comparison and makes no identity or biometric claim.','review_scale_observed':['native'],'pixel_regions':['face_native.png','cheeks_native.png']},
 'embodiment_body_ownership':{'status':'pass','evidence':'The two visible hands and forearms connect to the same worker through continuous sleeves and upper arms. The right hand in the image-left region meets the paperweight and the left hand in the image-right foreground meets the paper.','review_scale_observed':['overall','native'],'pixel_regions':['generated-original.png','contacts_native.png']},
 'embodiment_joint_chain_and_reach':{'status':'pass','evidence':'Both shoulder, elbow/forearm, wrist and finger chains have plausible continuity and short tabletop reaches. The separate contacts do not require an impossible crossing or a detached hand.','review_scale_observed':['overall','native'],'pixel_regions':['generated-original.png','contacts_native.png']},
 'embodiment_support_and_balance':{'status':'pass','evidence':'The solid worktable carries the forearms, flat scenery paper and full paperweight base. Her forward upper-body posture agrees with the nearby support and the visible manual action; lower support remains outside the frame.','review_scale_observed':['overall','native'],'pixel_regions':['generated-original.png','contacts_native.png']},
 'embodiment_contact_and_space':{'status':'pass','evidence':'Right fingertips rest against the curved enamel top with coherent finger boundaries; the circular base lies flat on paper. The left palm/fingers lie across the separate paper edge. Paper and tabletop retain distinct boundaries, and the rolled portion stays behind the flattened contact area.','review_scale_observed':['overall','native'],'pixel_regions':['contacts_native.png','generated-original.png']},
 'embodiment_visibility_and_projection':{'status':'pass','evidence':'The chest-height across-table projection exposes the face, both connected arm chains, red carrier and two hand contacts together. The raised roll and flat working sheet are assessable without a critical relation hidden off-frame.','review_scale_observed':['overall','native'],'pixel_regions':['generated-original.png','contacts_native.png']}}
assert set(gates)==set(e['required_hard_gates']+[f'embodiment_{x}' for x in c['embodiment_review']['review']['checks']])
review={'schema_version':'moe-render-review/v1','contract_version':'photo-visual-obligations/v1','pack_id':p['pack_id'],'reviewer':'independent agent /root/editing_tonal_skin','reviewed_at':datetime.datetime.now(datetime.timezone.utc).isoformat(),'result_image':meta['preserved_original_path'],'result_sha256':meta['image_sha256'],'effective_visual_contract_sha256':json.loads((b/'composition_audit.json').read_text())['effective_visual_contract_sha256'],'hard_gates':gates,'user_judgment':{'baseline_available':False,'genuinely_moe':'pending','better_than_baseline':'not_applicable','source':'not_yet_received','evidence':'No requesting-user acceptance or comparison judgment has been received.'},'supplemental_observations':{'artistic_direction':'The across-table worker, red repair carrier, curling/rolled plan and backstage props form a coherent observed workplace moment; face and working hands lead the image. The mild warm monochrome impression and deepest shadow endpoint miss two strict editing tests.','subject_presence':'The neutral attentive glance and practical cotton shirt create ordinary engaged presence; appeal is an agent observation and is not inferred as attraction, consent or user acceptance.','prompt_staging_variation':'Several collar buttons remain open in the produced ordinary work shirt despite the authorial neatly-fastened cue. Background prop-case/sign lettering is incidental. These staging differences do not replace any typed effect gate.','inspection_method':'Original image unchanged; overall view plus integer-coordinate native crops without scaling, filtering or color/tone edits.','diagnostics_file':str(b/'native_read_only_diagnostics.json')}}
ref={'schema_version':'photo-reference-scope-review/v1','reviewer':review['reviewer'],'reference_image':c and json.loads((b/'render_request.json').read_text())['references'][0]['path'],'reference_sha256':json.loads((b/'render_request.json').read_text())['references'][0]['sha256'],'result_image':meta['preserved_original_path'],'result_sha256':meta['image_sha256'],'status':'pass','scope':'visible adult face/hair appearance guidance for fictional adult woman','visible_configuration_evidence':['Short bob and divided airy bangs retain the guided hair arrangement.','Soft oval face, large dark almond eyes, small nose and full lips remain recognizably guided in this stylized treatment.'],'boundaries':['No identity, biometric, personality, trait or body-shape inference.','Fictional adult status is an authored prompt property, not an age inference from the reference pixels.','The tonal gray treatment may change color but does not license claims about a real person.'],'user_acceptance':'pending'}
assertions=json.loads((b/'authorial_core.json').read_text())['semantic_assertions'];effects=[]
for a,profile in zip(assertions,['pe_red_object_splash_relation','pe_lifted_black_floor_relation','pe_texture_preserving_tone_evening_relation']):
 gg=[x['id'] for x in next(x for x in e['obligations'] if x['id']==profile)['render_gates']];status='pass' if all(gates[x]['status']=='pass' for x in gg) else 'fail'
 effects.append({'assertion_id':a['assertion_id'],'authority':'original core advisory; chosen profile independently promotes explicit all-of gates','profile_id':profile,'status':status,'required_gates':gg,'pixel_evidence':[gates[x]['evidence'] for x in gg]})
result={'schema_version':'photo-editing-qualification-result/v1','revision':'v2','pack_id':p['pack_id'],'result_image':meta['preserved_original_path'],'result_sha256':meta['image_sha256'],'requester_locks_unchanged':True,'core_controls_envelope_unchanged':True,'random_seed_hex':'8f0040ca75299371254dbda8c32957fd','random_concept':'Theater prop repair room just after final curtain; adult worker briefly connects to photographer while hands flatten curling scenery plan under red enamel paperweight.','effects':effects,'effect_pass_count':sum(x['status']=='pass' for x in effects),'effect_count':3,'selected_profile_gate_pass_count':sum(gates[x]['status']=='pass' for x in e['required_hard_gates']),'selected_profile_gate_count':len(e['required_hard_gates']),'physical_gate_pass_count':5,'physical_gate_count':5,'reference_scope_status':ref['status'],'all_hard_gate_pass_count':sum(x['status']=='pass' for x in gates.values()),'all_hard_gate_count':len(gates),'strict_all_of_verdict':'FAIL','partial_is_fail':True,'user_acceptance':'pending','same_saved_image_required':True,'retries_or_fallback_after_this_render':0,'actual_image_calls':{'cumulative_arm':3,'this_revision':1,'previous_v1':2},'boundaries':['Prompt/runtime audits are not pixel tests.','The deterministic review auditor validates this record rather than independently reading pixels.','No effects are averaged or combined across attempts.','User acceptance remains separate.']}
for f,x in [('moe_render_review.json',review),('reference_scope_review.json',ref),('qualification_result.json',result)]: (b/f).write_text(json.dumps(x,ensure_ascii=False,indent=2)+'\n')
print(json.dumps({'effect_statuses':[(x['assertion_id'],x['status']) for x in effects],'hard_gate_pass':result['all_hard_gate_pass_count'],'hard_gate_total':len(gates),'strict_all_of':result['strict_all_of_verdict']},indent=2))
