import json,pathlib,hashlib
b=pathlib.Path(__file__).resolve().parent
p=json.loads((b/'candidate_pack.json').read_text())[0]
prompt=(b/'prompt_en.txt').read_text()
color1='One declared red object retains its red color: the saturated crimson enamel paperweight beneath her fingertips.'
color2='The rest of the picture is achromatic, including skin, lips, eyes, hair, shirt, paper, curtains and wood, all equal-channel neutral grayscale.'
floor1='Dark image tones are lifted to visible gray, including the darkest hair roots and shelf recesses sitting distinctly at soft charcoal, approximately 45/255 at the darkest tonal endpoint.'
floor2='Dark subject information remains readable as separate strands and shelf grain against that elevated tonal floor.'
skin1='Skin color transitions remain locally even through restrained local dodge-and-burn across her cheeks.'
skin2='Fine skin texture remains visible without facial-geometry alteration: fine pores and tiny natural variations stay crisp.'
ids=['slot:color_grading:pe_red_object_splash','slot:color_grading:pe_lifted_black_floor','slot:skin_finish:pe_texture_preserving_tone_evening']
profile_ids=['pe_red_object_splash_relation','pe_lifted_black_floor_relation','pe_texture_preserving_tone_evening_relation']
evidence=dict(zip(profile_ids,[(color1,color2),(floor1,floor2),(skin1,skin2)]))
clar=[]
for x in p['semantic_clarification']['candidates']:
 k=x['id']; profile=x.get('profile_id')
 if x.get('required_in_final_prompt'):
  clar.append({'clarification_id':k,'decision':'applied','rationale':'All four requester-owned frozen anchor phrases remain literal; the independently authored repair scene stays coherent.','prompt_evidence':prompt[:prompt.index(' The supplied image')]})
 elif profile in evidence:
  clar.append({'clarification_id':k,'decision':'applied','rationale':'This selected editing meaning realizes an original advisory target on the declared image-plane or skin owner without altering requester locks.','prompt_evidence':' '.join(evidence[profile])})
 else:
  clar.append({'clarification_id':k,'decision':'rejected','rationale':'The retained ordinary theater repair scene needs the three selected tonal and skin treatments; this additional visual mechanism would add an unrelated target or staging burden.'})
choices=[{'candidate_id':c,'artistic_interpretation':i,'transformation':t,'prompt_evidence':' '.join(evidence[profile]),'relation_evidence':{'effect_owner':' '.join(evidence[profile])}} for c,profile,i,t in zip(ids,profile_ids,[
 'Keep the physical repair consequence legible through the sole crimson carrier against a neutral scene.',
 'Place every deepest hair root and shelving recess on a visible charcoal floor while retaining dark material information.',
 'Balance broad cheek tones locally while keeping tactile fine skin texture on the same reference-guided fictional face.'
],[
 'Bind the declared red object to the existing enamel paperweight under her fingertips and extend achromatic rendering across every other region.',
 'Lift the global lower tonal endpoint across the existing roots and shelf recesses rather than substituting colored lighting or local haze.',
 'Use restrained local dodge-and-burn on the cheeks with crisp pores and small natural variations; retain the given visible facial configuration.'
])]
checks={
 'body_ownership':{'status':'supported','reason':'The one fictional adult woman owns both arms; right fingertips contact the domed weight and left palm contacts the opposite paper edge.','prompt_evidence':['Both forearms rest lightly on the tabletop','her right fingertips rest on a domed red enamel paperweight','her left palm spreads its opposite edge flat']},
 'joint_chain_and_reach':{'status':'supported','reason':'The three-quarter view preserves connected arms reaching nearby tabletop contacts with separate hand targets and ordinary joint reach.','prompt_evidence':['both connected arms, the paper and weight together','Both forearms rest lightly on the tabletop']},
 'support_and_balance':{'status':'supported','reason':'The tabletop supports both forearms and the weight seated through the paper; off-frame lower-body support is not needed to judge this stable manual action.','prompt_evidence':['Both forearms rest lightly on the tabletop','paperweight seated fully on the curling corner']},
 'contact_and_space':{'status':'supported','reason':'The weight base lies on the paper with right fingertips on its dome; the left palm presses another edge, while the separate curled section rises behind the flat corner.','prompt_evidence':['her right fingertips rest on a domed red enamel paperweight seated fully on the curling corner','her left palm spreads its opposite edge flat','A previously rolled portion still arcs upward behind the flattened corner']},
 'visibility_and_projection':{'status':'supported','reason':'The face, complete arm connections, weight and working paper share the frame from the opposite tabletop side; the hand contacts are available for native pixel inspection.','prompt_evidence':['A chest-height three-quarter view from the opposite side shows her face, both connected arms, the paper and weight together']}}
review={'contract_version':'photo-embodiment-review/v1','provenance':'agent_postcomposition','prompt_sha256':hashlib.sha256(prompt.encode()).hexdigest(),'scope':'body_action','summary':'The safer work shirt and neutral expression change open portrayal dimensions while the original two-hand repair contacts and visible raised paper curl remain coherent.','checks':checks}
c={'pack_id':p['pack_id'],'prompt_en':prompt,'negative_en':p['negative_en'],'composer':'agent','chosen_candidate_ids':ids,'chosen_visual_concept_ids':['visual-concept:'+x for x in profile_ids],'candidate_interpretations':choices,'visual_obligation_evidence':{k:{'component_1_phrase':v[0],'component_2_phrase':v[1]} for k,v in evidence.items()},'semantic_clarification_decisions':clar,'creative_augmentation_brief':{'decisions':[{'candidate_id':x['id'],'decision':'rejected','rationale':'Keep the across-table manual repair and readable face, hands and editing owners; this separate optional composition or focus mechanism adds no necessary target evidence.'} for x in p['creative_augmentation']['candidates']]},'authorial_core_binding':{'source_authorial_core_sha256':p['authorial_core']['canonical_sha256'],'source_intent_lock_sha256':p['authorial_core']['intent_lock']['canonical_sha256'],'preserved_anchor_ids':[x['anchor_id'] for x in p['authorial_core']['intent_lock']['semantic_anchors']],'preserved_evidence':[],'authorial_decisions':[
 {'dimension':'appearance','decision':'Use a plain buttoned work shirt neatly fastened on the same adult worker.','rationale':'Preserve the previously authorized ordinary fully clothed workplace portrayal within open appearance.','prompt_evidence':'Her plain buttoned cotton work shirt is neatly fastened'},
 {'dimension':'material','decision':'Retain matte practical cotton for the work shirt.','rationale':'The open material choice supports the ordinary repair task and neutral tonal rendering.','prompt_evidence':'plain buttoned cotton work shirt'},
 {'dimension':'expression','decision':'Use a neutral engaged expression during the glance toward the photographer.','rationale':'Preserve the safer previous retry expression without changing the brief connection during repair.','prompt_evidence':'she looks toward the photographer with a neutral engaged expression while finishing an ordinary repair'},
 {'dimension':'atmosphere','decision':'Keep the moment as an ordinary workplace repair after a public performance.','rationale':'The frozen theater, timing, prop and repair action stay intact while agent-owned private-pause styling is simplified.','prompt_evidence':'placing this ordinary repair task after a public performance'},
 {'dimension':'color','decision':'Specify equal-channel achromatic rendering outside the sole red enamel paperweight and a distinctly gray tonal floor throughout the roots and shelf recesses.','rationale':'Repair the whitelist-observed warm non-red areas and near-black floor using the same original advisory targets and selected profiles; keep local skin texture.','prompt_evidence':color2+' '+floor1}
 ]},'embodiment_review':{'source_contract_sha256':p['embodiment_preflight']['canonical_sha256'],'review':review},'adult_appeal_brief':{'adult_subject_phrase':'a fictional adult woman','agency_phrase':'she looks toward the photographer with a neutral engaged expression while finishing an ordinary repair','axes':{'sensual':{'intensity':1,'realization':'refined','affected_dimensions':['appearance','material','expression','atmosphere'],'artistic_interpretation':'At the unchanged supporting intensity, ordinary attentiveness and a brief self-directed glance carry subtle subject presence. The safe buttoned cotton shirt and neutral engaged expression refine open styling; perceived attraction remains a separate pixel/user judgment.','prompt_evidence':'she looks toward the photographer with a neutral engaged expression while finishing an ordinary repair'},'fetish':{'intensity':0}},'blend':{'emphasis':'sensual_led'},'contextual_review':[
 {'candidate_id':'augmentation:adult_appeal:sensual:gaze_engagement:same_adult_target_coordinated_gaze','reading':'potential','reason':'The existing glance could support coordinated gaze toward the photographer, though turning the full body would weaken the ongoing separate hand contacts.','proposed_application':'A viable supporting-intensity alternative would briefly align head and torso toward the photographer across the same table while keeping both hands at their targets; decline additional coordination here.'},
 {'candidate_id':'augmentation:adult_appeal:sensual:garment_detail:pfe_cleavage_candidate','reading':'conflicting','reason':'This particular garment boundary would undo the retained safely fastened work-shirt portrayal. It is optional and remains unselected.'},
 {'candidate_id':'augmentation:adult_appeal:sensual:wardrobe_style:ctx_c133','reading':'irrelevant','reason':'The complete breakfast-table, morning hair and sleepwear configuration belongs to a different setting and event from the preserved theater repair.'},
 {'candidate_id':'augmentation:adult_appeal:sensual:mood:vulnerable_glamour','reading':'potential','reason':'A slightly tired post-performance glance could be interpreted through quiet vulnerability at the same supporting intensity, but it does not improve the visibility of the repair or editing owners.','proposed_application':'A viable alternative would soften the brief gaze while the same cotton-shirt worker continues flattening the plan in broad window light; decline the added vulnerable glamour direction.'}
 ],'contextual_comparison':'At sensual 1 and fetish 0, the original baseline uses open-neckline satin and parted lips. The retained authorized safe direction instead uses fastened cotton and a neutral engaged glance during the same task. Coordinating head and torso toward the photographer or softly weary vulnerability are viable same-intensity alternatives, but the chosen ordinary attentiveness preserves hand-contact clarity and readable skin. The optional cleavage and breakfast/sleepwear configurations do not serve this repair-room scene. No appeal success is inferred from appearance or these choices.'}}
for field,body in [('composed_prompt.json',c),('embodiment_review_final.json',review)]: (b/field).write_text(json.dumps(body,ensure_ascii=False,indent=2)+'\n')
(b/'negative_en.txt').write_text(c['negative_en'],encoding='utf-8')
(b/'composition_decisions.json').write_text(json.dumps({'baseline_core_unchanged':True,'requester_locks_unchanged':True,'advisory_targets_remain_agent_owned':True,'selected_profiles_promote_opt_in_gates':True,'authorial_decisions':c['authorial_core_binding']['authorial_decisions']},ensure_ascii=False,indent=2)+'\n')
print({'pack_id':p['pack_id'],'prompt_sha256':hashlib.sha256(prompt.encode()).hexdigest(),'selected_slots':ids,'selected_profiles':c['chosen_visual_concept_ids']})
