import json,hashlib,pathlib,datetime,shutil
out=pathlib.Path(__file__).parent
repo=pathlib.Path.cwd()
def sha(b): return hashlib.sha256(b).hexdigest()
def write(name,x): (out/name).write_text(json.dumps(x,ensure_ascii=False,indent=2)+'\n')
env=json.loads((out/'request_envelope.json').read_text()); raw=(out/'request_envelope.json').read_bytes()
assert sha(raw)=='3a3bc536e695a4900b7c94c83209d1dec7297fba719f4f1342afc310fd531fb9'
ref=pathlib.Path('/Users/chasoik/Downloads/0CB25F47-BB90-4DBD-8993-733BA8282851(20260927-041323).jpeg')
assert sha(ref.read_bytes())=='06d6c6feeed0d2397ec9562d46113cd221ac54a0e190295f0aa7f7868c22ece7'
base='A single-frame photographic study of forward movement shows an adult fictional woman, with the supplied reference guiding the visible facial appearance and short dark bob with wispy bangs, taking one quick bounding stride past a low drainage threshold in a riverside pedestrian underpass with wet concrete. Her left forefoot pushes against the pavement behind the threshold while her right knee lifts ahead and her right shoe clears the low ridge; her torso inclines into the movement toward screen-right. Her left hand grips a rolled drawing tube beside her left thigh, her right elbow swings forward, and a rust-red crossbody canvas bag rests at her right hip with its strap crossing her clothed torso. She wears a light blue windbreaker, straight charcoal trousers, and practical sneakers. In an oblique side-front view at chest height, diagonal pavement seams and a foreground drainage ridge lead from the lower-left foreground toward the upper-right exit, echoing the inclined body and the lifted stride. The woman sits left of center with open space ahead of her movement, so her forward vector continues visibly into the frame. A near wet ridge, the midground woman, and the receding underpass exit form three readable depth layers. Her face, hands, shoe clearance, and connected limbs remain sharply readable, while a few trailing hair strands and a swinging bag edge give localized motion cues. Late-afternoon sun entering from one open side makes a warm stripe across her face and jacket, reflected in the wet concrete, while the shaded tunnel retains its cool concrete texture. The image reads as a natural editorial photograph with the moving woman as its first visual focus.'
base=' '.join(base.split())
evidence={
 'directional_diagonal':'diagonal pavement seams and a foreground drainage ridge lead from the lower-left foreground toward the upper-right exit',
 'directional_asymmetry':'The woman sits left of center with open space ahead of her movement',
 'layered_space':'A near wet ridge, the midground woman, and the receding underpass exit form three readable depth layers',
 'subject_legibility':'Her face, hands, shoe clearance, and connected limbs remain sharply readable',
 'localized_motion':'a few trailing hair strands and a swinging bag edge give localized motion cues'}
core={'contract_version':'photo-authorial-core/v3','provenance':'agent_prepack','source_request':env['request_text'],
 'interpreted_intent':'Produce this arm of the requested photographic test using a dynamic-feeling composition. General-knowledge interpretation: coherent diagonal spatial flow, directional asymmetry, layered depth and an immediately readable protagonist create visual momentum; the random physical scene is agent staging and not a requester definition.',
 'subject':'An adult fictional woman guided by the supplied portrait only for visible facial appearance and short dark bob with wispy bangs.',
 'setting':'Riverside pedestrian underpass with wet concrete, a low drainage threshold, and an open sunlit exit.',
 'event':'One quick bounding stride past the low drainage threshold, with left forefoot pushing from pavement and right shoe lifted clear.',
 'visual_priorities':['Diagonal spatial flow echoes the inclined body and forward stride.','Off-center placement leaves readable continuation space ahead.','Foreground ridge, woman and receding exit produce directional depth.','The reference-guided face and bodily action remain readable amid localized motion cues.'],
 'baseline_prompt_en':base,'user_definitions':[],
 'interpretation_provenance':[
 {'term':'reference_context','source_text':'아까 그 첨부 이미지로 이번엔','basis':'request_context','resolution':'Use the supplied image as visual reference for the face and hair of an adult fictional character; the scene is independently authored.','sources':[]},
 {'term':'동적인 느낌을 줄 수 있는 구도','source_text':'동적인 느낌을 줄 수 있는 구도','basis':'agent_general_knowledge','resolution':'Dynamic composition is made visible by coherent diagonal flow, directional asymmetry, depth progression and a readable protagonist; no specific dynamic subtype was defined by the requester.','sources':[]},
 {'term':'workflow','source_text':'이렇게 3개 주제로 아까와 같은 방식으로 테스트해줘.','basis':'request_context','resolution':'Run this as one separate single-frame photographic test using the authorized intent-first freeze, one candidate pack and one native render protocol.','sources':[]}],
 'unresolved_ambiguities':[],'user_exclusions':[],'runtime_forbidden_labels':[],
 'intent_lock':{'contract_version':'photo-intent-lock/v1','priority':'requesting_user','semantic_anchors':[
 {'anchor_id':'core_concept','source_text':'동적인 느낌을 줄 수 있는 구도','dimension':'concept','prompt_evidence':'diagonal pavement seams and a foreground drainage ridge lead from the lower-left foreground toward the upper-right exit'},
 {'anchor_id':'core_subject','source_text':'아까 그 첨부 이미지로 이번엔','dimension':'subject','prompt_evidence':'an adult fictional woman'},
 {'anchor_id':'core_event','source_text':'이렇게 3개 주제로 아까와 같은 방식으로 테스트해줘.','dimension':'event','prompt_evidence':'A single-frame photographic study of forward movement'},
 {'anchor_id':'core_composition','source_text':'동적인 느낌을 줄 수 있는 구도','dimension':'composition','prompt_evidence':'The woman sits left of center with open space ahead of her movement'},
 {'anchor_id':'core_reference','source_text':'아까 그 첨부 이미지로 이번엔','dimension':'reference_use','prompt_evidence':'the supplied reference guiding the visible facial appearance and short dark bob with wispy bangs'}],
 'locked_dimensions':['concept','subject','event','composition','reference_use'],
 'open_dimensions':['lighting','camera','color','atmosphere','framing','material','timing']},
 'semantic_assertions':[{'assertion_id':'dynamic_composition_visible','dimension':'composition','polarity':'required','source_span_ids':['topic'],'affected_dimensions':['composition'],'axes':{'directional_flow':'coherent_diagonal_spatial_flow','placement':'asymmetric_with_continuation_space','space':'foreground_midground_background_progression','readability':'recognizable_protagonist_and_action','motion_scope':'localized_motion_with_readable_body'},'evidence':evidence}],
 'request_lineage':None,'style':{'domain':'photographic editorial','family':'natural movement study','evidence':['natural editorial photograph','cool concrete texture']},'variation_key':'dynamic-composition-13179358549791421548'}
write('authorial_core.json',core); (out/'baseline_prompt_en.txt').write_text(base+'\n')
checks={
 'body_ownership':('All named hands, elbows, legs and shoulders belong to the single actor; prop and bag ownership are visible.',['Her left hand grips a rolled drawing tube beside her left thigh','her right elbow swings forward']),
 'joint_chain_and_reach':('The left hand reaches the adjacent thigh-level tube; right knee and elbow flex forward without conflicting reach.',['her right knee lifts ahead and her right shoe clears the low ridge','her right elbow swings forward']),
 'support_and_balance':('Left forefoot supplies the instantaneous propulsive contact while torso inclines and right foot clears the ridge.',['Her left forefoot pushes against the pavement behind the threshold','her torso inclines into the movement toward screen-right']),
 'contact_and_space':('A low threshold leaves clear path for the lifted shoe, and the bag rests on the hip supported by its strap.',['her right shoe clears the low ridge','a rust-red crossbody canvas bag rests at her right hip with its strap crossing her clothed torso']),
 'visibility_and_projection':('Chest-height oblique side-front projection exposes foot clearance and connected limbs while preserving face readability.',['an oblique side-front view at chest height','Her face, hands, shoe clearance, and connected limbs remain sharply readable'])}
review={'contract_version':'photo-embodiment-review/v1','provenance':'agent_prepack','prompt_sha256':sha(base.encode()),'scope':'body_action','summary':'Ordinary adult human body during the push-off phase of a stride past a low drainage ridge; one held tube and a shoulder-supported crossbody bag.','checks':{k:{'status':'supported','reason':v[0],'prompt_evidence':v[1]} for k,v in checks.items()}}
write('embodiment_review.json',review)
catpath=repo/'skills/photo-prompt-image-generator/precore/visual_feature_catalog.json'; cat=json.loads(catpath.read_text()); shutil.copyfile(catpath,out/'visual_feature_catalog.snapshot.json')
rows=[
 ('feature.subject','request_derived',['reference_context'],None,'Use the portrait for visible facial and hair appearance in the adult fictional subject.','Keeps the supplied portrait perceptibly relevant.','the supplied reference guiding the visible facial appearance and short dark bob with wispy bangs'),
 ('feature.action','agent_visual_choice',[],None,None,'An instantaneous stride makes the chosen spatial flow physically legible.','taking one quick bounding stride past a low drainage threshold'),
 ('feature.location','agent_visual_choice',[],None,None,'The tunnel supplies coherent receding geometry for the single frame.','in a riverside pedestrian underpass with wet concrete'),
 ('feature.props','agent_visual_choice',[],None,None,'The held tube and hip-supported bag give two different motion traces.','Her left hand grips a rolled drawing tube beside her left thigh'),
 ('feature.pose','agent_visual_choice',[],None,None,'Articulated push-off and clearance establish a plausible instant of movement.','Her left forefoot pushes against the pavement behind the threshold while her right knee lifts ahead'),
 ('feature.composition','explicit_request',['topic'],'동적인 느낌을 줄 수 있는 구도',None,'The focal topic calls for visual momentum organized through the frame.','diagonal pavement seams and a foreground drainage ridge lead from the lower-left foreground toward the upper-right exit'),
 ('feature.motion','request_derived',['topic'],None,'Localized trailing motion supports the requested dynamic feel while preserving the actor.','Small visible trailing elements reinforce direction without hiding the subject.','a few trailing hair strands and a swinging bag edge give localized motion cues'),
 ('feature.spatial_depth','request_derived',['topic'],None,'Sequential depth layers visibly extend the directional composition.','Distinct near and far layers make the path through space legible.','A near wet ridge, the midground woman, and the receding underpass exit form three readable depth layers'),
 ('feature.lighting_source','agent_visual_choice',[],None,None,'Side-entering sunlight reveals face and material relief within the shade.','Late-afternoon sun entering from one open side'),
 ('feature.visual_hierarchy','request_derived',['topic'],None,'Keep the protagonist legible as the visual focus of the dynamic composition.','A readable moving actor anchors the diagonal scene.','the moving woman as its first visual focus')]
selection={'contract_version':'photo-precore-feature-selection/v1','request_id':env['request_id'],'active_span_ids':[s['span_id'] for s in env['active_spans']],'catalog_path':'skills/photo-prompt-image-generator/precore/visual_feature_catalog.json','catalog_schema_version':cat['schema_version'],'catalog_sha256':sha(catpath.read_bytes()),'request_sha256':env['request_sha256'],'baseline_prompt_sha256':sha(base.encode()),'selected':[{'category_id':r[0],'basis':r[1],'source_span_ids':r[2],'source_text':r[3],'derivation':r[4],'reason':r[5],'baseline_evidence':r[6]} for r in rows]}
write('precore_feature_selection.json',selection)
case={'contract_version':'angle-motion-test-case/v1','arm':'dynamic_composition','provenance':'agent_prepack_pixel_criteria','requester_definition_present':False,'interpretation_basis':'agent_general_knowledge','composition_subtype':'diagonal-depth directional asymmetry','topic_all_of':{'operator':'all','partial_is_fail':True,'components':[
 {'id':'diagonal_flow','pass':'At least two clear scene/subject vectors share a diagonal direction and lead toward a visible continuation in the frame.','fail':'A random camera tilt or a lone diagonal decorative object without coherent flow.'},
 {'id':'directional_asymmetry','pass':'Actor is visibly off-center with more usable space ahead of the movement than behind; action direction agrees with that space.','fail':'Centered symmetry or movement running directly out of an immediately cropped edge.'},
 {'id':'depth_progression','pass':'A readable foreground object, midground actor and receding background form a traversable spatial route.','fail':'Flat backdrop, collage depth or incoherent vanishing directions.'},
 {'id':'motion_and_readability','pass':'Pose or localized trailing elements show movement direction while face, connected body and action remain readable at original and thumbnail size.','fail':'The word dynamic alone, static straight pose, full-frame blur, or unreadable protagonist.'}]},
 'confusion_boundaries':['Camera roll alone is insufficient.','Running alone in a centered flat portrait is insufficient.','Global blur does not prove dynamic composition.','A strong diagonal that competes with or erases the actor is insufficient.'],
 'fixed_scene_all_of':['Adult fictional woman with reference-guided visible face and dark bob with wispy bangs.','Riverside pedestrian underpass and wet concrete.','Left forefoot propulsive pavement contact behind a low threshold while right shoe clears it.','Tube held by left hand and rust-red crossbody bag supported at right hip by chest-crossing strap.','Light blue windbreaker, charcoal trousers and sneakers.','Side-entering late afternoon warm light with shaded concrete and visible wet reflections.'],
 'embodiment_pixel_checks':['Body ownership and connected limbs.','Left foot support and right shoe clearance.','Left hand and drawing tube contact.','Bag support and strap routing.','Available clearance around threshold and actor.'],
 'user_aesthetic_acceptance':'pending','status_domains_separate':['prompt_audit','runtime_request_audit','saved_output','topic_pixels','fixed_scene_pixels','embodiment_pixels','user_acceptance']}
write('test_case.json',case)
freeze={'contract_version':'angle-motion-core-freeze/v1','arm':'dynamic_composition','frozen_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'seed':json.loads((out/'random_draws.json').read_text())['seed'],'input_isolation':{'permitted':['coordinator execution brief (not source_request)','immutable requester envelope','directly viewed supplied portrait','general knowledge','photo-prompt-image-generator SKILL.md','system imagegen SKILL.md','exact current precore/visual_feature_catalog.json'],'not_accessed':['candidate data','code/scripts before freeze','references','assets','past experiments','other arms','memory'],'requester_text_authority':'request_envelope.json request_text only'},'hashes':{'request_envelope_file_sha256':sha(raw),'request_text_sha256':sha(env['request_text'].encode()),'reference_sha256':sha(ref.read_bytes()),'baseline_prompt_sha256':sha(base.encode()),'authorial_core_file_sha256':sha((out/'authorial_core.json').read_bytes()),'required_criteria_strings_sha256':sha(json.dumps(evidence,sort_keys=True,separators=(',',':')).encode()),'test_case_file_sha256':sha((out/'test_case.json').read_bytes()),'embodiment_review_file_sha256':sha((out/'embodiment_review.json').read_bytes()),'selection_file_sha256':sha((out/'precore_feature_selection.json').read_bytes()),'catalog_sha256':sha(catpath.read_bytes())},'precore_validator':'pending'}
write('core_freeze.json',freeze)
print(json.dumps({'baseline_words':len(base.split()),'freeze':freeze},ensure_ascii=False,indent=2))
