import pathlib,json,hashlib,datetime,subprocess
out=pathlib.Path(__file__).parent.resolve();repo=pathlib.Path.cwd();p=json.loads((out/'candidate_pack.json').read_text())[0];c=json.loads((out/'composed_prompt.json').read_text());meta=json.loads((out/'image_metadata.json').read_text())
def write(name,obj):(out/name).write_text(json.dumps(obj,ensure_ascii=False,indent=2)+'\n')
scales={'native':{'path':meta['saved_path'],'dimensions':meta['png_dimensions'],'directly_viewed':True},'thumbnail':{'path':meta['review_thumbnail_path'],'dimensions':meta['review_thumbnail_dimensions'],'directly_viewed':True}}
topic=[
 {'component_id':'diagonal_flow','status':'pass','native_evidence':'The inclined torso and long trailing leg rise diagonally toward screen-right; pavement seams and the receding exit also progress to the upper-right. At least two subject/scene vectors agree.','thumbnail_evidence':'The leaning actor and receding pavement remain strong diagonal directions at 512x384.','limit':'The dominant foreground ridge has the opposite slope; this fails the stronger frozen required assertion below.'},
 {'component_id':'directional_asymmetry','status':'pass','native_evidence':'Actor body occupies approximately x=304..866 of a 1448-wide frame, with a broad continuation area on the right; her gaze, lifted step and lean face that area.','thumbnail_evidence':'The actor remains left of center, with clear open wet pavement ahead to screen-right.'},
 {'component_id':'depth_progression','status':'pass','native_evidence':'Near drainage ridge, midground whole actor and background sunlit underpass exit/river railing are separable by overlap, scale and receding seams.','thumbnail_evidence':'Foreground lip, actor and bright distant opening remain three distinct layers.'},
 {'component_id':'motion_and_readability','status':'pass','native_evidence':'A raised lead shoe, rear toe support, bent forward elbow and inclined torso show a running/bounding direction; face, tube, connected limbs and both shoes are readable without global blur.','thumbnail_evidence':'The stride silhouette and held tube remain readable; the face remains recognizable as the main subject.'}]
assertion=[
 {'component_id':'directional_diagonal','status':'fail','native_evidence':'The foreground threshold runs from lower-left down toward lower-right, whereas the frozen phrase requires the foreground drainage ridge to lead toward the upper-right exit. The tunnel seams recede up-right, so the requested common ridge/seam vector survives only partly.','thumbnail_evidence':'The near ridge slopes down-right while the exit route slopes up-right; the mismatch is still evident.','partial_is_fail':True},
 {'component_id':'directional_asymmetry','status':'pass','native_evidence':'Actor left-of-center and larger open continuation space toward screen-right.','thumbnail_evidence':'Left placement and lead room are unmistakable.'},
 {'component_id':'layered_space','status':'pass','native_evidence':'Near ridge, midground woman and distant exit coexist in one spatially readable frame.','thumbnail_evidence':'Three layers remain distinct.'},
 {'component_id':'subject_legibility','status':'pass','native_evidence':'Face, fingers around tube, bent elbow, connected trouser legs and raised shoe edge are resolved.','thumbnail_evidence':'Face, main limb arrangement, shoes and tube remain discernible.'},
 {'component_id':'localized_motion','status':'fail','native_evidence':'Small hair strands trail to screen-left, but the bag rests against the hip with a settled lower edge. The required conjunction of trailing hair and a swinging bag edge is not clearly present.','thumbnail_evidence':'Hair and bag silhouette are clear, but a swinging bag-edge displacement is not assessable as a separate motion cue.','partial_is_fail':True}]
keyword={'contract_version':'keyword-pixel-results/v1','arm':'dynamic_composition','topic':'동적인 느낌을 줄 수 있는 구도','requester_definition_present':False,'interpretation_basis':'agent_general_knowledge','composition_subtype':'diagonal-depth directional asymmetry','result_image':meta['saved_path'],'result_sha256':meta['sha256'],'review_scales':scales,'test_case_file_sha256':hashlib.sha256((out/'test_case.json').read_bytes()).hexdigest(),'operator':'all','partial_is_fail':True,'topic_test_case_components':topic,'topic_test_case_all_of_status':'pass','frozen_required_assertion_components':assertion,'frozen_required_assertion_all_of_status':'fail','keyword_all_of_status':'fail','reason':'Broad movement/space criteria pass, but the non-substitutable frozen ridge vector and combined localized motion evidence fail. A label or pleasing overall impression cannot replace those components.','user_aesthetic_acceptance':'pending','reviewer':'angle_dynamic agent, direct pixel inspection'}
write('keyword_pixel_results.json',keyword)
fixed=[
 {'id':'reference_appearance','status':'pass','evidence':'The adult fictional actor has a short dark bob, fine bangs, dark visible eyes and a face visually guided by the supplied portrait. This is appearance resemblance, not identity verification.'},
 {'id':'underpass_wet_concrete','status':'pass','evidence':'Concrete roof/wall, wet reflective ground and open river railing beyond the exit are visible at both scales.'},
 {'id':'left_support_right_clearance','status':'fail','evidence':'The near front-facing side makes the screen-left rear limb read as actor-right and the screen-right lifted leg as actor-left; the frozen left push-off/right lifted-knee assignment is reversed. A generic plausible stride is present, but the exact side assignment fails.'},
 {'id':'left_tube_right_hip_bag','status':'fail','evidence':'The tube is gripped on the actor-right, screen-left side beside the bag. The bag and crossing strap are coherent, but the frozen left-hand tube relation is not preserved.'},
 {'id':'wardrobe','status':'pass','evidence':'Light blue windbreaker, charcoal straight trousers and practical sneakers are visible.'},
 {'id':'side_sun_stripe','status':'fail','evidence':'Side light, warm rim and wet pavement reflections are visible. A distinct warm stripe crossing both the face and jacket is not clearly rendered; exact frozen light staging survives only partly.'}]
gates={
 'embodiment_body_ownership':{'status':'pass','evidence':'Both arms and legs visibly connect to the same clothed actor; each hand belongs to a coherent elbow/shoulder chain. No unrelated body part is needed to explain the pose.'},
 'embodiment_joint_chain_and_reach':{'status':'pass','evidence':'The tube-holding hand reaches the thigh-level cylinder, the opposite elbow bends forward, and both trouser legs connect to plausible hips/knees. The generic mechanism is coherent although sides differ from the frozen event.'},
 'embodiment_support_and_balance':{'status':'fail','evidence':'A rear forefoot supplies a plausible support and the front shoe is lifted, but the actor-relative side assignment is reversed from the frozen left-support/right-clearance state. This requested load-bearing relation therefore fails.'},
 'embodiment_contact_and_space':{'status':'fail','evidence':'Fingers visibly grip the tube and clearance is available around the raised shoe. The grip is on the actor-right side rather than the frozen left-hand contact, so the intended contact relation is not preserved.'},
 'embodiment_visibility_and_projection':{'status':'pass','evidence':'The whole actor, rear contact, raised shoe, tube grip and bag strap are visible in the original and remain assessable in the 512x384 view. Failures are visible mismatches rather than hidden geometry.'}}
review={'schema_version':'moe-render-review/v1','pack_id':p['pack_id'],'contract_version':'photo-embodiment-preflight/v1','reviewer':'angle_dynamic agent: direct pixel inspection at native and thumbnail scales','result_image':meta['saved_path'],'result_sha256':meta['sha256'],'hard_gates':gates,'user_judgment':{'baseline_available':False,'genuinely_moe':'pending','better_than_baseline':'not_applicable','source':'not_yet_received','evidence':''},'review_scales':scales,'supplemental_observations':{'topic_keyword_review_path':str(out/'keyword_pixel_results.json'),'fixed_scene_components':fixed,'fixed_scene_all_of_status':'fail','effective_visual_concept_ids':[],'effective_visual_gates':[],'generic_repair_contract':'not_applicable: initial request with no render_repair lineage','reference_boundary':'Visible adult fictional appearance only; no identity, actual age or occupation claim.'}}
write('pixel_review.json',review)
write('generic_repair_review_applicability.json',{'contract_version':'generic-repair-review-applicability/v1','pack_id':p['pack_id'],'render_repair_present':False,'status':'not_applicable','reason':'Initial v3 core request_lineage=null; no generic repair gate contract is active. Embodiment gates are audited with audit_moe_render_review.py; no repair lineage is fabricated.'})
snap=json.loads((out/'source_snapshot_manifest.json').read_text());resp=json.loads((out/'native_response.json').read_text());ts=resp['started']['current_time'].replace(' UTC','+00:00').replace(' ','T')
argv=['.venv/bin/python','skills/photo-prompt-image-generator/scripts/generate_photo_prompt.py','--request-envelope-json',str(out/'request_envelope.json'),'--authorial-core-json',str(out/'authorial_core.json'),'--embodiment-review-json',str(out/'embodiment_review.json'),'--candidate-pack-version','v6','--selection-mode','semantic','--creativity','0.5','--seed','13179358549791421548','--emit-candidate-pack','--n','1','--output-file',str(out/'candidate_pack.json')]
cmd=['.venv/bin/python','skills/photo-prompt-image-generator/scripts/record_image_run.py','--ts',ts,'--concept',p['authorial_core']['source_request'],'--prompt-en',c['prompt_en'],'--negative-en',c['negative_en'],'--seed','13179358549791421548','--attempt','1','--status','success','--failure-reason','Native output saved successfully; strict keyword and fixed-scene pixel qualification failed. See keyword_pixel_results.json and pixel_review.json.','--image-path',meta['saved_path'],'--tool','native_imagegen','--argv-json',json.dumps(argv),'--pack-id',p['pack_id'],'--chosen-candidate-ids-json',json.dumps(c['chosen_candidate_ids']),'--chosen-visual-concept-ids-json','[]','--composer','agent','--audit-status','pass','--augmentation-brief-json',json.dumps(c['creative_augmentation_brief']),'--arm-id','dynamic_composition','--worktree-id',str(repo.resolve())+'#dynamic_composition','--skill-sha256',snap['skill_sha256'],'--source-ref','source-snapshot-sha256:'+snap['snapshot_identity'],'--candidate-pack-version','v6','--authorial-core-sha256',p['authorial_core']['canonical_sha256'],'--intent-lock-sha256',p['authorial_core']['intent_lock']['canonical_sha256'],'--reference-sha256','06d6c6feeed0d2397ec9562d46113cd221ac54a0e190295f0aa7f7868c22ece7','--image-call-count','1','--independent-no-cross-arm-inputs','--manifest',str(out/'run_manifest.json'),'--ledger',str(out/'image_runs.ndjson')]
assert not (out/'image_runs.ndjson').exists();r=subprocess.run(cmd,capture_output=True,text=True);(out/'ledger_recording.json').write_text(r.stdout);(out/'ledger_recording.stderr.txt').write_text(r.stderr);print(r.stdout);r.check_returncode()
freeze=json.loads((out/'core_freeze.json').read_text());checks={}
for file,key in [('authorial_core.json','authorial_core_file_sha256'),('test_case.json','test_case_file_sha256'),('embodiment_review.json','embodiment_review_file_sha256'),('request_envelope.json','request_envelope_file_sha256'),('precore_feature_selection.json','selection_file_sha256')]:
 actual=hashlib.sha256((out/file).read_bytes()).hexdigest();checks[file]={'expected':freeze['hashes'][key],'actual':actual,'unchanged':actual==freeze['hashes'][key]};assert checks[file]['unchanged']
write('post_render_freeze_integrity.json',{'contract_version':'freeze-integrity/v1','checked_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'checks':checks,'all_unchanged':True})
