import json,hashlib,pathlib,copy
p=pathlib.Path(__file__).parent
pack=json.loads((p/'candidate_pack.json').read_text());pack=pack[0] if isinstance(pack,list) else pack
c=json.loads((p/'authorial_core.json').read_text())
extra=' Use an 85mm portrait lens at eye level, with enough depth of field to keep the resting hands legible. A white reflector below the face lifts the eye sockets while retaining gentle shadows beside the nose. In this composition, the requested makeup design appears on its specified facial region; the crop and focus resolve that design at useful scale; adjacent skin and facial landmarks remain distinguishable.'
prompt=c['baseline_prompt_en']+extra
v={'component_1_phrase':'the requested makeup design appears on its specified facial region','component_2_phrase':'the crop and focus resolve that design at useful scale','component_3_phrase':'adjacent skin and facial landmarks remain distinguishable'}
clar=[]
for row in pack['semantic_clarification']['candidates']:
 cid=row['id']; apply='authorial-core' in cid or 'mep_beauty_detail' in cid
 clar.append({'clarification_id':cid,'decision':'applied' if apply else 'rejected','rationale':'Fits the frozen face-owned makeup study and retains resting hand staging.' if apply else 'A drink load would invent a prop and replace the frozen counter-supported forearm event.','prompt_evidence':v['component_1_phrase'] if 'mep_' in cid else 'Copper metallic pigment covers both upper eyelids in a smooth reflective sweep, while a precise plum stain defines the lips.'} if apply else {'clarification_id':cid,'decision':'rejected','rationale':'A drink load would invent a prop and replace the frozen counter-supported forearm event.'})
review=copy.deepcopy(json.loads((p/'embodiment_review.json').read_text()));review['provenance']='agent_postcomposition';review['prompt_sha256']=hashlib.sha256(prompt.encode()).hexdigest();review['summary']='Re-reviewed final prompt: eye-level 85mm projection and lower reflector retain the complete face, counter contact and separate hands; additional makeup-resolution clauses do not alter body staging.'
composed={'pack_id':pack['pack_id'],'composer':'agent','prompt_en':prompt,'negative_en':pack['negative_en'],'chosen_candidate_ids':[],'candidate_interpretations':[],'chosen_visual_concept_ids':['visual-concept:mep_beauty_detail'],'visual_obligation_evidence':{'mep_beauty_detail':v},'semantic_clarification_decisions':clar,'creative_augmentation_brief':{'decisions':[{'candidate_id':row['id'],'decision':'rejected','rationale':'Preserve frozen camera-facing expression, overhead illumination, both hands on counter and complete hair silhouette; this optional direction does not add needed evidence.'} for row in pack['creative_augmentation']['candidates']]},'authorial_core_binding':{'source_authorial_core_sha256':pack['authorial_core']['canonical_sha256'],'source_intent_lock_sha256':pack['authorial_core']['intent_lock']['canonical_sha256'],'preserved_anchor_ids':[a['anchor_id'] for a in c['intent_lock']['semantic_anchors']],'preserved_evidence':['Her face, makeup, skin, and hair are the visual center of the photograph.','Real skin retains fine pores and soft tonal variation beneath the luminous makeup.','Her upright torso supports a slight forward lean toward the camera.'],'authorial_decisions':[{'dimension':'camera','decision':'Use an eye-level 85mm lens with sufficient depth to resolve resting hands and facial details.','rationale':'Natural facial perspective and readable contact retain reference appearance and body evidence.'},{'dimension':'lighting','decision':'Introduce a low white reflector to open eye sockets and retain gentle nose shadows.','rationale':'The overhead source can otherwise obscure the copper upper-eyelid pigment.'}]},'semantic_assertion_evidence':{'source_contract_sha256':pack['semantic_assertion_obligations']['canonical_sha256'],'evidence':{'beauty_owner':c['semantic_assertions'][0]['evidence']}},'embodiment_review':{'source_contract_sha256':pack['embodiment_preflight']['canonical_sha256'],'review':review}}
(p/'composed_prompt.json').write_text(json.dumps(composed,ensure_ascii=False,indent=2)+'\n')
ex={'source_snapshot_sha256':'0715804477870cb410c752af4d4e5a6eabaee3822c7424795cbb15dcb32b4a82','pack_id':pack['pack_id'],'exposed_new_visual_concepts':['visual-concept:mep_beauty_detail'],'exposed_new_clarifications':['clarification:visual-profile:mep_beauty_detail'],'exposed_new_slot_candidates':[],'exposed_bundles':[],'selected_new_visual_concepts':composed['chosen_visual_concept_ids'],'selected_literal_evidence':v,'baseline_unchanged':True,'selection_rationale':'Beauty detail owner, crop and adjacent landmarks fit frozen meaning; all 3 opt-in gates adopted.'}
(p/'candidate-exposure-selection.json').write_text(json.dumps(ex,indent=2)+'\n')
print('prompt words',len(prompt.split()))
