import json,hashlib,pathlib
p=pathlib.Path(__file__).parent
root=p.parent
env=json.loads((root/'request_envelope.json').read_text());span=env['active_spans'][0]['text']
baseline='Create a photographic beauty editorial of one adult woman in a rain-streaked rooftop studio at dusk, using the attached portrait as the appearance reference. Preserve the visible reference features: long dark center-parted wavy hair, brown eyes, oval face, softly arched brows, a slender straight nose, and the natural shape of her lips. Her face, makeup, skin, and hair are the visual center of the photograph. Copper metallic pigment covers both upper eyelids in a smooth reflective sweep, while a precise plum stain defines the lips. Real skin retains fine pores and soft tonal variation beneath the luminous makeup. Her hair falls in distinct broad waves over both shoulders, with individual strands visible at the edges. She stands behind a waist-high stone counter, both forearms resting parallel on its top; her relaxed hands lie separately on the stone with fingers softly curved, wrists connected naturally to the forearms. Her upright torso supports a slight forward lean toward the camera. She looks directly into the lens with a calm, poised expression. A black open-collar blouse frames the neck. A large diffused overhead light reveals the eyelid shimmer and cheek texture, while a pink background glow illuminates the rain-streaked windows behind her. Frame a vertical waist-up portrait with the entire face, both hair silhouettes, and both resting hands visible; the counter crosses the lower foreground. Keep the background softly out of focus while the eyes and copper eyelids remain crisp.'
core={'contract_version':'photo-authorial-core/v3','provenance':'agent_prepack','source_request':env['request_text'],'interpreted_intent':'Independently randomized complex reference-based beauty editorial test of implemented visual keyword data. All staging choices are agent-owned, not user definitions.','subject':'one adult woman with visible facial and hair appearance from supplied portrait','setting':'rain-streaked rooftop studio at dusk','event':'woman rests both forearms and relaxed hands on a waist-high stone counter and looks at camera','visual_priorities':['visible copper eyelid makeup and plum lips on face with real skin texture','long dark broad hair waves and plausible resting hand contact'],'baseline_prompt_en':baseline,'user_definitions':[],'interpretation_provenance':[{'term':'independent randomized image test','source_text':span,'basis':'request_context','resolution':'The requester authorizes independent agent-authored concepts, test cases, reference-based prompts, generated images, and evaluation. This arm randomly chooses a beauty editorial realization.','sources':[]}],'unresolved_ambiguities':[],'user_exclusions':[],'runtime_forbidden_labels':[],'intent_lock':{'contract_version':'photo-intent-lock/v1','priority':'requesting_user','semantic_anchors':[{'anchor_id':'core_concept','source_text':span,'dimension':'concept','prompt_evidence':'photographic beauty editorial'},{'anchor_id':'core_subject','source_text':span,'dimension':'subject','prompt_evidence':'one adult woman'},{'anchor_id':'core_event','source_text':span,'dimension':'event','prompt_evidence':'both forearms resting parallel on its top'},{'anchor_id':'reference_use','source_text':'첨부한 이미지를 활용하여','dimension':'reference_use','prompt_evidence':'using the attached portrait as the appearance reference'}],'locked_dimensions':['concept','subject','event','reference_use'],'open_dimensions':['framing','composition','lighting','camera','color','material']},'semantic_assertions':[{'assertion_id':'beauty_owner','dimension':'appearance','polarity':'required','source_span_ids':['generation_request'],'affected_dimensions':['concept'],'axes':{'owner':'adult woman face makeup skin hair','test_focus':'copper eyelids plum lips real skin dark broad waves'},'evidence':{'focal_owner':'Her face, makeup, skin, and hair are the visual center of the photograph.','makeup':'Copper metallic pigment covers both upper eyelids in a smooth reflective sweep, while a precise plum stain defines the lips.','skin':'Real skin retains fine pores and soft tonal variation beneath the luminous makeup.','hair':'Her hair falls in distinct broad waves over both shoulders, with individual strands visible at the edges.'}}],'request_lineage':None,'style':{'domain':'beauty editorial photography','family':'rainy rooftop beauty study','evidence':['copper eyelids with precise plum lips','large diffused overhead light and pink window glow']},'variation_key':'arm-b-seed-2026091202'}
hashp=hashlib.sha256(baseline.encode()).hexdigest()
def check(reason,evidence):return {'status':'supported','reason':reason,'prompt_evidence':evidence}
review={'contract_version':'photo-embodiment-review/v1','provenance':'agent_prepack','prompt_sha256':hashp,'scope':'body_action','summary':'Adult human standing with both forearms and hands supported by waist-high counter; mild forward torso lean and camera-facing head.','checks':{'body_ownership':check('Both forearms and hands belong to the same single woman; wrist continuity explicit.',['one adult woman','wrists connected naturally to the forearms']),'joint_chain_and_reach':check('Waist-high surface reachable by bent elbows and forearms ahead of torso.',['She stands behind a waist-high stone counter','both forearms resting parallel on its top']),'support_and_balance':check('Standing torso carries slight lean while stone supports forearms.',['Her upright torso supports a slight forward lean toward the camera.']),'contact_and_space':check('Separate relaxed hands rest on plane with natural finger curvature; room between forearms.',['her relaxed hands lie separately on the stone with fingers softly curved']),'visibility_and_projection':check('Waist-up frontal projection includes wrists, both hands and entire face without hidden required contact.',['both resting hands visible','the counter crosses the lower foreground'])}}
case={'provenance':'agent_prepack','seed':2026091202,'keywords':['beauty editorial','copper metallic eyelids','plum lip stain','natural skin texture','broad wavy hair'],'success_criteria':['Face makeup skin and hair read as primary subject rather than clothing or background','Copper shimmer belongs to both upper eyelids and plum pigment to lips','Facial skin has visible believable microtexture at native detail','Long dark center-parted hair forms broad waves over both shoulders','Both forearms connect to separate relaxed hands resting on counter with plausible contact','Reference visible face and hair features broadly preserved'],'failure_policy':'partial_is_fail','user_judgment':'not_yet_received'}
for name,obj in [('authorial_core.json',core),('embodiment_review.json',review),('test-case.json',case)]: (p/name).write_text(json.dumps(obj,ensure_ascii=False,indent=2)+'\n')
files=['authorial_core.json','embodiment_review.json','test-case.json','randomization.json']
(p/'prepack-freeze-sha256.json').write_text(json.dumps({f:hashlib.sha256((p/f).read_bytes()).hexdigest() for f in files},indent=2)+'\n')
print((p/'prepack-freeze-sha256.json').read_text())
