"""Research authoring source, deliberately outside runtime skill assets."""
SOURCES = []
CARDS = []

def source(sid, title, url, role, access, supports, limit):
    SOURCES.append(dict(id=sid,title=title,url=url,role=role,access=access,
                        accessed_on="2026-10-09 KST",supports=supports,limits=limit))

def card(cid, title, owner, slot, prop, meaning, boundary, observation, refs, variants):
    """Each variant: explicit directed relation and independently selectable prose."""
    CARDS.append(dict(id=f"SF{cid:03d}",title=title,owner=owner,slot=slot,
                     property_family=prop,meaning_ko=meaning,confusion_boundary=boundary,
                     observation_condition=observation,source_ids=refs.split(),
                     variants=variants,authorship="researcher_derived_optional_realizations",
                     status="research_draft_not_runtime_registered"))

def variant(subject, predicate, obj, text):
    return dict(relation=dict(subject=subject,type=predicate,object=obj),prompt_en=text)

source("S01","Threads sewing glossary","https://www.threadsmagazine.com/project-guides/learn-to-sew/sewing-terms-to-know","sewing_educator","page_text","다트, 보닝, 바이어스, 프린세스 심, 암홀, 개더와 루싱의 제작 용어.","외형에서 숨은 보강재나 제조 공정을 확정하지 않는다.")
source("S02","Seamwork understanding ease","https://www.seamwork.com/sewing-tutorials/understanding-ease","pattern_maker","page_text","착용 여유와 디자인 여유의 구분.","핏·주름 사진은 여유량 수치나 압력 측정이 아니다.")
source("S03","Seamwork guide to shirring","https://www.seamwork.com/sewing-tutorials/a-guide-to-elastic-shirring","pattern_maker","page_text","탄성실 셔링과 자수 스모킹의 차이; 가벼운 직물의 반복 봉제.","현대 제품의 smocked 판매명을 모두 전통 자수 스모킹으로 번역하지 않는다.")
source("S04","Threads geometric flounces","https://www.threadsmagazine.com/2020/02/19/how-to-sew-geometric-flounces","sewing_educator","page_text","상부 부착선에 개더 없이 하부 폭을 늘리는 플라운스.","플라운스는 러플 계열에도 분류되므로 무조건 상호 배타적 판매명으로 만들지 않는다.")
source("S05","Seamwork cotton fabric guide","https://www.seamwork.com/fabric-guides/a-guide-to-cotton-fabrics-for-garment-sewing-from-lawn-to-denim-and-everything-in-between","pattern_maker","page_text","면 원료와 직물 조직 구분; lawn/voile/poplin/eyelet/seersucker/knits.","원료 이름은 두께·비침·시원함의 보편적 보증이 아니다.")
source("S06","Cotton Incorporated textile weaving","https://cottonworks.com/wp-content/uploads/2018/01/Weaving_booklet-for_web.pdf","textile_industry","pdf_text","평직·능직·새틴의 조직과 경사·위사; plain weave chambray.","미세 조직이 해상도에서 식별되지 않으면 exact weave를 픽셀로 확정하지 않는다.")
source("S07","CottonWorks single and double knits","https://cottonworks.com/learning-hub/knitting/single-and-double-knits/","textile_industry","page_text","저지·리브·테리 조직의 차이와 표면 구조.","골의 굵기와 고리 면은 제품별로 다르며 섬유 조성은 별도다.")
source("S08","Lenzing TENCEL brand portfolio","https://www.lenzing.com/products/brands/tenceltm/","fiber_manufacturer","page_text","TENCEL 브랜드 아래 Lyocell, Modal, Lyocell Filament 구분.","최초 대화의 lyocell/modal 설명에 filament를 보완; 모든 lyocell이 TENCEL인 것은 아니다.")
source("S09","LYCRA quality FAQ","https://one.lycra.com/en/lycra-frequently-asked-questions/quality-lycra","fiber_manufacturer","search_page_text","spandex/elastane은 같은 탄성 섬유 종류; LYCRA는 브랜드.","늘어나는 옷이 모두 LYCRA라는 추론은 배제한다.")
source("S10","REI breathable fabrics","https://www.rei.com/learn/expert-advice/how-to-pick-the-most-breathable-fabrics.html","outdoor_educator","page_text","원단 구조·무게·수분 이동·건조 속도가 별개 요인.","시각 후보에서 성능 수치·쾌적함의 체험 결과를 주장하지 않는다.")
source("S11","Skin Cancer Foundation clothing UPF","https://www.skincancer.org/skin-cancer-prevention/sun-protection/sun-protective-clothing/","health_education","search_page_text","UPF는 직물을 통과하는 자외선에 관한 성능 지표이며 표시와 연관된다.","이번 용도는 비시각 성능 메타데이터 분리; 건강 조언이나 성능 인증을 하지 않는다.")
source("S12","Seafolly fit guide","https://us.seafolly.com/blogs/sf-world/your-guide-to-find-the-perfect-fit","swimwear_brand","page_text","분리형 수영복의 형태·커버리지·지지 선택을 나누는 제품 안내.","브랜드의 편안함·체형 보정·자외선 홍보를 픽셀 의무로 옮기지 않는다.")
source("S13","Seafolly Brazilian bikini cut","https://us.seafolly.com/blogs/sf-world/dare-to-bare-the-brazilian-bikini-cut","swimwear_brand","page_text","브랜드가 Brazilian을 classic과 thong 사이의 뒤판 커버리지로 설명.","다른 브랜드의 cheeky/Brazilian 면적과 일치한다고 보지 않는다.")
source("S14","Seafolly tankini","https://us.seafolly.com/blogs/sf-world/what-is-a-tankini","swimwear_brand","page_text","긴 상의와 독립 하의가 있는 탱키니.","겹쳐 가려진 분리 경계는 사진에서 자동 확인되지 않는다.")
source("S15","Seafolly high-leg high-waist bottom","https://sg.seafolly.com/products/jetset-lure-high-leg-high-waist-bikini-bottom-j30196-black","swimwear_brand","search_snippet_open_failed","같은 제품명에 high leg와 high waist가 공존.","직접 열기는 접근 오류; 제품 제목 확인만 근거이며 정확한 치수·뒷면 면적은 미확인.")
source("S16","Seafolly resort cover ups","https://us.seafolly.com/collections/kaftans-cover-ups","swimwear_brand","search_page_text","kaftan/cover-up은 수영복 위의 의복 용도와 여러 형태를 결합.","해변 장면·젖은 상태·투명함을 자동 추가하지 않는다.")
source("S17","Cupshe Monokini / Cut Out","https://www.cupshe.com/collections/monokini-cut-out","swimwear_brand","page_text","현대 monokini 판매 분류는 컷아웃 원피스 수영복을 포함.","1964 역사형과 현대 상품명을 같은 기본 구조로 병합하지 않는다.")
source("S18","FIT history of women's swimwear","https://fashionhistory.fitnyc.edu/a-history-of-womens-swimwear/","fashion_history_education","page_text","1964 Gernreich monokini, 후기 high-cut와 bandeau 수영복의 역사적 문맥.","기관 문헌 종합이며 제품 범주나 현재 유행 순위의 보편 표준이 아니다.")
source("S19","Ahiida Sportz-Fit Burqini","https://ahiida.com/product/sz-ultramarine-black-spliced/","swimwear_designer","page_text","제품은 2-piece 구성이고 Hijood 머리 덮개가 부착됨.","모든 burkini를 3-piece나 분리형 후드로 고정하지 않고 종교·국적도 추론하지 않는다.")
source("S20","Seamwork Negroni camp shirt","https://www.seamwork.com/pdf-sewing-patterns/negroni-vintage-camp-shirt","pattern_maker","page_text","convertible/camp collar; 같은 패턴에 긴소매·짧은소매 버전.","camp/Cuban 판매명 중첩을 인정하되 반소매를 필수로 만들지 않는다.")
source("S21","Burda 6502 peasant blouses","https://simplicity.com/burda-style/bur6502","pattern_maker","search_page_text","래글런 반소매/넓은 목밴드와 긴소매/드로스트링 버전.","피전트는 컵·퍼프·스퀘어넥이 모두 필수인 단일 템플릿이 아니다.")
source("S22","Burda 5891 halter top","https://simplicity.com/burda-style/bur5891","pattern_maker","page_text","동일 원단 밴드가 앞부분을 모아 목 뒤에서 묶임.","끈의 연결 방식이 앞가슴 파임·소재·노출 전체를 결정하지 않는다.")
source("S23","Free People Prairie Field milkmaid top","https://www.freepeople.com/shop/prairie-field-top/","fashion_brand","page_text","milkmaid 상품에 ruched bust, flutter sleeves, square neck, semi-sheer, smocked back.","퍼프소매나 면 섬유는 milkmaid의 보편 필수가 아님; 이 상품은 polyester 표시.")
source("S24","Wacoal balconette vs demi","https://www.wacoalindia.com/blogs/stories/balconette-vs-demi-cup-choosing-the-right-style-for-you","lingerie_manufacturer","page_text","컵 윗선·끈 배치·커버리지에 관한 제조사 설명.","같은 사이트 제품명에도 balconette와 demi가 함께 쓰임; 전세계 배타적 표준 아님.")
source("S25","Wacoal normal vs push-up bra","https://www.wacoalindia.com/blogs/stories/understanding-the-difference-between-a-normal-bra-and-a-push-up-bra","lingerie_manufacturer","page_text","push-up의 패드와 와이어 유무는 독립적인 설계 요소.","가슴 모양만으로 패드·와이어의 실제 존재나 효과를 증명하지 않는다.")
source("S26","CAKES grippy circles","https://cakesbody.com/products/grippy-cakes-circles","garment_accessory_manufacturer","page_text_redirect","독립적인 국소 커버 제품; adhesive와 non-adhesive 제품군 구분.","소재·접착·피부 안전성·재사용 성능은 이미지 판단으로 일반화하지 않는다.")
source("S27","Seamwork Posie surplice dress","https://www.seamwork.com/pdf-sewing-patterns/posie-surplice-wrap-dress","pattern_maker","page_text","surplice 몸판에 허리끈과 side invisible zipper가 공존.","랩처럼 보이는 네크라인과 실제로 풀리는 랩 여밈을 구별한다.")
source("S28","Butterick B5764 mock wrap","https://simplicity.com/butterick/pdb5764","pattern_maker","page_text","pullover mock-wrap surplice 몸판, raised elasticized waist.","표면의 겹침과 탈착 방식은 서로 다른 구조다.")
source("S29","Simplicity S3118 corset and skort","https://simplicity.com/simplicity/pds3118","pattern_maker","page_text","크롭 코르셋과 앞판 비대칭으로 shorts가 보이는 pleated skort.","skort 내부가 가려져 있으면 바지 연결을 사진에서 확정하지 않는다.")
source("S30","Simplicity S8134 culottes trousers shorts","https://simplicity.com/simplicity/pds8134","pattern_maker","search_page_text","wrap-front pants, culottes, side-tie shorts, wide-leg elastic-waist pants 변형.","짧다·넓다·랩처럼 보인다는 한 단서만으로 기본 의복을 결정하지 않는다.")
source("S31","McCall M8454 romper","https://simplicity.com/mccalls/m8454","pattern_maker","search_snippet","랩 앞판 롬퍼에 shorts와 앞을 덮는 세 가지 skirt 옵션.","스커트 같은 앞판이 반드시 분리된 원피스를 뜻하지 않는다.")
source("S32","Liberty print collections","https://www.libertylondon.com/uk/features/craft/about-liberty-fabrics-collections.html","textile_design_house","page_text_partial_find_unavailable","프린트 아카이브의 식물·꽃·추상 구성 참조.","브랜드 아카이브 분류를 모든 floral 패턴의 필수 구성이나 원료로 일반화하지 않는다.")
source("S33","Saint James Breton shirt history","https://us.saint-james.com/pages/our-history","clothing_manufacturer","search_page_text","Breton/mariniere와 해양 의복의 브랜드 역사.","현재 모든 마린 패턴의 줄 수·폭·색·착용자 국적을 고정하지 않는다.")
source("S34","V&A paisley and India","https://www.vam.ac.uk/dundee/articles/a-long-way-from-home-the-paisley-pattern-and-india","museum","search_page_text","paisley/buta/kolka의 문화·직물 문맥과 다양한 표면 사용.","원래 문화 기록을 유지하되 착용자의 출신·지역을 생성하지 않는다.")
source("S35","V&A Vivienne Westwood","https://www.vam.ac.uk/collections/vivienne-westwood","museum","page_text","펑크·DIY·재조합의 복식 문맥.","패션의 체인·스터드·찢김은 실제 폭력 사건의 증거가 아니다.")
source("S36","Vogue aesthetics of 2023","https://www.vogue.com/article/core-aesthetic-microtrends-2023","editorial_usage","page_text","비공식 -core 명칭과 여러 옷의 연상군이 중첩됨.","2023 회고 자료; 2026 최신 유행 순위로 쓰지 않고 본문 파생 요약은 짧게 제한한다.")
source("S37","Vogue tomato girl summer","https://www.vogue.com/article/kendall-jenner-model-tomato-girl-summer-trend","editorial_usage","page_text","tomato-girl의 여름 착장 사용 문맥.","스타일명은 실제 토마토 소품·식생활·나이·거주지를 요구하지 않는다.")
source("S38","Bazaar A-Z microtrends","https://www.harpersbazaar.com/fashion/trends/a65784060/a-z-micro-trends-defined/","editorial_usage","search_page_text","coastal/cowgirl/cottage/coquette/sport 계열 스타일명의 중첩.","편집자의 사용 설명이며 엄격한 분류 표준이나 현재 인기 검증이 아니다.")
source("S39","Bazaar sheer clothing","https://www.harpersbazaar.com/fashion/trends/a43532183/how-to-wear-sheer-clothes/","editorial_usage","page_text","시어 의복을 이너·레이어와 함께 해석하는 착장 문맥.","비침이 곧 피부 노출·속옷 미착용이라는 의미는 아니다.")
source("S40","Vogue whale-tail outfit","https://www.vogue.com/article/teyana-taylor-aughties-trend-whale-tail","editorial_usage","search_page_text","의복 뒤쪽 개구부를 통해 별도 thong이 보인 착장 관찰.","고래 꼬리·보디수트 자체의 끈·전체 Y2K 필수로 확장하지 않는다.")
source("S41","Castañer espadrille atelier","https://castaner.com/en-gr/pages/atelier","footwear_manufacturer","page_text","jute braid를 사용하는 에스파드리유 제작 문맥.","로프 같은 질감은 실제 원료·전체 밑창 재료·생산지를 증명하지 않는다.")
source("S42","Camper Brutus fisherman sandals","https://www.camper.com/en_US/men/shoes/brutus/camper-brutus_sandal-K100778-006","footwear_manufacturer","page_text","fisherman 제품 분류와 갑피·끈 형태의 상품 참조.","이미지의 가죽·EVA·편안함을 모든 케이지 샌들로 일반화하지 않는다.")
source("S43","MasterClass neckline guide","https://www.masterclass.com/articles/guide-to-necklines","fashion_education","page_text","crew/scoop/V/square/sweetheart/boat/cowl/illusion/halter/surplice 외형 설명.","본문 갱신은 2021-06-07; 페이지 제목의 2026은 새 연구 날짜가 아님. 체형 보정 홍보는 사용하지 않는다.")
source("S44","Havaianas sandals vs flip-flops","https://www.havaianas.com/blogs/news/sandals-vs-flip-flops-what-s-the-difference","footwear_manufacturer","search_page_text","toe-post Y strap과 발등 band slide의 연결 차이.","thong은 신발 문맥에선 발가락 사이 끈 구조; 속옷으로 변환하지 않는다.")
source("S45","Vogue Alexander Wang spring 2025","https://www.vogue.com/fashion-shows/spring-2025-ready-to-wear/alexander-wang","runway_observation","search_snippet","아주 짧은 half-shirt 밑단과 underboob 표현이 함께 쓰인 사례.","패션 비평의 한 사례이며 모든 micro-crop이 같은 노출을 요구하지 않는다.")
source("S46","Fashion Fabrics Club fabric glossary","https://fashionfabricsclub.com/pages/fabric-glossary","fabric_supplier","page_text","georgette/organza/eyelet/rib와 silk·nylon·polyester satin의 조직 구분.","공급사 용어 사용의 근거; glossary의 모든 성능·원료 일반화 문장을 표준으로 채택하지 않는다.")
source("S47","Mood polyester charmeuse","https://www.moodfabrics.com/collections/polyester-charmeuse-fashion-fabrics?limit=90","fabric_supplier","page_text","polyester 섬유를 satin weave로 짠 charmeuse의 상품 설명.","Cotton Incorporated의 satin/sateen 구분과 지역/용어 경계가 다름; 조직과 원료를 별도 보존한다.")

card(1,"베이식 티와 베이비 티","same T-shirt","wardrobe_style","wardrobe.fit","베이식은 장식 수준, baby tee는 짧고 비교적 가까운 몸판·소매의 판매 형태다.","baby는 착용자 나이가 아니며 크롭 길이·배꼽 노출과 필연적으로 결합하지 않는다.","상체 앞면에서 소매 끝·몸판 밑단·여유를 함께 본다.","S02 S07",[variant("the T-shirt sleeve hem","ends_near","the upper arm","the T-shirt has short fitted sleeves; its compact body ends at the upper hip")])
card(2,"크롭·마이크로 크롭 길이","same top hem relative to torso","garment_detail","wardrobe.length","일반 상의보다 짧은 밑단의 상대 위치이며 micro는 비표준 강화 표현이다.","밑단, 하의 윗선, 배꼽 위치는 세 개의 기준선이다; 노출을 자동 추론하지 않는다.","상의 밑단과 허리 주변이 가려지지 않는 앞면.","S23 S45",[variant("the top hem","ends_above","the trouser waistband","the cropped top ends above the trouser waistband; a narrow band of abdomen separates the two garment edges"),variant("the top hem","ends_at","the lower ribcage","the short top ends at the lower ribcage; a separate high waistband rises close to that hem")])
card(3,"탱크·골지 탱크·캐미솔","same top shoulder connections","garment_detail","wardrobe.structure.strap","민소매 탱크의 어깨 연결과 가는 끈 캐미솔을 구분하고 rib는 별도 표면 축이다.","tank/cami 끈 폭의 판매 경계는 겹친다; 광택·레이스·피부 노출은 별도.","어깨 연결부·암홀·원단 골을 각각 식별.","S07 S43",[variant("the tank shoulder band","connects","the front and back bodice","broad fabric bands join the tank front and back over the shoulders; its armholes have finished edges"),variant("the camisole strap","connects","the front and back upper edges","two narrow straps join the camisole front and back; the light bodice hangs from those straps")])
card(4,"튜브·반도·스트랩리스","same strapless top","garment_detail","wardrobe.structure.strap","수평 몸통 밴드와 어깨 연결 없는 구조, 그리고 몸판 길이를 독립적으로 기술한다.","반도 밴드 형태에 탈착 스트랩이 있는 제품도 있어 bandeau=strapless 완전 동의어는 아니다.","앞·어깨·옆면, 탈착 연결 고리는 별도 가까운 시점.","S12 S43",[variant("the strapless top upper edge","runs_across","the upper torso","the strapless top has a horizontal upper edge across the torso; its continuous bodice extends to the waist")])
card(5,"홀터·하이넥 홀터","same halter top or dress","garment_detail","wardrobe.structure.strap","목 뒤 연결 경로와 앞쪽 덮는 높이를 분리한다.","halter는 깊은 V·백리스·삼각컵·짧은 길이의 동의어가 아니다.","목 뒤 연결까지 보이는 사선 시점; 앞목 높이는 앞면에서.","S22 S43",[variant("the halter front panel","joins_at","the back of the neck","the halter front panel rises to the base of the neck; its upper bands join behind the neck"),variant("the halter straps","join_at","the back of the neck","two bands rise from the open front neckline; they tie together behind the neck")])
card(6,"스카프·반다나 톱","same tied scarf top","wardrobe_style","wardrobe.structure.front_fastener_state","평면 천의 겹침·묶음과 삼각형 밑단이 특징인 하나의 실현 방식이다.","실제 스카프를 묶은 구조와 완성된 패턴 의복을 분리; paisley는 필수 아님.","앞의 삼각 밑단과 실제 묶임 위치를 연결해 본다.","S16 S30",[variant("the scarf corners","tie_at","the back of the same torso","a folded scarf wraps around the torso; its lower corner points downward and its side corners meet in a back knot")])
card(7,"브라톱·브라렛","same short bust-covering top","wardrobe_style","wardrobe.structure","짧은 상의의 컵·밴드·끈 형태와 부드러운 브라렛을 선택형으로 표현한다.","bra top이 스포츠 기능·와이어·란제리 문맥을 모두 요구하지 않는다.","가슴 위 가장자리와 밑가슴 밴드를 볼 수 있어야 한다.","S12 S24 S25",[variant("the short top cups","join","the underbust band","the short top has two fabric cup sections; both join a continuous underbust band")])
card(8,"랩 여밈과 서플리스 목둘레","same crossed front bodice","garment_detail","wardrobe.structure.front_fastener_state","사선 앞판 겹침은 네크라인 관계이고 실제 wrap은 여밈 관계까지 필요하다.","끈 장식이나 V선만으로 풀리는 랩을 확정하지 않는다. pullover mock-wrap과 side-zipper를 별도 변형으로 유지.","겹침의 자유 가장자리와 고정·매듭 양 끝을 확인한다.","S27 S28",[variant("the outer front panel","overlaps","the inner front panel of the same dress","one dress front panel overlaps the other diagonally; its free edge meets a waist tie"),variant("the two front bodice panels","cross_above","the fixed waist seam","two front bodice panels cross into a V neckline; their lower edges join the same fixed waist seam")])
card(9,"타이프런트·타이백","same top closure","garment_detail","wardrobe.structure.front_fastener_state","묶음이 놓인 방향과 실제로 연결하는 패널을 지정한다.","앞 매듭이 복부 틈을 반드시 만들지는 않으며 tie-back이 백리스와 같지는 않다.","매듭·끈 출발점·양 패널 끝을 한 시점에서 본다.","S22 S23",[variant("the two front fabric ends","join_in","a knot on the same top","two front fabric ends meet in a knot; each end remains attached to its own side of the bodice"),variant("the two back straps","join_in","a knot across the same back opening","two back straps meet in a visible knot; their ends connect to the left and right bodice edges")])
card(10,"밀크메이드·피전트","same blouse selected construction","wardrobe_style","wardrobe.structure","연상군을 컵 주변 모음·목둘레 모음·소매 볼륨·자수 등 선택 요소로 해체한다.","milkmaid에 퍼프·면·컵·스퀘어넥을 모두 의무화하지 않는다; peasant도 같은 템플릿 아님.","선택한 주름 출발점과 소매/몸판의 연결이 보이는 상체.","S21 S23",[variant("the blouse bust gathers","converge_toward","the lower bodice seam","small gathers shape the blouse bust above a horizontal seam; flutter sleeves extend from the shoulder openings"),variant("the blouse neckline gathers","radiate_into","the loose front bodice","fine gathers run around the blouse neckline; the loose bodice hangs below the gathered opening")])
card(11,"스모크 톱·셔링·스모킹","same garment gathered area","garment_detail","wardrobe.structure","평행 봉제 줄의 모음과 주름 위 장식 자수를 구분한다.","retail smocked가 실제 탄성 셔링일 수 있다; 늘어남 성능은 정지 사진으로 확정하지 않는다.","봉제 줄 또는 장식 자수가 식별되는 근접면.","S03",[variant("parallel stitch rows","gather","the same blouse waist panel","parallel stitched rows gather the blouse waist panel; small folds repeat between the rows"),variant("decorative crossing stitches","bridge","the gathered folds of the same panel","decorative stitches bridge adjacent gathered folds; the repeated stitching forms a small geometric pattern")])
card(12,"크로셰·크로셰 톱·커버업","same crocheted garment layer","surface_material","wardrobe.material.visible_weave","코바늘 고리·모티프와 조직 틈을 표현하되 의복 역할은 별도로 둔다.","crochet는 섬유 종류가 아니며 촘촘한 crochet도 가능; 모든 crochet가 비치지는 않는다.","원래 저장 해상도에서 고리·틈을 식별; 아래층도 함께 보이는 시점.","S01 S16",[variant("the crochet loops","form","the same top surface","interlinked yarn loops form the top surface; small openings separate the looped motifs")])
card(13,"시어·시어 셔츠·세미시어","same outer fabric and inner layer","surface_material","wardrobe.material.transmission","연속된 원단을 통한 광학 투과를 의복 안쪽 층에 연결한다.","같은 색 속옷은 피부와 다르며 시어를 구멍·나체로 대체하지 않는다.","외곽 원단 경계, 겹수, 아래층의 연속성이 보이는 시점.","S05 S39",[variant("the sheer shirt fabric","transmits_the_outline_of","the opaque camisole underneath","the sheer shirt remains a continuous outer fabric layer; the opaque camisole is visible through it"),variant("the overlapping sheer panels","reduce_visibility_of","the inner garment","the inner garment is visible through a single sheer panel; its outline becomes weaker where two panels overlap")])
card(14,"캠프·쿠반칼라","same shirt collar","garment_detail","wardrobe.neckline","목 주변에 평평하게 펼쳐지는 convertible 칼라와 열린 앞선을 기술한다.","칼라가 tropical print·반소매·특정 국적을 요구하지 않는다.","칼라의 접힌 끝과 앞여밈 연결이 보이는 정면.","S20",[variant("the open shirt collar","lies_flat_against","the same upper chest","the open collar folds flat against the upper chest; its points sit on either side of the front opening")])
card(15,"알로하 셔츠·트로피컬 프린트","same shirt printed surface","wardrobe_style","wardrobe.pattern","열대 식물 등의 무늬 모티프와 셔츠 기본 구조를 분리한다.","모든 camp collar가 Hawaiian은 아니며 착용자 민족·해변 배경은 필수 아님.","큰 잎·꽃의 반복이 원단을 따라 이어지는 시점.","S32 S18",[variant("tropical leaf motifs","repeat_across","the same shirt panels","large tropical leaf motifs repeat across the shirt panels; the print follows the fabric folds")])
card(16,"폴로 칼라와 짧은 플래킷","same polo shirt","garment_detail","wardrobe.neckline","접힌 칼라와 목에서 몸판 중간까지만 내려오는 짧은 단추선.","폴로 경기 장면이나 전체 셔츠형 단추 여밈이 아니다.","칼라와 부분 플래킷 끝이 함께 보이는 정면.","S01 S07",[variant("the button placket","ends_within","the polo front bodice","a folded collar surrounds the polo neckline; a short button placket ends within the front bodice")])
card(17,"베스트·웨이스트코트 단독 상의","same sleeveless vest","wardrobe_style","wardrobe.structure","앞단추·V선·조끼 몸판을 상의로 읽는 착장 방식.","속에 셔츠가 있어야 하는 의무도, 맨몸 단독 착장의 자동 의무도 없다.","소매 없는 연결과 앞여밈, 이너 여부는 실제로 보이는 부분만.","S01 S30",[variant("the vest front edges","meet_at","the central button row","the sleeveless vest fronts meet along a central button row; shaped side panels narrow toward the waist")])
card(18,"크루넥","same top neckline","garment_detail","wardrobe.neckline","목 아래를 비교적 높게 둥글게 감싸는 선.","high neck나 터틀넥 높이·필수 바디콘과 합치지 않는다.","목의 기준점과 원단 윗선이 드러난 앞면.","S43",[variant("the rounded top neckline","sits_near","the base of the neck","the rounded neckline sits near the base of the neck; the front fabric covers the upper chest")])
card(19,"스쿠프·딥 스쿠프","same top neckline","garment_detail","wardrobe.neckline","목 파임의 둥근 곡선과 깊이를 분리하여 기록한다.","U곡선, 넓은 폭, 깊은 파임은 관련 있지만 서로 동일하지 않다.","정면, 가장자리의 연속된 곡선과 내려가는 위치.","S43",[variant("the scoop neckline","curves_below","the collarbones","the neckline forms a broad rounded U; its lowest curve sits below the collarbones")])
card(20,"V와 플런징","same top central neckline","garment_detail","wardrobe.neckline","중앙 V 형상과 깊은 파임을 다른 속성으로 둔다.","plunge의 판매 설명이 V에 치우치더라도 특정 비V의 깊은 파임 문맥을 소거하지 않는다; cleavage 별도.","파임 양쪽 경계와 최저점이 식별되는 앞면.","S43 S24",[variant("the two sloping neckline edges","meet_at","a central front point","two sloping neckline edges meet at a central front point; the point lies below the upper chest")])
card(21,"스퀘어넥","same bodice neckline","garment_detail","wardrobe.neckline","가로 하단과 양쪽 직선에 가까운 측면으로 둘러싼 선.","쇄골 노출은 깊이·폭에 달림; 둥근 sweetheart나 bandeau의 직선만으로 대체 못함.","정면, 모서리가 실제 원단 가장자리여야 함.","S43 S23",[variant("the neckline side edges","join","the horizontal lower neckline edge","near-vertical neckline sides meet a horizontal lower edge; both corners are visible on the same bodice")])
card(22,"스위트하트","same bodice upper edge","garment_detail","wardrobe.neckline","두 윗곡선과 가운데 내려간 접점의 관계.","하트 프린트·가슴골·푸시업과 다른 구조.","컵 윗선 전체와 중앙 접점이 보이는 앞면.","S43",[variant("the two rounded upper edges","meet_at","the central neckline dip","two rounded upper edges meet at a central dip; the same fabric bodice continues below them")])
card(23,"스트레이트어크로스","same top upper edge","garment_detail","wardrobe.neckline","몸통 앞쪽을 수평으로 가로지르는 윗선.","어깨끈·컵 형태·밑단 길이는 별도다.","수평 윗선과 어깨 연결이 확인되는 앞면.","S43 S12",[variant("the straight upper edge","extends_across","the same front bodice","a straight upper edge extends across the front bodice; narrow shoulder straps attach at its outer ends")])
card(24,"보트·바토넥","same top neckline","garment_detail","wardrobe.neckline","얕고 좌우로 넓은 목 파임과 어깨 쪽 끝점.","넓음이 deep scoop이나 어깨 아래로 내려간 off-shoulder와 같지 않다.","양쪽 어깨까지 들어오는 정면.","S43",[variant("the boat neckline","extends_toward","both shoulder tops","the shallow neckline extends toward both shoulder tops; the fabric still covers the outer shoulders")])
card(25,"카울·드레이프","same hanging neckline fabric","garment_detail","wardrobe.material.drape","여분의 원단이 늘어져 생기는 앞목 주름과 중력 방향.","cowl은 단순 U컷·주름 프린트·별도 목걸이가 아니며 깊이는 선택.","드레이프 가장자리와 원단 연속이 읽히는 근접 사선.","S43 S01",[variant("the loose neckline fabric","hangs_between","its two shoulder attachments","loose neckline fabric hangs between its shoulder attachments; curved folds descend across the front")])
card(26,"오프숄더·바르도","same top upper edge and sleeves","garment_detail","wardrobe.coverage.shoulder","윗선이 양쪽 실제 어깨 아래로 내려간 상태.","drop shoulder 봉제선·cold-shoulder 개구부와 분리; 원단을 내린 착용 상태도 별도.","양쪽 어깨와 소매 시작점이 같이 보이는 앞면.","S43",[variant("the upper garment edge","sits_below","both shoulder tops","the upper garment edge sits below both shoulder tops; the sleeves begin around the upper arms")])
card(27,"원숄더·비대칭 목둘레","same bodice shoulder attachment","garment_detail","wardrobe.coverage.shoulder","원숄더는 한 어깨의 연결, asymmetry는 더 넓은 좌우 불균형 범주.","화면 왼쪽과 착용자 왼쪽을 혼동하지 않는다; 모든 비대칭이 원숄더는 아님.","어깨 양쪽과 같은 의복의 대각선을 확인.","S43",[variant("the bodice upper edge","rises_to","the wearer's right shoulder attachment","the bodice rises to the wearer's right shoulder; its opposite upper edge ends below the left shoulder")])
card(28,"콜드숄더","same sleeve shoulder bridge","garment_detail","wardrobe.coverage.shoulder","어깨의 개구부 위로 연결부가 남고 그 아래에 소매가 이어지는 구조.","off-shoulder 전체 이동과 다른 개구부 토폴로지.","어깨의 남은 브리지와 개구부 아래 소매 연결이 보임.","S43 S01",[variant("the shoulder bridge","spans_above","the sleeve shoulder opening","a fabric bridge remains over the shoulder opening; the sleeve continues below the exposed shoulder")])
card(29,"키홀·프런트 컷아웃","same front bodice opening","garment_detail","wardrobe.coverage.opening_location","키홀은 위쪽이 연결된 작은 개구부, front cutout은 위치 범주다.","목 파임의 열린 가장자리·망사 투과·찢김 프린트로 대체하지 않는다.","개구부 둘레의 연속된 경계와 위의 연결부.","S43 S17",[variant("the top neckline band","bridges_above","the enclosed keyhole opening","a small enclosed keyhole opens below the neckline; a fabric band bridges its upper edge")])
card(30,"일루전·누드 일루전","same sheer support panel","garment_detail","wardrobe.material.transmission","얇은 패널이 실제로 연결하는 경계와 피부색에 가까운 색을 별도로 기술한다.","nude는 색·착장·나체 다의어; 같은 피부색의 불투명 원단도 가능.","망사 가장자리·봉제·겹침이 확인되는 해상도; 피부색은 해당 착용자 기준.","S43 S39",[variant("the sheer support panel","connects","the bodice edge to the shoulder seam","a fine sheer panel connects the bodice edge to the shoulder seam; its faint boundary remains visible"),variant("the fabric surface color","resembles","the wearer's local skin tone","the fabric surface is close in color to the wearer's skin; a seam and folded fabric edge establish the garment layer")])
card(31,"슬리브리스·캡 슬리브","same top arm opening","garment_detail","wardrobe.structure.sleeve","소매 없음과 어깨끝만 덮는 짧은 소매의 차이.","슬리브리스는 암홀 깊이·겨드랑이 가시성·노출 면적을 자동 결정하지 않는다.","어깨끝·암홀 경계가 함께 보이는 앞/사선.","S01 S43",[variant("the sleeveless armhole edge","surrounds","the same arm opening","the finished armhole edge surrounds the arm opening; the bodice has no projecting sleeve"),variant("the cap sleeve edge","extends_over","the shoulder tip","a small cap sleeve extends over the shoulder tip; its lower edge ends above the upper arm")])
card(32,"플러터·퍼프 소매","same sleeve volume","garment_detail","wardrobe.structure.sleeve","플러터의 자유 하단 퍼짐과 퍼프의 모음으로 생긴 부피를 구분한다.","겹치는 flutter/puff cap 변형을 허용; 바람·움직임·좁은 허리를 필수화하지 않는다.","부착선·소매 하단과 부피를 동시에 봄.","S21 S23",[variant("the flutter sleeve free edge","flares_away_from","the upper arm","the flutter sleeve has a loose flared lower edge; its fabric hangs away from the upper arm"),variant("the gathered sleeve fabric","bulges_between","its shoulder seam and gathered cuff","the sleeve fabric bulges between the shoulder seam and a gathered cuff; small folds converge at both boundaries")])
card(33,"래글런·드롭숄더 연결선","same top sleeve-to-bodice seam","garment_detail","wardrobe.fit.shoulder.seam_position","겨드랑이-목 사선 연결과 실제 어깨보다 아래의 연결선 위치를 독립적으로 둔다.","노출·수치·어깨 너비·소매 길이는 다른 축; 원단무늬만 사선인 것은 raglan 아님.","봉제선의 실제 양 끝점과 신체 어깨 기준점을 확인.","S01 S02",[variant("the raglan sleeve seam","runs_from","the underarm to the neckline","the sleeve seam runs diagonally from the underarm to the neckline; the sleeve and bodice meet along that seam"),variant("the shoulder seam","lies_below","the wearer's shoulder tip","the shoulder seam lies below the wearer's shoulder tip; the sleeve begins down the upper arm")])
card(34,"딥 암홀·머슬 탱크","same armhole lower boundary","garment_detail","wardrobe.coverage.opening_location","암홀 아래끝이 몸통 옆으로 내려가는 위치와 민소매 기본 형태를 나눈다.","muscle tank가 항상 deep armhole는 아니며 팔을 올린 것만으로 넓은 암홀을 증명 못함.","팔이 옆면 경계를 가리지 않는 사선.","S01 S02",[variant("the armhole lower edge","descends_below","the underarm crease","the armhole lower edge descends below the underarm crease; the side opening exposes a narrow strip of torso")])
card(35,"레이서백·크로스백","same back strap network","garment_detail","wardrobe.structure.back_strap_connection","중앙 합류와 X 교차는 다른 연결 그래프다.","교차 그림·멀티끈·목걸이·다른 의복의 끈을 같은 스트랩으로 합치지 않는다.","뒤면에서 모든 연결 끝점과 교차/합류 지점을 확인.","S12 S22",[variant("the two upper back straps","converge_into","one central back band","two upper back straps converge into one central band; the band joins the lower back panel"),variant("the two back straps","cross_at","the center of the same back","two back straps cross at the center of the back; each continues to an opposite lower bodice attachment")])
card(36,"오픈백·백리스·로백","same back bodice boundary","garment_detail","wardrobe.coverage.opening_location","뒤판 개구부·적은 뒤판·낮은 뒤쪽 윗선을 구분한다.","앞면 높은 덮임과 공존 가능; hair occlusion은 등을 가리는 의복 커버리지와 다름.","뒤판 경계를 머리카락·팔이 가리지 않는 뒤 사선.","S22 S43",[variant("the back upper garment edge","sits_below","the shoulder blades","the back garment edge sits below the shoulder blades; the front bodice remains high at the neck")])
card(37,"오픈사이드·허리·사이드 컷아웃","same garment side opening","garment_detail","wardrobe.coverage.opening_location","완전히 둘러싼 구멍과 옆 가장자리까지 열린 틈의 경계를 구분한다.","waist와 side는 위치에 따라 중첩 가능; cutout은 단순 시어·분리 의복 간 공백이 아님.","열린 부위의 위·아래 연결과 둘레를 확인.","S17 S39",[variant("the side cutout perimeter","surrounds","a waist skin window within the same bodice","a skin window is enclosed within the bodice side; continuous fabric remains above and below the opening"),variant("the top and bottom side edges","join_through","a narrow connecting band","the garment side is open between its upper and lower panels; a narrow band connects those panels")])
card(38,"피티드·바디스키밍","same garment local contact","garment_detail","wardrobe.fit","재단된 가까운 핏과 윤곽을 가볍게 따르는 직물의 국소 접촉·여유.","새 체형을 생성하지 않으며 tight/압박/정확 치수는 별도.","몸통의 옷 경계·접촉 구간·처지는 구간이 보이는 사선.","S02",[variant("the body-skimming fabric","hangs_between","its local torso contact areas","the fabric lightly follows the torso; small loose spans hang between its contact areas")])
card(39,"바디콘·스킨타이트","same opaque fitted garment","wardrobe_style","wardrobe.fit","몸통과 하체 윤곽 가까이 따라가는 의복의 여유 상태.","붙음은 비침·피부 노출·가슴/힙 확대가 아니며 stretch 섬유 조성은 미확인.","불투명 원단의 경계와 주름 상태를 확인.","S02 S09",[variant("the close-fitting fabric","follows","the torso and hip contour","opaque close-fitting fabric follows the torso and hip contour; the garment edge remains continuous across the covered areas")])
card(40,"밴디지 스타일","same banded garment panels","garment_detail","wardrobe.structure","띠 같은 패널이 몸통 주위를 감싸는 시각적 구조.","진짜 압박·의료 붕대·로프 결박·무조건 가로줄 프린트로 합치지 않는다.","패널 부착 경계·겹침과 질감이 식별되는 근접면.","S02 S01",[variant("the broad fabric bands","join_along","their edges around the same bodice","broad fabric bands wrap around the bodice; their joined edges form visible horizontal panel boundaries")])
card(41,"허리 강조·아워글라스·핏앤플레어","same garment waist and skirt","wardrobe_style","wardrobe.fit.waist_suppression","의복 허리의 좁음, 상하부 폭 대비, 하부 퍼짐 시작을 따로 기술한다.","hourglass 의복을 신체 형태 변경으로 해석하지 않는다; 모든 허리강조가 flare 아님.","의복 허리와 상하부 폭을 한 시점에서 봄.","S02 S27",[variant("the skirt panels","flare_below","the fitted garment waist","the bodice narrows at the garment waist; the skirt panels flare outward below that seam")])
card(42,"바이어스 컷","same garment drape and grain specification","garment_detail","wardrobe.material.drape","재단 방향은 명세로, 몸을 따라 사선으로 흐르는 처짐은 관찰로 나눈다.","45도는 true bias 정의이지 사진의 주름각 측정치 아님; 새틴·silk·bodycon과 독립.","직물 결이 보이지 않으면 drape만 관찰하고 제작 방식은 NOT_OBSERVABLE.","S01 S06",[variant("the hanging skirt fabric","forms","oblique soft folds around the hips","soft oblique folds settle around the hips; the skirt fabric falls in a continuous fluid sheet")])
card(43,"릴랙스드·박시·오버사이즈","same garment ease distribution","wardrobe_style","wardrobe.fit","편한 여유, 직선 몸판, 확장된 품·어깨·길이는 서로 다른 속성이다.","boxy가 항상 oversized는 아니며 긴 길이만으로 전부 과대 사이즈라 확정 못함.","옷과 몸의 간격·어깨선·밑단을 함께 본다.","S02 S20",[variant("the boxy shirt side edges","descend_without_narrowing_to","the straight lower hem","the boxy shirt side edges descend to a straight hem; the bodice remains roomy through the waist")])
card(44,"뷔스티에·코르셋·오버/언더버스트","same structured garment upper boundary","wardrobe_style","wardrobe.structure","컵을 포함한 몸통 구조와 가슴 아래에서 시작하는 경계를 분리한다.","fashion corset 표면이 실제 압박·waist training을 입증하지 않는다; underbust는 다른 상의 층 필요할 수 있음.","실제 윗선과 이너의 층 순서·패널 경계를 볼 수 있어야 한다.","S01 S29",[variant("the underbust outer garment edge","starts_below","the bust of the inner blouse","the structured outer garment begins below the bust; the blouse continues above its upper edge"),variant("the overbust bodice panels","continue_from","the cup area into the garment waist","the overbust bodice panels continue from the cup area into the waist; visible seams divide the shaped panels")])
card(45,"발코네트·데미 컵","same cup top and strap attachment","garment_detail","wardrobe.coverage.cup_edge","컵 윗선의 방향·깊이와 넓게 떨어진 끈의 상대 배치를 기록한다.","브랜드가 두 이름을 함께 사용하므로 고정 컵 면적 %나 배타적 종류로 저장하지 않는다.","컵 윗선 양쪽과 중앙·끈 부착점이 보이는 앞면.","S24",[variant("the cup upper edges","run_nearly_horizontally_between","the outer strap attachments","the cup upper edges run nearly horizontally; the shoulder straps attach near the outer cup sides")])
card(46,"플런지 컵 중앙선","same bra or swim top center","garment_detail","wardrobe.coverage.cup_edge","낮은 중앙 연결부와 두 컵의 안쪽 경계.","plunge bra의 형태와 deep V dress의 겉목 파임을 하나의 의복으로 합치지 않는다.","컵 사이의 연결과 이너/겉옷을 구분할 앞면.","S24 S25",[variant("the two cup inner edges","meet_at","a low central connector","the cup inner edges descend toward a low central connector; each cup remains joined to the same underbust band")])
card(47,"푸시업·언더와이어·몰디드 컵","same cup internal specification","garment_detail","wardrobe.structure","패드 위치·컵하부 보강·성형 구조는 독립 설계 속성이다.","표면의 매끈함은 실제 wire/pad/열성형 공정 증거가 아니다; 몸 수정 후보로 전환하지 않는다.","숨은 속성은 명세로 보존; 원단 외곽·보강 채널을 보여주는 경우만 별도 후보화.","S24 S25",[])
card(48,"보닝·프린세스 심·다트·언더버스트 심","same bodice seam or casing","garment_detail","wardrobe.structure","보강재·패널 연결선·쐐기 접힘·가슴아래 절개는 다른 기능과 외형이다.","보닝 채널을 보강재 존재로, 절개선을 피부 노출로, princess를 왕족으로 읽지 않는다.","연결선의 시작/끝·원단 양쪽 이어짐·입체 fold apex를 확인.","S01",[variant("the dart fold legs","converge_at","one point in the same bodice","two stitched dart legs converge at one bodice point; the surrounding fabric forms a shallow shaped fold"),variant("the curved vertical seam","joins","two shaped panels of the same bodice","a curved vertical seam joins two shaped bodice panels; it continues from the upper chest toward the waist")])
card(49,"데콜테와 클리비지","same wearer and garment upper opening","garment_detail","wardrobe.coverage.upper_edge","목 아래·쇄골·가슴 윗부분의 영역과 가슴 사이 중앙 골 가시성을 구별한다.","네크라인 이름이나 컵 모양만으로 cleavage를 확정하지 않는다.","요청된 해당 부위가 실제 시점·원단·머리카락에 가려지지 않아야 한다.","S43 S24",[variant("the garment upper edge","leaves_visible","the collarbone area","the garment edge sits below the collarbones; the exposed collarbone area remains unobstructed")])
card(50,"사이드붑·언더붑","same adult wearer boundary and garment edge","garment_detail","wardrobe.coverage.opening_location","가슴 옆 경계와 아랫경계의 가시성은 위치가 다른 관찰 상태다.","깊은 암홀·micro crop·underbust seam이 해당 노출을 필수로 만들지 않는다; 슬랭은 의복 종류 아님.","해당 경계와 이를 덮는 가장자리의 관계가 직접 보여야 함; 선정 여부와 사실 판정은 별도.","S45 S43",[variant("the lateral garment edge","leaves_visible","a small lateral chest contour","the side garment edge leaves a small lateral chest contour visible; the front fabric remains in place"),variant("the short lower top edge","sits_above","a small lower chest contour","the short lower top edge sits above a small lower chest contour; the covered upper bodice remains continuous")])
card(51,"미드리프와 배꼽 가시성","same top hem, lower waistband and wearer","garment_detail","wardrobe.coverage.opening_location","복부의 연속된 틈과 그 틈 안에 실제 배꼽이 보이는 상태를 별개로 둔다.","cropped/high-rise/low-rise 각 이름은 배꼽의 실제 가시성을 보증하지 않는다.","상하의 기준선과 배꼽이 한 시점에 식별됨.","S02 S15",[variant("the exposed abdomen gap","contains","the visible navel","the top hem ends above the navel; the lower waistband sits below it, leaving the navel visible between the garment edges"),variant("the exposed abdomen gap","lies_above","the covered navel","a narrow abdomen strip appears below the top hem; the waistband covers the navel beneath that strip")])
card(52,"슬릿·사이하이·슬릿 스커트","same skirt slit and hem","garment_detail","wardrobe.coverage.opening_location","밑단에서 이어진 트임·상단 높이·시점에 따른 실제 벌어짐을 분리한다.","긴 skirt와 thigh-high slit은 공존; 트임 높음이 다리 노출을 항상 보증하지 않는다.","밑단·트임 상단과 다리가 보이는 전체/사선; 닫힌 겹침이면 가시성은 미확인.","S01 S27",[variant("the skirt slit edges","separate_below","a slit apex at the upper thigh","two skirt edges separate below a slit apex at the upper thigh; the same long hem continues on both sides")])
card(53,"오픈워크의 구멍과 투과","same openwork outer layer and inner layer","surface_material","wardrobe.material.transmission","실제 실 사이 개구부와 연속 원단을 통한 투과를 분리한다.","mesh/lace/crochet=나체가 아님; lining이 조직 구멍 뒤를 덮을 수 있다.","구멍·실·아래층 경계를 원해상도에서 확인.","S01 S05 S07",[variant("the openwork holes","reveal","the opaque inner layer","openwork holes reveal an opaque inner layer; the surrounding yarn forms the outer garment surface")])
card(54,"언라인드·브라리스","same hidden clothing layers","garment_detail","wardrobe.layers","안감 없음과 브라 미착용은 층 구성/착용 상태 명세이며 외관과 독립적이다.","불투명 겉옷·스트랩 부재·자연스러운 윤곽은 미착용의 증거가 아니다.","확인 가능한 단면·열린 안쪽이 없으면 비시각 메타데이터로 유지.","S25 S26 S39",[])
card(55,"비저블 란제리·웨일테일·네이키드 드레싱","same inner garment and outer garment","garment_detail","wardrobe.layers","별도 이너의 보이는 가장자리/끈과 넓은 착장 인상을 분리한다.","naked dressing은 실제 나체가 필수 아님; whale tail의 끈을 겉옷 허리띠나 동물 꼬리로 대체 못함.","층별 소유자와 이너의 계속되는 경계, 뒤쪽이면 뒤면 확인.","S39 S40",[variant("the inner underwear back straps","rise_above","the outer trouser waistband","the inner underwear back straps rise above the low trouser waistband; the straps join into a visible Y at the back")])
card(56,"국소 니플 커버·패스티","same independent coverage accessory","wearable_accessory","wardrobe.coverage","브라와 별도의 국소 덮개 제품 유형; 모양·색·부착 방식은 제품별로 다름.","braless와 양립 가능; 숨은 커버를 피부·겉옷 윤곽만으로 판정하지 않는다.","물품을 따로 볼 수 있는 제품 시점 또는 확실한 층 경계; 접착 성능은 관찰 불가.","S26",[])
card(57,"선드레스·슬립·셔츠·티셔츠 드레스","same dress base structure","wardrobe_style","wardrobe.structure","계절 용도, 얇은 끈 몸판, 셔츠 디테일, 길어진 티 구조를 별개로 둔다.","sundress가 모두 mini·노출·floral인 것은 아님; slip=새틴·속옷 착용도 아님.","상체 연결과 드레스 밑단을 볼 수 있는 전신/중거리.","S05 S27 S07",[variant("the narrow dress straps","support","the softly hanging dress bodice","narrow straps support a softly hanging dress bodice; the fabric continues into a simple skirt"),variant("the shirt dress front","continues_along","a button row toward its skirt hem","a folded collar frames the shirt dress neck; the front button row continues down toward the skirt")])
card(58,"시스·시프트·A라인","same dress waist and hem width","wardrobe_style","wardrobe.fit","몸 가까운 재단, 어깨에서 직선으로 떨어짐, 아래로 폭 증가를 나눈다.","sheath=skin-tight는 아님; A-line의 시작점과 waist fit은 선택.","어깨·허리·밑단 폭을 한 시점에서 읽음.","S02 S27",[variant("the shift dress side edges","fall_from","the shoulders toward a nearly straight hem","the dress side edges fall nearly straight from the shoulders; the waist has visible ease"),variant("the dress side edges","widen_toward","the lower hem","the dress side edges widen toward the lower hem; the skirt forms a clear A-shaped outline")])
card(59,"베이비돌·엠파이어·드롭웨이스트","same dress seam landmark","garment_detail","wardrobe.details.waistline_position","babydoll의 형태군과 높은/낮은 허리 절개 위치를 독립적으로 둔다.","babydoll은 아동 나이 요청이 아니고 empire=임신·체형 변경 아님; 정확 기준점 지정 필요.","가슴아래·자연허리·골반과 절개선을 함께 확인.","S05 S28",[variant("the dress skirt seam","sits_just_below","the bust","the skirt attaches just below the bust; loose fabric descends from the raised seam"),variant("the dress skirt seam","sits_below","the natural waist","the bodice extends below the natural waist; the skirt attaches at a lower seam near the hips")])
card(60,"티어드 드레스","same connected skirt tiers","garment_detail","wardrobe.structure","가로 층 연결과 각 층의 폭/모음.","러플 덧장식·실제 속치마 층과 서로 다른 구조; 전부 한꺼번에 요구하지 않는다.","각 가로 연결선과 위아래 원단 연속이 읽히는 시점.","S05 S01",[variant("successive skirt tiers","join_at","horizontal gathered seams","successive skirt tiers join at horizontal seams; each lower tier has more gathered width than the one above")])
card(61,"롬퍼·점프슈트·보디수트","same connected upper and divided lower garment","wardrobe_style","wardrobe.structure","상체와 하체의 의복 연속성, 다리통 길이, 보디수트의 아래 연결을 구분한다.","bodysuit가 swimsuit·속옷·wetness와 같은 의미 아님; 숨은 가랑이 연결은 픽셀 증거가 부족할 수 있음.","롬퍼/점프수트는 연결 몸판과 두 다리통을 함께; 가려진 bodysuit 연결은 미확인.","S31 S30",[variant("the romper bodice","continues_into","two separate short leg sections","the bodice continues into two separate short leg sections; one continuous garment seam joins the waist")])
card(62,"미니·마이크로·미디·맥시 길이","same skirt hem relative to legs","garment_detail","wardrobe.length","밑단을 무릎·종아리·발목 같은 기준점에 상대적으로 기록한다.","판매명이 통일된 cm 경계는 아님; 사진 crop으로 잘린 다리를 skirt 길이로 판정 못함.","실제 밑단과 대응 신체 기준점이 함께 보임.","S30 S05",[variant("the midi skirt hem","ends_between","the knee and ankle","the skirt hem ends between the knee and ankle; a clear lower-leg gap remains above the footwear"),variant("the mini skirt hem","ends_above","the knee","the skirt hem ends above the knee; the lower garment edge remains visible across the front")])
card(63,"펜슬·서클·스케이터","same skirt local width distribution","wardrobe_style","wardrobe.fit","좁고 가까운 하부 윤곽과 허리에서 넓게 퍼지는 형태를 나눈다.","circle는 패턴 재단 의미도 있음; 풍성한 사진만으로 정확한 원형 패턴 공정은 미확인.","허리·힙·밑단 폭과 옷의 경계를 함께 본다.","S02 S30",[variant("the skirt fabric","follows","the hip toward a narrow hem","the skirt follows the hips toward a narrow hem; its side edges remain close below the hip"),variant("the short skirt panels","flare_from","the fitted waistband","the short skirt panels flare from a fitted waistband; the broad hem forms loose curved folds")])
card(64,"플리츠·플리츠 스커트","same repeated folded fabric","garment_detail","wardrobe.structure","반복 접힘의 ridge/valley, 방향, 폭과 고정 구간.","주름 프린트·잔잔한 구김·셔링 모음은 다른 표면; box/knife를 동의어 병합하지 않는다.","접힌 외곽과 음영·실제 겹침이 해상도에서 보여야 함.","S01 S29",[variant("the repeated pleat ridges","alternate_with","recessed fold valleys","repeated pleat ridges alternate with recessed valleys; the folds continue from the skirt upper edge toward the hem")])
card(65,"사롱·파레오·랩 스커트","same wrapping cloth","wardrobe_style","wardrobe.structure.front_fastener_state","몸에 둘러 입은 천의 겹침·매듭과 용도; sarong/pareo 문화 명칭은 기록 유지.","현대 beach 용법의 유사성이 역사적 복식 전체의 동일성을 뜻하지 않는다; 단순 skirt 프린트가 아님.","겹친 천의 끝점과 실제 묶음·밑단을 확인.","S16 S18",[variant("the wrapped cloth ends","meet_at","a side waist knot","one sheet of cloth wraps around the hips; its two ends meet in a side waist knot")])
card(66,"하이로·비대칭 스커트","same skirt hem positions","garment_detail","wardrobe.length","앞뒤 길이 차이와 더 넓은 비대칭 범주.","원근·옷을 들어올린 상태를 재단된 비대칭으로 오인하지 않는다.","앞뒤 또는 좌우의 실제 밑단을 구분할 사선.","S28 S01",[variant("the front skirt hem","ends_above","the back hem of the same skirt","the front skirt hem ends above the back hem; both lengths belong to the same continuous skirt")])
card(67,"버블·머메이드 스커트","same lower skirt boundary","wardrobe_style","wardrobe.silhouette","안으로 모인 밑단의 풍선 부피와 힙/허벅지 아래 퍼짐을 구분한다.","mermaid skirt가 꼬리·물속 인물·mermaidcore를 뜻하지 않는다; flare onset을 구체화.","수축 밑단 또는 퍼짐 시작점과 같은 skirt 원단 연결.","S02 S30",[variant("the gathered lower skirt edge","turns_inward_under","the rounded skirt volume","the skirt swells above a gathered lower edge; the hem turns inward beneath that volume"),variant("the lower skirt","flares_below","the fitted upper-thigh section","the skirt follows the hips and upper thighs; its lower panels flare outward below that fitted section")])
card(68,"핫팬츠·조츠·데님 컷오프","same shorts length and raw edge","wardrobe_style","wardrobe.length","아주 짧은 다리통, 데님 원단, 잘라낸 듯 올풀림 마감은 독립 축.","jorts의 긴 버전도 있음; denim이나 cutoff가 반드시 hot pants를 뜻하지 않는다.","양 다리 밑단과 올풀림을 읽을 가까운 전신.","S06 S30",[variant("the denim shorts hems","have","short frayed edge threads","the denim shorts have short frayed edge threads; both separate leg hems remain visible")])
card(69,"버뮤다·테일러드 쇼츠","same shorts hem and tailoring","wardrobe_style","wardrobe.length","무릎 부근 길이와 허리밴드·다트·앞주름 등의 재단 구조를 분리한다.","tailored가 long/baggy 또는 남성 정체성과 동일하지 않다.","무릎과 두 밑단, 허리의 실제 봉제선.","S30 S01",[variant("the shorts hems","end_near","the knees","two shorts hems end near the knees; a shaped waistband joins the separate leg panels")])
card(70,"박서·블루머 쇼츠","same shorts waistband and leg openings","garment_detail","wardrobe.structure","고무줄 허리의 느슨한 다리통과 다리입구를 모은 부푼 형태.","boxer 판매명은 속옷 착용을 보증하지 않는다; bloomers도 아동 나이를 의미하지 않는다.","허리와 양 다리입구 경계가 보이는 전체 시점.","S30 S01",[variant("the gathered shorts leg openings","hold_below","the puffed leg fabric","each shorts leg has puffed fabric above a gathered opening; the two lower openings remain separate")])
card(71,"바이커·러닝 쇼츠","same short leg fit","wardrobe_style","wardrobe.fit","가까운 신축형 다리통과 여유 있는 달리기형 형태를 분리한다.","러닝의 성능·실제 운동 행동·체형·근육량을 자동 생성하지 않는다.","다리통의 여유·옆트임·길이가 보이는 시점.","S02 S09",[variant("the close-fitting short leg fabric","follows","the upper-thigh contour","the close-fitting shorts follow the upper thighs; their two hems end around mid-thigh")])
card(72,"카고 쇼츠 주머니","same shorts patch pockets","garment_detail","wardrobe.structure","허벅지 옆의 외부 덧주머니와 덮개 연결.","cargo가 군인·무기·폭력 상황·특정 색을 필수로 요구하지 않는다.","덧주머니 부착선과 덮개를 식별하는 사선.","S01 S30",[variant("the side patch pocket","attaches_to","the outer thigh panel of the shorts","a large patch pocket attaches to the outer thigh panel; a flap covers its upper opening")])
card(73,"스코트·큐롯","same visible skirt layer or divided trousers","wardrobe_style","wardrobe.structure","skort는 스커트와 바지의 결합, culottes는 넓은 분리 다리통이다.","앞의 skirt 같은 윤곽만으로 안쪽 shorts를 단정하지 않는다.","분리 다리통이나 바지/앞덮개 층 경계를 보여주는 시점.","S29 S30 S31",[variant("the skirt-like front panel","overlaps","the attached shorts","a skirt-like front panel overlaps attached shorts; the separate shorts hems remain visible at the side"),variant("the wide trouser legs","separate_below","the shared waist and crotch area","two wide trouser legs separate below the shared waist; each has its own broad lower hem")])
card(74,"카프리·페달푸셔","same trouser leg hem","garment_detail","wardrobe.length","종아리/무릎아래 상대 밑단과 판매명 중첩을 함께 기록한다.","고정 cm·필수 slim·얇은 다리·모든 cropped trousers와 합치지 않는다.","무릎·발목·밑단 기준이 모두 보임.","S30 S02",[variant("the cropped trouser hems","end_below","the knees above clear ankle gaps","the trouser hems end below the knees; clear ankle gaps separate the hems from the shoes")])
card(75,"팔라초·와이드 레그","same trousers width and drape","wardrobe_style","wardrobe.fit","넓은 다리통과 허리 아래부터 유연하게 퍼지는 팔라초 실현을 나눈다.","넓음이 반드시 얇고 부드러운 섬유·긴 길이를 뜻하지 않는다.","양 다리통, 허리/힙에서의 퍼짐, 처짐을 함께.","S30 S02",[variant("the broad trouser legs","fall_from","the same waistband in soft folds","broad trouser legs fall from the waistband in soft folds; their separate hems remain wide")])
card(76,"드로스트링 팬츠","same waistband cord and casing","garment_detail","wardrobe.structure.strap_fastener","끈이 통과하는 케이싱과 출입구·매듭의 관계.","허리에 놓인 장식 리본·belt와 달리 실제 끈 경로가 필요; 소재·허리 높이는 독립.","끈 출발 구멍과 매듭·케이싱 경계.","S01 S30",[variant("the waist drawcord","emerges_from","the waistband casing","a drawcord emerges from two waistband openings; its ends meet in a front waist knot")])
card(77,"하이·미드·로라이즈","same waistband relative to wearer landmarks","garment_detail","wardrobe.fit.waistband_landmark","허리선 높이는 배꼽·자연허리·골반 기준 관계로, rise 측정은 별도 명세로 둔다.","high waist는 high-leg·허리 잘록함·배꼽 노출의 동의어가 아니다.","밴드 윗선과 대응 신체 기준점이 보여야 한다.","S01 S15",[variant("the waistband upper edge","sits_above","the navel","the waistband upper edge sits above the navel; the two leg openings remain independently positioned"),variant("the waistband upper edge","sits_below","the navel","the waistband upper edge sits below the navel; the upper abdomen remains visible above it")])
card(78,"비키니·삼각 패널·스트링","same swim top and separate bottom","garment_detail","wardrobe.structure","분리 구성, 컵 패널 형상, 얇은 연결 끈은 조합 가능한 독립 속성.","triangle이 반드시 string은 아니며 bikini가 최소 커버리지·해변 배경을 뜻하지 않는다.","두 패널 형상·지지 연결과 상하 분리 경계.","S12 S18",[variant("each triangular swim panel upper point","joins","its supporting strap","two triangular swim panels form the top; each upper point joins its own supporting strap"),variant("the swim top side strings","tie_to","the same top back strings","thin side strings extend from the swim top panels; their ends tie together across the back")])
card(79,"반도·홀터·롱라인·언더와이어 비키니","same swim top selected axes","garment_detail","wardrobe.structure.strap","수평 패널·목 뒤 연결·밑가슴 아래 연장·보강 명세를 분리한다.","반도+halter 공존 가능; wire는 내부 명세여서 컵 아래 선만으로 확정 못함.","선택한 패널 경계와 목/밴드 연결이 보이는 시점.","S12 S24",[variant("the horizontal swim top band","joins","the halter straps at its outer edges","a horizontal swim top band wraps the chest; halter straps rise from its outer edges toward the neck"),variant("the swim top lower band","extends_below","the cup bases","the lower swim top band extends below the cup bases; a separate bottom remains below the top hem")])
card(80,"탱키니·원피스 수영복","same swim garment connectedness","wardrobe_style","wardrobe.structure","긴 분리 상의의 밑단과 하나로 이어진 몸통-하의 구조.","탱키니 겹침이 이어진 원피스처럼 보일 수 있으므로 가려진 경계는 미확인.","상의 밑단·독립 하의 윗선 또는 연결 몸통의 연속성을 확인.","S14 S18",[variant("the tankini top hem","overlaps","the separate swim bottom waistband","the long swim top has its own finished hem; that hem overlaps a separate swim bottom waistband"),variant("the swimsuit bodice","continues_into","the connected lower brief section","the swimsuit bodice continues through the waist into its lower brief section; two leg openings belong to the same garment")])
card(81,"모노키니 역사·현대 의미","same explicitly selected swimsuit design","wardrobe_style","wardrobe.structure","1964 역사형과 현대 컷아웃 원피스 판매 범주를 문맥으로 분리한다.","한 단어만으로 topless 역사형을 현대 수영복에 추가하지 않는다; 새 선택형도 보편 정의 아님.","현대형은 상하 연결과 컷아웃; 역사형은 명시적인 시대/디자인 요구가 필요.","S17 S18",[variant("the narrow torso panel","connects","the upper and lower swimsuit sections","a narrow torso panel connects the upper and lower swimsuit sections; side cutouts open on both sides of that connector")])
card(82,"플런지·백리스 수영복","same swimsuit front and back boundaries","garment_detail","wardrobe.coverage.opening_location","앞의 낮은 파임과 뒤의 넓은 개방은 각각 다른 면의 속성이다.","한쪽 면만 본 사진으로 반대면의 커버리지를 확정하지 않는다.","앞/뒤 따로 보거나 실제 양면 관계가 보이는 사선; 반사 속 소유자도 구별.","S12 S18",[variant("the swimsuit back edge","ends_below","the shoulder blade area","the swimsuit back edge ends below the shoulder blade area; the front panel remains high across the upper chest")])
card(83,"하이레그와 높은/낮은 허리선","same swim bottom waistband and leg openings","garment_detail","wardrobe.coverage.leg_opening","다리 입구 윗선과 허리 밴드 높이를 별도 기준선으로 기록한다.","high-leg+high-waist 공존; high cut의 leg 문맥과 deep neck cut을 분리한다.","허리 밴드·다리 입구·골반 기준이 같은 하의에 있어야 함.","S15 S18",[variant("the leg opening upper edges","rise_toward","the lateral hips beneath a high waistband","the swim bottom waistband sits high on the torso; its leg opening edges independently rise toward the lateral hips")])
card(84,"타이사이드 수영복","same swim bottom side closure","garment_detail","wardrobe.structure.strap_fastener","하의 앞뒤 패널이 옆의 끈 묶음으로 연결되는 경로.","일방·양방 위치를 선택; string 상의와 다른 owner이며 무조건 low-rise 아님.","하의 앞뒤 패널에서 매듭으로 이어지는 실제 끝점.","S12 S13",[variant("the swim bottom front and back ties","meet_in","a side hip knot","the swim bottom front and back ties meet in a side hip knot; each tie remains attached to its own fabric panel")])
card(85,"치키·브라질리언·통·지스트링","same swim bottom rear panel","garment_detail","wardrobe.coverage.rear_panel","뒤판 폭·하단 좁아짐·끈형 연결은 실제 보이는 형태로 기술한다.","브랜드별 면적 %를 보편화하지 않으며 Brazilian은 착용자 국적 아님; thong footwear 별도.","뒤판 양쪽 경계와 폭이 보이는 뒤면; 앞면만으론 미확인.","S13 S44",[variant("the swim rear panel","narrows_between","the two outer rear garment edges","the swim rear panel narrows toward its lower center; both outer rear garment edges remain visible"),variant("the narrow rear connector","joins","the waistband to the lower swim panel","a narrow rear connector joins the waistband to the lower swim panel; the same garment endpoints remain visible")])
card(86,"마이크로 비키니·보이쇼츠 하의","same swim panel area and leg sections","wardrobe_style","wardrobe.coverage.leg_opening","작은 패널 면적이라는 비표준 범주와 짧은 다리통 형태를 분리한다.","micro는 정확 cm·몸 확대·필수 특정 부위 노출이 아님; boyshort는 남성/아동 정체성 아님.","실제 패널 경계와 다리입구를 확인; 면적은 정량 인증하지 않음.","S12 S13",[variant("the boyshort lower edges","extend_below","the hip crease as two short legs","the swim bottom extends below the hip crease; two short leg sections end in separate horizontal hems")])
card(87,"래시가드·서프수트","same separate or connected swim garment","wardrobe_style","wardrobe.structure","독립 소매 상의의 밑단과 일체형 몸통/하의 연결을 나눈다.","긴소매=UPF 인증·실제 서핑·방수·neoprene·wetness는 아님.","소매, 독립 밑단 또는 하부 연결이 보이는 전체 시점.","S12 S11",[variant("the rashguard torso","ends_at","its own hem above the separate bottom","the sleeved swim top ends at its own hem; a separate swim bottom begins below that edge"),variant("the surf suit torso","continues_into","the connected lower swim section","the long-sleeved torso continues into the lower swim section; the same garment has two leg openings")])
card(88,"스윔쇼츠·보드쇼츠","same loose swim shorts","wardrobe_style","wardrobe.fit","수영 용도의 바지통 형상과 여유·여밈을 표현한다.","board shorts가 전부 무릎길이·내장 liner·특정 섬유·남성을 뜻하지 않는다.","분리된 양 다리통과 허리·밑단 관계.","S12 S30",[variant("the loose shorts legs","hang_below","the swim waistband","loose shorts legs hang below the swim waistband; both separate hems have visible ease around the thighs")])
card(89,"스윔스커트·스윔드레스","same skirt overlay and swim layer","wardrobe_style","wardrobe.layers","수영복 하의에 연결된 skirt 덮개와 상체까지 이어진 dress 외관을 나눈다.","일반 sundress나 분리 sarong을 연결 수영복으로 오인하지 않는다.","skirt와 하부 swim layer의 실제 이어짐/분리 경계를 볼 수 있어야 함.","S12 S16",[variant("the short skirt overlay","attaches_to","the same swim bottom waistband","a short skirt overlay attaches to the swim bottom waistband; the connected lower swim layer remains visible beneath it")])
card(90,"부르키니의 층 구성","same covered swim ensemble","wardrobe_style","wardrobe.layers","머리·소매·몸통·다리 덮개와 부착/분리 경로를 선택형으로 기록한다.","3-piece·헐렁함·특정 종교·국적·연령·UPF를 자동 부여하지 않는다.","후드/머리덮개 연결·상의 밑단·바지 경계를 전체 시점에서 본다.","S19",[variant("the swim head covering","connects_to","the long-sleeved upper garment","the head covering connects to the long-sleeved upper garment; separate full-length swim trousers continue below the top")])
card(91,"커버업·카프탄·튜닉·비치 셔츠·로브","same outer garment over swimwear","wardrobe_style","wardrobe.layers","커버업은 용도이며 몸판 길이·앞여밈·소매·밑단이 실제 형태다.","kaftan의 문화 복식 전체를 beach loose dress로 축소하지 않는다; sheer/wet 자동 추가 없음.","겉층 가장자리와 안쪽 수영복이 같은 착용자에게 연결됨.","S16 S19",[variant("the open outer shirt panels","frame","the swimsuit underneath","open outer shirt panels frame the swimsuit underneath; the shirt has its own collar and finished hem"),variant("the loose tunic hem","hangs_over","the separate swim bottom","a loose tunic hem hangs over the separate swim bottom; its broad body falls from the shoulders")])
card(92,"섬유·브랜드·조성","same textile material specification","surface_material","wardrobe.material","cotton/linen은 섬유, rayon/viscose/modal/lyocell은 재생 셀룰로오스 계열, TENCEL은 브랜드; nylon/polyester/elastane은 별도 조성 축이다.","브랜드와 일반 섬유를 합치지 않는다; 같은 섬유가 다양한 weave/knit/finish에 사용됨. 사진은 정확 혼방·브랜드·친환경 성능을 입증하지 못한다.","비시각 명세로 보존; 필요한 표면·처짐·투과만 별도 가시 후보에서 선택.","S05 S08 S09 S10",[])
card(93,"포플린·론·보일·거즈·더블거즈·시어서커","same light fabric structure","surface_material","wardrobe.material.visible_weave","미세하고 비교적 매끈한 원단, 성긴 원단, 겹친 거즈와 반복 puckering을 분리한다.","가벼움=투명함 아님; seersucker의 반복 요철을 무작위 착용 구김이나 shirring 봉제 줄로 대체하지 않는다.","매끈함/구멍/겹수/요철 각각 적절한 근접 해상도; 숨은 double layer는 미확인.","S05 S03",[variant("the seersucker raised bands","alternate_with","flatter woven bands","small raised puckered bands alternate with flatter woven bands; the pattern repeats across the same fabric"),variant("the fine voile layer","transmits","a faint inner garment outline","a fine voile layer hangs in light folds; a faint inner garment outline is visible through the continuous weave")])
card(94,"샴브레이·데님","same woven fabric surface","surface_material","wardrobe.material.visible_weave","평직의 색실 혼합과 데님의 능직 사선 표면을 나눈다.","파란 색 하나로 denim을 확정하지 않으며 chambray를 모든 denim과 동일시하지 않는다.","실 방향이 분해되는 원해상도 근접면.","S06 S05",[variant("the visible diagonal yarn ridges","cross","the denim fabric surface","fine diagonal yarn ridges cross the denim surface; the ridges continue through the fabric folds")])
card(95,"시폰·조젯·오간자","same sheer fabric drape","surface_material","wardrobe.material.drape","가볍게 흐르는 투과면, 잔 크레이프 표면, 얇지만 형태를 지탱하는 부피의 차이를 다룬다.","세 판매명을 전부 동일한 흐르는 silk로 병합하지 않는다; 섬유 조성·정확 weave는 별도.","처짐과 실제 주름 면·비침을 비교할 근접 사선.","S01 S06",[variant("the thin organza folds","hold_away_from","the covered garment underneath","thin translucent folds hold away from the garment underneath; sharp fold edges maintain a light structured volume")])
card(96,"새틴 조직과 광택","same fabric face","surface_material","wardrobe.material","조직 이름과 매끈한 광택의 시각 표현을 나눈다.","satin=실크·젖음·vinyl이 아니며 광택만으로 새틴 조직을 확정하지 않는다.","연속 하이라이트와 접힘 변화; exact weave는 근접 결 증거가 별도로 필요.","S06",[variant("the smooth fabric face","carries","broad highlights along the folds","the smooth fabric face carries broad highlights; the highlights change gently across the soft folds")])
card(97,"저지·리브·테리","same knitted surface","surface_material","wardrobe.material.visible_weave","편직 고리면, 반복 골, 표면 pile loop를 각각 기록한다.","rib의 줄무늬와 인쇄 stripe는 다르고 terry가 반드시 젖은 수건은 아니다.","골·고리가 분해되는 근접 해상도.","S07",[variant("the rib knit raised columns","alternate_with","recessed knitted columns","raised knit columns alternate with recessed columns; the vertical rib texture follows the same top folds"),variant("small pile loops","project_from","the same terry fabric face","small pile loops project from the fabric face; their repeated looped texture remains visible in the light")])
card(98,"메시·튤·레이스·아일렛·브로드리·오픈니트","same perforated or openwork material","surface_material","wardrobe.material.visible_weave","규칙 망눈, 장식 고리무늬, 바탕천에 자수 마감 구멍, 성긴 knit를 독립 형태로 둔다.","eyelet은 hardware 고리도 될 수 있어 문맥 구분; tulle의 layer volume와 한겹 transmission은 별도.","실·바탕천·구멍·마감 경계가 원해상도에서 구별돼야 함.","S05 S07 S01",[variant("the embroidered hole edges","surround","small openings in the woven base cloth","embroidered edges surround small holes in a woven base cloth; intact fabric separates the openings"),variant("fine net threads","enclose","repeated mesh openings","fine net threads enclose repeated openings; an opaque inner garment remains behind the net layer")])
card(99,"개더·루싱","same locally gathered garment panel","garment_detail","wardrobe.structure","긴 원단의 모음과 국소 장식 주름이 어느 봉제/끈으로 모이는지 지정한다.","제조사 glossary에서 ruching을 gathering으로 설명하므로 억지 배타 범주로 만들지 않는다; 무작위 wrinkles와 다름.","모이는 시작/끝, 실제 봉제선과 주름 방향.","S01 S03",[variant("small bodice folds","converge_into","the same side gathering seam","small bodice folds converge into a side gathering seam; the surrounding fabric remains part of the same panel")])
card(100,"러플·프릴·플라운스","same attached trim edge","garment_detail","wardrobe.structure","부착선에 모음이 있는 장식과 모음 없이 하단 폭이 커지는 곡선 재단의 차이.","판매명 flounce가 넓은 ruffle 가족에 속할 수 있음; 두 구조를 한 번에 의무화하지 않는다.","부착선의 gathers 여부와 free edge 폭을 확인.","S04 S01",[variant("the gathered trim attachment edge","joins","the same neckline seam","small gathers run along the trim attachment edge; its loose outer edge ripples below the neckline seam"),variant("the smooth flounce attachment edge","joins","the same skirt seam","a smooth flounce edge joins the skirt seam; its wider free edge falls in curved waves below it")])
card(101,"프린지·태슬·스캘럽","same garment edge ornament","garment_detail","wardrobe.structure","여러 늘어진 가닥, 묶인 술, 반복 곡선 가장자리의 형태를 나눈다.","fringe는 머리 앞머리 다의어, scallop은 조개 생물과 분리한다.","가닥 부착점·묶임·실제 원단 끝을 근접 확인.","S01 S34",[variant("the fringe strands","hang_from","the same garment hem","separate fringe strands hang from the garment hem; their upper ends attach along the finished edge"),variant("the repeated rounded fabric lobes","form","the same scalloped hem edge","repeated rounded fabric lobes form the hem edge; each curve belongs to the continuous garment fabric")])
card(102,"레이스업·멀티스트랩·링·매듭","same garment connection hardware","garment_detail","wardrobe.structure.strap_fastener","끈 통과 구멍·교차 경로·고리 연결·실제 매듭은 다른 그래프다.","lace fabric과 lace-up, 주얼리 ring과 garment connector를 구별. metal이 실제 폭력/구속을 요구하지 않는다.","모든 연결 끝점과 끈 owner가 보이는 근접면.","S01 S12",[variant("the garment lacing cord","passes_through","opposing rows of eyelets","one cord passes through opposing eyelet rows; crossed cord spans join the two garment edges"),variant("the connector ring","joins","two fabric strap ends of the same garment","a connector ring joins two fabric strap ends; both fabric ends visibly loop around that ring")])
card(103,"디스트레스드·스터드","same garment surface treatment","garment_detail","wardrobe.material","의도적으로 해진 듯한 경계와 부착된 금속 장식을 관찰한다.","프린트 찢김·원단 구멍·실제 부상·폭력 맥락을 분리; studs가 spikes나 무기와 같지 않다.","해진 섬유끝 또는 stud 부착점이 보이는 원해상도.","S35 S01",[variant("the frayed edge threads","project_from","a worn fabric opening","frayed threads project from the fabric opening; intact woven cloth borders the worn edge"),variant("small studs","attach_along","the garment edge","small studs attach along the garment edge; their raised metal-like heads cast short local shadows")])
card(104,"깅엄·브르통/마린 줄무늬","same garment repeating pattern","color","wardrobe.pattern","교차 격자와 수평 stripe의 반복 주기·방향을 나눈다.","체크가 모두 gingham 아님; Breton의 과거 줄 수를 현대 모든 의복에 강제하지 않는다.","직물 주름 따라 왜곡되는 무늬의 반복을 확인.","S33 S32",[variant("the small crossing bands","form","a repeated two-color check on the same fabric","small crossing bands form a repeated two-color check; the checks continue across the fabric folds"),variant("horizontal contrasting bands","repeat_across","the same shirt torso","horizontal contrasting bands repeat across the shirt torso; the bands bend with the garment folds")])
card(105,"꽃 크기·식물·열대·페이즐리·도트","same fabric motif field","color","wardrobe.pattern","모티프 종류, 크기, 밀도와 반복 방향을 각각 기록한다.","floral과 botanical 중첩 허용; tropical이 실제 tropical location을 추가하지 않음; paisley 문화와 착용자 출신을 분리.","꽃/잎 형태와 원단 기준 반복 규모가 식별되어야 함.","S32 S34",[variant("tiny floral motifs","repeat_densely_across","the same garment panels","tiny floral motifs repeat densely across the garment panels; each motif stays small relative to the bodice width"),variant("large leaf motifs","span","broad areas of the same garment panels","large leaf motifs span broad areas of the garment panels; the repeat remains tied to the fabric surface")])
card(106,"타이다이·색면·모노크롬·파스텔·네온·메탈릭","same garment color and finish","color","wardrobe.color","불규칙 번짐, 경계 분명한 색면, 유사색 구성, 명도/채도, 반사는 독립 축이다.","tie-dye 제조 이력·neon 실제 발광·metallic 실제 금속 원료를 이미지로 확정하지 않는다.","색면 경계·명도·반사 위치를 확인하고 white balance 영향을 기록.","S32 S06",[variant("two contrasting color fields","meet_at","a clear boundary on the same garment","two contrasting color fields meet at a clear garment boundary; each field remains continuous within its panel"),variant("soft irregular color patches","spread_across","the same fabric surface","soft irregular color patches spread across the fabric surface; blurred color transitions follow the cloth folds")])
card(107,"리조트·비치·마린·코스털 그랜드마더","same optional outfit components","wardrobe_style","wardrobe.layers","용도와 비공식 연상군은 의복의 구조·색·레이어 후보를 묶는 문맥이다.","grandmother는 나이·혈연이 아니며 resort/nautical이 해변·요트·계층을 강제하지 않는다.","선택된 옷의 요소만 확인; 장소·연령·생활습관은 독립 요청.","S16 S33 S38",[variant("the light outer shirt","layers_over","the simple sleeveless top","a light roomy shirt layers over a simple sleeveless top; straight trousers continue below the shirt hem")])
card(108,"보호·코티지·코케트·발레코어","same selected outfit adornments","wardrobe_style","wardrobe.layers","자수·작은 무늬·리본·랩 형태 등 선택한 단서를 조합한다.","style label이 나이·성적 의도·전원 장소·전부 pink/puff인 all-of 묶음을 만들지 않는다.","실제로 선택한 장식의 의복 부착과 층 연결만 확인.","S21 S36 S38",[variant("small ribbon bows","attach_at","the same blouse neckline","small ribbon bows attach at the blouse neckline; a soft wrap skirt overlaps at the waist")])
card(109,"Y2K·머메이드코어·코스털 카우걸·토마토 걸","same optional fashion realization","wardrobe_style","wardrobe.layers","시대 연상·물빛 표면·웨스턴 혼합·여름 색채는 별개 스타일 문맥이다.","Y2K=whale tail 필수 아님; mermaidcore=꼬리 아님; cowgirl 직업·tomato 실제 식물·girl 나이를 추론하지 않는다.","선택한 신발/허리띠/색/장식만 이미지에서 확인.","S36 S37 S38",[variant("the western belt","sits_over","the waist of the light summer dress","a western belt sits over the light dress waist; cowboy-style boots remain separate footwear below the hem"),variant("the pearl-like embellishments","attach_to","the sea-colored fabric surface","pearl-like embellishments attach to sea-colored fabric; soft iridescent highlights follow the garment folds")])
card(110,"테니스·애슬레저·고프·블록코어","same sports-inspired outfit","wardrobe_style","wardrobe.layers","스포츠 의복의 외형·야외 장비·축구 저지 활용을 일상 옷과 조합한 용도군.","실제 운동·팀 소속·성별·기능 성능·야외 배경을 이름만으로 강제하지 않는다.","selected polo/pleated/skort/jersey/utility 등의 실제 형태만.","S38 S12",[variant("the sports jersey hem","rests_above","the separate denim waistband","the sports jersey has a loose short-sleeved body; its hem rests above a separate denim waistband")])
card(111,"콰이어트 럭셔리·란제리 드레싱·서머 고스·펑크","same selected visible style treatment","wardrobe_style","wardrobe.layers","로고 절제·이너 유래 구조·검정 가벼운 레이어·재조합이라는 선택 문맥.","quiet luxury가 실제 가격·재력·브랜드 보증을 뜻하지 않는다. black·mesh·chain은 공격성·강요·폭력 증거 아님.","선택한 재단·표면·레이어를 관찰; 심리·경제 상태는 평가하지 않음.","S35 S36 S39",[variant("the black openwork layer","lies_over","the same opaque inner dress","a black openwork layer lies over an opaque inner dress; the airy outer holes reveal the covered inner layer")])
card(112,"슬라이드·통·스트래피·피셔맨 샌들","same shoe strap network","footwear","wardrobe.footwear.sandal_strap_paths","발등 band, toe-post Y, 여러 가는끈, cage형 교차띠의 실제 연결을 분리한다.","thong은 여기서 속옷이 아님; fisherman이 직업·낚시 장면을 만들지 않는다.","발가락 사이 기둥·발등 띠·밑창 연결을 각각 확인.","S44 S42",[variant("the Y-shaped sandal strap","passes_between","the first and second toes","a Y-shaped sandal strap passes between the first and second toes; its side ends join the same sole"),variant("the interlaced sandal bands","span","the same foot instep","interlaced sandal bands span the instep; their ends attach along both sides of the sole")])
card(113,"에스파드리유·웨지·플랫폼·뮬·스포츠 샌들","same shoe sole and heel topology","footwear","wardrobe.footwear.backless_vs_strapped","밑창 둘레 질감, 연결된 쐐기 굽, 앞발 포함 높이, 뒤꿈치 개방, 조절끈은 조합 축이다.","wedge+platform 공존 가능; mule의 앞코는 열리거나 닫힘; rope질감이 황마 인증은 아님.","옆면에서 앞발과 뒤꿈치 높이, 밑창·뒤끈을 확인.","S41 S44",[variant("the wedge sole","forms_one_continuous_mass_between","the forefoot and heel","the sole forms one continuous wedge between forefoot and heel; braided rope-like bands wrap its outer edge"),variant("the open shoe back","leaves_unenclosed","the heel","the shoe has an open back around the heel; the covered forefoot rests on a low sole")])
card(114,"젤리 슈즈·메시 플랫","same shoe upper optical surface","footwear","wardrobe.material.transmission","성형된 반투명 갑피와 실제 망눈을 가진 낮은 신발 구조.","젤리 질감은 젤리 음식·젖음 아님; mesh 구멍을 투명 고체로 대체하지 않는다.","갑피 가장자리·망눈·밑창의 연결이 보이는 근접면.","S42 S07",[variant("the molded translucent upper","joins","the same low shoe sole","a molded translucent upper joins a low sole; the covered foot is faintly visible through the solid upper"),variant("the fine mesh upper","covers","the foot above the same flat sole","a fine mesh upper covers the foot; repeated net openings remain visible above the flat sole")])
card(115,"스트로 햇·버킷·바이저","same headwear crown and brim","wearable_accessory","wardrobe.accessories","짜임 소재, 아래로 내려간 둘레챙, 머리윗부분 열린 visor는 별개 축.","straw가 반드시 wide-brim은 아니며 visor가 full crown/UPF/스포츠 행동을 뜻하지 않는다.","챙·크라운의 실제 연결과 머리윗부분 덮임.","S11 S38",[variant("the visor brim","projects_from","a head band below an open crown","the visor brim projects from a head band; the top of the head remains uncovered")])
card(116,"라피아·바스켓 백·헤드스카프","same bag structure or separate head wrap","wearable_accessory","wardrobe.accessories","원료 명칭·바구니 구조와 머리에 둘러 묶은 천을 분리한다.","raffia-like synthetic 가능; basket은 원료 아님; headscarf가 religion·nationality를 결정하지 않는다.","가방 짜임·handle 연결 또는 머리 천의 knot/끝점.","S41 S38",[variant("the woven bag handles","join","the same basket-like bag body","woven handles join a basket-like bag body; crossing strips form the bag surface"),variant("the headscarf ends","tie_at","the back of the same head","a cloth scarf wraps around the head; its two ends tie at the back")])
card(117,"셸·비즈 주얼리·앵클릿","same wearable ornament","wearable_accessory","wardrobe.accessories","조개 모티프, 구슬 연결, 발목 위치는 소재·형태·착용위치라는 다른 축이다.","shell/pearl 외형은 생물 재료·진품 인증이 아니고 anklet은 body chain 전체와 다름.","구슬과 끈·chain 연결 또는 발목 둘레 부착이 식별됨.","S34 S38",[variant("the anklet chain","encircles","the same ankle above the shoe","a fine chain encircles the ankle above the shoe; small connected beads follow its curve")])
card(118,"웨이스트·벨리·보디 체인","same chain ornament network on wearer","wearable_accessory","wardrobe.accessories","허리 둘레 체인과 목/가슴/허리/등 연결망의 경로를 별개로 다룬다.","장신구 chain이 의복 지지끈·body pose·결박 관계로 바뀌지 않도록 owner를 둔다.","체인 연결·경로·겉옷 앞뒤 층 순서가 보이는 시점.","S01 S35",[variant("the waist chain","encircles","the abdomen above the lower waistband","a fine waist chain encircles the abdomen; it remains separate from the lower waistband"),variant("the ornament center chain","connects","the neck chain to the waist chain","a center ornament chain connects the neck chain to the waist chain; all three chains belong to the same body accessory")])

# Directly inspected source supplements; no new source data enters a runtime draft.
for row in CARDS:
    if row["id"] in {"SF092","SF095","SF098","SF105"}:
        row["source_ids"].append("S46")
    if row["id"] == "SF096":
        row["source_ids"] += ["S46","S47"]
        row["confusion_boundary"] += " satin/sateen 용어 경계는 기술 문헌과 현대 판매 문맥마다 달라 별도 provenance가 필요하다."
    if row["id"] == "SF049":
        row["variants"].append(variant("the central garment neckline opening","reveals","the groove between the same adult wearer's breasts","the central neckline opening reveals the groove between the adult wearer's breasts; the garment panels retain visible inner edges beside that opening"))
    if row["id"] == "SF050":
        row["variants"]=[
            variant("the same adult bodice side edge","leaves_visible","a bounded outer breast contour","a bounded outer breast contour is visible beside the adult bodice arm opening; the same opaque bodice covers the central breast surface"),
            variant("the same adult top lower edge","sits_above","a bounded lower breast contour","a bounded lower breast contour is visible below the adult top edge; the upper breast surface remains covered by the same opaque top")
        ]
    if row["id"] == "SF086":
        row["variants"].append(variant("the small swim panels","connect_through","thin supporting straps around the same torso","small swim panels connect through thin supporting straps; each panel retains a distinct fabric perimeter"))

# One card per seed row. These are family assignments, never synonym equivalence.
GROUP_MAP = [
 [1,1,2,2,3,3,3,4,4,5,6,7],
 [8,9,10,10,11,12,13,14,14,15,16,17],
 [18,19,19,20,20,21,22,23,24,25,5,26,27,28,27,29,30,8],
 [31,31,32,32,33,33,34,34,35,35,36,36,36,9,37],
 [38,38,39,39,40,41,41,41,42,43,43,43],
 [7,44,44,44,44,45,45,46,47,47,47,48,48,48,48],
 [49,49,50,50,51,51,37,37,37,29,52,52],
 [13,13,53,30,54,54,55,55,55,56],
 [57,57,57,57,8,58,58,58,59,59,59,60,5,37,61,61,61],
 [62,62,62,62,63,63,63,64,8,65,66,66,67,67,52],
 [68,68,68,69,69,70,70,71,71,72,73,73,74,74,75,75,76],
 [77,77,77],
 [78,78,78,79,79,79,79,80,80,81,82,82],
 [83,83,83,84,85,85,85,85,86,86],
 [87,87,88,88,89,89,90],
 [91,91,91,65,65,91,12,98,91],
 [92,92,92,92,92,92,92,92],
 [93,93,93,93,93,93,94,94,95,95,95,96],
 [97,97,97,98,98,98,98,98,12,98],
 [99,99,11,11,64,100,100,25,101,101,101,102,102,102,102,103,103],
 [104,104,105,105,105,15,105,105,106,106,106,106,106,106],
 [107,107,107,107,108,108,108,108,109,109,109,109,110,110,110,110,111,111,111,111],
 [112,112,112,112,113,113,113,113,113,114,114],
 [115,115,115,116,116,116,117,117,117,118,118]
]

from research_supplements import enrich
enrich(CARDS, SOURCES, source, variant)
