"""Planned behavioral comparisons; none are recorded as executed."""
# Left/right are distinguishable examples, not a universal exclusive taxonomy.
PAIR_ROWS = [
 ("crop_nav_visible","짧은 상의 + 높은 밴드가 배꼽을 덮음","짧은 상의 + 낮은 밴드 사이 배꼽이 보임","길이와 배꼽 가시성을 따로 보존",2,51),
 ("micro_underbust","micro-crop 라벨만 있음","성인 의복 밑단과 가슴 아래 경계의 실제 관계를 명시","micro 라벨에서 underboob 자동 의무 금지",2,50),
 ("tank_cami","넓은 어깨 원단 연결","좁은 가는 어깨끈 연결","대표 끈 폭 변형을 구별하되 판매명 경계는 중첩",3,3),
 ("bandeau_strapless","수평 밴드 + 탈착 어깨끈","어깨 연결 없는 밴드 몸판","bandeau에서 strapless를 무조건 요구하지 않음",4,79),
 ("halter_front_depth","앞가슴을 높게 덮는 목 뒤 연결","낮은 앞 파임 + 목 뒤 연결","끈 경로와 앞 커버리지 독립",5,20),
 ("camp_print","무지 camp collar 긴소매 셔츠","열대 프린트 반소매 camp shirt","칼라·소매·무늬를 분리",14,15),
 ("milkmaid_bundle","스퀘어넥 + ruched bust + flutter 소매","목둘레 모음 + loose peasant 몸판","판매 스타일명에서 고정 all-of 묶음 금지",10,32),
 ("wrap_surplice","자유 앞판 + 풀리는 허리 끈","고정된 surplice 앞판 + 옆 지퍼","V겹침이 실제 wrap closure를 증명하지 않음",8,8),
 ("tie_gap","매듭 아래 몸판이 닫혀 있음","매듭 아래 피부 틈이 있음","tie-front가 복부 노출을 자동 추가하지 않음",9,51),
 ("scoop_v","둥근 U 아래 경계","각진 중앙 V 접점","round/point 관계 구별",19,20),
 ("sweetheart_square","두 곡선 + 중앙 dip","직선 양옆 + 가로 하단","하트 프린트나 단순 cup 이름으로 대체 금지",21,22),
 ("boat_off","얕고 넓으며 어깨 윗면을 덮음","윗선이 양 어깨 아래에 있음","width와 shoulder position 독립",24,26),
 ("off_cold","전체 윗선이 어깨 아래","어깨 위 브리지와 아래 소매가 남음","남아 있는 연결부가 핵심",26,28),
 ("drop_off","어깨 아래 봉제선 + 덮인 어깨","어깨 자체가 노출되는 윗선","봉제선 위치와 피부 노출 독립",33,26),
 ("raglan_print","겨드랑이에서 목까지 실제 소매 seam","비슷한 사선 프린트","실제 연결 양 끝점을 확인",33,106),
 ("cap_flutter_puff","어깨끝만 덮는 짧은 cap","하단 자유 퍼짐 또는 모음으로 부푼 선택 소매","길이·고정·부피를 별도 축으로 유지",31,32),
 ("sleeveless_armhole","소매 없음 + 얕은 암홀","소매 없음 + 옆몸통 아래까지 내려간 암홀","소매 유무는 암홀 깊이가 아님",31,34),
 ("racer_cross","두 끈이 중앙 yoke로 합류","두 끈이 X로 교차 후 반대 아래에 연결","합류와 교차 그래프를 보존",35,35),
 ("front_back","앞 high neck + 뒤 low back","앞 deep scoop + 뒤 높은 덮임","반대면 속성 전이 금지",5,36),
 ("opening_gap","같은 의복 내부의 둘러싼 cutout","별도 상하의 가장자리 사이의 공백","개구부 owner 및 토폴로지 구별",37,51),
 ("keyhole_neckline","위 연결부가 남은 닫힌 keyhole","윗선까지 열린 목 파임","boundary closure 구별",29,20),
 ("sheer_mesh_cutout","연속 원단을 통한 이너 투과","실 사이 구멍 또는 의복 cutout","광학 투과와 실제 개구부 구별",13,53),
 ("nude_color","피부색에 가까운 불투명 옷","얇은 피부색 패널로 연결된 illusion","색·투과·나체는 다름",30,13),
 ("unlined_sheer","안감 없는 불투명 원단","안감 있는 시어 겉층","숨은 lining과 외관 비침 독립",54,13),
 ("braless_hidden","매끈한 불투명 top 외관","실제 브라 미착용 명세","사진 외관만으로 hidden state PASS 금지",54,47),
 ("underbust_exposure","가슴 아래 원단 seam","가슴 아래 실제 skin opening","절개선과 노출을 분리",48,50),
 ("wire_pushup","underwire가 있으나 padding 명세 없음","와이어 유무 별도인 push-up padding 명세","숨은 내부 속성 및 성능을 분리",47,47),
 ("balconette_demi","제조사 balconette와 demi 중첩 판매명","명시적 horizontal cup edge + outer strap attachments","고정 % 범위 금지; geometry 우선",45,46),
 ("bodycon_skin","불투명 high-neck bodycon","느슨한 off-shoulder blouse","밀착과 피부 노출 독립",39,26),
 ("bias_satin","원단 grain 방향 명세","매끈한 광택과 fluid drape 사진","제작 방향·원료·광택을 혼동하지 않음",42,96),
 ("skort_culottes","skirt overlay 아래 연결 shorts가 보임","넓게 벌어진 두 trouser legs","숨은 internal shorts는 별도 증거 필요",73,73),
 ("romper_dress","상체에서 이어진 두 짧은 leg sections","상체에서 이어진 하나의 skirt","앞의 덮개만으로 base garment 결정 금지",61,57),
 ("highlow_pose","실제 앞뒤 hem 높이 차이","같은 hem을 손으로 들어 올린 현재 상태","재단과 착용 상태 구별",66,62),
 ("maxi_slit","긴 hem + upper-thigh slit apex","짧은 mini hem + slit 없음","hem length와 aperture height 독립",52,62),
 ("jorts_hot","무릎 부근 denim shorts","허벅지 위쪽 short shorts","denim 소재와 길이 독립",68,69),
 ("bikini_triangle_string","넓은 band로 지지된 triangle panels","비삼각 panel을 가는 끈으로 연결","triangle과 string은 서로의 필수 조건 아님",78,78),
 ("tankini_onepiece","free upper hem + separate waistband","연결된 torso/brief + 두 leg openings","겹침이 연결로 바뀌지 않음",80,80),
 ("monokini_context","1964 Gernreich 역사 문맥","현대 cutout one-piece 상품 문맥","historical topless 이웃의 잘못된 의미 전이 방지",81,81),
 ("highleg_highrise","높은 waistband + 낮은 leg opening","높은 waistband + 높은 leg opening","독립 축의 정상 조합 허용",77,83),
 ("cheeky_brand","한 브랜드 Brazilian 라벨","다른 브랜드 cheeky 라벨","rear geometry 없이 보편 % 판정 금지",85,85),
 ("thong_shoe","발가락 사이 Y-strap sandal","좁은 rear underwear connector","footwear/underwear owner 구별",112,85),
 ("rash_surf","자체 밑단 있는 소매 top","몸통에서 brief로 연결된 sleeved suit","분리/연결의 관계 보존",87,87),
 ("coverup_wet","마른 opaque kaftan over swimwear","젖은 translucent coverup 요청","coverup label에서 젖음/비침 자동 추가 금지",91,13),
 ("seersucker_shirring","직조 단계의 반복 puckered bands","평행 봉제 줄에 모인 fabric","surface relief와 sewn gather 원인 구별",93,11),
 ("eyelet_hardware","자수 둘레 구멍이 있는 base cloth","레이스업 끈이 통과하는 metal eyelet","fabric/hardware owner 구별",98,102),
 ("chambray_denim","평직 색실 혼합면","사선 twill ridges","파란 색만으로 weave 확정 금지",94,94),
 ("organza_chiffon","얇고 형태를 지탱하는 folds","얇고 부드럽게 처지는 folds","비침이 drape stiffness를 결정하지 않음",95,95),
 ("fiber_brand","lyocell 원료 명세","TENCEL branded fiber 명세","raw fiber와 brand provenance 독립",92,92),
 ("gather_smock","평행 rows of gathers","주름 사이 decorative crossing embroidery","retail name 중첩 허용; 공정별 구조 구별",11,99),
 ("ruffle_flounce","모인 부착선 + free edge","매끈한 부착선 + wider curved free edge","변형들을 하나의 all-of로 합치지 않음",100,100),
 ("fringe_tassel","가장자리 여러 strands","한 attachment에서 뭉친 술","부착 topology를 구별",101,101),
 ("metallic_wet","metal-like specular finish","wet fabric state 명시","광택에서 원인/재료 자동 추론 금지",96,106),
 ("style_identity","coastal grandmother style를 입은 성인","grandmother 가족관계 요청","스타일 label과 identity 구별",107,107),
 ("style_figure","mermaidcore sea-colored dress","mermaid 신체 구조 요청","fashion style이 꼬리를 생성하지 않음",109,67),
 ("waist_bodychain","허리 둘레 chain","neck-to-waist accessory network","장신구를 의복 strap/결박/pose로 대체 금지",118,102),
 ("wedge_platform","앞발 얇고 heel 높은 wedge","앞발도 높은 wedge platform","두 sole 축 공존 허용",113,113),
 ("jelly_transmission","jelly shoe 판매명만 지정","opaque molded upper를 명시","jelly 라벨에서 광학 투과를 자동으로 필수화하지 않음",114,114),
]

COMBINATION_ROWS = [
 ("bandeau_halter", [4,5,79], "수평 band + 목 뒤 strap 연결은 함께 가능"),
 ("highwaist_highleg", [77,83], "높은 waistband + 높은 leg opening은 함께 가능"),
 ("highneck_lowback", [5,36,82], "높은 front coverage + 낮은 back coverage 가능"),
 ("crop_highrise", [2,77,51], "crop + highrise이며 배꼽이 가려질 수 있음"),
 ("crochet_opaque_inner", [12,53,91], "openwork outer + opaque inner + covered skin 가능"),
 ("maxi_thigh_slit", [52,62], "maxi hem + high slit apex 가능"),
 ("bodycon_opaque", [39,13], "close fit + opaque fabric 가능"),
 ("square_flutter_milkmaid", [10,21,32], "milkmaid selected variant + flutter sleeves 가능"),
 ("unlined_opaque", [54,13], "unlined + opaque appearance 가능"),
 ("fitted_flare", [38,41], "fitted upper + flared lower 가능"),
 ("platform_wedge_strappy", [112,113], "platform + wedge + strappy footwear 가능"),
 ("same_color_different_layers", [13,30,55], "skin-like color inner fabric와 실제 skin을 구별"),
 ("multiple_garment_owners", [3,35,118], "top straps와 body-chain endpoints를 섞지 않음"),
 ("dry_surfwear", [87,92], "surf suit의 마른 상태·별도 material 명세 가능"),
 ("shift_empire", [58,59], "plenty of ease인 shift + slight empire waist가 함께 가능"),
 ("mesh_upper_solid_toe", [114], "mesh upper와 opaque knit toe가 같은 신발에 공존; 전 영역 투과 강제 금지")
]

MUTATIONS = [
 ("wrong_wearer", "의복을 다른 사람에게 옮기고 기존 evidence 유지", "owner/relation audit reject"),
 ("wrong_layer", "이너를 겉옷으로 바꾸고 투과 evidence 유지", "layer order audit reject"),
 ("drop_endpoint", "레이서백 합류 또는 크로스백 아래 연결 끝점 제거", "complete relation evidence reject"),
 ("mixed_alternatives", "racerback/X-back 또는 shirring/smocking 두 변형을 하나의 필수 계약으로 합침", "independent variant audit reject"),
 ("source_leak", "URL·논문 제목·카드 번호·research status를 runtime payload/prose에 삽입", "semantic hygiene reject"),
 ("blanket_wardrobe", "국소 armhole 후보가 locked wardrobe color/length까지 수정", "effect scope lock reject"),
 ("body_edit", "curvy/hourglass/bodycon 후보가 body_geometry/identity를 수정", "ownership and lock reject"),
 ("hidden_pass", "wire/padding/lining/fiber/UPF를 외관만으로 pixel PASS", "claim limit reject"),
 ("thumbnail_only", "작은 mesh나 strap 연결을 축소 미리보기만 보고 PASS", "native gate reject"),
 ("occluded_pass", "hard로 선택한 back cutout이 머리카락/프레임에 가려짐", "UNOBSERVABLE_NOT_PASS"),
 ("negated_activation", "not halter 또는 배꼽 노출 제외가 hard profile을 켬", "polarity gate reject"),
 ("approx_hard", "semantic similarity/profile label에서 requester hard authority 생성", "authority gate reject"),
 ("stale_pack", "core/pack을 수정하고 예전 composed receipt/hash 유지", "binding audit reject"),
 ("sibling_activation", "선택한 cold-shoulder가 off-shoulder와 deep-cut exposure sibling도 켬", "routing reject"),
 ("invisible_full_pass", "부분 gate 성공을 all-of full pass로 올림", "partial_is_fail"),
]

PIXEL_ROWS = [
 ("front_hem_navel",[2,51,77],"상의 밑단·하의 윗선·배꼽을 함께 보여주는 앞면","두 가시성 변형을 따로 시험; 숨은 배꼽은 exposed PASS 불가"),
 ("high_neck_halter",[5,36],"앞목 패널과 목 뒤 join이 읽히는 사선","앞 높은 덮임·목 뒤 경로 각각 gate; backside가 가려지면 해당 gate 미확인"),
 ("shoulder_topologies",[26,28,33],"양 어깨·윗선·sleeve bridge가 읽히는 앞 사선","off/cold/drop 각 변형별 독립 평가"),
 ("back_strap_graph",[35],"전체 strap endpoint가 드러나는 뒤면","Y convergence와 X crossing은 서로 대체 불가"),
 ("sheer_layer",[13,30,53],"원단 경계와 이너를 식별하는 중거리+근접","outer surface continuity·inner owner·layer order 모두 필요"),
 ("cutout_closure",[29,37],"aperture 전체 perimeter가 보이는 사선","keyhole/side opening/inter-garment gap 구별"),
 ("slit_long_hem",[52,62],"slit apex와 실제 긴 밑단이 모두 프레임 안","필수 apex는 가려지거나 crop되면 통과 못함"),
 ("sleeve_attachment",[31,32,33,34],"목·어깨·armhole에서 소매로 이어지는 시점","seam print·팔 포즈를 구조 대체로 인정하지 않음"),
 ("bra_visible_geometry",[44,45,46,48],"컵 윗선·center connector·패널 seam을 근접 확인","wire/pad/압박 효과는 이 픽셀 시험에서 주장하지 않음"),
 ("swim_axes",[78,79,80,83],"상의 연결·허리·leg opening을 읽는 앞 사선","서로 독립인 axis를 all-of로 평가"),
 ("rear_swim_coverage",[85,86],"뒤판 외곽과 connector가 보이는 뒤면","정확 coverage %나 브랜드 분류 인증은 없음"),
 ("swim_layer_roles",[87,89,90,91],"separate hems와 connected edges를 보이는 전신","rash/surf/tankini/skirt-overlay/cover-up 구별"),
 ("skort_culottes",[61,73],"실제 divided legs 또는 연결 inner shorts가 보이는 사선","숨은 inner shorts는 UNOBSERVABLE"),
 ("textile_relief",[11,93,97,98,99,100],"native crop과 전체 원본 모두","seersucker·shirring·smocking·rib·eyelet·flounce의 선택 변형마다 구조 gate"),
 ("pattern_scale",[104,105,106],"가슴폭/원단폭과 motif를 같이 읽는 시점","ditsy vs large motif, print vs 실제 relief 구별"),
 ("footwear_topology",[112,113,114],"발가락·instep·heel·forefoot sole이 읽히는 사선","toe-post와 cage, wedge와 platform, solid translucent와 mesh를 구별"),
 ("chain_graph",[118],"목·중앙 chain·waist loop 또는 waist-only를 식별","같은 accessory의 모든 endpoint; 옷끈·다른 착용자 chain 대체 금지"),
 ("style_without_identity",[107,108,109,110,111],"선택한 의복만 정해진 identity와 기존 장소 안에서","스타일의 의미 fidelity와 사진의 미학/사용자 선호는 별도 기록")
]
