from pathlib import Path
import json,hashlib
BASE=Path('/Users/chasoik/Projects/image-prompt/docs/research-evidence/photo-prompt/spring-fashion-integration-20261009/arms/bodice_hem')
WORK=Path('/Users/chasoik/.codex/worktrees/spring-fashion-integration-20261009/image-prompt')
state=json.loads((BASE/'run/workflow.json').read_text())
assert state['phase']=='core_frozen' and not state.get('operations')
artifacts=state['artifacts']
corepath=Path(artifacts['authorial_core_normalized']['path'])
core=json.loads(corepath.read_text())
receipt=json.loads(Path(artifacts['freeze_receipt']['path']).read_text())
assert receipt['contracts']['core']=='044840c152936e0bfb6af90f898429516e5465c6fd9364fbf5b29b80912205b2'
assert hashlib.sha256((BASE/'request_envelope.json').read_bytes()).hexdigest()=='baff8c059a45fcc3ec01f372d3795d4ec437512f10c6837d4bfc9846ba939de4'
ref=Path('/Users/chasoik/Downloads/0CB25F47-BB90-4DBD-8993-733BA8282851(20260927-041323).jpeg')
refs=['SKILL.md','references/photo-workflow.md','references/image-runtime.md','references/composition-contract.md','references/embodiment-preflight.md']
docs=[{'path':str(WORK/'skills/photo-prompt-image-generator'/r),'sha256':hashlib.sha256((WORK/'skills/photo-prompt-image-generator'/r).read_bytes()).hexdigest()} for r in refs]
rows=[
 {'id':'OBS01','subject':'전체 인상과 우선순위','origin':'agent_artistic_direction','scale':['thumbnail','whole_native'],'view':'전체 프레임을 먼저 독립적으로 읽음','success':'얼굴·상의 구조·작은 종이 작업이 한 장면으로 이어져 보이고, 배경 프린트가 주제보다 앞서지 않음','failure_or_limit':'보이는 인상만 기술함. 상상한 사연이나 sensual 수치를 먼저 보고 성공을 만들지 않음','evidence':'첫인상 자유 묘사와 실제 시선 이동'},
 {'id':'OBS02','subject':'사진의 얼굴·짧은 검은 bob 참고','origin':'requester_reference_use','scale':['native','source_comparison'],'view':'원본 사진과 생성 얼굴·머리 영역을 비교','success':'눈에 보이는 얼굴 인상과 짧은 검은 bob의 길이·실루엣이 참고 사진과 연속성을 보임','failure_or_limit':'생성된 사람의 실제 신원·연령·성격·생애·몸 치수는 확정하지 않음. 보이지 않는 얼굴은 참고 유지 성공이 아님','evidence':'소스 사진과 결과 얼굴/머리 영역의 관찰 차이'},
 {'id':'OBS03','subject':'목선과 얇은 두 끈','origin':'agent_authored_optional_wardrobe','scale':['native'],'view':'앞가슴과 양어깨의 접속이 읽히는 3/4 정면','success':'같은 상의의 비교적 직선인 square 윗선, 목선 모서리의 두 가는 끈 뿌리, 어깨로 향하는 각 경로가 구분됨','failure_or_limit':'머리·팔·그림자가 끈 뿌리나 목선 경계를 가리면 그 부분은 관찰 실패. 목걸이·브라 끈의 소유자가 대신하지 않음','evidence':'목선 천 경계와 두 끈의 실제 부착점·경로'},
 {'id':'OBS04','subject':'몸판의 반복된 수평 모음','origin':'agent_authored_optional_wardrobe','scale':['native'],'view':'몸판 앞면의 실제 요철을 읽는 확대','success':'밀착된 같은 몸판에 반복되는 좁은 수평 모음과 작은 주름 그림자가 실제 직물 면을 따라 이어짐','failure_or_limit':'평면 줄무늬·피부 주름·큰 자연 구김과 구분함. 고무실·셔링 공정·신축률·압박은 주장하지 않음','evidence':'몸판 소유자와 반복 주름의 높이·방향'},
 {'id':'OBS05','subject':'허리에서 top에 붙은 peplum','origin':'agent_authored_optional_wardrobe','scale':['native'],'view':'상의 앞허리 연결선과 바깥으로 퍼지는 부분을 함께 봄','success':'모인 몸판의 가로 허리 연결선에서 짧게 퍼지는 peplum이 같은 top에 속하고 자유 끝으로 이어짐','failure_or_limit':'별도 치마·벨트 러플·단순 큰 주름이 top 부착선을 대신하면 실패. 가려진 접속은 진단 가능한 구조 성공이 아님','evidence':'몸판→허리 seam→퍼진 연장부→자유 밑단 경로'},
 {'id':'OBS06','subject':'레이스 가장자리의 둥근 scallops','origin':'agent_authored_optional_wardrobe','scale':['native'],'view':'peplum 자유 끝의 천 경계를 확대','success':'크림 레이스 가장자리의 개별 둥근 바깥 곡선이 연속된 자유 끝으로 읽히며 top과 연결됨','failure_or_limit':'scallop 무늬가 원단 안에 인쇄되어 있거나 한 조각만 보이면 전체 끝단을 입증하지 못함. 섬유·제작법·구멍 자수 방식은 별도','evidence':'실제 바깥 외곽, 레이스와 바탕의 경계·연결'},
 {'id':'OBS07','subject':'앞이 짧고 뒤가 긴 별도 A-line midi skirt','origin':'agent_authored_optional_wardrobe','scale':['whole_native','native'],'view':'앞/뒤 쪽 밑단과 같은 다리 기준점이 함께 보이는 3/4 전신','success':'치마가 위에서 아래로 넓어지고, 앞은 윗종아리 부근에서 끝나며 뒤는 발목 쪽으로 더 내려가는 두 높이가 실제 같은 치마 끝에서 구분됨','failure_or_limit':'프레임 crop·팔로 들린 치마·바람 접힘만으로 high-low 재단 관계를 확정하지 않음. 뒷쪽 끝이 가려지면 비교는 관찰 실패','evidence':'같은 skirt 앞 끝·뒤 끝·다리/신발 기준점'},
 {'id':'OBS08','subject':'top과 skirt의 소유자와 층 경계','origin':'agent_authored_optional_wardrobe','scale':['native'],'view':'scallop 아래 부드러운 치마 면과 틈/경계를 함께 봄','success':'top peplum 자유 끝이 별도 skirt 바깥에 놓이고, scallop 끝과 매끈한 skirt 면이 다른 경계로 분리되어 읽힘','failure_or_limit':'한 드레스의 밑단처럼 합쳐지거나 skirt의 장식을 peplum으로 잘못 소유시키면 실패','evidence':'top 자유 끝→아래/안쪽 skirt 면의 별도 경계'},
 {'id':'OBS09','subject':'오른 손바닥·종이·mesh table 접촉','origin':'agent_authored_scene_and_applicable_embodiment','scale':['native'],'view':'인물과 옆 table을 함께 보고 손끝 영역을 확대','success':'같은 사람의 오른 forearm이 옆 table로 이어지고, 손바닥은 table 위 종이 모서리를 눌러 평평하게 함. 손끝 밖의 남은 crease와 접촉면 경계가 공존함','failure_or_limit':'손·종이가 떠 있거나 손이 torso를 가로질러 차단되거나 관절 소유가 불명확하면 실패. 가려진 접촉을 기형으로 단정하지 않음','evidence':'shoulder→elbow→wrist→palm 소유, paper→table 지지, 손/종이 경계'},
 {'id':'OBS10','subject':'지지와 반대손의 clip','origin':'agent_authored_scene_and_applicable_embodiment','scale':['whole_native','native'],'view':'양발과 몸통, 왼손 영역을 확인','success':'양발은 마른 stone deck에 놓이고 골반·상체의 가벼운 옆 reach가 지지와 양립함. 왼손은 왼 hip 옆의 작은 clip을 소유함','failure_or_limit':'발 접지가 가려져 판단 불가하거나 clip 소유자·팔 연결이 불명확하면 관찰 실패. 보이지 않는 관절의 정량 각도는 추정하지 않음','evidence':'발/바닥 경계, 몸통 지지 방향, 왼팔·clip의 실제 연결'},
 {'id':'OBS11','subject':'작은 작업의 전후 관계와 복잡성','origin':'agent_artistic_direction','scale':['thumbnail','whole_native','native'],'view':'설명 없이 sheet·clip·drying line·table의 현재 상태를 읽음','success':'헐거워진 sheet, 평평해진 모서리, 남은 종이 crease와 위의 빈 clip이 현재 처리 중인 일을 암시하고 outfit을 가리지 않음','failure_or_limit':'소품 개수만 많거나 원인·접촉·다음 가능성이 단절되면 복잡한 씬의 관계 전달은 약함. 설명 문구만으로 unseen backstory를 PASS하지 않음','evidence':'실제 보이는 현재 상태·trace·연결; 상상에 남는 부분은 따로 기록'}
]
plan={
 'schema_version':'photo-independent-preretrieval-pixel-plan/v1','status':'prepared_waiting_ready','arm_id':'bodice_hem','concept':'Last Cyanotype on the Rooftop Drying Line','seed':9878669292090812608,
 'frozen_bindings':{'core_canonical_sha256':receipt['contracts']['core'],'intent_lock_canonical_sha256':receipt['contracts']['intent_lock'],'controls_canonical_sha256':receipt['contracts']['controls'],'envelope_file_sha256':'baff8c059a45fcc3ec01f372d3795d4ec437512f10c6837d4bfc9846ba939de4','baseline_sha256':hashlib.sha256(core['baseline_prompt_en'].encode()).hexdigest(),'core_path':str(corepath)},
 'reference':{'path':str(ref),'sha256':hashlib.sha256(ref.read_bytes()).hexdigest(),'role':'visible_face_and_short_dark_hair_reference','scope':'Only visible face and hair cues. Identity, biography, personality and body measurements are not inferred.'},
 'documents_read':docs,
 'observation_plan':rows,
 'view_requirements':{'authorial_camera':'Comfortable three-quarter frontal position; camera is open in the core. No numerical angle or requester camera lock is introduced.','coverage':'Include neckline, both shoulder attachments, bodice, waist join, peplum free edge, distinct skirt front/rear edges and grounded shoes. Keep the table lateral so the forearm and sheet contact remain assessable.','native_checks':'Inspect original saved pixels first; crops may support evidence but never replace the original image binding. Do not combine different generated attempts.','complexity':'One person, one connected garment outfit and one small ongoing paper task. Complexity comes from visible relations and texture/layer distinctions, not a required prop count.'},
 'hard_contract_closure':{'status':'awaiting_verified_generation_pack_and_audited_composition','effective_hard_gate_ids':None,'unconditional_visual_obligations':'derive from exact pack','selected_optional_visual_obligations':'derive only from chosen_visual_concept_ids and their immutable opt-in contracts','embodiment_gates':'derive from applicable checks in the exact final postcomposition review','character_or_repair_gates':'include only if an actual typed contract is present','wire_statuses':['pass','fail'],'partial_or_occluded':'Use fail with image-grounded visibility reason; partial is not promotable.','supplemental_observations':'OBS rows do not independently create hard duties. After adoption, test complete selected contracts; source labels, associated profile IDs, approximate retrieval or the preplan alone cannot harden an obligation.','acceptance':'user_judgment.source remains not_yet_received until actual requester feedback'},
 'execution_after_ready':{'source_generation':None,'runtime_store':None,'pack_count':1,'native_invocation_limit':1,'runtime':'built-in image_gen','api_fallback_authorized':False,'core_changes':False,'scope':'Only this arm; no other arm prompts, packs, images or evaluation records are inputs.','phases':['retrieve on the verified runtime generation','read compact view then complete considered candidate contracts','compose only compatible authorial or optional selections with unchanged user locks','fresh composed/body/runtime audits','durable native plan/start','one native image call with the actual local reference','record only actual returned paths/error evidence','derive exact review shape and author image-grounded reviews','strict review audits and supplemental artistic observations'],'unknown_outcome':'Stop automatic reexecution; retain actual native observation and operation journal.','preview_only':'No invented local image path or ledger image, and no extra image call.'},
 'document_note':'Composition reference has one trailing historical prompt-budget V2 label despite its earlier current V3 description. Use the returned generation\u2019s actual pack and auditors; do not construct or downgrade a contract from that stale line.'
}
raw=(json.dumps(plan,ensure_ascii=False,indent=2)+'\n').encode();(BASE/'pre-retrieval-pixel-plan.json').write_bytes(raw)
lines=['# B 사전 픽셀 평가표','',f'컨셉: {plan["concept"]}',f'Frozen core: `{receipt["contracts"]["core"]}`','',
 '이 표는 아직 생성되지 않은 결과의 관찰 계획이다. 각 의복·장면 선택은 authorial/optional이며, hard gate는 READY 후 실제 pack과 audited composed selection에서만 확정한다.','',
 '| 항목 | 관찰 범위 | 성공을 뒷받침하는 실제 픽셀 | 관찰 실패·한계 |','| --- | --- | --- | --- |']
for r in rows:lines.append(f'| {r["id"]} {r["subject"]} | {r["view"]} | {r["success"]} | {r["failure_or_limit"]} |')
lines.extend(['','3/4 정면의 거의 전신 구성으로 앞면 구조와 앞뒤 skirt 끝을 동시에 읽고, table은 옆에 둔다. 카메라 각도는 독립 staging 선택이며 사용자 lock으로 만들지 않는다. 원본 해상도 확인과 전체 이미지 확인을 함께 하고, 가려진 필요 관계는 `fail`로 기록하되 기형으로 단정하지 않는다.','',
 'READY 후 검증된 단일 generation에서 pack 1개를 가져오고, 완전한 계약을 확인한 후보만 선택한다. 최종 body review와 runtime audit 이후 native 호출은 1회이며, 실제 반환된 경로와 바이트만 저장·기록한다. preview-only/unknown이면 자동 재호출하지 않는다.','',
 '기술·프롬프트·runtime·pixel·미적 관찰·실제 사용자 판단은 별도로 기록한다. 사용자 판단은 아직 `not_yet_received`다.'])
(BASE/'pre-retrieval-pixel-plan.md').write_text('\n'.join(lines)+'\n')
print(json.dumps({'status':plan['status'],'observation_rows':len(rows),'plan_path':str(BASE/'pre-retrieval-pixel-plan.json'),'sha256':hashlib.sha256(raw).hexdigest(),'reference_sha256':plan['reference']['sha256'],'core_unchanged':True,'retrieval_compose_generation_calls':0},ensure_ascii=False,indent=2))
