import pathlib,json,hashlib,datetime
B=pathlib.Path('/Users/chasoik/Projects/image-prompt/docs/research-evidence/photo-prompt/universal-authorship-qualification-20261005/arm-b');p=json.loads((B/'candidate_pack.json').read_text())[0];im=B/'generated.png';sha=hashlib.sha256(im.read_bytes()).hexdigest()
def write(n,x):(B/n).write_text(json.dumps(x,ensure_ascii=False,indent=2)+'\n')
hard={
'embodiment_body_ownership':{'status':'pass','evidence':'At native size, the screen-left pinching hand connects to the actor right forearm and the screen-right support palm to her actor left forearm. Both belong to the same pictured adult figure.'},
'embodiment_joint_chain_and_reach':{'status':'pass','evidence':'The elbows and forearms lead forward from the torso; the right wrist and fingers reach the left visible toy flipper while the left forearm curves toward the underside. No disconnected segment or incompatible reach is visible.'},
'embodiment_support_and_balance':{'status':'pass','evidence':'The plush sits upright across the actor left palm and curled support fingers. Her seated torso is behind the bench; the small light toy is supported independently of the separate right-finger adjustment.'},
'embodiment_contact_and_space':{'status':'pass','evidence':'The actor right fingers visibly meet the folded screen-left flipper. The other palm touches the gray underside, with distinct skin/cloth boundaries and a narrow soft dark edge at the support contact; the belly patch remains uncovered.'},
'embodiment_visibility_and_projection':{'status':'pass','evidence':'The native frame includes the complete head, both forearms, the supporting palm, the adjusting fingers and the plush. The critical hand-to-flipper and underside-to-palm relations are assessable despite ordinary partial finger overlap.'}}
review={'schema_version':'moe-render-review/v1','pack_id':p['pack_id'],'contract_version':'photo-embodiment-preflight/v1','reviewer':'arm-b independent agent; direct view_image of original returned local PNG at original detail','result_image':str(im),'result_sha256':sha,'source_embodiment_preflight_sha256':p['embodiment_preflight']['canonical_sha256'],'hard_gates':hard,'user_judgment':{'baseline_available':False,'genuinely_moe':'pending','better_than_baseline':'not_applicable','source':'not_yet_received','evidence':'No direct requesting-user judgment was received for this saved image.'},'supplemental_observations':{'overall_impression_ko':'창가의 따뜻한 수선실에서 작은 장난감을 조심히 다루는 인물의 편안한 존재감이 먼저 읽힌다. 둥근 봉제 바다표범과 작게 웃는 얼굴이 부드럽고 귀여운 인상을 만든다. 손과 패치가 역할과 순간을 설명한다.','strengths_ko':['참조의 어두운 짧은 단발·앞머리와 눈·코·입의 외형이 사진에 가깝게 남는다. 이것은 신원 인증이나 원본의 실제 나이 판단이 아니다.','얼굴에서 두 손과 하나의 봉제 장난감으로 이어지는 위계가 읽힌다.','봉제 바다표범의 작은 눈·둥근 몸·짧은 지느러미와 수선 패치가 구체적으로 보인다.'],'weaknesses_ko':['새 문구의 얕은 천 눌림은 뚜렷하게 확인되지 않는다.','작성한 3/4 시점보다 정면에 가까운 구도다. 접촉 가독성은 유지된다.','배경에 추가 장난감·작업 도구·문구가 생겨 독립 초안보다 정보량이 많다. 주 장면을 가리지는 않는다.'],'unexpected_generated_content':['Small Repairs Big Happiness background sign','Good Toys Brighter Days tool-container text','additional shelf toys and workshop tools'],'controls_comparison':{'sensual_saved':1,'perceived_expression':'Subtle supporting everyday attraction through relaxed neckline, gentle direct eye contact and natural ease; cute tactile moment remains primary.','fetish_saved':0,'perceived_fetish_treatment':'No distinct added erotic object/role focus is evident.','surreal_saved':0,'perceived_surreal_treatment':'Ordinary studio space, lighting and material behavior remain coherent.','user_preference':'pending'}}}
write('PIXEL-REVIEW.json',review)
case=json.loads((B/'CASE.json').read_text());evidence={
'case-cute-form':'A small plush seal has a pear-like rounded body, small black stitched/button-like eyes, a short blunt muzzle and soft stubby flippers. It is a recognizable soft object, not a text label.',
'case-care-contact':'One palm cradles the underside while the other hand adjusts the raised flipper; the contact survives at native size.',
'case-adult-presence':'The authored adult restorer meets the camera with a small smile. Reference bob/fringe and visible face features are recognizable. A photo cannot verify real age or identity.',
'case-repair-trace':'A blue checkered belly patch and its surrounding stitches are clear between the supporting fingers.',
'case-hierarchy':'The face carries the first read, then the paired hands and seal; the softer workshop shelving remains background context.'}
write('CASE-PIXEL-REVIEW.json',{'schema_version':'photo-case-pixel-review/v1','case_file_sha256':hashlib.sha256((B/'CASE.json').read_bytes()).hexdigest(),'result_image':str(im),'result_sha256':sha,'criteria':[{'criterion_id':r['id'],'status':'pass','evidence':evidence[r['id']],'origin':r['origin'],'hard_user_gate':False} for r in case['one_frame_observable_criteria']],'authored_criteria_all_pass':True,'meaning_data_effect_is_separate':True,'deviations':['View is more frontal than the authored three-quarter camera treatment.','Toy is roughly hand-sized and slightly taller than a flat palm silhouette; exact palm-size metrology is not claimed.'],'actual_reference_person_age_or_identity_inferred':False})
write('DATA-PIXEL-REVIEW.json',{'schema_version':'photo-data-pixel-review/v1','result_image':str(im),'result_sha256':sha,'selected_candidate_id':'slot:contact_point:pr_object_contact_shadow_support_candidate','source_contract_checks':[{'id':'object_and_support_visible','status':'pass','evidence':'The seal lower surface and supporting palm are visible together in the same native frame.'},{'id':'local_darkening_or_compression_at_load_point','status':'pass','evidence':'A narrow soft gray dark edge lies where the plush underside meets the skin. The source contract permits darkening OR compression; a definite fabric indentation is not claimed.'},{'id':'shadow_consistent_with_light','status':'pass','evidence':'The small soft contact edge agrees with broad bright window illumination rather than a detached hard cast shadow.'},{'id':'object_and_support_align','status':'pass','evidence':'The underside follows the cupped palm and support fingers continuously with no visible floating gap.'}],'complete_selected_candidate_contract_survives':True,'newly_added_prompt_cues':[{'cue':'narrow soft contact shadow','status':'pass','evidence':'A soft dark transition is visible at the underside-to-palm contact.'},{'cue':'shallow fabric indentation meeting the skin','status':'fail','evidence':'The underside rests against the palm, but a discrete shallow dent in the plush cannot be confidently distinguished at native size; this missing detail is not inferred.'}],'all_new_data_prompt_cues_survive':False,'cute_visual_profile_exposed':False,'cute_visual_profile_selected':False,'causal_cute_data_effect_proven':False,'causal_contact_data_effect_proven':False,'causal_boundary':'This single composed image shows a compatible support relationship. No image of the frozen baseline was generated, so the image alone cannot isolate the causal contribution of the added DATA phrase.'})
write('RENDER-REPAIR-REVIEW.json',{'schema_version':'photo-render-repair-applicability/v1','status':'not_applicable','reason':'Initial request has request_lineage null and no v2 generic render_repair contract; its exact generic repair hard-gate set is empty. No repair lineage or gates were fabricated. Applicable original-generation embodiment gates are reviewed and audited separately.','required_repair_gate_ids':[],'audit_image_render_review_called':False})
write('IMAGE-INSPECTION.json',{'schema_version':'photo-native-pixel-inspection/v1','result_file':str(im),'result_sha256':sha,'native_size':[1237,1272],'original_result_file':'/Users/chasoik/.codex/generated_images/01a10a8e-ab61-7942-97e8-e93990195bb5/exec-a56191f7-3ce6-457d-ada9-7641d535a2ad.png','original_and_copy_sha256_equal':hashlib.sha256(pathlib.Path('/Users/chasoik/.codex/generated_images/01a10a8e-ab61-7942-97e8-e93990195bb5/exec-a56191f7-3ce6-457d-ada9-7641d535a2ad.png').read_bytes()).hexdigest()==sha,'view_image_original_detail_succeeded':True,'display_observation':'Early view_image outputs for the copied identical file appeared tiny; direct view_image of the returned original path displayed the complete native image. File, pixel dimensions and SHA were independently read. No screenshot, app-cache extraction, reconstructed PNG or regeneration was used.'})
print(json.dumps({'hard_gate_count':len(hard),'case_count':len(evidence),'data_full_contract':'pass','new_indentation_cue':'fail','user_judgment':'pending'}))
