import json,hashlib,pathlib,datetime,shutil
B=pathlib.Path('/Users/chasoik/Projects/image-prompt/docs/research-evidence/photo-prompt/universal-authorship-qualification-20261005/arm-b')
R=pathlib.Path('/Users/chasoik/Projects/image-prompt/docs/research-evidence/photo-prompt/universal-authorship-qualification-20261005/runtime/skills/photo-prompt-image-generator')
def sha(x): return hashlib.sha256(x).hexdigest()
def write(name,x): (B/name).write_text(json.dumps(x,ensure_ascii=False,indent=2)+'\n')
e=json.loads((B/'request_envelope.json').read_text()); controls=json.loads((B/'creative_controls.json').read_text())
span=e['active_spans'][0]['text']; sid=e['active_spans'][0]['span_id']
prompt=' '.join('''A photographic scene in a small neighborhood toy-repair studio: an adult woman, authored as a 27-year-old toy restorer, shares a visible hands-on moment with a palm-sized plush seal. Use the supplied reference for the visible face and hair. Her dark chin-length bob and airy fringe frame the reference facial features, with natural adult proportions. Seated behind a low wooden workbench, she cups the little seal upright in her left palm while her right thumb and forefinger gently unfold its bent cloth flipper; both wrists stay close together above the bench. The toy has a rounded pear-shaped body, small stitched eyes, a blunt muzzle and soft, stubby flippers. A fresh hand-sewn patch on its belly is visible between her supporting fingers. Her eyes lift briefly toward the photographer, the corners of her mouth curving into a small, pleased smile, as if sharing the tiny repair's success. She wears an oatmeal scoop-neck knit top with sleeves pushed to her forearms and a worn walnut-colored work apron; the relaxed neckline and easy eye contact give her a quiet, everyday adult appeal. A thread spool and folded fabric scraps sit lower on the bench, subordinate to her hands and the toy. A broad window lights the face, fingertips and brushed fabric softly. Photograph from across the workbench at her upper-chest height in a three-quarter medium view, keeping her complete head, both forearms, the seal and its contact with her hands readable. Use a natural 50mm perspective with sufficient depth to resolve the fresh stitches; softly receding shelves establish the working room. The visual rhythm is her amused face, the careful paired hands, then the small rounded creature they protect.'''.split())
open_dims=['identity','count','age','role','species','appearance','pose','body_geometry','expression','action','setting','relationship','sexual_tone','style','viewer_outcome','text','format','framing','composition','lighting','camera','color','material','timing','atmosphere','character_response']
anchors=[{'anchor_id':'test_photograph','source_text':span,'dimension':'concept','prompt_evidence':'A photographic scene'}, {'anchor_id':'test_reference_subject','source_text':span,'dimension':'subject','prompt_evidence':'an adult woman'}, {'anchor_id':'test_visible_event','source_text':span,'dimension':'event','prompt_evidence':'a visible hands-on moment'}, {'anchor_id':'test_reference_scope','source_text':span,'dimension':'reference_use','prompt_evidence':'Use the supplied reference for the visible face and hair.'}]
core={'contract_version':'photo-authorial-core/v3','provenance':'agent_prepack','source_request':e['request_text'],'creative_controls_sha256':controls['canonical_sha256'],'interpreted_intent':'The contextual user request authorizes another independent complex photographic test using the supplied reference and actual generation. The coordinator topic cute/귀여운 is an author-owned experimental direction, not a requester definition. My photograph lets a capable adult toy restorer and a small repaired plush seal share a quiet, tactile success: rounded toy forms, careful support and an amused acknowledgement carry tenderness while her everyday appeal remains a subtle supporting quality. Studio, age, role, garment, color, handling geometry, expression and camera are authored open choices. Reference use is face and hair only; it supplies no biography, age, body or outfit.','subject':'An authored 27-year-old adult woman toy restorer using reference face and hair.','setting':'A small neighborhood toy-repair studio with a low wooden workbench.','event':'A visible hands-on moment as she supports a repaired palm-sized plush seal and unfolds its cloth flipper.','visual_priorities':['The adult restorer acknowledges the viewer with a small pleased smile while maintaining the reference facial appearance.','Her paired hands visibly support the little seal and adjust one folded flipper.','Rounded soft toy forms and fresh stitches turn a tiny practical repair into a gentle, cute moment.'],'baseline_prompt_en':prompt,'user_definitions':[],'interpretation_provenance':[{'term':span,'source_text':span,'basis':'request_context','resolution':'The phrase refers to the preceding user-authorized method: independent authors choose complex photographic concepts, use the attachment, compose prompts, generate actual images, and inspect semantic-data application. It does not prescribe a specific scene, palette, garment or action.','sources':[]}],'unresolved_ambiguities':[],'user_exclusions':[],'runtime_forbidden_labels':[],'intent_lock':{'contract_version':'photo-intent-lock/v2','priority':'requesting_user','semantic_anchors':anchors,'locked_dimensions':['concept','subject','event','reference_use'],'open_dimensions':open_dims},'semantic_assertions':[{'assertion_id':'camera_review','dimension':'camera','polarity':'advisory','source_span_ids':[sid],'affected_dimensions':['camera'],'axes':{'camera_axis_review':'camera_axis_review_v1','capture_owner':'unprescribed','direction_requirement':'open','height_requirement':'open'},'evidence':{}}],'request_lineage':None,'style':{'domain':'photographic','family':'intimate craft-work environmental portrait','evidence':['A broad window lights the face, fingertips and brushed fabric softly.','softly receding shelves establish the working room.']},'variation_key':'arm-b-toy-repair-cute'}
write('authorial_core.json',core); (B/'baseline_prompt_en.txt').write_text(prompt)
checks={
'body_ownership':{'status':'supported','reason':'Both hands and both forearms belong to the same seated adult. Actor-relative left supports the toy, actor-relative right adjusts the flipper.','prompt_evidence':['she cups the little seal upright in her left palm','her right thumb and forefinger gently unfold its bent cloth flipper']},
'joint_chain_and_reach':{'status':'supported','reason':'Forearms stay forward from the seated torso. Close wrists over a low bench permit right finger-to-flipper reach while left palm supports the same toy.','prompt_evidence':['both wrists stay close together above the bench','sleeves pushed to her forearms']},
'support_and_balance':{'status':'supported','reason':'A chair implied by seated supports the adult outside the crop; the bench is lower than the hands. Left palm carries the light plush so the right pinch need not bear its weight.','prompt_evidence':['Seated behind a low wooden workbench','she cups the little seal upright in her left palm']},
'contact_and_space':{'status':'supported','reason':'One palm contacts the plush underside and the other hand pinches a separate cloth flipper. Supporting fingers leave a gap for the belly patch; no crossed hand assignment is necessary.','prompt_evidence':['gently unfold its bent cloth flipper','A fresh hand-sewn patch on its belly is visible between her supporting fingers.']},
'visibility_and_projection':{'status':'supported','reason':'The upper-chest three-quarter view includes full head, both forearms and the toy-hand contacts. Natural perspective and sufficient depth preserve contact and stitches.','prompt_evidence':['keeping her complete head, both forearms, the seal and its contact with her hands readable.','sufficient depth to resolve the fresh stitches']}}
review={'contract_version':'photo-embodiment-review/v1','provenance':'agent_prepack','prompt_sha256':sha(prompt.encode()),'scope':'body_action','summary':'Seated human adult supports one light plush object in her left palm and adjusts its right-side cloth flipper with her own right fingers; the close wrists and medium three-quarter crop make reach and contact plausible.','checks':checks}
write('embodiment_review.json',review)
rows=[('feature.situation','The visible repair success supplies the moment that makes the portrait matter.','shares a visible hands-on moment with a palm-sized plush seal.'),('feature.subject','The authored adult craft role provides presence independent of the reference portrait biography.','authored as a 27-year-old toy restorer'),('feature.facial_expression','A small pleased response connects the adult to the tiny achievement without exaggerating facial anatomy.','the corners of her mouth curving into a small, pleased smile'),('feature.hand_gesture','Separate support and adjustment contacts make the gentle interaction understandable.','she cups the little seal upright in her left palm while her right thumb and forefinger gently unfold its bent cloth flipper'),('feature.props','Rounded soft toy form offers a physical carrier of cute rather than a wardrobe code.','a rounded pear-shaped body, small stitched eyes, a blunt muzzle and soft, stubby flippers'),('feature.location','A working studio gives the repair an intelligible place.','a small neighborhood toy-repair studio'),('feature.narrative_clues','The new stitches are an already-present trace of the work just completed.','A fresh hand-sewn patch on its belly is visible between her supporting fingers.'),('feature.composition','The hierarchy connects face to careful hands to their small target.','The visual rhythm is her amused face, the careful paired hands, then the small rounded creature they protect.')]
sel={'contract_version':'photo-precore-feature-selection/v1','request_id':e['request_id'],'active_span_ids':[sid],'catalog_path':'skills/photo-prompt-image-generator/precore/visual_feature_catalog.json','catalog_schema_version':'photo-precore-feature-catalog/v1','catalog_sha256':sha((R/'precore/visual_feature_catalog.json').read_bytes()),'request_sha256':e['request_sha256'],'baseline_prompt_sha256':sha(prompt.encode()),'selected':[{'category_id':cid,'basis':'agent_visual_choice','source_span_ids':[],'source_text':None,'derivation':None,'reason':reason,'baseline_evidence':evidence} for cid,reason,evidence in rows]}
write('precore_feature_selection.json',sel); shutil.copyfile(R/'precore/visual_feature_catalog.json',B/'visual_feature_catalog.snapshot.json')
now=datetime.datetime.now(datetime.timezone.utc).isoformat()
case={'schema_version':'photo-independent-test-case/v1','arm':'arm-b','created_before_candidate_access':True,'frozen_at_utc':now,'request_envelope_file_sha256':sha((B/'request_envelope.json').read_bytes()),'request_context_file_sha256':sha((B/'REQUEST-CONTEXT.json').read_bytes()),'request_text_sha256':e['request_sha256'],'topic':{'keyword':'귀여운','owner':'coordinator_assigned_experimental_topic','meaning':'General-knowledge cute: small rounded soft form, gentle handling and quietly delighted response. Not a named behavioral archetype or a requester-defined fixed costume.'},'concept':{'owner':'agent_author','title_ko':'작은 수선의 성공','summary':'An adult toy restorer supports a repaired plush seal and straightens its folded flipper while sharing a pleased look with the camera.'},'source_ownership':{'requester':['repeat the prior independent complex-photo test method','use attachment within context-resolved scope','generate actual image and assess semantic application'],'coordinator':['experimental topic 귀여운','reference scope visible face and hair only'],'reference_observation':['dark chin-length bob','airy fringe','visible eye/nose/mouth proportions and face contour'],'agent_author':['27-year-old adult role','toy repair studio','plush seal','gesture','garment','palette','smile','camera and light'],'data':'No candidate or profile read before this freeze.'},'one_frame_observable_criteria':[{'id':'case-cute-form','description':'The toy reads as a small, soft, rounded seal rather than a flat symbol or merely a cute word.','origin':'agent_prepack','hard_user_gate':False},{'id':'case-care-contact','description':'One adult palm supports the toy; fingers of the other hand gently adjust its flipper, with readable physical contact and plausible ownership.','origin':'agent_prepack','hard_user_gate':False},{'id':'case-adult-presence','description':'The adult has a pleased camera acknowledgement and recognizable reference face/hair without facial infantilization.','origin':'agent_prepack','hard_user_gate':False},{'id':'case-repair-trace','description':'A fresh stitched belly patch remains visible.','origin':'agent_prepack','hard_user_gate':False},{'id':'case-hierarchy','description':'Face, paired hands and toy carry the frame; workshop context remains subordinate.','origin':'agent_prepack','hard_user_gate':False}], 'pixel_rule':'Report each authored criterion independently. All actual hard/opt-in gates will be enumerated from the returned pack; partial evidence fails a gate. Do not promote an authored criterion to a user lock.','freeze_hashes':{name:sha((B/name).read_bytes()) for name in ['authorial_core.json','baseline_prompt_en.txt','embodiment_review.json','precore_feature_selection.json','creative_controls.json','AUTHORING-NOTES.md']},'baseline_prompt_utf8_sha256':sha(prompt.encode()),'candidate_access_at_freeze':False}
write('CASE.json',case)
write('PRECORE-FREEZE.json',{'frozen_at_utc':now,'core_file_sha256':sha((B/'authorial_core.json').read_bytes()),'core_json_canonical_sha256':sha(json.dumps(core,ensure_ascii=False,sort_keys=True,separators=(',',':')).encode()),'baseline_prompt_utf8_sha256':sha(prompt.encode()),'case_file_sha256':sha((B/'CASE.json').read_bytes()),'candidate_access':False,'data_read':False})
print(json.dumps({'freeze':now,'words':len(prompt.split()),'core_file_sha256':sha((B/'authorial_core.json').read_bytes()),'baseline_sha256':sha(prompt.encode()),'case_sha256':sha((B/'CASE.json').read_bytes())}))
