"""Production V6 replay with an unchanged genuine context and two source actions."""
import copy,hashlib,json,socket,sys,urllib.request
from pathlib import Path
from unittest.mock import patch
sys.dont_write_bytecode=True
R=Path('/workspace/scratch/ce8f20680f5a/image-prompt');O=R.parent/'daylong-progress/boundary-transition-source-scout';A=R/'skills/photo-prompt-image-generator/assets';S=A.parent/'scripts';sys.path[:0]=[str(R),str(S)]
import prompt_generator as g
import photo_candidate_semantics as semantics
import compose_pack_view as views
sha=lambda b:hashlib.sha256(b).hexdigest();save=lambda n,v:(O/n).write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n')
f=json.loads((O/'frozen-proposal-and-unmeasured-probes.json').read_text());freeze_sha=sha((O/'frozen-proposal-and-unmeasured-probes.json').read_bytes());assert freeze_sha==(O/'frozen-proposal-sha256.txt').read_text().strip();ID='waiting_in_between_use_space';SLOT='action';CID='slot:action:'+ID
assert all(sha((R/p).read_bytes())==h for p,h in f['repository_snapshot'].items())
data=g.load_json(A/'photo_prompt_tags.json');data[g.QUALITY_LAYERS_DATA_KEY]=g.load_quality_layers(A/'photo_prompt_quality_layers.json');reg=g.load_visual_obligation_registry(A/'photo_prompt_visual_obligations.json');data[g.VISUAL_OBLIGATIONS_DATA_KEY]=reg;data[g.VISUAL_PROFILE_INDEX_DATA_KEY]=g.load_visual_profile_index(A/'photo_prompt_visual_profile_index.json',reg)
subject=next(r for r in data['slots']['subject'] if r['id']=='elderly_commuter');location=next(r for r in data['slots']['location'] if r['id']=='between_use_transit_interior');control=next(r for r in data['slots'][SLOT] if r['id']=='waiting_train');picked={'subject':subject,'location':location};result=json.loads((O/'generated-contract.json').read_text());assert result['provenance']['authorial_core']['intent_lock']['locked_dimensions']==['concept','subject','event']
for row in [f['before'],f['proposal'],control]:assert g.compatible_with_picked([row],picked,forced=False,slot=SLOT,source=data)==[row]
fixture_record={'recorded_before_replay':True,'source_proposal_probes_unchanged':True,'original_generated_contract_sha256':sha((O/'generated-contract.json').read_bytes()),'subject_row':subject,'location_row':location,'companion_row':control,'companion_role':'Unchanged source waiting quietly alternative avoids the production singleton action projection. It is compatible with the exact same waiting event and human/context.','forced':False,'action_used_for_its_own_compatibility':False,'generated_core_policies_guards_preserved':True,'script_sha256':sha(Path(__file__).read_bytes())};save('two-action-fixture-freeze.json',fixture_record)
surfaces={};blocked=AssertionError('Network/API forbidden')
with patch.object(g,'embed_texts_with_gemini',side_effect=blocked),patch.object(urllib.request,'urlopen',side_effect=blocked),patch.object(urllib.request.OpenerDirector,'open',side_effect=blocked),patch.object(socket,'create_connection',side_effect=blocked):
 for name,row in [('baseline',f['before']),('proposal',f['proposal'])]:
  d=copy.deepcopy(data);d['slots'][SLOT]=[copy.deepcopy(row) if r['id']==ID else r for r in d['slots'][SLOT]];semantics.validate_candidate_entries(d,g.AUTHORIAL_CORE_V3_INTENT_LOCK_DIMENSIONS)
  fixture=copy.deepcopy(result);fixture['choices']={'subject':copy.deepcopy(subject),'location':copy.deepcopy(location),SLOT:{'id':ID}};fixture['preset_id']=None;trace=fixture['semantic_trace'];trace['preset_scores']=[];trace['slot_scores']=[{'slot':SLOT,'selected':ID,'candidate_count':2,'top':[{'id':r['id'],'weight':r['weight'],'score':1.,'applicability_status':'eligible','applicability_source':'controlled_source_compatible_fixture'} for r in [row,control]]}];contract=trace['generation_contract'];contract['candidate_pool_trace']={SLOT:{'eligible_ids':[ID,control['id']],'weights':{r['id']:r['weight'] for r in [row,control]},'forced':False}}
  pack=g.build_candidate_pack(fixture,d,'v6');candidate=next((x for x in pack.get('slots',{}).get(SLOT,{}).get('candidates',[]) if x['id']==CID),None);overview=views.build_view(pack);views.verify_view(pack,overview);detail=views.build_view(pack,[CID]) if candidate else None
  if detail:views.verify_view(pack,detail)
  assert pack['authorial_core']==result['provenance']['authorial_core'];assert pack['negative_intent_guard']==result['negative_intent_guard'];assert contract['soft_anchor_policy']==result['semantic_trace']['generation_contract']['soft_anchor_policy'];assert fixture['provenance']==result['provenance']
  surfaces[name]={'full_pack':pack,'candidate':candidate,'overview':overview,'detail':detail,'detail_verified':bool(detail)};save('two-action-'+name+'-actual-v6.json',surfaces[name]);print('V6',name,bool(candidate),pack.get('pack_id'),flush=True)
assert surfaces['baseline']['candidate'] and surfaces['proposal']['candidate'];assert surfaces['baseline']==surfaces['proposal'];assert all(sha((R/p).read_bytes())==h for p,h in f['repository_snapshot'].items())
checks={'full_pack_equal':True,'candidate_equal':True,'overview_equal':True,'hash_verified_detail_equal':True,'target_exposed_in_both':True,'companion_exposed_in_both':all(any(r['id']=='slot:action:waiting_train' for r in s['full_pack']['slots']['action']['candidates']) for s in surfaces.values()),'genuine_human_location_context_unforced':True,'action_not_used_for_its_own_compatibility':True,'core_and_guards_and_soft_policy_preserved':True,'proposal_and_probes_and_source_and_runtime_unchanged':True};assert all(checks.values())
save('actual-v6-preservation.json',{'status':'pass_controlled_two_action_production_v6_preservation','checks':checks,'pack_id':surfaces['baseline']['full_pack']['pack_id'],'freeze_sha256':freeze_sha,'generated_contract':'generated-contract.json','fixture':'two-action-fixture-freeze.json','baseline_artifact':'two-action-baseline-actual-v6.json','proposal_artifact':'two-action-proposal-actual-v6.json','api_calls':0,'retrieval_executions':0,'new_rule_generations':0,'repository_writes':0,'limits':['Controlled exposure only, not natural retrieval or adoption.','Korean benefit is the actual catalog correction; unchanged English V6 is preservation, not a semantic uplift.','Singleton control omitted the action by the explicit authorial-opening policy; invalid event-open control was rejected by normal core validator. Both controls retained.']})
print('PASS complete target candidate, full pack, overview and verified detail identical',flush=True)
