import json,hashlib
from pathlib import Path
R=Path('/workspace/scratch/ce8f20680f5a/image-prompt');O=R.parent/'daylong-progress/boundary-transition-source-scout';sha=lambda b:hashlib.sha256(b).hexdigest(); save=lambda n,v:(O/n).write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n')
f=json.load(open(O/'frozen-proposal-and-unmeasured-probes.json'));d=json.load(open(O/'source-inventory-and-decisions.json'));cat=json.load(open(O/'korean-catalog-consumer.json'));v6=json.load(open(O/'actual-v6-preservation.json'))
assert all(sha((R/p).read_bytes())==h for p,h in f['repository_snapshot'].items());assert len(d['rows'])==22;assert cat['status']=='pass';assert all(v6['checks'].values());assert sha((O/'frozen-proposal-and-unmeasured-probes.json').read_bytes())==(O/'frozen-proposal-sha256.txt').read_text().strip()
for r in d['rows']:
 if r['entry_id']=='waiting_in_between_use_space':
  r['decision']='qualified_ko_only_proposal_not_published';r['reason']=f['adjudication'];r['proposal']=f['proposal'];r['changed_fields']=['ko'];r['independent_review']='adjudicate_liminal_trace, corroborated by parent reviewer review_remaining_data_cycles';r['source_research_line']=85
for p in d['proposals']:p['status']='qualified_catalog_correction_and_controlled_full_v6_preservation; retrieval_unmeasured; unpublished'
d['limits'][-1]='Twelve independently authored EN/KO probes frozen and unmeasured. Production Korean action catalog changes one of 963 lines. Target candidate/full V6 pack/overview/hash-verified detail preserved in a two-action genuine context. No natural exposure/adoption, composed prose, image or retrieval benefit claimed. No repository writes, paid calls, commits or pushes.'
d['consumer_evidence']={'korean_catalog':'korean-catalog-consumer.json','v6':'actual-v6-preservation.json','genuine_context':'two-action-fixture-freeze.json','control_limits':'control-diagnosis-correction.json'};save('source-inventory-and-decisions.json',d)
summary={'status':'bounded_audit_complete_one_source_qualified_proposal_not_published','reviewed_rows':22,'new_keeps':21,'qualified_proposals':1,'entry_id':'waiting_in_between_use_space','change':'ko only: 사용 흔적 없이 -> 예상된 이용 활동 없이','original_boundary_extension_rows_excluded':36,'review_map_and_later_scout_overlap':0,'earlier_authored_source_row_matches':22,'probe_count':12,'probe_categories':{'positive':4,'coexistence':4,'near_miss':4},'probe_authorship':'Independent adjudicator before measurement','retrieval_measurements':0,'api_calls':0,'repository_files_written':0,'commits':0,'pushes':0,'consumer_results':{'production_catalog_rows':963,'changed_catalog_rows':1,'other_lines_unchanged':962,'actual_v6_target_exposed':True,'full_pack_equal':True,'candidate_equal':True,'overview_equal':True,'verified_detail_equal':True,'pack_id':v6['pack_id'],'source_compatible_subject':'elderly_commuter','source_compatible_location':'between_use_transit_interior','unchanged_companion_action':'waiting_train','unforced_context_checks_without_action_self_support':True,'original_frozen_core_and_policies_preserved':True},'maintenance':'Current record binds slots and matches historical pre-metadata snapshot. Immutable new record/reference plan was frozen before experiments; proposal is external only.','controls':'Initial singleton action was removed by explicit production authorial-opening projection. Premature event-lock diagnosis is explicitly superseded in control-diagnosis-correction.json. Event-open fixture was rejected by the unchanged validator. Two genuine compatible actions permit valid final consumer exposure.','freeze_sha256':(O/'frozen-proposal-sha256.txt').read_text().strip(),'inventory_sha256':sha((O/'source-inventory-and-decisions.json').read_bytes()),'limits':['Source/canonical Korean catalog consistency improvement only.','Unchanged English V6 is preservation, not uplift.','Natural retrieval, adoption, final prose and generated images unmeasured.','No regression suite or paid measurement performed; parent owns later acceptance/publication.']};save('summary.json',summary)
(O/'REPORT.md').write_text('''# Boundary-transition source scout\n\n22 previously unreviewed adjacent rows inspected: 4 liminal, 6 metamorphosis, 6 apotheosis and 6 katabasis. All 36 rows in the requested boundary extension were already individually reviewed and were excluded. Exact prior-ID evidence and later-scout checks are in prior-exclusions.json. All 22 selected current rows match their earlier authored snapshot in full; each has individual source pointers and a decision.\n\n21 rows keep authored meaning. One Korean field is a source-qualified proposal: waiting_in_between_use_space says “사용 흔적 없이” (without traces of use), while its English/embedding suspend expected active activity and the original research/profile retain just-before/just-after operational residue. The minimal replacement is “예상된 이용 활동 없이”. Independent Korean adjudication and the parent reviewer support this change. All other row fields and authored liminal specialization remain fixed.\n\nThe production Korean --list-tags action consumer changes exactly 1 of 963 lines; 962 others are identical. A valid genuine elderly_commuter plus between_use_transit_interior context, using the unchanged waiting_train action as a second source candidate, exposes the target in both production V6 packs. Candidate, complete pack, overview and hash-verified detail are identical, pack 9a9674d57112ec23. This is English preservation, not V6 uplift.\n\nThe first one-candidate fixture produced an explicit singleton_scene_candidate_would_create_fixed_prompt_influence authorial opening and omitted the action. The initial event-lock diagnosis was premature and is explicitly superseded in control-diagnosis-correction.json. A separately attempted event-open fixture was rejected by the unchanged core validator before generation. Both controls remain inspectable. The final replay uses the original mandatory locks, generated core, provenance, negative guard and soft policy unchanged; it does not use the action to satisfy its own context requirement.\n\nTwelve independent EN/KO probes (4 positive, 4 coexistence, 4 legitimate near misses) were frozen before the consumer experiments and remain unmeasured. No retrieval rank, paid call, repository edit, runtime/schema/weight/guard change, commit or push was performed.\n\nThe current metadata record binds slots and its authored hash matches the historical pre-metadata snapshot. maintenance-binding-plan.json records a new immutable versioned record/reference before experiments. Proposed raw source and metadata are saved externally only.\n\nMain artifacts: source-inventory-and-decisions.json; frozen-proposal-and-unmeasured-probes.json; maintenance-binding-plan.json; korean-catalog-consumer.json; actual-v6-preservation.json; two-action-fixture-freeze.json; control-diagnosis-correction.json. No natural retrieval/adoption, final composed prose, rendered-image or publication benefit is claimed.\n''')
# Include every artifact except this manifest itself; no subsequent artifact mutation.
manifest={str(p.relative_to(O)):sha(p.read_bytes()) for p in sorted(O.rglob('*')) if p.is_file() and p.name!='artifact-sha256.json'};save('artifact-sha256.json',manifest)
print(json.dumps({'status':summary['status'],'freeze_sha256':summary['freeze_sha256'],'inventory_sha256':summary['inventory_sha256'],'v6_report_sha256':sha((O/'actual-v6-preservation.json').read_bytes()),'artifact_manifest_sha256':sha((O/'artifact-sha256.json').read_bytes())},indent=2))
