import json,hashlib,copy
from pathlib import Path
R=Path('/workspace/scratch/ce8f20680f5a/image-prompt');O=R.parent/'daylong-progress/boundary-transition-source-scout';A=R/'skills/photo-prompt-image-generator/assets';B=R/'docs/research-evidence/photo-prompt'
sha=lambda b:hashlib.sha256(b).hexdigest();dig=lambda v:sha(json.dumps(v,ensure_ascii=False,sort_keys=True,separators=(',',':')).encode()); save=lambda n,v:(O/n).write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n')
p=A/'photo_prompt_imaginal_extension.json';raw=json.loads(p.read_text());before=next(r for r in raw['slots']['action'] if r['id']=='waiting_in_between_use_space');after=copy.deepcopy(before);after['ko']=before['ko'].replace('사용 흔적 없이','예상된 이용 활동 없이');assert before!=after
mp=B/'extension-maintenance'/ (raw['maintenance_ref']['record_id']+'.json');old=json.loads(mp.read_text());historical=B/'angle-motion-20260927/dynamic_composition/source_snapshot/assets'/p.name;assert sha(historical.read_bytes())==old['authored_source_sha256'];assert dig(old)==raw['maintenance_ref']['sha256']
prop=copy.deepcopy(raw);prop['slots']['action'][3]=after
record=copy.deepcopy(old);record['record_id']='photo_prompt_imaginal_extension_liminal_use_20261002';record['authored_source_sha256']=dig({k:v for k,v in prop.items() if k!='maintenance_ref'});newref={'contract_version':'photo-extension-maintenance-ref/v1','record_id':record['record_id'],'sha256':dig(record)};prop['maintenance_ref']=newref
save('proposed-versioned-maintenance-record.json',record);save('baseline-raw-extension.json',raw);save('proposed-raw-extension.json',prop)
maintenance={'documented_before_experiment':True,'current_record':str(mp.relative_to(R)),'current_record_file_sha256':sha(mp.read_bytes()),'current_ref':raw['maintenance_ref'],'current_authored_hash_recipe':'SHA256 of pre-metadata authored snapshot file bytes','historical_snapshot':str(historical.relative_to(R)),'historical_hash_matches':True,'authored_runtime_keys':old['runtime_keys'],'slots_bound_by_current_contract':True,'required_revision':'Preserve current immutable record; add the proposed versioned record and update only the source reference on later approved publication. No repository edits in scout.','proposed_record_destination':str((mp.parent/(record['record_id']+'.json')).relative_to(R)),'proposed_record':record,'proposed_reference':newref,'new_authored_hash_recipe':'Canonical JSON digest of revised source excluding maintenance_ref, matching maintained current-source record convention','proposed_authored_source_sha256':record['authored_source_sha256'],'unchanged_old_record':True}
save('maintenance-binding-plan.json',maintenance)
pairs=[
('p01','positive_suspended_station_passage','A lone person waits in a clean, well-maintained station passage. Lit arrows and orderly benches promise a connection onward, but the expected passenger movement has paused and the arrival route has no clear endpoint.','관리가 잘된 깨끗한 역 통로에서 한 사람이 홀로 기다린다. 불이 켜진 화살표와 가지런한 벤치는 다음 연결 경로를 암시하지만, 예상되는 승객의 이동은 멈춰 있고 도착 경로의 끝은 분명하지 않다.'),
('p02','positive_pool_threshold','One person waits between the changing rooms and a maintained indoor pool. The lights remain on and the route signs are intact, while the expected swimming activity is absent and the passage seems suspended between one use and the next.','탈의실과 관리가 잘된 실내 수영장 사이에서 한 사람이 기다린다. 조명은 켜져 있고 안내 표식은 온전하지만, 예상되는 수영 활동은 보이지 않으며 통로는 한 차례의 이용과 다음 이용 사이에 멈춰 있는 듯하다.'),
('c01','coexistence_footprints_after_service','A lone person waits in a maintained ferry-terminal passage after passenger service has paused. Fresh wet footprints remain beneath working lights, but no arriving passengers appear and the marked route continues toward an unresolved destination.','여객 운항이 잠시 멈춘 뒤, 관리가 잘된 여객선 터미널 통로에서 한 사람이 홀로 기다린다. 작동 중인 조명 아래에는 젖은 발자국이 선명하게 남아 있지만 도착하는 승객은 보이지 않고, 표시된 경로는 도착 지점이 분명하지 않은 곳으로 이어진다.'),
('c02','coexistence_recently_used_waiting_area','One person waits in a clean, maintained transfer waiting area. A recently emptied paper cup and a chair pulled slightly out of line show recent use, while the expected boarding activity is absent and the onward doorway offers no clear arrival point.','깨끗하게 관리된 환승 대기 공간에서 한 사람이 기다린다. 방금 비운 종이컵과 줄에서 조금 벗어난 의자가 최근의 이용 흔적을 보여 주지만, 예상되는 탑승 활동은 보이지 않고 다음 구간으로 이어지는 출입구 너머의 도착 지점도 분명하지 않다.'),
('n01','near_miss_ordinary_active_transit','A single passenger waits beside a clean station information board while commuters stream past, staff announce arrivals, and an open platform entrance leads directly to a train that is boarding.','한 승객이 깨끗한 역 안내판 옆에서 기다리는 동안 통근객들이 계속 지나가고 직원들은 도착 안내를 한다. 열린 승강장 입구는 승객이 탑승 중인 열차로 곧장 이어진다.'),
('n02','near_miss_ordinary_empty_bedroom','One person waits quietly in a tidy bedroom for a friend to return. The made bed, bedside lamp, and familiar personal belongings serve their ordinary domestic purposes; the room is simply unoccupied apart from the waiting person.','한 사람이 친구가 돌아오기를 기다리며 정돈된 침실에 조용히 머문다. 정리된 침대와 침대 옆 조명, 익숙한 개인 물건은 일상적인 가정용으로 쓰이고 있으며, 방에는 기다리는 사람 외에 다른 사람이 없을 뿐이다.')]
queries=[{'id':i+'_'+lang,'kind':kind,'language':lang,'query':q,'query_sha256':sha(q.encode()),'authorship':'independent adjudicator before any retrieval or zero-cost runtime experiment','expected':'Preserve authored lone-subject, maintained transition and absent expected active use; permit operational residue.' if not i.startswith('n') else 'Legitimate different scene; no new exclusion or guard. General waiting/cleanliness alone does not establish this liminal relation.'} for i,kind,en,ko in pairs for lang,q in [('en',en),('ko',ko)]]
files=[p,mp,A/'photo_prompt_tags.json',A/'photo_prompt_semantic_index.json',A/'photo_prompt_visual_obligations.json',A/'photo_prompt_visual_profile_index.json',A/'photo_prompt_quality_layers.json',A.parent/'scripts/prompt_generator.py',A.parent/'scripts/photo_candidate_semantics.py',A.parent/'scripts/compose_pack_view.py',R/'tests/photo_prompt_fixtures.py']
freeze={'status':'qualified_source_field_proposal_frozen_unmeasured','candidate_id':'slot:action:waiting_in_between_use_space','source':str(p.relative_to(R)),'source_pointer':'/slots/action/3','before':before,'proposal':after,'semantic_change_fields':['ko'],'before_row_sha256':dig(before),'proposal_row_sha256':dig(after),'adjudication':'Independent reviewer confirms no-traces wording removes material evidence while authored English/embedding suspend active use; temporal residue is explicitly retained by same liminal source contract. No supported trace-free variant exists for this row.','proposed_ko':after['ko'],'preserved_scope':['lone waiting subject','clean maintained route','route markers imply passage and destination','expected active use and arrival point absent','all EN/aliases/keywords/embedding/tags/weight/filters unchanged'],'authored_sources':[{'path':str((B/'imaginal-visual-semantics-20260901/source-research.md').relative_to(R)),'section':'3.6','line':85},{'path':str((A/'photo_prompt_visual_obligations.json').relative_to(R)),'pointer':'/profiles/173/semantics/component_semantics/groups/3'}],'queries':queries,'query_measurements':0,'api_calls':0,'maintenance_binding_plan_sha256':sha((O/'maintenance-binding-plan.json').read_bytes()),'repository_snapshot':{str(p.relative_to(R)):sha(p.read_bytes()) for p in files},'limits':['Source correction only, not yet publication-ready.','No retrieval, natural exposure, adoption, final composed prose or image benefit is claimed.']}
save('frozen-proposal-and-unmeasured-probes.json',freeze);(O/'frozen-proposal-sha256.txt').write_text(sha((O/'frozen-proposal-and-unmeasured-probes.json').read_bytes())+'\n')
print(json.dumps({'proposed_ko':after['ko'],'queries':len(queries),'freeze_sha256':sha((O/'frozen-proposal-and-unmeasured-probes.json').read_bytes()),'metadata_plan_frozen':True},ensure_ascii=False))
