from pathlib import Path
import json,subprocess,hashlib
p=Path(__file__).resolve().parent;read=lambda n:json.loads((p/n).read_text());c=read('composed_prompt.json');pack=read('candidate_pack.json');pack=pack[0] if isinstance(pack,list) else pack;r=read('native_result.json');snap=read('source_snapshot.json')
gargv=['skills/photo-prompt-image-generator/scripts/generate_photo_prompt.py','--request-envelope-json',str(p/'request_envelope.json'),'--authorial-core-json',str(p/'authorial_core.json'),'--embodiment-review-json',str(p/'embodiment_review.json'),'--candidate-pack-version','v6','--selection-mode','semantic','--creativity','0.5','--seed','7350812925794127079','--emit-candidate-pack','--n','1','--output-file',str(p/'candidate_pack.json')]
args=['.venv/bin/python','skills/photo-prompt-image-generator/scripts/record_image_run.py','--ts',r['saved_at_utc'],'--concept','하이 앵글','--prompt-en',c['prompt_en'],'--negative-en',c['negative_en'],'--seed','7350812925794127079','--attempt','1','--status','success','--image-path',r['saved_path'],'--tool','native_imagegen','--argv-json',json.dumps(gargv,ensure_ascii=False),'--pack-id',pack['pack_id'],'--chosen-candidate-ids-json',json.dumps(c['chosen_candidate_ids']),'--chosen-visual-concept-ids-json','[]','--composer','agent','--audit-status','pass','--arm-id','high_angle','--worktree-id','/Users/chasoik/Projects/image-prompt::angle-motion-20260927/high_angle','--skill-sha256',snap['skill_sha256'],'--source-ref',snap['source_ref'],'--candidate-pack-version','v6','--authorial-core-sha256',pack['authorial_core']['canonical_sha256'],'--intent-lock-sha256',pack['authorial_core']['intent_lock']['canonical_sha256'],'--reference-sha256','06d6c6feeed0d2397ec9562d46113cd221ac54a0e190295f0aa7f7868c22ece7','--image-call-count','1','--independent-no-cross-arm-inputs','--manifest',str(p/'run_manifest.json'),'--ledger',str(p/'image_runs.ndjson')]
assert not (p/'image_runs.ndjson').exists(), 'Do not append another row.'
rr=subprocess.run(args,text=True,capture_output=True);(p/'ledger_record_result.txt').write_text(rr.stdout+rr.stderr);print(rr.stdout+rr.stderr);rr.check_returncode()
ledger=[json.loads(x) for x in (p/'image_runs.ndjson').read_text().splitlines() if x.strip()];assert len(ledger)==1
f=read('core_freeze.json');sha=lambda name:hashlib.sha256((p/name).read_bytes()).hexdigest();checks={
 'request_envelope.json':('request_envelope_sha256',sha('request_envelope.json')),
 'authorial_core.json':('authorial_core_file_sha256',sha('authorial_core.json')),
 'test_case.json':('test_case_sha256',sha('test_case.json')),
 'embodiment_review.json':('embodiment_review_sha256',sha('embodiment_review.json')),
 'precore_feature_selection.json':('feature_selection_sha256',sha('precore_feature_selection.json')),
 'visual_feature_catalog.snapshot.json':('catalog_sha256',sha('visual_feature_catalog.snapshot.json')),
 'random_staging.json':('random_staging_sha256',sha('random_staging.json'))}
v={'contract_version':'angle-motion-freeze-verification/v1','all_unchanged':all(f[field]==actual for field,actual in checks.values()),'checks':{name:{'expected':f[field],'actual':actual,'unchanged':f[field]==actual} for name,(field,actual) in checks.items()},'image_call_count':1,'candidate_pack_count':1,'other_arm_outputs_used':False,'normalized_core_sha256':pack['authorial_core']['canonical_sha256'],'normalization_did_not_rewrite_original_core':True};assert v['all_unchanged'];(p/'freeze_verification.json').write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n');print(json.dumps({'ledger_rows':len(ledger),'run_id':ledger[0]['run_id'],'prompt_id':ledger[0]['prompt_id'],'freeze_unchanged':v['all_unchanged']},ensure_ascii=False,indent=2))
