from pathlib import Path
import json,hashlib,shutil
p=Path(__file__).resolve().parent
sha=lambda b:hashlib.sha256(b).hexdigest()
write=lambda name,data:p.joinpath(name).write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n')
e=json.loads(p.joinpath('request_envelope.json').read_text())
assert sha(p.joinpath('request_envelope.json').read_bytes())=='a2806f096c30f72af305d6ad95e67db40508e45c9f0caeaf6902989bb13cac1e'
cat=Path('skills/photo-prompt-image-generator/precore/visual_feature_catalog.json')
baseline='''One adult fictional woman is seated at a paper conservation worktable, pressing a large paper sheet flat with a soft broad brush in a single photographic scene. Use the supplied image as a reference for visible facial appearance and the dark bob with fine bangs. She wears a plain linen work shirt with rolled sleeves. The photograph captures one complete visible activity: her right hand holds the brush against the paper while her left palm steadies its far corner. The brush bristles make a broad contact patch on the sheet, with a slightly lifted edge flattening beside them. Her hips rest on a square wooden stool, both feet rest on the floor, and her torso leans a little forward within comfortable reach of the table. A metal ruler and shallow pigment dish sit apart from the paper, while stacked drying boards and a window sill give the compact studio a used working character. Diffuse north-window daylight reveals the paper fibers, linen folds, and soft hand shadows. The elevated oblique viewpoint looks downward across the subject and the work surface. The camera is above her head and angled downward; the crown of her head, shoulder tops, the broad tabletop, and the floor around the stool are visible together. In this perspective her upper body appears nearer and larger than her knees and feet, which recede toward the floor. An oblique view retains the front edge of the table and a partial view of her face. The rectangular window frame remains upright in the image, giving the downward projection a stable orientation. Show the hands, brush contact, paper, stool, and feet together in a coherent environmental photograph.'''
baseline=' '.join(baseline.split())
cam={
 'elevated_position':'The camera is above her head and angled downward',
 'top_surfaces':'the crown of her head, shoulder tops, the broad tabletop, and the floor around the stool are visible together',
 'depth_projection':'her upper body appears nearer and larger than her knees and feet, which recede toward the floor',
 'oblique_boundary':'An oblique view retains the front edge of the table and a partial view of her face'
}
anchors=[
 {'anchor_id':'core_concept','source_text':'하이 앵글','dimension':'concept','prompt_evidence':'The elevated oblique viewpoint looks downward across the subject and the work surface'},
 {'anchor_id':'core_subject','source_text':e['active_spans'][0]['text'],'dimension':'subject','prompt_evidence':'One adult fictional woman'},
 {'anchor_id':'core_event','source_text':e['active_spans'][2]['text'],'dimension':'event','prompt_evidence':'The photograph captures one complete visible activity'},
 {'anchor_id':'reference_use','source_text':e['active_spans'][0]['text'],'dimension':'reference_use','prompt_evidence':'Use the supplied image as a reference for visible facial appearance and the dark bob with fine bangs'},
 {'anchor_id':'camera_downward','source_text':'하이 앵글','dimension':'camera','prompt_evidence':cam['elevated_position']}
]
core={
 'contract_version':'photo-authorial-core/v3','provenance':'agent_prepack','source_request':e['request_text'],
 'interpreted_intent':'An independent photographic test of a clearly elevated, downward-looking oblique camera angle using the provided face and hair appearance reference. The setting, action, props and light are independently randomized agent staging, not requester definitions.',
 'subject':'One adult fictional woman using the supplied reference only for visible face and hair appearance.',
 'setting':'A compact paper conservation studio with a worktable, square stool, drying boards, window sill, metal ruler and shallow pigment dish.',
 'event':'Seated with both feet supported, she presses a paper sheet flat with a right-hand brush while her left palm steadies a far corner.',
 'visual_priorities':['An elevated oblique viewpoint visibly looks down across the woman and table.','Crown, shoulder tops, tabletop and surrounding floor jointly reveal downward projection.','Upper body projects nearer and larger while knees and feet recede.','Brush bristles, right hand and paper form readable contact while the left palm stabilizes the sheet.','Her seated support and both feet remain visible within the complete work scene.'],
 'baseline_prompt_en':baseline,'user_definitions':[],
 'interpretation_provenance':[
  {'term':'하이 앵글','source_text':'하이 앵글','basis':'agent_general_knowledge','resolution':'A camera located above the subject and directed downward, visibly exposing top surfaces and a receding lower body in an oblique projection.','sources':[]},
  {'term':'reference context','source_text':e['active_spans'][0]['text'],'basis':'request_context','resolution':'Use the supplied reference photograph for its visible face and hair appearance in the new image test. No biography or real identity is inferred.','sources':[]},
  {'term':'test workflow','source_text':e['active_spans'][2]['text'],'basis':'request_context','resolution':'This arm is one of three independent topic tests; preserve the first image outcome and separately assess focal keyword and complete scene.','sources':[]}
 ],'unresolved_ambiguities':[],'user_exclusions':[],'runtime_forbidden_labels':[],
 'intent_lock':{'contract_version':'photo-intent-lock/v1','priority':'requesting_user','semantic_anchors':anchors,'locked_dimensions':['concept','subject','event','reference_use','camera'],'open_dimensions':['setting','action','pose','framing','composition','lighting','color','material','atmosphere','style']},
 'semantic_assertions':[{'assertion_id':'high_angle_camera','dimension':'camera','polarity':'required','source_span_ids':['topic'],'affected_dimensions':['camera','concept'],'axes':{'camera_position':'above_subject_head','optical_direction':'downward','projection':'oblique_elevated','observable_components':['crown_and_shoulder_tops','broad_tabletop_and_floor','upper_near_lower_receding'],'boundary':'oblique_face_and_table_front_edge_retained'},'evidence':cam}],
 'request_lineage':None,'style':{'domain':'lifestyle','family':'observational environmental photography','evidence':['paper fibers and linen folds','soft hand shadows in diffuse daylight']},'variation_key':'high_angle-7350812925794127079'
}
write('authorial_core.json',core); p.joinpath('baseline_prompt_en.txt').write_text(baseline+'\n')
review={'contract_version':'photo-embodiment-review/v1','provenance':'agent_prepack','prompt_sha256':sha(baseline.encode()),'scope':'body_action','summary':'Ordinary adult human body seated on a stool, feet on floor, two connected arms reaching a nearby sheet, right-hand brush in material contact and left palm stabilizing it. Actor-relative right/left are body sides, not screen sides.','checks':{
 'body_ownership':{'status':'supported','reason':'Each hand belongs to the one visible actor; the brush is gripped by her right hand and the left palm stabilizes the paper.','prompt_evidence':['her right hand holds the brush against the paper','her left palm steadies its far corner']},
 'joint_chain_and_reach':{'status':'supported','reason':'A small forward torso lean brings both forearms to the nearby tabletop within ordinary elbow and wrist reach.','prompt_evidence':['her torso leans a little forward within comfortable reach of the table']},
 'support_and_balance':{'status':'supported','reason':'Seat bears the hips while both feet provide stable floor contact; the working hands need not bear body weight.','prompt_evidence':['Her hips rest on a square wooden stool','both feet rest on the floor']},
 'contact_and_space':{'status':'supported','reason':'Brush bristles contact the paper sheet; the ruler and dish occupy separate space, and one corner remains accessible to the left palm.','prompt_evidence':['The brush bristles make a broad contact patch on the sheet','A metal ruler and shallow pigment dish sit apart from the paper']},
 'visibility_and_projection':{'status':'supported','reason':'Elevated oblique view reveals hands and top surfaces while retaining the face, table front edge, seat and floor-supported feet.','prompt_evidence':['An oblique view retains the front edge of the table and a partial view of her face','Show the hands, brush contact, paper, stool, and feet together']}
}}
write('embodiment_review.json',review)
rows=[
 ('feature.situation','agent_visual_choice',[] ,None,None,'The image needs one complete legible working moment rather than isolated camera tags.','pressing a large paper sheet flat with a soft broad brush in a single photographic scene'),
 ('feature.subject','request_derived',['reference_context'],None,'The supplied photograph provides observable facial and hair guidance for a fictional adult actor.','Retain reference appearance through visible face and hair rather than inferred identity.','Use the supplied image as a reference for visible facial appearance and the dark bob with fine bangs'),
 ('feature.location','agent_visual_choice',[],None,None,'A table-based studio supplies broad top planes for downward projection and a coherent action setting.','at a paper conservation worktable'),
 ('feature.action','agent_visual_choice',[],None,None,'Brush pressure and left-hand stabilization make the randomized action visible in one instant.','her right hand holds the brush against the paper while her left palm steadies its far corner'),
 ('feature.pose','agent_visual_choice',[],None,None,'A seated posture provides clear hip and floor supports, with a plausible reach to the paper.','Her hips rest on a square wooden stool, both feet rest on the floor'),
 ('feature.props','agent_visual_choice',[],None,None,'Separate ruler and dish enrich the scene while preserving room for both hands and sheet.','A metal ruler and shallow pigment dish sit apart from the paper'),
 ('feature.lighting_source','agent_visual_choice',[],None,None,'Window diffusion reveals paper fibers and soft contact shadows without obscuring the top planes.','Diffuse north-window daylight reveals the paper fibers, linen folds, and soft hand shadows'),
 ('feature.camera_angle','explicit_request',['topic'],'하이 앵글',None,'The requested camera meaning needs an unmistakably elevated downward-looking oblique view.','The camera is above her head and angled downward'),
 ('feature.spatial_depth','request_derived',['topic'],None,'A high viewpoint projects the upper body nearer and the lower body receding toward visible ground.','Relative body scale and floor depth distinguish elevation from a tilted eye-level photograph.','her upper body appears nearer and larger than her knees and feet, which recede toward the floor')
]
selection={'contract_version':'photo-precore-feature-selection/v1','request_id':e['request_id'],'active_span_ids':[s['span_id'] for s in e['active_spans']],'catalog_path':str(cat),'catalog_schema_version':'photo-precore-feature-catalog/v1','catalog_sha256':sha(cat.read_bytes()),'request_sha256':e['request_sha256'],'baseline_prompt_sha256':sha(baseline.encode()),'selected':[dict(zip(['category_id','basis','source_span_ids','source_text','derivation','reason','baseline_evidence'],r)) for r in rows]}
write('precore_feature_selection.json',selection); shutil.copyfile(cat,p/'visual_feature_catalog.snapshot.json')
test={'contract_version':'angle-motion-pixel-test/v1','arm':'high_angle','frozen_before_generation':True,'definition_origin':'agent_general_knowledge','requester_definition_present':False,'all_of_policy':'partial_is_fail','topic_components':[
 {'id':'elevated_downward_projection','required':True,'criterion':'The joint visible projection reads as a camera above the subject looking down, rather than eye-level with a high background.','evidence_expected':'Crown and shoulder tops seen from above alongside a broad tabletop and floor.'},
 {'id':'multiple_top_planes','required':True,'criterion':'Crown or hair top, shoulders, tabletop and surrounding floor expose upper surfaces together.','evidence_expected':'Independent top surfaces reinforce one downward projection.'},
 {'id':'body_depth_recession','required':True,'criterion':'Upper body is visually nearer/larger, with knees and feet receding toward the ground.','evidence_expected':'Qualitative relative scale and foreshortening; actual camera height is not measurable from the generated image.'},
 {'id':'oblique_not_orthographic_overhead','required':True,'criterion':'Some face and the table front edge remain visible while the camera looks down.','evidence_expected':'A sloped oblique view rather than a flat plan view.'},
 {'id':'orientation_not_dutch_substitute','required':True,'criterion':'A stable vertical reference and downward projection distinguish high angle from merely tilting the frame.','evidence_expected':'Window frame approximately upright and depth projection still downward.'}
 ],'confusion_boundaries':['eye-level viewpoint with subject lowering her head','pure vertical overhead or flat plan view','Dutch roll without elevated viewpoint','wide lens making head larger without multiple downward-looking planes','a label or prompt mention without visible perspective'],'full_scene_components':[
 {'id':'reference_face_hair','criterion':'Visible face and dark bob with fine bangs provide qualitative appearance-reference correspondence; no identity claim.'},
 {'id':'paper_studio','criterion':'Paper worktable, drying boards and window sill form the studio setting.'},
 {'id':'brush_press_and_stabilize','criterion':'Right hand grips brush contacting paper, left palm steadies far corner, broad bristle patch and flattening edge are legible.'},
 {'id':'seated_support','criterion':'Hips sit on square wooden stool, both feet visibly contact floor, connected torso/arms plausibly reach sheet.'},
 {'id':'props_and_light','criterion':'Separate metal ruler and shallow pigment dish are visible; soft window light reveals paper/linen texture.'},
 {'id':'whole_frame_visibility','criterion':'Hands, brush contact, paper, stool and feet are visible together.'}
 ],'embodiment_components':['body_ownership','joint_chain_and_reach','support_and_balance','contact_and_space','visibility_and_projection'],'user_aesthetic_acceptance':'pending','review_scale':['original','reduced'],'runtime_measurement_limit':'A generated perspective can support an elevated-view interpretation, not a measured real camera height or focal length.'}
write('test_case.json',test)
freeze={'contract_version':'angle-motion-core-freeze/v1','arm':'high_angle','seed':json.loads(p.joinpath('random_staging.json').read_text())['seed'],'request_envelope_sha256':sha(p.joinpath('request_envelope.json').read_bytes()),'request_text_sha256':sha(e['request_text'].encode()),'authorial_core_file_sha256':sha(p.joinpath('authorial_core.json').read_bytes()),'baseline_prompt_sha256':sha(baseline.encode()),'semantic_assertion_evidence_sha256':sha(json.dumps(cam,ensure_ascii=False,sort_keys=True,separators=(',',':')).encode()),'topic_criterion_strings_sha256':sha(json.dumps(test['topic_components'],ensure_ascii=False,sort_keys=True,separators=(',',':')).encode()),'test_case_sha256':sha(p.joinpath('test_case.json').read_bytes()),'embodiment_review_sha256':sha(p.joinpath('embodiment_review.json').read_bytes()),'feature_selection_sha256':sha(p.joinpath('precore_feature_selection.json').read_bytes()),'catalog_sha256':sha(cat.read_bytes()),'random_staging_sha256':sha(p.joinpath('random_staging.json').read_bytes()),'reference_image_sha256':'06d6c6feeed0d2397ec9562d46113cd221ac54a0e190295f0aa7f7868c22ece7','input_isolation':{'allowed_inputs':['delegation_execution_brief','request_envelope.json','supplied_reference_image_viewed_original','general_knowledge','skills/photo-prompt-image-generator/SKILL.md','/Users/chasoik/.codex/skills/.system/imagegen/SKILL.md','skills/photo-prompt-image-generator/precore/visual_feature_catalog.json'],'project_candidate_profile_code_assets_previous_experiment_access_before_freeze':False,'other_arm_access':False,'task_brief_used_as_requester_text':False,'source_request_is_entire_envelope_request_text':True},'precore_validator':'pending'}
write('core_freeze.json',freeze)
print('Precore written. Baseline words:',len(baseline.split()))
