from pathlib import Path
import json,hashlib,datetime
p=Path(__file__).resolve().parent; read=lambda n:json.loads(p.joinpath(n).read_text()); write=lambda n,d:p.joinpath(n).write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n');sha=lambda b:hashlib.sha256(b).hexdigest()
result=read('native_result.json');test=read('test_case.json'); comp=read('composed_prompt.json');pack=read('candidate_pack.json');pack=pack[0] if isinstance(pack,list) else pack
native_e={
 'elevated_downward_projection':'The large visible tabletop, the crown of the bob, the upper shoulder surfaces and the floor behind/beside the seated actor jointly read as an elevated camera aimed downward. The viewpoint is clearly above her face even though she lifts her eyes to it.',
 'multiple_top_planes':'Hair crown is visible at the upper center, shoulder/shirt tops occupy the middle, paper and wooden tabletop spread across the lower-left, and floor texture is exposed at right and beneath the stool.',
 'body_depth_recession':'The head and upper torso dominate the upper-middle frame, while knees and the two shoes taper into the lower-right floor space. This qualitative recession agrees with the downward view; it is not a measured camera height.',
 'oblique_not_orthographic_overhead':'Her face, chest-facing shirt plane, near/front table edge and stool side are all visible, so the camera retains an oblique side component instead of producing a flat overhead plan.',
 'orientation_not_dutch_substitute':'The upright wall joint and drying-rack posts provide stable vertical references. Table and window sill diagonals arise from perspective; frame roll is not carrying the high-angle effect.'}
reduced_e={
 'elevated_downward_projection':'At 420 px the head-top, broad paper table and surrounding floor remain visible together, making elevation read immediately.',
 'multiple_top_planes':'Crown, shoulder top, table plane and floor survive reduction as separate upper-facing surfaces.',
 'body_depth_recession':'Head and shoulders remain large while both shoes appear smaller and farther below, maintaining qualitative body depth.',
 'oblique_not_orthographic_overhead':'The face and table front remain recognizable at reduced size, preserving the oblique boundary.',
 'orientation_not_dutch_substitute':'Rack posts remain broadly upright at thumbnail scale; the scene reads as looking down, not merely rotated.'}
kw={'contract_version':'angle-motion-keyword-pixel-results/v1','arm':'high_angle','topic':'하이 앵글','source_test_case_sha256':sha((p/'test_case.json').read_bytes()),'source_core_file_sha256':sha((p/'authorial_core.json').read_bytes()),'result_image':result['saved_path'],'result_sha256':result['sha256'],'all_of_policy':'partial_is_fail','components':[{'component_id':c['id'],'criterion':c['criterion'],'status':'pass','scale_results':{'original':{'status':'pass','evidence':native_e[c['id']]},'reduced_420px':{'status':'pass','evidence':reduced_e[c['id']]}}} for c in test['topic_components']],'passed_components':5,'required_components':5,'all_of_result':'pass','measurement_limit':'The pixels support a qualitative elevated downward-looking viewpoint. Real camera elevation, exact pitch angle and focal length are not established.','focal_semantic_prompt_coverage':'required high_angle_camera assertion, four immutable literal evidence fields preserved; source contract ea5f0e9e0f9c8f1af873744ab6927f55611ac6bcbe97c7c7c347c0c8a6b64b98','user_aesthetic_acceptance':'pending','reviewer':'agent high_angle'}
write('keyword_pixel_results.json',kw)
full={
 'reference_face_hair':('pass','The generated actor has a short dark bob with fine bangs, dark visible eyes, and a softly rounded facial outline broadly corresponding to the supplied appearance reference. This is qualitative appearance correspondence, not identity verification.'),
 'paper_studio':('pass','A large fibrous sheet lies on a used wooden worktable; a multi-level paper drying rack and the window sill are visible in the same studio.'),
 'brush_press_and_stabilize':('fail','The right hand grips a broad brush with bristles touching the paper. The left hand instead uses fingertips along the near/right paper edge; its palm is raised and does not press the far corner as frozen. The sheet is broadly flat, but a lifted edge flattening immediately beside the bristles is not legible. These missing simultaneous components make the complete action fail.'),
 'seated_support':('pass','The hips sit on the square wooden stool visible at right, the trouser legs descend coherently beneath the apron, and both shoes meet the floor. The torso leans toward a reachable table surface.'),
 'props_and_light':('pass','A metal ruler and shallow blue pigment dish occupy the left table area, away from the brush-paper contact. Window daylight and soft material shadows reveal paper fibers and linen folds; compass direction is not verifiable from the image.'),
 'whole_frame_visibility':('pass','Both hands, brush contact, paper sheet, stool and both shoes are included in the same saved frame. The exact wrong left-hand contact is visible rather than concealed.')}
emb={
 'embodiment_body_ownership':{'status':'pass','evidence':'Both forearms connect through rolled sleeves to the one actor. The right hand visibly grips the brush, and the left fingers belong to the extended left arm at the paper edge.'},
 'embodiment_joint_chain_and_reach':{'status':'pass','evidence':'Connected upper arms, elbows, forearms and wrists reach the nearby tabletop with a moderate forward lean; no impossible reach is required by the rendered posture.'},
 'embodiment_support_and_balance':{'status':'pass','evidence':'The hips are seated on the visible wooden stool and both shoes contact the floor, forming a coherent seated support state while the hands work.'},
 'embodiment_contact_and_space':{'status':'fail','evidence':'Brush bristles meet the paper and the ruler/dish have separate space. However, the left palm remains lifted while fingertips grip the near edge, rather than the reviewed left-palm contact at the far corner. The intended simultaneous stabilizing contact did not survive.'},
 'embodiment_visibility_and_projection':{'status':'pass','evidence':'The oblique high view exposes both working hands, brush-paper boundary, table front, stool, legs and floor-supported shoes. It makes the critical contact difference assessable.'}}
review={'schema_version':'moe-render-review/v1','contract_version':'photo-embodiment-preflight/v1','pack_id':pack['pack_id'],'reviewer':'agent high_angle pixel review','result_image':result['saved_path'],'result_sha256':result['sha256'],'source_embodiment_preflight_sha256':pack['embodiment_preflight']['canonical_sha256'],'hard_gates':emb,'user_judgment':{'baseline_available':False,'genuinely_moe':'pending','better_than_baseline':'not_applicable','source':'not_yet_received','evidence':''},'user_aesthetic_acceptance':'pending','review_scales':{'original':{'width':1237,'height':1272,'source':'native tool original displayed; saved file has identical SHA-256'},'reduced':{'path':str(p/'review_420px.png'),'long_edge':420,'sha256':sha((p/'review_420px.png').read_bytes())}},'supplemental_observations':{'keyword_results_path':str(p/'keyword_pixel_results.json'),'full_scene_all_of':'fail','full_scene_components':[{'component_id':c['id'],'criterion':c['criterion'],'status':full[c['id']][0],'evidence':full[c['id']][1]} for c in test['full_scene_components']],'selected_optional_visual_concepts':[],'effective_visual_gates':[],'generic_render_repair':'not_applicable: the initial run has no render_repair contract; only the exact composed embodiment gates are active','minor_nonblocking_changes':['An apron was added over the linen shirt.','The actor addresses the camera instead of looking only at the work.'],'measurement_limit':kw['measurement_limit']}}
write('pixel_review.json',review)
summary={'contract_version':'angle-motion-pixel-summary/v1','keyword_all_of':'pass','full_scene_all_of':'fail','embodiment_all_of':'fail','all_requested_and_frozen_conditions':'fail','failed_components':['full_scene:brush_press_and_stabilize','embodiment_contact_and_space'],'user_aesthetic_acceptance':'pending','prompt_audit':'pass','runtime_request_audit':'pass','native_generation_outcome':'success','file_preservation':'success','note':'These statuses answer different questions and are not interchangeable.'};write('pixel_status_summary.json',summary)
print(json.dumps(summary,ensure_ascii=False,indent=2))
