"""Finish methods after the timed-out fixture; do not rerun its expensive prefix."""
from pathlib import Path
import json,re,subprocess,sys,concurrent.futures
ROOT=Path.cwd();OUT=ROOT/'docs/research-evidence/photo-prompt/model-editorial-professional-implementation-20260912';PRE=OUT/'timeout-resume-test_photo_visual_obligations';DEST=OUT/'visual-tail';DEST.mkdir(exist_ok=True);plan=json.loads((PRE/'plan.json').read_text());base=Path(json.loads((OUT/'head-baseline.json').read_text())['path']);prefixes={}
for label in ['current','head']:
 log=(PRE/f'{label}.log').read_text();headers=list(re.finditer(r'^\w+ \((tests\.[^)]+)\) \.\.\.',log,re.M));last=headers[-1];prefix=log[:last.start()];prefixes[label]={'completed_ids':[h.group(1) for h in headers[:-1]],'unresolved_id':last.group(1),'failed_case_lines':[re.sub(r' \.\.\. (?:FAIL|ERROR)$','',line.strip()) for line in prefix.splitlines() if re.search(r' \.\.\. (?:FAIL|ERROR)$',line)]};(DEST/f'{label}-completed-prefix.log').write_text(prefix)
assert prefixes['current']['unresolved_id']==prefixes['head']['unresolved_id'];blocked=prefixes['current']['unresolved_id'];targets=[i for i in plan['target_ids'] if i not in set(prefixes['current']['completed_ids'])|{blocked}];(DEST/'plan.json').write_text(json.dumps({'prefix_evidence':prefixes,'unresolved_test_id':blocked,'target_ids':targets,'target_count':len(targets),'reason':'A following test header proves the preceding test method returned. Preserve its printed failure-case lines; run only not-yet-started tail methods.'},indent=2)+'\n');print('tail',len(targets),flush=True)
def run(label,cwd):
 try:
  p=subprocess.run([sys.executable,'-m','unittest',*targets,'-v'],cwd=cwd,text=True,stdout=subprocess.PIPE,stderr=subprocess.STDOUT,timeout=900);log=p.stdout;rc=p.returncode
 except subprocess.TimeoutExpired as e:log=e.stdout.decode() if isinstance(e.stdout,bytes) else e.stdout or '';rc=124
 (DEST/f'{label}.log').write_text(log);counts=re.findall(r'Ran (\d+) tests?',log);r={'returncode':rc,'reported_test_count':int(counts[-1]) if counts else None,'failures':re.findall(r'^(?:FAIL|ERROR): ([^\n]+)',log,re.M)};(DEST/f'{label}.json').write_text(json.dumps(r,indent=2)+'\n');print(label,r['returncode'],r['reported_test_count'],flush=True);return r
with concurrent.futures.ThreadPoolExecutor(max_workers=2) as pool:
 a=pool.submit(run,'current',ROOT);b=pool.submit(run,'head',base);current=a.result();head=b.result()
complete=current['reported_test_count']==len(targets) and current['returncode'] in (0,1);finished_count=plan['completed_pass_or_skip_count']+len(prefixes['current']['completed_ids'])+(current['reported_test_count'] or 0)
summary={'module':plan['module'],'all_module_methods_finished':False,'tail_finished':complete,'unresolved_test_ids':[blocked],'total_unique_methods_completed':finished_count,'original_pass_or_skip_count':plan['completed_pass_or_skip_count'],'completed_prefix_count':len(prefixes['current']['completed_ids']),'tail':current,'head_tail':head,'current_failures':prefixes['current']['failed_case_lines']+current['failures'],'baseline_failures':prefixes['head']['failed_case_lines']+head['failures'],'comparison_scope':'completed_methods_only_excludes_timed_out_fixture','baseline_returncode':head['returncode'],'same_failure_names':prefixes['current']['failed_case_lines']==prefixes['head']['failed_case_lines'] and current['failures']==head['failures'],'source_timeout_summaries_preserved':True}
(DEST/'summary.json').write_text(json.dumps(summary,indent=2)+'\n');print('completed',finished_count,'of',plan['expected_total_methods'],'same failures',summary['same_failure_names'],flush=True)
