import json,pathlib,hashlib,copy
p=pathlib.Path(__file__).resolve().parent; root=p.parent; pack=json.loads((p/'candidate_pack.json').read_text())[0];core=pack['authorial_core'];b=core['baseline_prompt_en']
b=b.replace('She wears a charcoal weatherproof coat over a cream knit top, straight dark trousers and practical ankle boots.','She wears a charcoal coat, cream knit top, dark trousers and ankle boots.')
b=b.replace('Her torso turns a little toward the camera, with a quiet attentive expression.','Her torso turns slightly toward the camera.')
b=b.replace('Keep the ordinary infrastructure legible across the image, with believable material surfaces and continuous geometry. ','').replace('The result should feel like a candid photograph made at an actual working transit stop.','')
infra=['a drain cover fits flush within the walking surface','a service pipe follows the wall on visible supports','the fixtures leave a continuous passage through the space']
mat='The shelter base has broad matte concrete shading beside a narrow steel highlight and transparent glass carrying a pale sky reflection.'
foc='Her face and handrail contact are crisp, shelter posts remain recognizable at middle distance, and apartment windows soften progressively farther uphill.'
joint='These material responses and the depth of focus belong to the same continuous landing-to-shelter view.'
prompt=' '.join((b+' At the landing, '+infra[0]+'; along the retaining wall, '+infra[1]+'; '+infra[2]+'. '+mat+' '+foc+' '+joint+' Frame horizontally at chest height with a 35mm lens, placing her just right of center.').split())
comp=json.loads((root/'composed_prompt.json').read_text());comp.update(pack_id=pack['pack_id'],prompt_en=prompt,negative_en=pack['negative_en'],chosen_candidate_ids=['bundle:rbb_surface_focus'],chosen_visual_concept_ids=['visual-concept:rb_infrastructure_attachment'])
comp['candidate_interpretations']=[{'candidate_id':'bundle:rbb_surface_focus','artistic_interpretation':'Resolve the shelter concrete, steel and glass as distinct surfaces while the woman stays legible within receding transit architecture.','transformation':'Tie surface reflectance to the particular shelter base and let uphill apartment detail diminish with distance within the same view.','prompt_evidence':mat,'component_evidence':{'rb_material_response_contrast_component':mat,'rb_readable_environment_focus_component':foc},'relation_evidence':{'rbb_surface_focus_joint':joint}}]
comp['visual_obligation_evidence']={'rb_infrastructure_attachment':{f'component_{i+1}_phrase':v for i,v in enumerate(infra)}}
comp['authorial_core_binding']['authorial_decisions']=[{'dimension':'camera','decision':foc,'rationale':'Control depth of focus so face, contact and transit context stay assessable without uniform sharpness.'},{'dimension':'material','decision':mat,'rationale':'Resolve the three existing shelter materials through different responses to the same overcast sky.'}]
comp['semantic_clarification_decisions']=[]
for r in pack['semantic_clarification']['candidates']:
 apply=r['required_in_final_prompt'] or r.get('profile_id')=='rb_infrastructure_attachment'
 comp['semantic_clarification_decisions'].append({'clarification_id':r['id'],'decision':'applied' if apply else 'rejected','rationale':'Preserve the frozen transit scene and clarify its already present ordinary infrastructure.' if apply else 'This optional body, behavioral, or rendering concept is outside the frozen natural transit scene.','prompt_evidence':infra[0] if r.get('profile_id')=='rb_infrastructure_attachment' else 'one adult woman at a terraced hillside bus interchange on an overcast morning after rain' if apply else ''})
review=copy.deepcopy(json.loads((root/'embodiment_review.json').read_text()));review.update(provenance='agent_postcomposition',prompt_sha256=hashlib.sha256(prompt.encode()).hexdigest(),summary='Rechecked the final prompt after adding infrastructure and optical/material clauses. Both arms keep separate targets, both boots share the broad landing, the service pipe lies along the retaining wall and leaves the passage clear, and chest-height full-figure view preserves contact visibility.')
comp['embodiment_review']={'source_contract_sha256':pack['embodiment_preflight']['canonical_sha256'],'review':review}
(p/'composed_prompt.json').write_text(json.dumps(comp,ensure_ascii=False,indent=2)+'\n');(p/'final_prompt.txt').write_text(prompt+'\n')
exp={'phase':'calibrated_revision_2_after_first_pack_zero_exposure','pack_id':pack['pack_id'],'same_frozen_core_sha256':core['canonical_sha256'],'same_baseline_prompt_sha256':hashlib.sha256(core['baseline_prompt_en'].encode()).hexdigest(),'seed':1751180039,'candidate_pack_calls_total':2,'new_standalone_candidate_count':0,'new_profile_count':1,'new_bundle_count':6,'selected_profile_ids':['rb_infrastructure_attachment'],'selected_bundle_ids':['rbb_surface_focus'],'selected_component_ids':['rb_material_response_contrast_component','rb_readable_environment_focus_component'],'partial_is_fail':True,'original_failure':'../exposure_report.json','not_independent_holdout':True}
(p/'exposure_report.json').write_text(json.dumps(exp,indent=2)+'\n');print('WORDS',len(prompt.split()))
