import json,pathlib,hashlib,subprocess,datetime,sys
p=pathlib.Path(__file__).resolve().parent; root=p.parent; project=p.parents[4]; image=p/'generated.png'; pack=json.loads((p/'candidate_pack.json').read_text())[0]; comp=json.loads((p/'composed_prompt.json').read_text());aud=json.loads((p/'composed_audit.json').read_text());req=json.loads((p/'render_request.json').read_text());sha=lambda x:hashlib.sha256(x.read_bytes()).hexdigest()
evidence={
'vo_rb_infrastructure_attachment_1':'At native and 512px thumbnail, the long slotted drainage grate spans the foreground within the paving plane; its rim meets the walking surface without a raised floating edge.',
'vo_rb_infrastructure_attachment_2':'At both scales, the silver service pipe runs along the upper right retaining wall and turns downward; dark clamp brackets visibly fasten it to that wall at intervals.',
'vo_rb_infrastructure_attachment_3':'At both scales, the grate lies underfoot and the pipe remains against the wall; the broad landing and stair passage stay visibly continuous around the woman.',
'embodiment_body_ownership':'Native view shows each sleeve connected to one arm; screen-right left hand touches the rail, and screen-left right hand owns the tote straps. Both legs terminate in visible boots.',
'embodiment_joint_chain_and_reach':'The left forearm extends naturally outward from the coat sleeve with a modest elbow bend to the side rail. Right arm hangs beside the body to reachable tote handles.',
'embodiment_support_and_balance':'Both boot soles meet the same broad landing just behind the drain. The legs support an upright body, with the side-rail touch providing light supplementary support.',
'embodiment_contact_and_space':'Left fingers rest and partly curl over the rail with coherent contact; right fingers meet the tote straps. Neither object crosses a disconnected limb and there is clear space beside the feet.',
'embodiment_visibility_and_projection':'The full figure includes both boots and both arm targets. Chest-height projection makes the rail contact and tote ownership assessable at native scale.'}
review={'schema_version':'moe-render-review/v1','contract_version':'photo-visual-obligations/v1','pack_id':pack['pack_id'],'reviewer':'independent arm-a agent','result_image':str(image),'result_sha256':sha(image),'reviewed_scales':{'native':'1536x1024','thumbnail':'512x341','thumbnail_path':str(p/'review-thumbnail.png')},'partial_is_fail':True,'hard_gates':{k:{'status':'pass','evidence':v} for k,v in evidence.items()},'user_judgment':{'baseline_available':False,'genuinely_moe':'not_applicable','better_than_baseline':'not_applicable','source':'not_yet_received','evidence':'No direct requesting-user preference or acceptance has been received.'},'boundary':'Agent inspection of this saved image; neither capture provenance nor actual personal identity is established.'}
(p/'strict_pixel_review.json').write_text(json.dumps(review,indent=2)+'\n')
tests=[('A1','pass','The woman has the reference-consistent oval face, dark eyes, full lips and long dark waves; face remains visible. This is visual likeness assessment only.'),('A2','pass','Full-body support and actor-relative left-hand rail/right-hand tote ownership survive; both soles share the landing.'),('A3','pass','Foreground drainage and landing, central rising stairs and glazed shelter, upper retaining wall/hillside facades form separate coherent spatial planes; visible buses confirm working transit use.'),('A4','pass','Concrete wall/stair planes, tile seams, metal posts and glazed roof panels remain distinct; rail/posts and stair treads have coherent perspective and plausible human scale.'),('A5','pass','Wet darker paving and shallow puddling collect beside the drain, while shelter glass has pale sky reflection and visible structural transmission. Woman and surroundings share diffuse overcast illumination, with practical shelter lights locally visible.')]
bundle=[('rb_material_response_contrast_component','pass','Concrete stair/retaining and shelter support surfaces have broad subdued shading, adjacent steel rails/posts show narrow highlights, and shelter glass transmits frame/light structures while reflecting the gray sky. All material owners coexist in this view.'),('rb_readable_environment_focus_component','pass','Face, clothing edges and hand-to-rail contact are crisp; middle-distance shelter posts remain recognizable; distant hillside apartment windows lose fine detail compared with foreground rails and clothing.'),('rbb_surface_focus_joint','pass','The material responses and focus progression connect from woman and landing through the same shelter to the uphill apartments; they are not separate scenes or inserted patches.')]
report={'schema_version':'arm-render-test-results/v1','pack_id':pack['pack_id'],'result_image':str(image),'result_sha256':sha(image),'partial_is_fail':True,'preregistered_tests':[{'id':i,'status':s,'evidence':e} for i,s,e in tests],'selected_bundle_all_of_review':[{'id':i,'status':s,'evidence':e} for i,s,e in bundle],'all_components_in_one_image':True,'preregistered_result':'pass_5_of_5','bundle_result':'pass_3_of_3','quality_observations':['Generated transit signs and tote lettering were not requested; they were not a registered exclusion and do not determine the tested material/infrastructure result.','The exact handrail wrapping is a light partial finger curl over the rail, consistent with light contact rather than a load-bearing grip.'],'calibration_boundary':'Second candidate pack follows source and breadth calibration after first pack zero exposure. Same independently frozen scene and preregistered criteria; not an untouched retrieval holdout.','user_judgment':'pending','image_tool_call_count':1,'retry_count':0}
(p/'test_results.json').write_text(json.dumps(report,indent=2)+'\n')
source=p.parents[1]/'data-ready-2.json'
args=[sys.executable,str(project/'skills/photo-prompt-image-generator/scripts/record_image_run.py'),'--ts',datetime.datetime.now(datetime.timezone.utc).isoformat(),'--concept','Terraced hillside bus interchange after rain; reference woman handrail contact','--prompt-en',comp['prompt_en'],'--negative-en',comp['negative_en'],'--seed','1751180039','--attempt','1','--status','success','--image-path',str(image),'--tool','image_gen','--pack-id',pack['pack_id'],'--chosen-candidate-ids-json',json.dumps(comp['chosen_candidate_ids']),'--chosen-visual-concept-ids-json',json.dumps(comp['chosen_visual_concept_ids']),'--effective-visual-contract-sha256',aud['effective_visual_contract_sha256'],'--composer','agent','--audit-status','pass','--arm-id','arm-a','--worktree-id',str(root),'--skill-sha256',sha(project/'skills/photo-prompt-image-generator/SKILL.md'),'--source-ref','data-ready-2-sha256:'+sha(source),'--candidate-pack-version','v6','--authorial-core-sha256',pack['authorial_core']['canonical_sha256'],'--intent-lock-sha256',pack['authorial_core']['intent_lock']['canonical_sha256'],'--reference-sha256',req['references'][0]['sha256'],'--image-call-count','1','--independent-no-cross-arm-inputs','--manifest',str(p/'run_manifest.json'),'--ledger',str(p/'image_runs.ndjson')]
r=subprocess.run(args,text=True,capture_output=True);(p/'record_result.txt').write_text(r.stdout+r.stderr);print(r.returncode,r.stdout,r.stderr)
