import collections,copy,hashlib,json,pathlib,re,sys
P=pathlib.Path('/Users/chasoik/Projects/image-prompt/docs/research-evidence/photo-prompt/spring-fashion-integration-20261009/arms/knit_layer')
W=pathlib.Path('/Users/chasoik/.codex/worktrees/spring-fashion-integration-20261009/image-prompt')
RE=pathlib.Path('/Users/chasoik/Projects/image-prompt/docs/research-evidence/photo-prompt/spring-fashion-20261009')
A=W/'skills/photo-prompt-image-generator/assets'
specs={}
def R(key,ko,owners,paths,parts,relations,gate,contrast,limit='',slot=None,file=None):
    assert key not in specs
    specs[key]={'ko':ko,'owners':owners.split(','),'paths':paths.split(','),'parts':parts.split(' @@ '),'relations':[x.split('>') for x in relations.split(';;')], 'gate':gate,'contrast':contrast,'limit':limit,'slot':slot,'file':file}
# Every row below is authored for one assigned variant. Related family alternatives are excluded from its duties.
R('SF001_01','목 밑에 가까운 얕은 둥근 상의 경계','top_A,wearer_A','wardrobe.neckline.contour,wardrobe.neckline.depth','The neckline of top A forms a continuous shallow curve immediately below the same wearer\'s neck base.','top_A.neckline>curves_below>wearer_A.neck_base','Read the curved textile edge from one side to the other together with the wearer\'s neck base; the shallow gap must be visible.','A deeper scoop opening, a necklace arc or a skin shadow supplies a different boundary.')
R('SF003_01','쇄골 아래로 내려가는 넓은 둥근 목선','top_A,wearer_A','wardrobe.neckline.contour,wardrobe.neckline.width,wardrobe.neckline.depth','Top A has a broad rounded opening whose lowest edge lies below the same wearer\'s collarbones.','top_A.neckline>curves_below>wearer_A.collarbones','Read both side edges and the rounded bottom of this one opening with the collarbone landmarks.','A V point, merely wide shallow edge or neckline shadow does not establish this rounded depth.')
R('SF005_01','같은 앞판에서 뾰족하게 수렴하는 V 목선','top_A','wardrobe.neckline.contour','Two slanting textile edges of top A meet at one pointed bottom on its front neckline.','top_A.neckline.left_edge>converges_with>top_A.neckline.right_edge;;top_A.neckline.point>belongs_to>top_A.front','See both fabric edges and their single shared V point on the same front panel.','Two straps crossing or a central skin shadow is not the neckline; this variant prescribes no depth or breast exposure.')
R('SF007_01','윗선의 두 둥근 봉우리와 중앙 낮은 지점','bodice_A','wardrobe.neckline.contour','The upper boundary of bodice A has two rounded lobes joined by a shallow dip at the center.','bodice_A.upper_edge.left_lobe>meets_at>bodice_A.upper_edge.center_dip;;bodice_A.upper_edge.right_lobe>meets_at>bodice_A.upper_edge.center_dip','Trace the actual upper textile boundary across both lobes and the central dip.','Cup seams or breast outlines inside a straight upper edge do not supply this contour; strap state remains open.')
R('SF009_01','소매가 이어지는 양 어깨 아래 상의 윗선','top_A,wearer_A','wardrobe.shoulder.coverage,wardrobe.sleeve.attachment','The upper edge of top A lies below both of the same wearer\'s shoulder tops. @@ Both sleeves remain visibly joined to this lowered bodice edge.','top_A.upper_edge>lies_below>wearer_A.shoulder_tops;;top_A.sleeves>join>top_A.bodice','Show both shoulder landmarks above the fabric edge and the two sleeve-to-bodice connections.','A broad boat neck at shoulder height or an isolated missing sleeve does not show both lowered shoulders.')
R('SF010_02','어깨 위 연결부가 남는 닫힌 소매 개구부','top_A,wearer_A','wardrobe.shoulder.opening,wardrobe.shoulder.support_topology','A fully bounded cutout in top A\'s sleeve reveals the same wearer\'s shoulder. @@ A band of that sleeve fabric still crosses above the cutout.','top_A.sleeve.cutout>reveals>wearer_A.shoulder;;top_A.sleeve.upper_band>crosses_above>top_A.sleeve.cutout','Read the opening perimeter and the continuous fabric bridge above it on the same sleeve, with shoulder skin inside.','An off-shoulder free upper edge, sheer insert or painted pale patch has a different topology.')
R('SF012_02','불투명 몸판에 봉합된 투명 목선 망사','top_A','wardrobe.neckline.panel_connection,wardrobe.neckline.panel_transmission,wardrobe.neckline.mesh_structure','A transparent mesh insert spans the upper neckline of top A. @@ Its visible seam joins the mesh edge continuously to the opaque bodice below.','top_A.neckline.mesh>spans>top_A.upper_neckline;;top_A.neckline.mesh.edge>sewn_to>top_A.opaque_bodice.edge','Resolve actual mesh cells or yarn texture, transmission through the insert and its connected seam into the solid bodice.','Bare skin, a skin-colored opaque lining or an unbounded keyhole cannot replace a connected transparent textile panel.')
R('SF014_02','캐미솔 앞뒤 몸판에 붙은 좁은 어깨끈','camisole_A,wearer_A','wardrobe.strap.width,wardrobe.strap.attachment','Narrow straps of camisole A pass across the same wearer\'s shoulders. @@ Each strap joins the front and rear bodice of that one camisole.','camisole_A.straps>pass_across>wearer_A.shoulders;;camisole_A.straps.front_ends>join>camisole_A.front;;camisole_A.straps.rear_ends>join>camisole_A.back','See each strap width and both ends attached to the same camisole; a rear endpoint hidden by hair is unobservable.','A necklace, a separate inner garment\'s straps or a strap floating over the shoulder does not establish the attachment.')
R('SF015_02','한 상의의 앞뒤를 잇는 넓은 어깨끈','top_A,wearer_A','wardrobe.strap.width,wardrobe.strap.attachment','Broad flat straps of top A cover bands across the same wearer\'s shoulders. @@ Their front and rear ends attach to that same top body.','top_A.straps>span>wearer_A.shoulders;;top_A.straps.front_ends>attach_to>top_A.front;;top_A.straps.rear_ends>attach_to>top_A.back','Resolve both side edges of each broad strap and its actual front and rear garment junctions.','A sleeve cap, narrow string or straps belonging to a separate lower layer are different owners.')
R('SF017_01','목 쪽으로 들어간 앞 암홀 곡선','top_A,wearer_A','wardrobe.armhole.front_contour,wardrobe.shoulder.front_coverage','The front armhole edge of top A sweeps inward toward the neck. @@ The front shoulder of the same wearer lies outside that curved textile edge.','top_A.armhole.front_edge>curves_toward>wearer_A.neck_base;;wearer_A.front_shoulder>lies_outside>top_A.armhole.front_edge','Read the front armhole arc, its continuation into the same top and the shoulder region left outside it.','A dropped sleeve seam, a side opening or a deep lower armhole alone does not establish this inward front contour.')
R('SF018_02','넓은 암홀과 연속 앞판의 느슨한 짧은 탱크','tank_A,wearer_A','wardrobe.armhole.width,wardrobe.top.hem_height,wardrobe.fit.local_ease,wardrobe.front.continuity','Tank A has wide arm openings, a short body and an unbroken front panel. @@ Its side fabric hangs with loose folds away from the same wearer\'s torso.','tank_A.armholes>border>wearer_A.arms;;tank_A.front>connects_to>tank_A.short_hem;;tank_A.side_panels>stand_away_from>wearer_A.torso','Read both arm opening edges, the short hem and continuous front; loose side folds must belong to this tank.','Muscle definition, athletic role or a single large slit cannot replace the stated tank structure; no skin exposure below it is inferred.')
R('SF020_01','연결된 뒤판 경계가 둘러싼 오픈백','top_A','wardrobe.back.opening_topology','An open region interrupts the back of top A while connected edges of that same top frame the opening.','top_A.back.opening>bounded_by>top_A.connected_back_edges','Use a rear view to trace the actual opening perimeter and residual continuous fabric connections.','A sheer filled back panel, front neckline or merely concealed back is different; the surface behind the opening is not prescribed.')
R('SF021_02','부착부에서 물결 끝으로 퍼지는 소매','blouse_A','wardrobe.sleeve.flare,wardrobe.sleeve.free_edge_contour','The sleeve of blouse A widens outward from its bodice attachment. @@ Its free outer edge hangs in loose waves.','blouse_A.sleeve>flares_from>blouse_A.armhole_attachment;;blouse_A.sleeve.free_edge>terminates>blouse_A.sleeve','Trace the same sleeve from attached armhole edge to the broad wavy free hem.','A separate shoulder ruffle, a cuff-gathered balloon sleeve or simple body folds have different attachments.')
R('SF023_01','블라우스 위에서 가슴 아래 시작하는 코르셋','corset_A,blouse_A,wearer_A','wardrobe.corset.upper_edge_height,wardrobe.corset.waist_coverage,wardrobe.layer.order','Corset A starts below the same wearer\'s bust and encircles the waist. @@ The separate blouse A remains continuous above and behind the corset, which overlaps it on the outside.','corset_A.upper_edge>lies_below>wearer_A.bust;;corset_A>wraps_around>wearer_A.waist;;corset_A>overlaps_outside>blouse_A','See the corset upper boundary below the bust, its waist wrap and the separate blouse continuing into the overlap.','An underbust seam on a single dress, a belt or visible underside breast skin is not this two-garment relation.','The visible wrap establishes no boning material, compression force or hidden closure.')
R('SF025_01','몸통을 두르는 짧은 끈 없는 직물 밴드','top_A,wearer_A','wardrobe.bodice.length,wardrobe.strap.presence,wardrobe.bodice.wrap_continuity','A short textile band forms top A around the same wearer\'s torso. @@ Its uninterrupted upper edge is strapless and its lower edge remains separate and visible.','top_A.band>encircles>wearer_A.torso;;top_A.upper_edge>bounds>top_A.band;;top_A.lower_edge>bounds>top_A.band','Read the short upper-to-lower textile span and continuous torso wrap; visible upper boundary must carry no shoulder straps.','A long strapless dress, crop with hidden straps or horizontal print on a shirt does not supply the short band.')
R('SF026_02','각 컵의 하단을 따라가는 외부 케이싱','top_A','wardrobe.cup.visible_casing','A narrow curved casing on top A follows the lower boundary of each of its two cups.','top_A.cup_left.casing>follows>top_A.cup_left.lower_edge;;top_A.cup_right.casing>follows>top_A.cup_right.lower_edge','Resolve the two actual casing strips following their respective cup boundaries, independently of skin and cast shadows.','An isolated breast shadow, ordinary fold or horizontal underbust seam lacks the two cup-bound channels.','The casing does not prove a concealed wire, metal content, padding or support performance.')
R('SF029_01','옆선에서 버스트 가까운 끝으로 수렴하는 다트','blouse_A','wardrobe.bodice.dart_topology','A stitched dart on blouse A begins at its side seam and tapers to one short tip near the bust.','blouse_A.dart.base>starts_at>blouse_A.side_seam;;blouse_A.dart>tapers_to>blouse_A.dart.bust_adjacent_tip','See the stitched convergence, side-seam origin and terminating tip on one blouse panel.','A seam continuing down the full bodice, loose crease or skin contour is not a terminating dart.')
R('SF031_01','앞판의 작은 주름이 모인 중앙 버스트 봉제선','top_A','wardrobe.bust.folds,wardrobe.folds.center_anchor','Small fabric folds on top A converge into a stitched anchor at the center bust.','top_A.front.small_folds>converge_into>top_A.center_bust.seam','Read several fabric folds converging to one actual central seam, with the fold surfaces attached to the same front.','Crossed twist panels, a body shadow or elastic assumed from the word shirring cannot replace the fold-to-seam relation.','Elastic thread and stretch magnitude remain unverified.')
R('SF032_02','높은 상의 밑단과 아래 허리단 사이의 넓은 틈','top_A,bottom_A,wearer_A','wardrobe.top.hem_height,wardrobe.coverage.midriff_gap','The hem of top A ends high on the same wearer\'s torso. @@ A broad visible skin interval lies between this hem and the separate bottom A waistband.','top_A.hem>lies_above>bottom_A.waistband;;wearer_A.midriff.skin_interval>lies_between>top_A.hem_and_bottom_A.waistband','See both garment boundaries with uninterrupted midriff skin between them; a cropped-out waistband cannot establish the interval.','A high crop over a continuous inner layer or image cropping is a different coverage result; underside breast exposure is not required.')
R('SF033_02','연속 앞판을 중앙에 모으는 고정 매듭 외관','top_A','wardrobe.front.knot,wardrobe.front.fabric_gathering','A compact fabric knot occupies the center front of top A. @@ The adjoining front fabric stays continuous around the knot and gathers into it.','top_A.front.fabric>gathers_into>top_A.front.knot;;top_A.front.knot>belongs_to>top_A.front','Read actual interlaced knot fabric and continuity of the surrounding front panel into its gathers.','A separate ribbon bow, printed knot or split tie closure does not establish a knot on a continuous front.','Whether the knot opens as a functional closure is metadata unless demonstrated separately.')
R('SF034_03','삼각 상의 직물의 몸통 랩과 뒤 매듭','top_A,wearer_A','wardrobe.bodice.panel_shape,wardrobe.bodice.wrap_topology,wardrobe.back.tie_attachment','A triangular panel of top A wraps across the same wearer\'s torso. @@ Its two fabric ends continue around the torso and meet in a tied knot on the back.','top_A.triangular_panel>wraps_across>wearer_A.torso;;top_A.end_left>meets_in>top_A.back_knot;;top_A.end_right>meets_in>top_A.back_knot','Trace the triangular panel and both continuing ends to the same rear knot; hidden rear connections remain unobservable.','A scarf print, triangular hem on an unrelated sewn shirt or detached back bow supplies no panel-to-knot continuity.','Reuse of an actual scarf, exact fiber and manufacturing history are not established.')
R('SF035_03','위아래 직물이 남는 옆 허리 개구부','dress_A,wearer_A','wardrobe.cutout.location,wardrobe.cutout.topology','A closed-perimeter opening sits at the side waist of dress A. @@ Fabric of the same dress continues both above and below the opening.','dress_A.cutout>located_at>wearer_A.side_waist;;dress_A.cutout>bounded_by>dress_A.continuous_surrounding_fabric','Read the entire actual opening perimeter at the side waist and both residual dress bridges above and below it.','A sheer insert, skin-colored patch or free cropped hem has a different topology; the layer behind the hole remains a separate declaration.')
R('SF038_01','배꼽보다 아래인 같은 착용자의 바지 허리단','trousers_A,wearer_A','wardrobe.bottom.waistband_height','The top edge of trousers A\'s waistband lies below the same wearer\'s visible navel.','trousers_A.waistband.top_edge>lies_below>wearer_A.navel','See the actual waistband top boundary and navel landmark in the same image.','An obscured navel, camera crop or changed body proportions cannot establish the relative waistband height.')
R('SF039_02','상의 밑단 바로 아래의 작은 아래가슴 피부 영역','top_A,adult_wearer_A','wardrobe.coverage.lower_breast','A small underside-breast skin region of the declared adult wearer is visible directly below top A\'s lower fabric edge. @@ The visible textile edge belongs to that same top and remains distinct from the skin contour.','adult_wearer_A.lower_breast.skin_region>visible_below>top_A.lower_edge','Resolve the adult subject context, the exact lower-breast skin location and the same top\'s real boundary; fabric or shadow cannot be scored as skin.','An underbust seam, corset worn over a blouse, midriff skin or a cup shadow does not supply underside-breast exposure.','This one coverage result neither implies nudity elsewhere nor establishes absent hidden underwear.')
R('SF040_03','같은 착용자의 발목 부근까지 내려오는 치마','skirt_A,wearer_A','wardrobe.skirt.hem_height','The lower edge of skirt A reaches the same wearer\'s ankle level.','skirt_A.hem>reaches>wearer_A.ankles','Read the skirt hem and ankle landmarks together; loss of either to the crop prevents a pass.','A long skirt label, floor contact or a hem hidden by another garment cannot establish ankle-relative length.')
R('SF041_02','치마 옆에 놓인 하나의 실제 트임','skirt_A','wardrobe.skirt.slit_location,wardrobe.skirt.slit_count','One slit interrupts a side edge of skirt A. @@ Its two separated textile margins meet at a visible upper starting point on that side.','skirt_A.single_side_slit>interrupts>skirt_A.side_edge;;skirt_A.slit.margins>meet_at>skirt_A.slit.upper_start','Count one actual side opening and read its two margins plus common upper start; no slit height is prescribed.','An overlapping wrap panel, knife fold or printed dark stripe is not a side slit; a concealed second opening makes the count unverified.')
R('SF042_01','허리 고정점에서 겹치는 두 치마 앞판','skirt_A','wardrobe.skirt.overlap,wardrobe.skirt.closure_attachment','A front panel of skirt A crosses over its other front panel. @@ The upper crossing panel visibly attaches to the same skirt at the waistband.','skirt_A.front_panel_outer>overlaps_outside>skirt_A.front_panel_inner;;skirt_A.front_panel_outer.upper_end>attaches_to>skirt_A.waistband','See two distinct textile boundaries with their overlap order and the outer panel\'s actual waist attachment.','A diagonal printed stripe, free slit or loose scarf draped nearby lacks the two-panel attachment.','Visible attachment does not establish an adjustable closure or how far the skirt opens while walking.')
R('SF044_01','짧은 치마의 허리에서 밑단으로 이어진 반복 플리츠','skirt_A,wearer_A','wardrobe.skirt.pleats,wardrobe.skirt.hem_height','Repeated folded pleats of skirt A begin at its waistband and continue toward the hem. @@ The short skirt hem lies above the same wearer\'s knees.','skirt_A.pleats>continue_from>skirt_A.waistband;;skirt_A.pleats>extend_toward>skirt_A.hem;;skirt_A.hem>lies_above>wearer_A.knees','Trace several actual folded ridges from the waist to the short hem and read the knee landmarks.','Printed stripes, gathered wrinkles or a long pleated skirt do not satisfy this selected short waist-to-hem arrangement.','The short hem is an authored visible variant, not a universal named-style length in centimeters.')
R('SF045_02','밑단 쪽에서 꽃잎처럼 겹치는 곡선 앞판','skirt_A','wardrobe.skirt.front_overlap,wardrobe.skirt.hem_contour','Two curved front panels of skirt A cross over one another toward the lower edge like overlapping petals.','skirt_A.front_panel_left>overlaps>skirt_A.front_panel_right;;skirt_A.front_panels.curved_edges>continue_toward>skirt_A.hem','Resolve both curved free textile boundaries and their actual layer order down toward the hem.','A single rounded skirt silhouette, bubble hem or floral print lacks two overlapping petal edges.')
R('SF047_02','양쪽 쇼츠 밑단에 이어진 불규칙한 올풀림','shorts_A','wardrobe.hem.finish,wardrobe.textile.visible_twill','The twill-like surface of shorts A ends at two uneven lower openings. @@ Frayed yarn ends project directly from both actual hem boundaries.','shorts_A.hem_left.frayed_yarns>continue_from>shorts_A.hem_left;;shorts_A.hem_right.frayed_yarns>continue_from>shorts_A.hem_right','Resolve both leg openings and individual yarn ends rooted in the irregular hems; assess surface only.','A fray print, unrelated fringe or tears above a clean hem do not establish rooted hem yarns.','Denim fiber identity and the history of cutting full-length jeans remain metadata.')
R('SF048_02','양 허벅지를 따르며 중간 높이에서 끝나는 쇼츠','shorts_A,wearer_A','wardrobe.shorts.fit,wardrobe.shorts.hem_height','Both legs of shorts A follow the same wearer\'s thigh contours closely. @@ Their separate hems end around mid-thigh.','shorts_A.legs>follow_closely>wearer_A.thighs;;shorts_A.hems>end_at>wearer_A.mid_thigh','Read fabric continuity against both thigh contours and each hem relative to the thigh span.','Loose shorts, one tight leg or a cropped image without both hems is a different fit-and-length result.','The image does not establish stretch percentage, pressure or sports performance.')
R('SF049_03','하나의 하의에서 갈라지는 두 넓은 바짓단','trousers_A','wardrobe.pants.leg_width,wardrobe.pants.branch_topology','Two broad legs branch from the shared upper body of trousers A. @@ Each leg widens toward its own separate hem.','trousers_A.leg_left>branches_from>trousers_A.upper_body;;trousers_A.leg_right>branches_from>trousers_A.upper_body;;trousers_A.legs>widen_toward>trousers_A.separate_hems','Read the shared garment branch and two distinct wide leg outlines with separate lower openings.','A single skirt tube, loose skirt folds or a second garment supplies no two-leg branching; absolute length remains open.')
R('SF050_03','몸통을 가볍게 따르는 드레스의 작은 느슨한 주름','dress_A,wearer_A','wardrobe.fit.local_contact,wardrobe.folds.local_drape','Dress A follows the same wearer\'s torso with small loose folds interrupting its surface.','dress_A.torso_panel>follows_with_soft_folds>wearer_A.torso','See the dress panel follow the torso outline while small fabric folds remain locally slack and distinguishable from body shading.','A uniformly taut panel, a rigid stand-away shell or body contour without visible cloth does not establish this local drape.','Pressure, comfort, exact ease and bodily dimensions remain unmeasured.')
R('SF051_02','자연 허리에서 같은 드레스를 모으는 별도 벨트','belt_A,dress_A,wearer_A','wardrobe.waist.gathering,wardrobe.belt.placement,wardrobe.layer.order','Belt A crosses around dress A at the same wearer\'s natural waist. @@ Fabric of that dress converges inward beneath the visible belt.','belt_A>encircles_at>wearer_A.natural_waist;;belt_A>overlaps_outside>dress_A;;dress_A.waist_fabric>gathers_under>belt_A','Read the belt as a separate continuous object over the dress and the local fabric convergence at the waist.','A printed belt, dark shadow or body narrowing without a visible gathering device lacks this relation.','Fabric gathering does not imply a change in actual waist size, pressure or comfort.')
R('SF053_01','몸통과 다리 옆으로 곧게 내려오는 드레스 외곽','dress_A,wearer_A','wardrobe.silhouette.contour','The lateral edges of dress A descend in a nearly straight outline beside the same wearer\'s torso and legs.','dress_A.side_edges>descend_beside>wearer_A.torso_and_legs','Read both dress side outlines over the torso-to-lower-skirt span; the near-straight contour must belong to cloth.','A lower flared skirt, a rectangular background panel or a changed body shape supplies a different contour.','This visible column-like outline does not prove tightness, body measurements or a specific fiber.')
R('SF054_02','자연 허리보다 낮은 몸판과 치마 연결선','dress_A,wearer_A','wardrobe.waist_seam.height','A continuous seam of dress A joins its long bodice to the skirt below the same wearer\'s natural waist.','dress_A.bodice.lower_edge>joins>dress_A.skirt.upper_edge;;dress_A.waist_seam>lies_below>wearer_A.natural_waist','Trace the true bodice-skirt junction with the same wearer\'s waist landmark above it.','A low trouser waistband, ornamental belt or seam on a separate overlay is a different owner and connection.')
R('SF056_01','작고 촘촘한 루프가 보이는 니트 면','knit_top_A','wardrobe.textile.loop_scale,wardrobe.textile.loop_spacing','The surface of knit top A consists of small closely spaced yarn loops that remain individually visible.','knit_top_A.small_loops>repeat_across>knit_top_A.surface','At native resolution resolve individual small loop contours and their close spacing across the same fabric area.','A smooth blurred knit label, printed microdots or random grain cannot supply yarn-loop continuity.','Exact needle gauge, stretch percentage, fiber content and tactile softness remain metadata.')
R('SF057_02','실 경로 사이의 실제 열린 니트 구멍','knit_garment_A','wardrobe.textile.openwork_topology','Open stitches of knit garment A leave clear gaps bounded by connected yarn paths. @@ The opaque yarn and the surface visible through each true gap remain distinct.','knit_garment_A.yarn_paths>bound>knit_garment_A.open_gaps;;knit_garment_A.open_gaps>reveal>declared_under_surface_A','Resolve continuous connected yarn around multiple true open cells and distinguish the underneath surface from the opaque yarn.','Printed diamonds, a dark flat patch or a transparent filled panel has a different structure.','The underneath surface must be independently declared; gaps do not imply skin, missing lining or fiber identity.')
R('SF059_02','자연 허리 부근에서 끝나는 카디건 밑단','cardigan_A,wearer_A','wardrobe.cardigan.length','Cardigan A\'s lower textile boundary ends near the same wearer\'s natural waist.','cardigan_A.hem>ends_near>wearer_A.natural_waist','Read the actual cardigan hem together with the natural waist landmark; identify it apart from an inner top hem.','A short image crop, blouse hem or long cardigan folded out of view cannot establish this length.','Front closure state, underwear, midriff visibility and exact hem centimeters remain open.')
R('SF061_01','허리 위의 짧은 볼레로가 안쪽 상의를 둘러싼 겹침','bolero_A,inner_top_A,wearer_A','wardrobe.outer.hem_height,wardrobe.outer.front_opening,wardrobe.layer.order','The short body of bolero A ends above the same wearer\'s natural waist. @@ Its separated front edges frame the distinct inner top A, with the bolero lying outside it.','bolero_A.hem>lies_above>wearer_A.natural_waist;;bolero_A.front_edges>frame>inner_top_A;;bolero_A>overlaps_outside>inner_top_A','See the bolero body and short hem, its open front boundaries and the inner garment continuing behind those boundaries.','Sleeves joined without a body, a single cropped top or an inner-panel print supplies a different arrangement.')
R('SF062_02','칼라 없이 앞판 중간에서 끝나는 짧은 단추 플래킷','top_A','wardrobe.collar.presence,wardrobe.placket.extent','The collarless neck edge of top A opens into a short button placket. @@ That placket terminates within the same front bodice.','top_A.neck_edge>joins>top_A.short_button_placket;;top_A.placket.lower_end>ends_within>top_A.front_bodice','Read the simple collarless neck boundary, actual buttons along its opening and a terminating placket endpoint within the front.','A full-length shirt opening, zipper, detached button strip or concealed collar cannot establish the selected topology.')
R('SF063_01','모인 목선과 느슨한 몸판·풍성한 소매의 블라우스','blouse_A','wardrobe.blouse.neck_gathers,wardrobe.fit.local_ease,wardrobe.sleeve.volume_distribution','Fabric of blouse A gathers into its neck boundary and hangs loosely below. @@ Both attached sleeves hold soft fullness around the arms.','blouse_A.neck_fabric>gathers_into>blouse_A.neck_edge;;blouse_A.body>hangs_below>blouse_A.neck_edge;;blouse_A.sleeves>expand_around>wearer_A.arms','Read the actual neck anchor, fabric gathered there, slack body folds and fullness belonging to both connected sleeves.','A neck ruffle over a tight body, simple wrinkling or a single puff sleeve does not establish this complete selected combination.')
R('SF065_01','넓은 끈과 모아 붙인 치마의 한 드레스','dress_A,wearer_A','wardrobe.strap.width,wardrobe.strap.attachment,wardrobe.skirt.gather_attachment','Broad shoulder straps attach to dress A\'s bodice across the same wearer\'s shoulders. @@ Its separate skirt portion gathers into a continuous joining seam on that bodice.','dress_A.straps>attach_to>dress_A.bodice;;dress_A.skirt.gathers>join>dress_A.bodice.lower_edge','Read the broad straps as parts of the same dress and the skirt fabric converging into its true bodice seam.','A camisole plus separate skirt, narrow-string dress or floral print supplies different garment connections.','Light weight, seasonal comfort and warm-weather performance are metadata rather than pixel duties.')
R('SF066_02','가는 끈에 이어지는 형태를 유지한 원피스 몸판','dress_A,wearer_A','wardrobe.strap.width,wardrobe.dress.panel_continuity,wardrobe.fit.body_shape_retention','Narrow shoulder straps of dress A attach to its continuous bodice-to-skirt body. @@ The body holds a defined textile outline around the same wearer with limited small folds.','dress_A.straps>join>dress_A.bodice;;dress_A.bodice>continues_into>dress_A.skirt;;dress_A.body_outline>surrounds>wearer_A.torso','See actual strap attachments and fabric continuing into the skirt; the cloth outline must stay visibly distinct from body shading.','A separate cami and skirt, a fully fluid folded slip or an unseen rear attachment supplies different continuity.','No fiber, lining, hidden interfacing, bias cutting or support force follows from the visible outline.')
R('SF068_01','드레스 앞판으로 이어지는 셔츠 칼라와 단추 플래킷','dress_A','wardrobe.collar.structure,wardrobe.dress.placket','A shirt-like collar of dress A joins the top of its front button placket. @@ The same placket runs downward through the continuous dress front.','dress_A.collar>joins>dress_A.front_placket.upper_end;;dress_A.front_placket>runs_down>dress_A.continuous_front','Read both collar attachment and actual button opening continuing into the same dress-length front.','A shirt under a separate dress, short Henley placket or printed buttons lacks this connected front structure.')
R('SF069_01','컵 봉제 몸판과 허리에서 이어진 치마','dress_A,wearer_A','wardrobe.cup.seaming,wardrobe.dress.panel_connection,wardrobe.waist_seam.height','Visible cup seams divide the bodice of dress A. @@ The same bodice joins a continuous skirt along the same wearer\'s waist.','dress_A.cup_seams>divide>dress_A.bodice;;dress_A.bodice.lower_edge>joins>dress_A.skirt.upper_edge;;dress_A.join_seam>lies_at>wearer_A.waist','Resolve cup seams as sewn fabric boundaries and the actual bodice-to-skirt junction at the waist.','A bra over a separate skirt, cup-shaped shadows or knit texture alone does not establish this one-piece connection.','Hidden wire, padding and fiber remain unverified.')
R('SF070_02','원피스 몸판으로 이어진 라펠과 겹여밈','dress_A','wardrobe.lapel.structure,wardrobe.dress.front_overlap,wardrobe.dress.front_continuity','Lapels of dress A frame a double-breasted overlapping front. @@ This front remains continuous down into the dress skirt.','dress_A.lapels>frame>dress_A.double_breasted_front;;dress_A.front>continues_into>dress_A.skirt','Read lapel folds, overlapping front edges with their offset closure rows and continuous cloth down into the skirt.','An ordinary jacket over a separate skirt, two printed button rows or a single-breasted opening is different.','Internal tailoring and exact garment length class are not inferred.')
R('SF072_01','겹여밈 코트에 붙은 뒤 플랩과 어깨 탭','coat_A','wardrobe.coat.front_overlap,wardrobe.coat.back_flap_attachment,wardrobe.coat.shoulder_tab_attachment','Coat A has an overlapping double-breasted front. @@ A distinct flap attaches across its upper back, and fabric tabs attach on its shoulders.','coat_A.front_outer>overlaps_outside>coat_A.front_inner;;coat_A.back_flap>attaches_to>coat_A.upper_back;;coat_A.shoulder_tabs>attach_to>coat_A.shoulders','Resolve the overlapping front and actual closure rows, the attached upper-back flap boundary and shoulder-tab junctions; hidden back is unobservable.','A yoke seam, scarf overlay or detachable bag strap is a different structure.','Belt presence, coat length, waterproofing and military identity remain open.')
R('SF073_01','열린 앞판을 둘러싼 라펠과 뚜렷한 블레이저 어깨선','blazer_A,wearer_A','wardrobe.lapel.structure,wardrobe.outer.front_opening,wardrobe.blazer.shoulder_contour','Blazer A\'s lapels border its open front. @@ The same blazer forms a clearly defined shoulder outline above the sleeves.','blazer_A.lapels>border>blazer_A.front_opening;;blazer_A.shoulder_outline>continues_into>blazer_A.sleeves','Read true lapel folds and separated open-front edges, then follow both shoulder outlines into the attached sleeves.','An inner shirt collar, body shoulder silhouette or printed lapel line cannot replace this blazer outline.','Pads, interfacing, canvas and internal tailoring construction are metadata.')
R('SF074_01','짧은 트윌형 재킷의 두 가슴 포켓과 앞판 봉제선','jacket_A,wearer_A','wardrobe.outer.hem_height,wardrobe.jacket.chest_pocket_count,wardrobe.jacket.front_seams,wardrobe.textile.visible_twill','The short twill-like body of jacket A ends around the same wearer\'s waist. @@ Two chest pockets attach to its front panels alongside visible panel seams.','jacket_A.hem>ends_near>wearer_A.waist;;jacket_A.chest_pockets>attach_to>jacket_A.front_panels;;jacket_A.front_seams>join>jacket_A.front_panels','Read a short actual jacket hem, two sewn chest-pocket boundaries and seams on the same twill-looking front.','Printed pockets, shirt folds or a long coat with a similar color does not supply the selected short jacket.','Denim fiber identity, origin and exact manufacturing process are not scored.')
R('SF074_04','서로 얽힌 실이 보이는 재킷의 불규칙 표면','jacket_A','wardrobe.textile.surface_structure','Interlaced yarn paths form an irregular raised surface across jacket A\'s cloth.','jacket_A.interlaced_yarns>form>jacket_A.irregular_surface','At native resolution distinguish intersecting yarn strands and uneven relief attached to the actual jacket panels.','A noise filter, mottled flat print or background texture is not interlaced cloth on the jacket.','Fiber composition, a named tweed specification, thickness and seasonal warmth remain metadata.')
R('SF075_03','안쪽 의복 아래로 길게 내려오는 별도 겉옷','outer_A,inner_outfit_A','wardrobe.layer.order,wardrobe.layer.length_relation','Outer garment A overlaps the separate inner outfit A. @@ Its free lower edge hangs well below the visible inner outfit boundary.','outer_A>overlaps_outside>inner_outfit_A;;outer_A.hem>hangs_below>inner_outfit_A.lower_edge','Read both separate garment edges and the outer hem visibly lower than the inner outfit boundary.','A long inner dress behind a short jacket, a detached curtain or one garment\'s fold does not establish the order.','Light weight, protection, lining and seasonal suitability remain metadata.')
R('SF077_01','다른 색의 경위사가 교차하는 미세 평직 외관','fabric_A','wardrobe.textile.visible_weave,wardrobe.textile.yarn_color_relation','Fine yarns of fabric A cross in a visible over-one-under-one grid. @@ The two crossing directions carry distinguishable pale and colored yarns.','fabric_A.warp_paths>interlace_alternately>fabric_A.weft_paths;;fabric_A.warp_color>differs_from>fabric_A.weft_color','Resolve the alternating individual crossings and color difference between their two directions on the same cloth.','Blue diagonal twill, printed checks or blended image grain lacks the stated crossing order.','Trade-name identity, fiber content and exact thread count are unverified; yarn directions require a resolved weave view.')
R('SF077_04','촘촘하고 고른 작은 교차가 보이는 블라우스 원단','blouse_A','wardrobe.textile.weave_scale,wardrobe.textile.visible_weave','Fine closely spaced yarn crossings form an even woven face on blouse A.','blouse_A.fine_yarn_crossings>repeat_across>blouse_A.fabric_face','At native resolution resolve small repeated yarn crossings across one blouse region; a smooth blurred surface cannot pass.','Knitted loops, textured noise or a trade label does not establish a woven face.','Light weight, lawn identity, actual thread count and fiber content are metadata.')
R('SF079_02','투과가 보이는 잔입자 무광 원단','fabric_A,under_surface_A','wardrobe.textile.surface_structure,wardrobe.textile.reflectance,wardrobe.layer.transmission','Fabric A carries a fine pebbled matte face. @@ The declared underlying surface A remains softly visible through that fabric.','fabric_A.pebbled_face>belongs_to>fabric_A;;fabric_A>transmits>under_surface_A','Resolve fine uneven surface relief, diffuse shading and actual transmission of the specified lower surface in the same cloth.','Opaque pebble texture, sheer smooth film or grain added to the entire image supplies different properties.','Georgette identity, fiber twist, GSM, tactile feel and construction process are metadata.')
R('SF080_02','실 문양 덩어리 사이의 실제 빈 공간','lace_panel_A,under_surface_A','wardrobe.textile.open_space_pattern','Connected thread motifs form patterned islands in panel A. @@ Actual open spaces separate those thread motifs and reveal the independently declared lower surface.','lace_panel_A.thread_motifs>bound>lace_panel_A.open_spaces;;lace_panel_A.open_spaces>reveal>under_surface_A','Read motif threads, their physical connecting paths and true spaces between them with a distinguishable underneath surface.','Floral print, holes colored onto opaque cloth or a sheer filled sheet has different topology.','Neither a specific lace-making process nor bare skin under the pattern is required.')
R('SF081_02','한 원단 면의 불규칙한 미세 입자 외관','fabric_A','wardrobe.textile.surface_structure','A fine irregular pebbled relief remains visible on the face of fabric A.','fabric_A.pebbled_relief>belongs_to>fabric_A.face','Resolve local fine uneven relief that follows the fabric surface and folds at native resolution.','Global grain, flat speckle print or large random wrinkles does not establish the local pebbled cloth face.','Crepe family identity, translucency, fiber twist and tactile feel are not established.')
R('SF082_02','안쪽 의복의 색을 부드럽게 전달하는 반투명 겉층','outer_fabric_A,inner_garment_A','wardrobe.layer.order,wardrobe.layer.transmission,wardrobe.layer.boundary_visibility','Outer fabric A transmits a softened color region from the separate inner garment A. @@ The inner edge stays blurred through the outer cloth rather than sharply resolved.','outer_fabric_A>lies_outside>inner_garment_A;;outer_fabric_A>softly_transmits>inner_garment_A.color_region;;outer_fabric_A>softens>inner_garment_A.boundary','See the separate outer cloth and transmitted inner color while its inner boundary remains softly blurred beneath the same region.','A bare visible inner edge through an open hole, opaque skin-colored lining or sharp transparency is a different transmission result.','No fiber identity, exact optical transmittance or missing lining is established.')
R('SF084_02','날카로운 하이라이트가 없는 원단의 확산 음영','fabric_A','wardrobe.textile.reflectance','Fabric A shows subdued diffuse shading across its surface, with its fold transitions broad and matte.','fabric_A.diffuse_shading>follows>fabric_A.surface_and_folds','Inspect broad diffuse shading on the actual fabric region; no concentrated sharp specular ridge should replace the matte transitions.','A global exposure reduction or a shiny region simply hidden in shadow cannot establish local matte appearance.','Observed reflectance belongs to this lighting condition and does not prove fiber quality or exact roughness.')
R('SF086_02','몸판의 국소 고정선으로 모인 장식 주름','bodice_A','wardrobe.folds.anchor_topology,wardrobe.folds.local_distribution','Decorative folds of bodice A converge into a visible local anchor line on its fabric.','bodice_A.decorative_folds>gather_into>bodice_A.local_anchor_line','Read multiple folds converging to the attached gathering line and remaining continuous with the same bodice panel.','Random wearing creases, skin folds or a stitch print lacks the fold-to-anchor relation.','Elastic content and gathering method remain metadata; this selected variant does not require smocking rows.')
R('SF087_01','한 방향으로 누운 반복 평행 플리츠','fabric_A','wardrobe.details.pleat_topology','Parallel folded pleats of fabric A lie repeatedly toward the same side.','fabric_A.parallel_pleats>fold_toward>fabric_A.shared_direction','Read real repeated parallel fold ridges lying in one shared direction on the cloth.','Printed stripes, rib knitting, opposed box pleats or random wrinkles have different topology.')
R('SF087_04','치마의 돌출 능선과 들어간 면을 반복하는 접힘','skirt_A','wardrobe.pleats.repeat_topology','Repeated folds of skirt A alternate raised textile ridges with recessed fabric faces.','skirt_A.raised_fold_ridges>alternate_with>skirt_A.recessed_faces','Resolve repeated actual ridges and recessed faces continuous with the same skirt; inspect both lit edges and self-shaded recesses.','Flat stripes, rib-knit texture or isolated wrinkling does not establish repeated folded skirt sections.','Fold direction, heat-setting process and exact fold width remain open.')
R('SF089_02','매끈한 부착선에서 물결 자유 끝으로 퍼지는 플라운스','trim_A,garment_A','wardrobe.trim.attachment,wardrobe.trim.free_edge_contour','Curved fabric trim A joins garment A along a smooth continuous attachment edge. @@ The separate free edge widens outward into waves.','trim_A.attachment_edge>joins>garment_A.edge;;trim_A.free_edge>widens_away_from>trim_A.attachment_edge','Trace the smooth attached boundary and the same trim\'s wider undulating free edge.','A gathered seam with indistinct trim owner, a printed wave or ordinary sleeve volume does not establish this selected edge pair.','Curved-cut manufacturing history is not inferred solely from the wave shape.')
R('SF090_03','한 의복 경계의 반복 둥근 스캘럽','garment_A','wardrobe.edge.contour','The actual edge of garment A repeats a sequence of rounded scallops.','garment_A.rounded_scallops>form>garment_A.free_edge','Trace repeated curved lobes on the real textile silhouette, with the fabric ending at each lobe.','A scallop print inside a straight edge, embroidery holes or folds behind a straight hem is a different boundary.')
R('SF091_03','같은 앞판에 붙은 두 고리와 중앙 매듭의 리본','bow_A,garment_A','wardrobe.ornament.bow_topology,wardrobe.ornament.attachment','Two ribbon loops of bow A meet at its central knot. @@ That knot visibly attaches to garment A\'s front.','bow_A.loop_left>joins>bow_A.central_knot;;bow_A.loop_right>joins>bow_A.central_knot;;bow_A.central_knot>attaches_to>garment_A.front','Resolve two folded ribbon loops continuous into one knot and an actual anchoring point on the garment front.','Printed bows, hair accessories, a flower rosette or detached loops do not establish this front-mounted bow.','The bow need not function as a closure.')
R('SF093_02','한 묶음 머리에서 이어져 내려오는 태슬 실','tassel_A,declared_carrier_A','wardrobe.trim.tassel_topology,wardrobe.trim.attachment','A bundle of loose strands hangs from one tied head of tassel A. @@ The head attaches at one point on its declared carrier A.','tassel_A.strands>descend_from>tassel_A.tied_head;;tassel_A.tied_head>attaches_to>declared_carrier_A','Read the gathered common strand head, individual descending strands and its one actual carrier anchor.','Fringe rooted along a long edge, loose hair or a printed tassel has different endpoint topology.','No fiber content or historical craft method is asserted.')
R('SF094_01','블라우스 목선의 작은 리본과 별도 좁은 레이스','bow_A,lace_trim_A,blouse_A','wardrobe.ornament.bow_attachment,wardrobe.trim.lace_attachment,wardrobe.trim.lace_openwork','A small ribbon bow A attaches to blouse A\'s neckline. @@ A separate narrow lace trim follows the adjacent neckline edge with visible thread motifs and openings.','bow_A>attaches_to>blouse_A.neckline;;lace_trim_A>follows>blouse_A.neckline.edge;;lace_trim_A.thread_motifs>bound>lace_trim_A.open_spaces','Resolve the bow attachment, the distinct lace strip joined beside it and actual small open threadwork on that same neckline.','A bow print, detached hair ribbon or solid floral piping is a different owner or texture.','This exact combination does not establish a broad style identity, age, personality or sexual behavior.')
R('SF095_01','랩 니트 상의와 별도 레그워머·낮은 신발 조합','wrap_top_A,legwarmers_A,shoes_A,wearer_A','wardrobe.top.front_overlap,wardrobe.textile.knit_structure,wardrobe.legwarmer.coverage,wardrobe.shoe.heel_height','A knitted wrap top A crosses its own front panels on the same wearer. @@ Separate leg warmers A cover the lower legs, and separate low flat shoes A enclose the feet.','wrap_top_A.front_outer>crosses_over>wrap_top_A.front_inner;;legwarmers_A>cover>wearer_A.lower_legs;;shoes_A>enclose>wearer_A.feet','See the knit wrap crossing, both separate warmer edges on the lower legs and actual low shoe soles on the same wearer.','A plain cardigan, tights replacing warmers or pointe shoes replacing low flats does not establish the selected item combination.','This combination proves no ballet role, skill, required tutu or complete style-family membership.')
R('SF096_03','느슨한 복식의 열린 문양 베스트와 별도 자수 테두리','vest_A,embroidered_trim_A,wearer_A','wardrobe.fit.local_ease,wardrobe.vest.openwork_topology,wardrobe.trim.embroidery_attachment','The same wearer\'s loose outfit includes vest A with open thread motifs. @@ Separate embroidered trim A attaches to a garment edge in that outfit.','vest_A.open_thread_motifs>bound>vest_A.open_spaces;;embroidered_trim_A>attaches_to>declared_outfit_A.garment_edge','Read slack garment folds, true threaded openings on the vest and a distinct stitched trim attached to its declared garment edge.','A floral vest print, generalized rustic background or embroidery floating on skin does not establish the selected clothing combination.','Broad bohemian identity, nationality, residence and fiber provenance are not implied.')
R('SF097_03','같은 착용자의 폴로·짧은 플리츠 치마·별도 삭스','polo_A,skirt_A,socks_A,wearer_A','wardrobe.collar.structure,wardrobe.placket.extent,wardrobe.skirt.pleats,wardrobe.skirt.hem_height,wardrobe.hosiery.sock_presence','Polo A has an attached shirt-like collar and a short front placket. @@ The same wearer combines it with a short pleated skirt A and separate sports-style socks A.','polo_A.collar>joins>polo_A.short_placket;;skirt_A.pleats>belong_to>skirt_A;;socks_A>cover>wearer_A.feet_and_lower_legs','See the polo collar-to-placket junction, real short-skirt folds and distinct sock edges on the same wearer.','A crew tee, printed skirt stripes or bare lower legs does not establish the selected three-item combination.','Sports performance, school enrollment, tennis role and social class remain unproved.')
R('SF098_03','티셔츠·트윌 바지 위에 놓인 형태 있는 재킷','tee_A,trousers_A,jacket_A,wearer_A','wardrobe.top.tee_structure,wardrobe.pants.branch_topology,wardrobe.textile.visible_twill,wardrobe.jacket.contour,wardrobe.layer.order','The same wearer combines a simple tee A and twill-looking trousers A. @@ Separate jacket A lies outside the tee and holds a clearly formed textile shoulder and front outline.','tee_A>worn_with>trousers_A;;jacket_A>overlaps_outside>tee_A;;jacket_A.shoulder_and_front_contour>belongs_to>jacket_A','Read the separate tee, two-leg trouser structure and actual shaped jacket boundary layered over the tee.','A one-piece printed outfit, a body shoulder contour or loose cloth without a distinct jacket is different.','Jeans fiber identity, price, status and internal tailoring remain metadata.')
R('SF099_03','짙은 남색과 밝은 줄의 상의·밝은 바지 배색','top_A,trousers_A,wearer_A','wardrobe.color.top_a.pattern,wardrobe.color.trousers_a.lightness','Alternating navy and light bands repeat across top A\'s fabric. @@ The same wearer\'s separate trousers A have a light color.','top_A.navy_bands>alternate_with>top_A.light_bands;;top_A>worn_with>trousers_A','Read alternating dark-blue and light textile bands on the top and a separately bounded light trouser surface.','A striped background, navy solid top or global light filter does not supply these item-owned colors.','Nautical role, nationality, coastal residence, economic status and logo absence are not implied.')
R('SF101_02','어두운 레이스 블라우스와 별도 형태 있는 치마','blouse_A,skirt_A,wearer_A','wardrobe.color.blouse_a,wardrobe.color.skirt_a,wardrobe.textile.lace_openwork,wardrobe.skirt.contour','The same wearer\'s dark blouse A contains visibly connected lace threads and open motif spaces. @@ Separate dark skirt A holds a defined textile outline below the blouse.','blouse_A.lace_threads>bound>blouse_A.open_motif_spaces;;blouse_A>worn_with>skirt_A;;skirt_A.defined_outline>belongs_to>skirt_A','Resolve real open-thread motifs on the dark blouse and a distinctly bounded dark skirt with a formed cloth silhouette.','A dark floral print, one-piece lace dress or uniformly dark image supplies different owners and structure.','Broad goth identity, sexual conduct and wearer personality are not established.')
R('SF102_01','부드럽게 반사하는 드레스 목선의 작은 장식','dress_A,ornament_A','wardrobe.textile.reflectance,wardrobe.ornament.attachment','The surface of dress A carries broad soft reflections along its folds. @@ A small separate ornament A visibly attaches near that dress\'s neckline.','dress_A.soft_highlights>follow>dress_A.folds;;ornament_A>attaches_near>dress_A.neckline','Read broad smooth reflected highlights on the dress and an actual small ornament attachment near its own neckline.','A lens flare, jewel-like print or detached necklace unrelated to the dress cannot establish the relation.','Glamour, wealth, body measurements, age and gemstone identity are not pixel facts.')
R('SF103_02','선택한 블라우스의 매우 옅은 차가운 파랑','blouse_A','wardrobe.color.blouse_a','The declared blouse A has a very pale cool-blue color across its fabric surface.','blouse_A.pale_cool_blue>belongs_to>blouse_A.fabric_surface','Resolve the blouse boundary and pale cool-blue body color under the scene light; keep adjacent owners separate.','Blue light cast over every object or a blue wall cannot substitute for the blouse\'s local color.','No exact RGB, Pantone number or current trend frequency is inferred.',slot='color')
R('SF103_05','선택한 의복의 밝고 채도가 부드러운 색','garment_A','wardrobe.color.garment_a.lightness,wardrobe.color.garment_a.chroma','The declared garment A uses a light color with softly reduced saturation across its fabric.','garment_A.light_soft_color>belongs_to>garment_A.surface','Read both high local lightness and visibly gentle chroma within this bounded garment surface under the present light.','Overexposure washing out every surface or a saturated bright color supplies a different result.','This qualitative pastel appearance supplies no fixed hue, numeric color value or pigment process.',slot='color')
R('SF103_08','선택한 치마의 부드러운 분홍·주황 중간색','skirt_A','wardrobe.color.skirt_a','The declared skirt A carries a soft pink-orange color across its fabric.','skirt_A.soft_pink_orange>belongs_to>skirt_A.fabric_surface','Identify the actual skirt surface and its gentle pink-orange body color apart from skin and surrounding light casts.','Orange fruit nearby, pink skin or a warm global filter does not supply skirt-owned color.','No exact RGB, commercial shade standard or spring trend rank is asserted.',slot='color')
R('SF103_11','선택한 상의의 밝은 청록 계열','top_A','wardrobe.color.top_a','The declared top A has a light blue-green color on its textile surface.','top_A.light_blue_green>belongs_to>top_A.textile_surface','Read a locally bounded light blue-green textile color on the top, separate from nearby green plants and sky light.','A mint plant, green background or uniformly colored illumination is a different owner.','No fixed numeric color or named-dye identity is inferred.',slot='color')
R('SF104_01','같은 파랑 계열이지만 명도가 다른 상의와 바지','top_A,trousers_A,wearer_A','wardrobe.color.top_a,wardrobe.color.trousers_a,wardrobe.color.item_lightness_relation','Top A and trousers A share a recognizable blue hue family on the same wearer. @@ Their textile colors differ visibly in lightness.','top_A.blue_hue>shares_family_with>trousers_A.blue_hue;;top_A.color_lightness>differs_from>trousers_A.color_lightness','See both separate garments in one image with blue hue kinship and an actual lightness difference between their bounded surfaces.','A uniform blue global filter, two unrelated blue props or equal colored regions with only different shadows cannot establish item colors.','No exact color coordinates, full-frame monochrome filter or brand shade code is required.',slot='color')
R('SF105_01','같은 드레스 원단의 작고 촘촘한 꽃 모티프','dress_A','wardrobe.print.motif,wardrobe.print.scale,wardrobe.print.density','Small floral motifs repeat closely across dress A\'s fabric. @@ The repeating marks follow the same cloth around its folds.','dress_A.small_flower_motifs>repeat_across>dress_A.fabric;;dress_A.motif_repeat>follows>dress_A.folds','Resolve recognizable small flower units, their dense spacing and continuation on the actual folded dress surface.','Background flowers, embroidery assumed from a label or large widely spaced flowers supplies a different repeat.','Exact motif millimeters and print process are not measured.',slot='color')
R('SF106_01','같은 원단 면에 교차하는 균등 폭의 작은 체크','fabric_A','wardrobe.print.repeat_topology,wardrobe.print.band_width_relation','Equal-width horizontal and vertical bands on fabric A cross to form small repeated checks.','fabric_A.horizontal_bands>cross>fabric_A.vertical_bands;;fabric_A.band_crossings>repeat_as>fabric_A.small_checks','Read both orthogonal equal-width band sets and their repeated small crossings on the cloth as it follows folds.','A diagonal lattice, a large windowpane grid or a checked background is a different pattern.','Yarn dyeing, fiber and exact check millimeters are not inferred.',slot='color')
R('SF106_04','한 의복 원단에 반복되는 작은 풍경 선화','fabric_A','wardrobe.print.motif,wardrobe.print.repeat_topology','Small line-drawn landscape vignettes repeat across the declared garment fabric A. @@ The scene marks remain printed on that cloth as it bends.','fabric_A.landscape_vignettes>repeat_across>fabric_A.surface;;fabric_A.linework>follows>fabric_A.folds','Resolve repeated landscape scene units drawn with lines and their attachment to the same folding cloth surface.','A real landscape behind the wearer, a single picture panel or floral linework alone does not supply repeated landscape units.','No national identity, single mandatory blue hue or textile production history is implied.',slot='color')
R('SF107_02','같은 신발 양옆에 붙어 발등을 가로지르는 끈','shoe_A,wearer_A','wardrobe.shoe.strap_route,wardrobe.shoe.strap_attachment','A strap of shoe A crosses the same wearer\'s instep. @@ Its two ends attach to opposite sides of that same shoe.','shoe_A.instep_strap>crosses>wearer_A.instep;;shoe_A.strap.end_left>attaches_to>shoe_A.side_left;;shoe_A.strap.end_right>attaches_to>shoe_A.side_right','Read the strap over the foot\'s instep and both actual junctions into the same shoe body.','An ankle strap, loose ribbon or a strip drawn on the foot belongs to a different route.','Heel height, toe opening and material remain open.',slot='footwear')
R('SF107_05','같은 신발 뒤쪽 밑창에 연결된 짧고 가는 굽','shoe_A','wardrobe.shoe.heel_height,wardrobe.shoe.heel_shape','A short slender heel of shoe A joins the rear underside of its sole.','shoe_A.short_slender_heel>joins>shoe_A.sole.rear_underside','Resolve a low narrow heel as a distinct continuous support below the rear sole, with its full contour visible.','A broad block heel, high stiletto, wedge or rear foot shadow has a different structure.','Exact heel centimeters, comfort and support performance are unmeasured.',slot='footwear')
R('SF108_01','발을 가로지르는 연결끈과 별도의 발목끈','sandals_A,wearer_A','wardrobe.shoe.foot_strap_route,wardrobe.shoe.ankle_strap_route,wardrobe.shoe.strap_attachment','Several straps of sandals A cross the same wearer\'s feet and connect to their respective soles. @@ A separate strap on each sandal circles the corresponding ankle and joins that sandal.','sandals_A.foot_straps>cross>wearer_A.feet;;sandals_A.foot_straps>join>sandals_A.soles;;sandals_A.ankle_straps>circle>wearer_A.ankles;;sandals_A.ankle_straps>join>sandals_A','Read the multiple foot routes, their sole junctions and separate ankle loops attached to the same corresponding sandals.','Floating ribbons, instep-only straps or an ankle bracelet independent of the shoe is a different owner.','No exact material or support performance is established.',slot='footwear')
R('SF108_04','같은 착용자의 발목에서 끝나는 부츠 샤프트','boot_A,wearer_A','wardrobe.shoe.shaft_height','The upper rim of boot A\'s continuous shaft ends around the same wearer\'s ankle.','boot_A.shaft.upper_rim>ends_near>wearer_A.ankle;;boot_A.shaft>continues_into>boot_A.foot_body','Read the actual shaft top boundary around the ankle and its continuity into the same boot foot.','A sock above a low shoe, a calf-height shaft or a cropped boot top cannot establish ankle shaft height.',slot='footwear')
R('SF109_03','다리 색을 전달하는 연속된 얇은 호지어리층','hosiery_A,wearer_A','wardrobe.hosiery.surface,wardrobe.hosiery.transmission','A continuous fine hosiery layer A covers the same wearer\'s leg. @@ The skin color remains softly visible through that separate textile layer.','hosiery_A.continuous_layer>covers>wearer_A.leg;;hosiery_A>softly_transmits>wearer_A.leg_skin_color','Resolve positive textile continuity and an actual boundary or weave cue while leg skin color transmits through it.','Bare leg, opaque skin-colored lining or disconnected net holes cannot establish a continuous sheer hosiery layer.','Denier, fiber, hidden upper attachment and support function remain metadata.',slot='wearable_accessory')
R('SF110_01','실제 머리카락에 고정된 별도 리본 매듭','hair_bow_A,wearer_A','hair.accessory.bow_topology,hair.accessory.attachment','A separate ribbon bow A has two folded loops meeting at a central knot. @@ The bow visibly anchors into the same wearer\'s hair.','hair_bow_A.loops>meet_at>hair_bow_A.knot;;hair_bow_A.anchor>secured_in>wearer_A.hair','Resolve real ribbon loops and their knot, plus an actual contact or clasp fixing that bow into hair.','A garment-front ribbon, background bow or loose ribbon hovering near the head has a different owner.','Silk identity and personal preference are not inferred.',slot='wearable_accessory')
R('SF111_01','가방 면에서 서로 엮이는 넓은 짚 같은 가닥','bag_A','wardrobe.bag.surface_structure','Broad straw-like strands of bag A interlace across its own bounded surface.','bag_A.broad_strands>interlace_across>bag_A.surface','Resolve broad individual strand paths crossing over and under each other within the actual bag panel boundary.','A basket behind the wearer, weave print or narrow yarn texture cannot establish this bag surface.','Actual raffia content, plant provenance, fiber composition and strap length remain metadata.',slot='wearable_accessory')
R('SF112_02','블라우스 위에 놓인 연결 스트랩과 버클의 별도 하네스','harness_A,blouse_A,wearer_A','wardrobe.accessory.harness_strap_topology,wardrobe.accessory.buckle_attachment,wardrobe.layer.order','Separate harness A lies over blouse A with its straps visibly connected to one another. @@ One buckle joins two strap segments of that harness.','harness_A>overlaps_outside>blouse_A;;harness_A.strap_segments>connect_to>harness_A.strap_network;;harness_A.buckle>joins>harness_A.two_strap_ends','Trace the distinct outer strap network, actual strap junctions and buckle attachment between two ends on the same harness.','Printed crossing lines, blouse seams or a detached metal ornament lacks the separate connected accessory.','Restraint, consent, sexual conduct, function and material identity are not inferred.',slot='wearable_accessory')
R('SF113_01','겉 카디건과 별도 안쪽 상의의 두 실제 경계','cardigan_A,inner_top_A,wearer_A','wardrobe.layer.order,wardrobe.layer.revealed_garment','Cardigan A lies outside the separate inner top A. @@ Its front edges frame the inner top, and both garments retain distinct visible boundaries.','cardigan_A>overlaps_outside>inner_top_A;;cardigan_A.front_edges>frame>inner_top_A','Read the outer cardigan edge, the separate inner-top boundary and their actual occlusion order on the same wearer.','One panel with an inset print, bare skin or a separate scarf nearby does not establish two layered tops.','No invisible garment absence or particular underwear type is required.')
R('SF114_01','열린 재킷 안에 보이는 브라형 상의의 윗선과 끈','jacket_A,bra_top_A,wearer_A','wardrobe.outer.front_opening,wardrobe.layer.order,wardrobe.layer.revealed_garment,wardrobe.inner_top.upper_edge,wardrobe.inner_top.strap_attachment','The opened front of jacket A frames a separate bra-shaped top A on the same wearer. @@ That inner top\'s upper edge and attached shoulder straps remain visibly distinct behind the jacket.','jacket_A.front_edges>frame>bra_top_A;;jacket_A>overlaps_outside>bra_top_A;;bra_top_A.straps>join>bra_top_A.body','Read the actual jacket opening and a separate cup-like inner top boundary with its connected straps.','A lingerie print, hidden actual bra or camisole shape without the stated bra-like form is different.','The exterior styling does not establish intimate conduct, hidden underwear state or support mechanics.')
R('SF116_02','짧은 하의를 대부분 겹쳐 가린 긴 상의와 작은 밑단 노출','long_top_A,short_bottom_A,wearer_A','wardrobe.layer.order,wardrobe.layer.coverage_relation','Long top A overlaps most of the separate short lower garment A. @@ A small strip of that lower garment\'s own hem remains visible beneath the top.','long_top_A>overlaps_outside>short_bottom_A;;long_top_A.hem>occludes_most_of>short_bottom_A;;short_bottom_A.hem_strip>visible_below>long_top_A.hem','Read both real textile hems and their order, with a narrow visible lower-garment strip proving its presence.','A bare-leg no-garment inference, a single long dress or shorts entirely hidden cannot establish this positive two-hem relation.','This does not imply absent pants, invisible underwear, actual nudity or exact hem lengths.')
R('SF118_01','무광 니트 상의와 매끈하게 반사하는 별도 치마','knit_top_A,skirt_A,wearer_A','wardrobe.textile.top_a.knit_structure,wardrobe.textile.top_a.reflectance,wardrobe.textile.skirt_a.reflectance,wardrobe.textile.skirt_a.surface_structure','A matte knitted top A sits above a separate skirt A on the same wearer. @@ The skirt has a smooth face carrying broad soft reflections that contrast with the top\'s diffuse yarn surface.','knit_top_A>worn_above>skirt_A;;knit_top_A.matte_loop_surface>contrasts_with>skirt_A.smooth_reflective_surface','Read separate garment boundaries, visible knit loops and matte diffuse shading on the top against the skirt\'s smooth broad highlights.','A global gloss filter, only differing colors or two unbounded fabric samples do not establish this item-owned texture contrast.','Fiber authenticity, body proportions and exact material roughness are not compared.')
# A genuinely equivalent existing knife-pleat candidate/profile is retained by identity.
reuse={'SF087_01': {'candidate_id':'clt_ct063_v1','profile_id':'clothing_ct063_v1','candidate_file':'photo_prompt_clothing_structure_extension.json','profile_file':'photo_prompt_visual_obligations_clothing_structure.json','reason':'The existing candidate and profile already specify repeated parallel folds toward one shared side, with actual fabric fold topology and a native gate. The draft prescribes no added scale, owner replacement, hem or closure condition, so reuse is exact at the selected visible meaning.'}}
# Discovery phrases are advisory descriptors; only the complete relation sentence below is an exact activation term.
component_terms={
'SF001_01':[['shallow rounded neckline','neck base']], 'SF003_01':[['broad rounded opening','below collarbones']], 'SF005_01':[['slanting neckline edges','V point']], 'SF007_01':[['two rounded lobes','central neckline dip']],
'SF009_01':[['below both shoulders'],['attached sleeves']], 'SF010_02':[['shoulder cutout'],['fabric bridge above']], 'SF012_02':[['transparent mesh insert','sheer mesh panel'],['mesh bodice seam']],
'SF014_02':[['narrow shoulder straps'],['front and rear strap attachments']], 'SF015_02':[['broad shoulder straps'],['front and rear attachments']], 'SF017_01':[['inward armhole curve'],['front shoulder outside']],
'SF018_02':[['wide arm openings','short tank body'],['loose side fabric']], 'SF020_01':[['open back','connected back edges']], 'SF021_02':[['flaring sleeve'],['wavy sleeve edge']],
'SF023_01':[['corset below bust'],['corset over blouse']], 'SF025_01':[['short textile torso band'],['strapless upper edge']], 'SF026_02':[['curved cup casing']], 'SF029_01':[['stitched bust dart','side seam dart']],
'SF031_01':[['center bust gathers','central seam folds']], 'SF032_02':[['high top hem'],['midriff skin gap']], 'SF033_02':[['front fabric knot'],['continuous gathered front']], 'SF034_03':[['triangular wrap panel'],['back tied knot']],
'SF035_03':[['side waist opening'],['fabric above and below']], 'SF038_01':[['waistband below navel']], 'SF039_02':[['underside breast skin'],['same top lower edge']], 'SF040_03':[['skirt ankle level']],
'SF041_02':[['single side slit'],['separated slit margins']], 'SF042_01':[['overlapping skirt front'],['waist panel attachment']], 'SF044_01':[['waist to hem pleats'],['above knee hem']], 'SF045_02':[['curved petal overlap']],
'SF047_02':[['two irregular hems'],['rooted frayed yarns']], 'SF048_02':[['close thigh fit'],['mid-thigh hems']], 'SF049_03':[['two broad trouser legs'],['two separate flared hems']], 'SF050_03':[['soft torso folds','skimming cloth']],
'SF051_02':[['belt over dress'],['waist fabric gathers']], 'SF053_01':[['straight dress outline']], 'SF054_02':[['bodice skirt join below waist']], 'SF056_01':[['small knitted loops','closely spaced yarn loops']],
'SF057_02':[['open stitches','connected yarn paths','knit openings'],['opaque yarn','true gaps']], 'SF059_02':[['cardigan waist hem']], 'SF061_01':[['short bolero hem'],['bolero inner top']],
'SF062_02':[['collarless short placket'],['placket stops within bodice']], 'SF063_01':[['gathered neck edge'],['full blouse sleeves']], 'SF065_01':[['broad dress straps'],['skirt gathers into bodice']],
'SF066_02':[['narrow dress straps'],['defined cloth outline']], 'SF068_01':[['collar placket join'],['dress front placket']], 'SF069_01':[['cup seams'],['bodice skirt waist join']], 'SF070_02':[['lapels double-breasted front'],['continuous dress skirt']],
'SF072_01':[['double-breasted coat'],['back flap shoulder tabs']], 'SF073_01':[['open blazer lapels'],['defined shoulder outline']], 'SF074_01':[['short twill jacket'],['two chest pockets']], 'SF074_04':[['interlaced raised yarns']],
'SF075_03':[['outer garment overlap'],['outer hem below inner']], 'SF077_01':[['over-one-under-one grid'],['colored crossing yarns']], 'SF077_04':[['fine woven crossings']], 'SF079_02':[['pebbled matte surface'],['transmitted underlying surface']],
'SF080_02':[['connected thread motifs'],['open patterned spaces']], 'SF081_02':[['fine irregular pebbled texture']], 'SF082_02':[['softly transmitted inner color'],['blurred inner edge']], 'SF084_02':[['diffuse matte shading']],
'SF086_02':[['decorative folds local anchor']], 'SF087_01':[['parallel same-direction pleats']], 'SF087_04':[['raised pleat ridges recessed faces']], 'SF089_02':[['smooth trim attachment'],['wavy flounce free edge']],
'SF090_03':[['rounded scalloped edge']], 'SF091_03':[['two ribbon loops'],['front bow attachment']], 'SF093_02':[['strands tied tassel head'],['tassel carrier anchor']], 'SF094_01':[['neckline ribbon bow'],['narrow open lace trim']],
'SF095_01':[['knitted wrap top'],['separate leg warmers','low flat shoes']], 'SF096_03':[['open-motif vest'],['separate embroidered trim']], 'SF097_03':[['polo collar placket'],['pleated skirt sports socks']],
'SF098_03':[['tee twill trousers'],['shaped jacket over tee']], 'SF099_03':[['navy light stripes'],['light trousers']], 'SF101_02':[['dark open lace blouse'],['defined dark skirt']], 'SF102_01':[['soft reflective dress'],['attached neckline ornament']],
'SF103_02':[['pale cool-blue blouse']], 'SF103_05':[['light soft garment color']], 'SF103_08':[['soft pink-orange skirt']], 'SF103_11':[['light blue-green top']], 'SF104_01':[['shared blue hue family'],['different item lightness']],
'SF105_01':[['small dense floral repeat'],['motifs follow dress folds']], 'SF106_01':[['equal-width crossing bands','small repeating checks']], 'SF106_04':[['line-drawn landscape repeat'],['cloth scene marks']],
'SF107_02':[['instep strap'],['opposite shoe-side attachments']], 'SF107_05':[['short slender shoe heel']], 'SF108_01':[['foot straps sole connections'],['separate ankle straps']], 'SF108_04':[['boot shaft ankle height']],
'SF109_03':[['continuous fine hosiery'],['leg color through textile']], 'SF110_01':[['ribbon loops central knot'],['bow secured in hair']], 'SF111_01':[['broad interlaced bag strands']], 'SF112_02':[['harness over blouse'],['buckle joins strap ends']],
'SF113_01':[['outer cardigan inner top'],['distinct garment edges']], 'SF114_01':[['jacket bra-shaped top'],['inner upper edge straps']], 'SF116_02':[['long top short lower garment'],['visible lower garment hem']], 'SF118_01':[['matte knitted top'],['smooth softly reflective skirt']]}
# Final effect review: spell out every extra visible clause rather than inherit family-level effects.
for key_,extra_ in {
    'SF012_02':['wardrobe.bodice.opacity'],
    'SF026_02':['wardrobe.cup.count'],
    'SF031_01':['wardrobe.folds.bust_scale'],
    'SF041_02':['wardrobe.skirt.slit_topology'],
    'SF094_01':['wardrobe.ornament.bow_scale','wardrobe.trim.lace_width'],
    'SF102_01':['wardrobe.ornament.scale'],
    'SF109_03':['wardrobe.hosiery.leg_coverage'],
    'SF114_01':['wardrobe.inner_top.bodice_shape'],
}.items(): specs[key_]['paths'].extend(extra_)
specs['SF111_01']['paths']=['wardrobe.bag.strand_width','wardrobe.bag.interlace_topology']
specs['SF070_02']['parts'][0]='Lapels of dress A frame an overlapping front with two offset closure rows.'
specs['SF070_02']['paths'].append('wardrobe.dress.closure_row_layout')
specs['SF070_02']['relations'].append(['dress_A.offset_closure_rows','belong_to','dress_A.overlapping_front'])
specs['SF072_01']['parts'][0]='The outer front of coat A overlaps its inner front with two offset button rows.'
specs['SF072_01']['paths'].append('wardrobe.coat.button_row_layout')
specs['SF072_01']['relations'].append(['coat_A.offset_button_rows','belong_to','coat_A.overlapping_front'])
specs['SF074_01']['parts'][0]='The short body of jacket A shows diagonal yarn ridges and ends around the same wearer\'s waist.'
specs['SF074_01']['relations'].append(['jacket_A.diagonal_yarn_ridges','belong_to','jacket_A.fabric_surface'])
specs['SF074_01']['gate']='Read diagonal cloth yarn ridges, a short actual jacket hem, two sewn chest-pocket boundaries and front seams on the same jacket.'
specs['SF047_02']['parts'][0]='Diagonal yarn ridges on shorts A reach two uneven lower openings.'
specs['SF047_02']['relations'].append(['shorts_A.diagonal_yarn_ridges','belong_to','shorts_A.fabric_surface'])
specs['SF047_02']['gate']='Resolve diagonal textile yarn ridges, both leg openings and individual frayed yarn ends rooted in the irregular hems.'
specs['SF098_03']['parts'][0]='The same wearer combines a simple tee A and trousers A with visible diagonal cloth yarn ridges.'
specs['SF098_03']['relations'].append(['trousers_A.diagonal_yarn_ridges','belong_to','trousers_A.fabric_surface'])
specs['SF098_03']['gate']='Read the separate tee, two trouser branches with resolved diagonal cloth yarn ridges and an actual shaped jacket boundary layered over the tee.'
# Repair one composite endpoint into three concrete endpoints.
specs['SF032_02']['relations']=[['top_A.hem','lies_above','bottom_A.waistband'],['wearer_A.midriff.skin_interval','lies_below','top_A.hem'],['wearer_A.midriff.skin_interval','lies_above','bottom_A.waistband']]
# Explicitly list independent declared owners introduced by applicable node phrases.
specs['SF057_02']['owners'].append('declared_under_surface_A')
specs['SF063_01']['owners'].append('wearer_A')
specs['SF096_03']['owners'].append('declared_outfit_A')
for dkey in ['SF077_01','SF077_04','SF079_02','SF081_02','SF084_02','SF086_02']:
    # Surface samples remain garment-bound: no supporting wall/prop can donate their evidence.
    specs[dkey]['limit']=(specs[dkey]['limit']+' ').strip()+' The described surface must belong to the existing declared garment, not a nearby swatch or background.'
raw={n:json.load(open(RE/n)) for n in ['candidate-drafts.json','semantic-cards.json','term-plan.json','sources.json']}
all_drafts=sorted(raw['candidate-drafts.json']['drafts'],key=lambda x:x['draft_id']); assigned=[d for i,d in enumerate(all_drafts) if i%3==0]
key=lambda d:d['draft_id'].replace('SPR_DRAFT_','')
assert set(specs)=={key(d) for d in assigned}, (len(specs),set(specs)^{key(d) for d in assigned})
assert set(component_terms)==set(specs)
cards={c['id']:c for c in raw['semantic-cards.json']['cards']}
source_map={s['id']:s for s in raw['sources.json']['sources']}
def clean(s):return ' '.join(s.split())
specs['SF032_02']['parts'][1]='A broad visible skin interval lies between this hem and the waistband of the separate lower garment A.'
# Authoring object suffixes stay only in the graph node IDs. Runtime prose uses natural garment references.
NOUN_PATTERN = r"(?:declared garment fabric|underlying surface|lower garment|knit garment|knit top|inner outfit|inner garment|inner top|outer garment|outer fabric|leg warmers|flat shoes|hosiery layer|bra-shaped top|long top|wrap top|ribbon bow|embroidered trim|top|bodice|tank|corset|blouse|camisole|cardigan|bolero|shorts|trousers|dress|skirt|coat|blazer|jacket|fabric|panel|trim|garment|bow|tassel|vest|polo|tee|ornament|shoe|shoes|sandals|boot|bag|harness|carrier|bottom|socks|layer|surface|belt)"
MODIFIER_PATTERN = r"(?:separate|distinct|declared|dark|small|simple|short|long|light|matte|knitted|fine|continuous|narrow|transparent|open|curved|outer|inner|lower|same|sports-style|pleated|fabric|low)"
OWNER_LABEL_PATTERN = re.compile(r"(?P<article>(?i:a|an|the|that|its|each)\s+)?(?P<modifiers>(?:(?i:"+MODIFIER_PATTERN+r")\s+)*)(?P<noun>(?i:"+NOUN_PATTERN+r"))\s+A\b(?P<possessive>'s)?")
def naturalize(text):
    def replace(match):
        article=(match.group('article') or '').lower()
        modifiers=(match.group('modifiers') or '').lower()
        noun=match.group('noun').lower()
        prefix=text[:match.start()]
        possessed=bool(re.search(r"(?:\b(?:his|her|their|our|your|its)|\b\w+'s)\s*$",prefix))
        if noun=='polo': noun='polo top'
        if not article and not modifiers and not possessed and noun=='top': noun='same top'
        if not article and not modifiers and not possessed and noun=='inner top': noun='separate inner top'
        result=(article or ('' if possessed else 'the '))+modifiers+noun
        if match.group('possessive'): result += "'" if noun in {'shorts','trousers','sandals','shoes','socks','leg warmers','flat shoes'} else "'s"
        return result
    result=OWNER_LABEL_PATTERN.sub(replace,text)
    result=' '.join(result.split())
    if result:result=result[0].upper()+result[1:]
    assert not re.search(r"[a-z] A\b",result), result
    return result
for _s in specs.values():
    _s['parts']=[naturalize(v) for v in _s['parts']]
    for _field in ['gate','contrast','limit']:
        _s[_field]=naturalize(_s[_field])
# Preserve the explicit outer-versus-inner context of this one already-layered variant.
specs['SF113_01']['parts'][0]=specs['SF113_01']['parts'][0].replace('The cardigan','The outer cardigan')
def uniq(v):return list(dict.fromkeys(v))
def sha(o):return hashlib.sha256(json.dumps(o,ensure_ascii=False,sort_keys=True,separators=(',',':')).encode()).hexdigest()
def entities(spec):
    nodes=uniq([e for r in spec['relations'] for e in [r[0],r[2]]])
    return [{'node_id':n,'object_owner':n.split('.')[0],'wearer_binding':'same existing primary wearer; independent declared lower surfaces remain separately owned'} for n in nodes]
# Capture current existing records without editing any of them.
existing_candidates={}; existing_profiles={}
for f in uniq([d['candidate_file_proposal'] for d in assigned]):
    x=json.load(open(A/f))
    for slot,vs in x['slots'].items():
        for v in vs:existing_candidates[v['id']]={'file':f,'slot':slot,'record':v}
for f in uniq([cards[d['card_id']]['route_profiles'][0] for d in assigned]):
    for v in json.load(open(A/f))['profiles']:existing_profiles[v['id']]={'file':f,'record':v}
domains={}; decisions=[]; evidence=[]
for d in assigned:
    k=key(d); s=specs[k]; card=cards[d['card_id']]; cid='spf_'+k.lower(); pid='spring_'+k.lower()
    cfile=s['file'] or d['candidate_file_proposal']; pfile=card['route_profiles'][0]
    if k in reuse:
        r=reuse[k]; c=existing_candidates[r['candidate_id']]; p=existing_profiles[r['profile_id']]
        decisions.append({'draft_id':d['draft_id'],'decision':'reuse','candidate_id':r['candidate_id'],'profile_id':r['profile_id'],'source_ids':d['source_ids'],'reason':r['reason']})
        evidence.append({'draft_id':d['draft_id'],'decision':'reuse','existing_candidate':{'file':c['file'],'slot':c['slot'],'id':r['candidate_id'],'record_sha256':sha(c['record']),'visible_meaning':c['record']['en']},'existing_profile':{'file':p['file'],'id':r['profile_id'],'record_sha256':sha(p['record']),'definition':p['record']['semantics']['definition']},'source_support':[source_map[x] for x in d['source_ids']],'reason':r['reason']})
        continue
    assert cid not in existing_candidates and pid not in existing_profiles
    slot=s['slot'] or ('surface_material' if 'textile_surface' in cfile else 'garment_detail')
    assert slot in json.load(open(A/cfile))['slots'],(cfile,slot)
    dims=[]; props=[]
    for p in s['paths']:
        dim='color' if p.startswith('wardrobe.color.') else 'appearance'; dims.append(dim); props.append({'dimension':dim,'target':'main_subject','property':p})
    dims=uniq(dims); parts=list(map(clean,s['parts'])); en=clean(' '.join(parts)); ko=s['ko']
    relations=[{'id':f'{k.lower()}_edge_{i+1}','type':t,'subject':a,'object':b} for i,(a,t,b) in enumerate(s['relations'])]
    candidate={'id':cid,'ko':ko,'en':en,'weight':0.35,'aliases':[ko], 'keywords':uniq([ko,en,*parts,*[t for ls in component_terms[k] for t in ls]]),'embedding_text':' | '.join(uniq([en,ko,*parts])),'concept_units':parts,'relations':relations,'tags':['clothing','human'],'affected_dimensions':dims,'affected_properties':props,'core_assertion_discovery':True,'for_any':['human']}
    adult=bool(d.get('requires_adult_context')) or k=='SF039_02'
    if adult:candidate.update(requires_all_tags=['human','adult'],requires_primary_any_tags=['human'])
    component_ids=['part_'+str(i+1) for i in range(len(parts))]
    assert len(component_terms[k])==len(parts),(k,len(component_terms[k]),len(parts))
    components=[{'id':ci,'match_terms':uniq([part,*component_terms[k][i]])} for i,(ci,part) in enumerate(zip(component_ids,parts))]
    profile={'id':pid,'category':'spring_selected_clothing_relation','activation':{'exact_terms':[en],'requires_adult_character':adult,'semantic_discovery_requires_component_evidence':True,'hard_activation':{'contract_version':'photo-visual-hard-activation/v1','required_any_groups':[{'id':'complete_visible_variant','any_terms':[en]}]}},
        'semantics':{'definition':en,'paraphrase_examples':['On the existing declared garment owners, '+en[0].lower()+en[1:]],'visual_components':parts,'contrast_examples':[s['contrast']], 'claim_limits':uniq(['Only this explicitly selected visible variant is described. Related family variants remain alternatives.','Apply to the existing declared owners and same primary wearer. An unbound garment or different wearer cannot donate its components.','A required visible endpoint hidden by occlusion or crop is unobservable and cannot pass. Native pixels, prompt binding and user preference are separate evidence.',*([s['limit']] if s['limit'] else [])])},
        'authored_components':{'contract_version':'photo-authored-visual-components/v2','components':components,'discovery':{'minimum_component_groups':len(parts),'required_group_ids':component_ids},'obligations':[{'component_ids':component_ids,'evidence':[{'field':ci+'_phrase','requirement':{'min_content_words':3,'must_mention_any':[part]}} for ci,part in zip(component_ids,parts)],'instruction':'Preserve the selected owner-bound arrangement in one coherent image: '+en,'render_gates':[{'id':'vo_'+pid+'_visible_variant','review_scale':'native','description':s['gate']+' All declared parts refer to these same owners. An occluded endpoint, cropped landmark, printed imitation or different owner is UNOBSERVABLE_NOT_PASS; partial fulfillment fails.'}]}]},
        'concept_candidate':{'concept_terms':uniq([ko,en,*parts]),'core_assertion_discovery':True,'affected_dimensions':dims,'affected_properties':copy.deepcopy(props)},
        'runtime_expression':{'default_mode':'definition_with_optional_label','prompt_label_terms':[],'forbidden_prompt_terms':[],'runtime_forbidden_labels':[]},'reject_substitutes':[s['contrast']]}
    dk=(cfile,slot,pfile); group=domains.setdefault(dk,{'candidate_file':cfile,'slot':slot,'candidates':[],'profile_file':pfile,'profiles':[],'context_extensions':[]}); group['candidates'].append(candidate); group['profiles'].append(profile)
    reason='New narrow visible variant: every authored clause is bound to declared owner endpoints and specific property paths; lexical family neighbors do not prove equivalent effects and activation. No existing identity or context is changed.'
    if k=='SF009_01':reason='Existing clt_ct038_v2/clothing_ct038_v2 is a close lexical neighbor, but its wardrobe.neckline parent effect is broader and its edge ownership is generic. This variant explicitly binds both shoulder landmarks and two sleeve junctions with narrow shoulder coverage and sleeve attachment effects; preserve the existing identity unchanged.'
    if k=='SF014_02':reason='Existing clt_ct004_v1/clothing_ct004_v1 describes suspended narrow straps but does not separately bind both front and rear endpoints. This new variant declares both attachment ends and narrow strap properties without rewriting the old profile.'
    if k=='SF056_01':reason='Existing clt_ct087_v2/clothing_ct087_v2 requires a macro view. This variant requires resolved small close-spaced loops on an existing worn knit surface without adding camera/framing effects; no exact gauge measurement is claimed.'
    if k=='SF062_02':reason='Existing clt_ct001_v1/clothing_ct001_v1 defines the partway placket, but collar absence is a separate clause in this draft. This complete variant adds no top-length effect and binds collar boundary plus placket endpoint without modifying the predecessor.'
    if k=='SF077_01':reason='Existing clt_ct086_v2/clothing_ct086_v2 is a chambray-like neighbor. This selected variant separately requires resolved over-one-under-one crossings and differently colored yarn directions; textile identity and fiber remain metadata.'
    decisions.append({'draft_id':d['draft_id'],'decision':'new','candidate_id':cid,'profile_id':pid,'source_ids':d['source_ids'],'reason':reason})
    evidence.append({'draft_id':d['draft_id'],'card_id':d['card_id'],'decision':'new','candidate_id':cid,'profile_id':pid,'research_draft_text':d['en'],'authored_variant_text':en,'authored_nodes':entities(s),'authored_edges':relations,'declared_owner_objects':s['owners'],'affected_properties':props,'source_support':[source_map[x] for x in d['source_ids']], 'source_scope':'The source register supports only its named definition or construction distinction. Node geometry, English realization, property mapping and native gates here are independent data authoring; they are not quoted primary-source assertions.','omitted_or_unverified_claims':s['limit'],'family_scope_not_adopted':d['property_path_proposals'],'decision_reason':reason,'qualification':{'source_profile':'authored','retrieval':'not_run','selection':'not_run','prompt':'not_run','runtime':'not_published','native_pixel':'not_run','user_acceptance':'not_requested'}})
fragment={'domain_writes':list(domains.values()),'decisions':decisions,'evidence':evidence}
(P/'data-fragment.json').write_text(json.dumps(fragment,ensure_ascii=False,indent=2)+'\n')
(P/'data-authoring-summary.json').write_text(json.dumps({'assigned_count':len(assigned),'new_count':sum(d['decision']=='new' for d in decisions),'reuse_count':sum(d['decision']=='reuse' for d in decisions),'source_file_sha256':{n:hashlib.sha256((RE/n).read_bytes()).hexdigest() for n in raw},'fragment_sha256':hashlib.sha256((P/'data-fragment.json').read_bytes()).hexdigest(),'shared_asset_writes':False,'frozen_before_research':True,'runtime_retrieval':'not_run'},ensure_ascii=False,indent=2)+'\n')
print(json.dumps({'assigned':len(assigned),'decisions':dict(collections.Counter(d['decision'] for d in decisions)),'candidates':sum(len(d['candidates']) for d in fragment['domain_writes']),'profiles':sum(len(d['profiles']) for d in fragment['domain_writes']),'domain_writes':len(fragment['domain_writes'])}))
