import hashlib,json,pathlib,random
P=pathlib.Path('/Users/chasoik/Projects/image-prompt/docs/research-evidence/photo-prompt/spring-fashion-integration-20261009/arms/knit_layer')
W=pathlib.Path('/Users/chasoik/.codex/worktrees/spring-fashion-integration-20261009/image-prompt')
def write(name,x): (P/name).write_text(json.dumps(x,ensure_ascii=False,indent=2)+'\n')
e=json.load(open(P/'request_envelope.json'))
assert hashlib.sha256((P/'request_envelope.json').read_bytes()).hexdigest()=='81731e13b667c5f32f60476d3a826f47bfa7a8c45651eb0c69fcd33e3f25a1ac'
assert hashlib.sha256(e['request_text'].encode()).hexdigest()==e['request_sha256']
s=json.load(open(P/'run/workflow.json')); cc=json.load(open(s['artifacts']['creative_controls']['path']))
prompt='''Photograph a woman wearing visible spring fashion layers, using the supplied photograph as the face and short black bob reference. She is fastening a fresh botanical print to a drying line inside a small riverside print workshop just after a spring shower. A newly opened sash window has sent a breath of air through the room: the bottom of the pale paper curls toward her while a gauze curtain lifts behind the taut line. At the shutter, her right thumb and index finger squeeze a small metal spring clip around the print's dry upper margin and the line; her left thumb and fingertips steady its dry lower corner beside her right hip. Her shoulders turn slightly toward the paper, both elbows bend naturally, and her weight rests on two feet set a little apart. The lower corner has stopped fluttering in her hand while the free opposite corner still bends in the breeze. Her eyes follow the upper clip; her mouth holds the beginning of a relieved smile, with the softness and natural asymmetry of the reference face intact. The held print is beside her torso, leaving the front clothing layers legible. Her ivory sleeveless knitted vest has repeated open diamond holes made by visible intersecting yarn loops, bounded by dense ribbing around the neckline and hem. Beneath the holes sits a pale blue sheer long-sleeved blouse, with a sage opaque camisole forming a clear straight upper edge under the transparent chest panel. Above that camisole edge the sheer blouse transmits the skin tone; below it the same sheer fabric transmits the sage surface. Across the arms the blue translucent sleeves reveal softened skin through their fabric, and the gathered cuffs form small folds at each wrist. The knitted vest sits outside the blouse, its yarn remaining opaque while its true gaps reveal the separate fabric beneath. A strip of the blouse extends below the vest's ribbed hem and lies over the upper edge of a taupe pleated midi skirt. The skirt's broad folds fall vertically, with a distinct diagonal wrap edge crossing its front. A second clipped sheet hangs farther along the line, and a low workbench carries an ink-stained cloth and an open wooden type tray; their small irregularities suggest a working room rather than a showroom. Frame her from head to mid-calf in a vertical photograph, slightly to the right of center, with the botanical sheet occupying the space beside her and the workshop window giving a shallow view of the river. Soft window light grazes the yarn loops, preserves the blue fabric's transmission and the camisole's solid coverage, and leaves a quiet shadow between the overlapping hems. Use a natural perspective and enough depth of field to read her face, finger contacts, knit openings and the three clothing layers together. The photograph should feel like a delicate, practical interruption caught at the instant she regains control, with her understated warmth carrying a subtle attraction through attention and bearing.'''
prompt=' '.join(prompt.split()); (P/'baseline_draft.txt').write_text(prompt+'\n')
h=hashlib.sha256(prompt.encode()).hexdigest()
core={
'contract_version':'photo-authorial-core/v3','provenance':'agent_prepack','source_request':e['request_text'],'creative_controls_sha256':cc['canonical_sha256'],
'interpreted_intent':'Requester asks for independently randomized complex concepts to test the newly integrated spring-fashion topic and to use the supplied photo. The title establishes the spring-fashion topic. The agent chooses a riverside workshop moment with drying paper affected by wind; no biography is inferred from the reference. The viewer should read a quiet recovery of control while seeing true knit gaps, sheer transmission and solid coverage. These exact garments, hand mechanics, place, paper and camera treatment are agent-owned open realizations. Sensual 1 supports subtle attraction through attentive bearing and an emerging smile; fetish 0 adds no focal erotic significance; surreal 0 retains ordinary causality; creativity 1 keeps all details tied to this coherent practical moment.',
'subject':'A woman whose visible face and short black bob follow the supplied photograph, wearing spring fashion layers.',
'setting':'An agent-chosen riverside print workshop after a spring shower.',
'event':'A present moment displaying the spring outfit while the woman steadies a freshly clipped botanical print.',
'visual_priorities':['Reference-guided face and short black bob remain recognizable within the practical moment.','Opaque looped yarn and true open holes reveal a distinct sheer blue layer and sage solid coverage.','The camisole upper edge divides skin transmission from opaque fabric coverage under one sheer panel.','Right-hand clip contact and left-hand dry-corner support explain the curled paper regaining stability.','Separated vest, blouse and pleated wrap-skirt edges remain visible together.'],
'baseline_prompt_en':prompt,'user_definitions':[],
'interpretation_provenance':[
{'term':'이번에 반영한 주제','source_text':'이번에 반영한 주제가','basis':'request_context','resolution':'The conversation title is 봄 패션 용어 조사. The topic here is spring-fashion clothing structures; the particular outfit is an independent agent realization.','sources':[]},
{'term':'랜덤한 복잡한 컨셉','source_text':'랜덤한 복잡한 컨셉을 정하여','basis':'request_context','resolution':'Independently select a coherent concept with multiple connected visible structures for later image testing; random seed selects among independently written situations without making the selected detail a requester lock.','sources':[]},
{'term':'첨부한 이미지를 활용하여','source_text':'첨부한 이미지를 활용하여','basis':'request_context','resolution':'Use only visible face and short black bob cues from the supplied photograph as appearance guidance. No name, personality, biography or body measurement follows from it.','sources':[]}],
'unresolved_ambiguities':[],'user_exclusions':[],'runtime_forbidden_labels':[],
'intent_lock':{'contract_version':'photo-intent-lock/v2','priority':'requesting_user','semantic_anchors':[
{'anchor_id':'core_concept','source_text':'이번에 반영한 주제가','dimension':'concept','prompt_evidence':'visible spring fashion layers'},
{'anchor_id':'core_subject','source_text':'첨부한 이미지를 활용하여','dimension':'subject','prompt_evidence':'a woman wearing'},
{'anchor_id':'core_event','source_text':'이번에 반영한 주제가 이미지에 실제로 반영되는지까지 테스트할 수 있는','dimension':'event','prompt_evidence':'wearing visible spring fashion layers'},
{'anchor_id':'face_hair_reference','source_text':'첨부한 이미지를 활용하여','dimension':'reference_use','target':'main_subject','property':'appearance.face_and_hair_reference','prompt_evidence':'using the supplied photograph as the face and short black bob reference'}],
'locked_dimensions':['concept','subject','event'],
'open_dimensions':['appearance','pose','expression','action','setting','relationship','style','reference_use','framing','composition','lighting','camera','color','material','timing','atmosphere']},
'semantic_assertions':[{'assertion_id':'capture_camera_review','dimension':'camera','polarity':'advisory','source_span_ids':['concept_scope'],'affected_dimensions':['camera'],'axes':{'camera_axis_review':'camera_axis_review_v1','capture_owner':'unprescribed','direction_requirement':'open','height_requirement':'open'},'evidence':{}}],
'request_lineage':None,'style':{'domain':'photographic fashion','family':'inhabited spring workshop portrait','evidence':['natural workshop daylight','clothing structures readable during a practical hand action']},'variation_key':'spring_knit_layer_198294653418842'}
write('authorial_core.json',core)
rows=[
('feature.subject','request_derived',['reference_use'],None,'A person-centered test is derived from the visible person in the supplied photograph; concrete pose and wardrobe remain agent choices.','Carry permitted face and hair cues without inferring personal facts.','using the supplied photograph as the face and short black bob reference'),
('feature.situation','agent_visual_choice',[],None,None,'Tie the clothing study to a current practical interruption with a visible resolution.','She is fastening a fresh botanical print to a drying line'),
('feature.narrative_context','agent_visual_choice',[],None,None,'The open window and curled paper explain why the stabilizing action happens now.','A newly opened sash window has sent a breath of air through the room'),
('feature.location','agent_visual_choice',[],None,None,'The workshop supports real paper handling and gives the clothing a useful context.','inside a small riverside print workshop'),
('feature.clothing','agent_visual_choice',[],None,None,'Separate true knit holes, sheer transmission and opaque coverage for later pixel inspection.','Her ivory sleeveless knitted vest has repeated open diamond holes made by visible intersecting yarn loops'),
('feature.hand_gesture','agent_visual_choice',[],None,None,'Both hands have concrete compatible roles on dry paper margins.','her right thumb and index finger squeeze a small metal spring clip around the print\'s dry upper margin and the line'),
('feature.facial_expression','agent_visual_choice',[],None,None,'Subtle relief and concentration give the figure presence at sensual level one.','her mouth holds the beginning of a relieved smile'),
('feature.spatial_depth','agent_visual_choice',[],None,None,'Place the paper beside the subject so it does not hide the layered front.','The held print is beside her torso, leaving the front clothing layers legible.'),
('feature.lighting_source','agent_visual_choice',[],None,None,'Window grazing makes opaque loop yarn and sheer transmission distinguishable.','Soft window light grazes the yarn loops')]
cat=(W/'skills/photo-prompt-image-generator/precore/visual_feature_catalog.json').read_bytes()
sel={'contract_version':'photo-precore-feature-selection/v1','request_id':e['request_id'],'active_span_ids':[x['span_id'] for x in e['active_spans']],'catalog_path':'skills/photo-prompt-image-generator/precore/visual_feature_catalog.json','catalog_schema_version':'photo-precore-feature-catalog/v1','catalog_sha256':hashlib.sha256(cat).hexdigest(),'request_sha256':e['request_sha256'],'baseline_prompt_sha256':h,'selected':[{'category_id':a,'basis':b,'source_span_ids':c,'source_text':d,'derivation':f,'reason':g,'baseline_evidence':v} for a,b,c,d,f,g,v in rows]}
write('precore_feature_selection.json',sel)
review={'contract_version':'photo-embodiment-review/v1','provenance':'agent_prepack','prompt_sha256':h,'scope':'body_action','summary':'Ordinary human body model. One hand squeezes a clip at shoulder height while the other supports the dry lower paper margin near the same-side hip. The line carries the sheet weight after clipping. Feet outside or near the lower crop carry body weight; no unseen limb has an unusual load.','checks':{
'body_ownership':{'status':'supported','reason':'Both named hands belong to the single referenced woman. Right fingers operate the upper clip; left fingers steady the lower paper corner.','prompt_evidence':['her right thumb and index finger squeeze a small metal spring clip','her left thumb and fingertips steady its dry lower corner']},
'joint_chain_and_reach':{'status':'supported','reason':'Shoulders rotate toward a sheet beside the right torso; a bent right elbow reaches the upper dry margin while the left arm reaches a lower nearby margin, keeping each wrist separate.','prompt_evidence':['Her shoulders turn slightly toward the paper, both elbows bend naturally','beside her right hip']},
'support_and_balance':{'status':'supported','reason':'Two separated feet support a small torso turn. The taut drying line receives the light paper load after clipping, and the left hand merely prevents flutter rather than carrying a large load.','prompt_evidence':['her weight rests on two feet set a little apart','the taut line']},
'contact_and_space':{'status':'supported','reason':'The spring clip spans the dry top border and line, not wet ink. Thumb and fingertips support another dry margin beside the hip; separate contact areas leave space for each hand.','prompt_evidence':['around the print\'s dry upper margin and the line','her left thumb and fingertips steady its dry lower corner beside her right hip']},
'visibility_and_projection':{'status':'supported','reason':'Head-to-mid-calf framing includes both hand contacts, torso garment boundaries and the lateral paper. Natural perspective makes a plausible body chain assessable; feet remain accounted for even if cropped.','prompt_evidence':['The held print is beside her torso, leaving the front clothing layers legible.','Frame her from head to mid-calf','read her face, finger contacts, knit openings and the three clothing layers together']}}}
write('embodiment_review.json',review)
(P/'visual_feature_catalog.snapshot.json').write_bytes(cat)
seed=json.load(open(P/'concept_seed.json'))['seed']; alternatives=['봄 씨앗 교환 온실에서 열린 통풍구의 바람에 들린 식물 도판을 누르는 순간','옛 역의 수선탁자에서 바람에 밀린 종이 재단선을 다시 맞추는 순간','강변 인쇄 공방에서 젖은 첫 인쇄본의 건조 줄을 고치는 순간']; idx=random.Random(seed).randrange(3)
write('concept_note.json',{'phase':'independent_precore','concept_name':'강변 인쇄 공방의 첫 도판과 봄바람','random_seed':seed,'random_source':'secrets.randbits(48)','selection_method':'random.Random(seed).randrange(3)','selected_index':idx,'independently_authored_alternatives':alternatives,'selection_reason':'The random draw selected the print-workshop scene. It offers coherent wind-to-paper causality, hand contact, an uncrowded front outfit and layered opacity comparisons in one ordinary moment. All alternatives were authored from current request and general reasoning before local corpus access.','controls_canonical_sha256':cc['canonical_sha256'],'controls_seed':83671,'precore_inputs':['request_envelope.json','supplied photograph','current SKILL.md','exact allowed neutral precore controls/catalog/helpers'],'ownership':'Workshop, paper, window, exact garments, hand mechanics and camera are agent choices. Only the spring-fashion topic, person-from-reference use and in-image testing meaning are requester-bound.','reference_observations':'Short black bob; wispy fringe; visible facial contours, eyes, lips and small facial marks. No inferred identity or biography.','physical_review':'Reviewed each hand contact, joint reach, feet support and paper load before freeze.'})
print(json.dumps({'words':len(prompt.split()),'baseline_sha256':h,'selected_categories':len(rows),'concept':alternatives[idx]},ensure_ascii=False))
