import copy,hashlib,json,pathlib
P=pathlib.Path(__file__).resolve().parent
s=json.load(open(P/'run/workflow.json'));pack=json.load(open(s['artifacts']['pack']['path']));pack=pack[0] if isinstance(pack,list) else pack
core=pack['authorial_core'];prompt=core['baseline_prompt_en']
prompt=prompt.replace('pale blue sheer long-sleeved blouse','pale muted peach sheer long-sleeved blouse').replace('blue translucent sleeves','peach translucent sleeves').replace("blue fabric's transmission","peach fabric's transmission").replace('a taupe pleated midi skirt','a warm mushroom-taupe pleated midi skirt')
knit1='Open stitches of the knit garment leave clear gaps bounded by connected yarn paths.'
knit2='The opaque yarn and the surface visible through each true gap remain distinct.'
prompt=prompt.replace('bounded by dense ribbing around the neckline and hem.','bounded by dense ribbing around the neckline and hem. These open stitches belong to her outer ivory vest. '+knit1+' '+knit2)
sheer='The peach blouse is a translucent organza layer, with visible weave seam and edge along its cuff and hem. Window light passes through the fabric from behind her sleeves. The sage opaque underlayer remains partly visible through the blouse, and folds become denser and less transparent where the sleeves gather into the cuffs.'
prompt=prompt.replace('and the gathered cuffs form small folds at each wrist.','and the gathered cuffs form small folds at each wrist. '+sheer)
palette='Her blouse and skirt share a quiet peach-and-mushroom warmth, making two soft adjoining tones against the cooler sage inner top; their different lightness keeps the blouse hem separate from the skirt waistband.'
prompt=prompt.replace("The skirt's broad folds fall vertically",palette+" The skirt's broad folds fall vertically")
prompt=prompt.replace('Soft window light grazes the yarn loops','Soft window light from behind her right shoulder grazes the yarn loops')
prompt=' '.join(prompt.split()); h=hashlib.sha256(prompt.encode()).hexdigest()
first='Photograph a woman wearing visible spring fashion layers, using the supplied photograph as the face and short black bob reference.'
clarification_reasons={
'commercial_appeal_revealing_armor':'The selected scene contains spring fabric layers rather than a deliberately exposed fantasy armor design; its rigid protection and attachment components would supply another costume meaning.',
'contained_affect_self_presentation':'The moment shows practical concentration and relief, without the social presentation, affect leak and interrupted connection pattern of this distinct realization.',
'diegetic_reality_invariant_failure':'Window wind, curled paper and cloth transmission use ordinary causality; no invariant failure is being authored at surreal zero.',
'hands_free_supported_drink_load':'Both hands have specific clip and paper contacts; there is no supported cup or hands-free torso balancing state.',
'kuudere_composed_warmth_relation':'Reference appearance does not establish a behavioral archetype. No particular trusted counterpart and same-target helpful consequence are present.',
'mg_paper_cut_relation':'The action handles one botanical print; layered cut-paper artwork with overlap shadows is a distinct material arrangement.',
}
semantic=[]
for c in pack['semantic_clarification']['candidates']:
 pid=c.get('profile_id')
 if c.get('required_in_final_prompt'):
  semantic.append({'clarification_id':c['id'],'decision':'applied','rationale':'Retain all four literal source anchors and the original requester meaning; the new garments and colors remain optional authorial realizations.','prompt_evidence':first})
 elif pid=='spring_sf057_02':
  semantic.append({'clarification_id':c['id'],'decision':'applied','rationale':'The independently authored vest already carries true open cells. Explicit opt-in now binds the entire selected owner-bound knit relation to evidence and a native gate.','prompt_evidence':knit1+' '+knit2})
 elif pid=='sheer_garment_optical_layering':
  semantic.append({'clarification_id':c['id'],'decision':'applied','rationale':'The separate blouse textile transmits the declared camisole and arm surfaces, with folds and window light coherently identifying one organza layer. All five optical gates are opted into.','prompt_evidence':sheer})
 else:semantic.append({'clarification_id':c['id'],'decision':'rejected','rationale':clarification_reasons[pid]})
aug_reasons={
'slot:light_shape:fire_f138':'A blue-violet pointed-object glow would add an unrelated electrical-looking light event to an ordinary spring workshop and weaken the natural textile hierarchy.',
'slot:focus:vg_face_hands_place_readability':'Its readable face, contact and place goals are already concretely authored. Retain the current purposeful camera relationship rather than adopt a second focus contract.',
'slot:hair_style:ca_compact_bob':'The supplied photograph governs face and hair guidance; a generic compact-bob reinterpretation adds no useful individual cue and might replace the referenced perimeter.',
'augmentation:adult_appeal:sensual:garment_detail:spf_sf097_02':'The blazer, collared shirt and straight trousers are a coherent alternative within open appearance, but would conceal the deliberately compared knit and transmitting cloth surfaces. Prefer the lighter working outfit at the same subtle appeal level.',
'slot:wearable_accessory:sca_g13':'Long opaque gloves would obscure wrist cloth boundaries and small clip contacts without serving this paper-handling event.'}
aug=[{'candidate_id':c['id'],'decision':'rejected','rationale':aug_reasons[c['id']]} for c in pack['creative_augmentation']['candidates']]
context_ids=pack['adult_appeal']['contextual_retrieval']['review_candidate_ids'];context=[]
for cid in context_ids:
 if cid.endswith('water_w061'):context.append({'candidate_id':cid,'reading':'irrelevant','reason':'This is a geothermal spring outlet and pool relation, while the scene uses the season of spring and an ordinary river beyond a workshop window.','proposed_application':'No application is adopted; condensed mist and a pool would require a distinct place premise.'})
 elif cid.endswith('spf_sf097_02'):context.append({'candidate_id':cid,'reading':'potential','reason':'A collared shirt under an open blazer with straight trousers could credibly portray the same self-directed print worker with structured everyday attraction.','proposed_application':'A full alternative would place the woman clipping the same print in those separate layers; it is declined because their coverage would hide the current knit-gap and transparency comparison.'})
 elif cid.endswith('winter_expedition_fashion_layers'):context.append({'candidate_id':cid,'reading':'irrelevant','reason':'A winter expedition whole direction would introduce a different environmental and clothing purpose into the small spring print workshop.','proposed_application':'No adoption: the current working garments better support the specific warm-season material study.'})
 else:context.append({'candidate_id':cid,'reading':'potential','reason':'Couture support tapes, tulle and lining could create a visibly constructed garment demonstration with delicate tactile appeal.','proposed_application':'A coherent alternative would expose those connections during a making task, but that changes the paper-drying moment into clothing demonstration; retain the current relaxed practical action.'})
review=copy.deepcopy(pack['embodiment_preflight']['baseline_review']);review['provenance']='agent_postcomposition';review['prompt_sha256']=h;review['summary']='Re-reviewed the entire final prompt: the same ordinary human body chain and two dry-margin paper contacts remain. The blouse is now peach organza and the skirt warm mushroom taupe; those color and material clarifications do not change reach, support or contact. Sleeve cuff folds remain on each actual wrist, and the paper stays beside the torso rather than concealing critical garment surfaces.'
profile_evidence={
'spring_sf057_02':{'part_1_phrase':knit1,'part_2_phrase':knit2},
'sheer_garment_optical_layering':{'translucent_textile_phrase':'The peach blouse is a translucent organza layer','visible_weave_edge_phrase':'visible weave seam and edge along its cuff and hem','transmitted_light_phrase':'Window light passes through the fabric from behind her sleeves.','layer_contrast_phrase':'The sage opaque underlayer remains partly visible through the blouse','material_behavior_phrase':'folds become denser and less transparent where the sleeves gather into the cuffs.'}}
color1='Her blouse and skirt share a quiet peach-and-mushroom warmth, making two soft adjoining tones against the cooler sage inner top'
color2='their different lightness keeps the blouse hem separate from the skirt waistband.'
composed={'pack_id':pack['pack_id'],'core_retrieval_sha256':pack['core_retrieval']['canonical_sha256'],'composer':'agent','prompt_en':prompt,'negative_en':pack['negative_en'],'chosen_candidate_ids':['bundle:spf_sf104_2_bundle'],'chosen_visual_concept_ids':['visual-concept:spring_sf057_02','visual-concept:sheer_garment_optical_layering'],
'candidate_interpretations':[{'candidate_id':'bundle:spf_sf104_2_bundle','artistic_interpretation':'Related low-chroma warmth connects the blouse and skirt to a quiet print-workshop moment while the sage camisole preserves a separate color owner under the sheer surface.','transformation':'Use diluted peach on the blouse and warm mushroom taupe on the skirt, keeping their actual hem and waistband distinct by lightness and fabric overlap rather than applying a global warm filter.','prompt_evidence':palette,'component_evidence':{'component_1':color1,'component_2':color2},'relation_evidence':{'existing_wearer_scope':color1,'sf104_2_relation_1':color1,'sf104_2_relation_2':color2}}],
'coverage_assertions':{m['text']:[m['text']] for m in pack['mandatory_intents']},
'authorial_core_binding':{'source_authorial_core_sha256':core['canonical_sha256'],'source_intent_lock_sha256':core['intent_lock']['canonical_sha256'],'preserved_anchor_ids':[a['anchor_id'] for a in core['intent_lock']['semantic_anchors']],'preserved_evidence':[],'authorial_decisions':[
{'dimension':'color','decision':'Pair a muted peach blouse with a warm mushroom skirt while retaining the sage inner top as a distinct owner.','rationale':'The compatible new color bundle creates a coherent subdued spring palette in the already-chosen workshop without changing the reference or mechanism. Color was never a requester lock.','prompt_evidence':palette,'affected_properties':[{'dimension':'color','target':'main_subject','property':p} for p in ['wardrobe.blouse.color','wardrobe.skirt.color','wardrobe.palette.item_relationship']]},
{'dimension':'appearance','decision':'Bind the open cells to the exterior vest and identify the separate transmitting blouse as organza with real textile boundaries.','rationale':'Complete opt-in contracts make the existing layered material idea assessable rather than relying on broad fashion labels. The selected surfaces and owner order remain in the independent scene.','prompt_evidence':sheer,'affected_properties':[{'dimension':'appearance','target':'main_subject','property':p} for p in ['wardrobe.textile.openwork_topology','wardrobe.blouse.textile.structure','wardrobe.layer.transmission']]},
{'dimension':'lighting','decision':'Let the existing window light enter from behind her right shoulder and traverse the sleeves.','rationale':'A concrete source direction keeps transmission and dense cuff folds coherent across one material without adding another light or apparatus.','prompt_evidence':'Window light passes through the fabric from behind her sleeves.'}]},
'semantic_clarification_decisions':semantic,'creative_augmentation_brief':{'decisions':aug},'visual_obligation_evidence':profile_evidence,
'embodiment_review':{'source_contract_sha256':pack['embodiment_preflight']['canonical_sha256'],'review':review},
'adult_appeal_brief':{'agency_phrase':'She is fastening a fresh botanical print to a drying line','axes':{'sensual':{'intensity':1,'realization':'baseline','affected_dimensions':[],'artistic_interpretation':'Subtle attraction remains in attentive self-directed paper handling, soft relief and understated bearing rather than adding a new body display.','prompt_evidence':'her understated warmth carrying a subtle attraction through attention and bearing'},'fetish':{'intensity':0,'realization':'baseline','affected_dimensions':[],'artistic_interpretation':'No added fetish focus is introduced.','prompt_evidence':''}},'blend':{'emphasis':'sensual_led'},'contextual_review':context,'contextual_comparison':'At sensual one and fetish zero, the blazer alternative could carry composed everyday appeal and couture layers could carry delicacy, but both would reduce the current knit-gap and transparent-cloth evidence or redirect its practical event. Keep the original attentive action and emerging relief, with only the compatible muted warm palette refinement. Geothermal and winter-expedition directions do not serve this spring workshop.'}}
for p in [first,knit1,knit2,sheer,palette,color1,color2]:assert p in prompt
(P/'composed-stage2-authored.json').write_text(json.dumps(composed,ensure_ascii=False,indent=2)+'\n');(P/'prompt_en.txt').write_text(prompt+'\n')
plan={'status':'not_run','source_generation':'a7fd58162695c7c23a9257ac89b13434e94e6899fc3891858b837636ad1ced6c','pack_id':pack['pack_id'],'new_applied_sources':['spf_sf104_2','spring_sf057_02'],'actual_selected_new_ids':['bundle:spf_sf104_2_bundle','visual-concept:spring_sf057_02'],'associated_color_profile':'spring_sf104_2','associated_color_profile_hard_activation':False,'authority':'Supplemental all-of new-candidate review separate from exact runtime hard_gates. New knit profile has its independently selected opt-in native gate.',
'rows':[
{'id':'warm_bundle_owner','candidate_id':'bundle:spf_sf104_2_bundle','relation_id':'existing_wearer_scope','owners':['same woman','her blouse','her skirt'],'success':'Both separately bounded garments belong to the same pictured woman.','failure':'A garment on another figure, sample or background cannot donate this evidence.','status':'not_run'},
{'id':'warm_bundle_hue','candidate_id':'bundle:spf_sf104_2_bundle','component_id':'component_1','relation_id':'sf104_2_relation_1','owners':['peach blouse surface','mushroom skirt surface'],'success':'Both actual garment surfaces carry closely related muted warm tones within one image.','failure':'Global warm cast, saturated opposing colors or one hidden garment fails; partial is fail.','status':'not_run'},
{'id':'warm_bundle_boundaries','candidate_id':'bundle:spf_sf104_2_bundle','component_id':'component_2','relation_id':'sf104_2_relation_2','owners':['blouse hem','skirt waistband'],'success':'Both real cloth boundaries remain distinct and readable in the same region and image.','failure':'A flat print, hidden seam or missing edge is UNOBSERVABLE_NOT_PASS.','status':'not_run'},
{'id':'new_knit_topology','candidate_id':'visual-concept:spring_sf057_02','component_id':'part_1','owners':['outer ivory vest yarn paths','true knit gaps'],'success':'Connected opaque yarn paths physically bound multiple actual holes on the same vest.','failure':'Printed diamonds, dark filled areas or unresolved yarn continuity fail.','status':'not_run'},
{'id':'new_knit_under_surface','candidate_id':'visual-concept:spring_sf057_02','component_id':'part_2','owners':['outer vest opaque yarn','separate peach blouse visible through holes'],'success':'The lower blouse surface is owned separately and visible through true gaps while yarn remains opaque.','failure':'A flat combined print, missing lower owner or obscured cells fails.','status':'not_run'}],'all_of_policy':'Every row for a selected new meaning must pass in the one returned image; no component averaging across images or labels.'}
(P/'selected-new-candidate-observation-plan.json').write_text(json.dumps(plan,ensure_ascii=False,indent=2)+'\n')
print(json.dumps({'composed_path':str(P/'composed-stage2-authored.json'),'prompt_sha256':h,'words':len(prompt.split()),'new_selected_ids':plan['actual_selected_new_ids'],'total_visual_opt_in':2,'associated_color_profile_hard_activation':False},indent=2))
