import json,pathlib,hashlib
p=pathlib.Path(__file__).parent
pack=json.loads((p/'candidate_pack.json').read_text())[0]; core=pack['authorial_core']; lock=core['intent_lock']; baseline=core['baseline_prompt_en']
extra=' Use a vertical portrait frame with a narrow band of floor beneath the boots and open breathing room above the hair. Position the distant window mullions so their receding rhythm converges behind the chrome chair, leaving the cape outline against a broad quiet window pane. A normal focal length and level camera preserve the garment proportions.'
prompt=baseline+extra
review=json.loads((p/'embodiment_review.json').read_text()); review['provenance']='agent_postcomposition'; review['prompt_sha256']=hashlib.sha256(prompt.encode()).hexdigest(); review['summary']+=' The final vertical crop retains hands and feet, window geometry stays behind actor and chair, level normal-lens view preserves contact legibility.'
chosen=['slot:subject_framing:full_body_framing','slot:composition:strong_leading_lines_vanish']
ev={chosen[0]:'Use a vertical portrait frame with a narrow band of floor beneath the boots and open breathing room above the hair.',chosen[1]:'Position the distant window mullions so their receding rhythm converges behind the chrome chair, leaving the cape outline against a broad quiet window pane.'}
clar=[]
for x in pack['semantic_clarification']['candidates']:
 required=x.get('required_in_final_prompt',False)
 clar.append({'clarification_id':x['id'],'decision':'applied' if required else 'rejected','rationale':'Preserve independently frozen cape presentation and reference usage.' if required else 'Raised underarm and continuous dress interpretations conflict with low arm cape-over-trousers staging.','prompt_evidence':'The photograph presents the actual drape and construction of the garment as its visual center.' if required else ''})
dec=[]
for x in pack['creative_augmentation']['candidates']:
 d={'candidate_id':x['id'],'decision':'transformed' if x['id'] in chosen else 'rejected','rationale':'Clarify garment outline and maintain complete physical contact visibility.' if x['id'] in chosen else 'The proposed pose, crop or viewpoint obscures or changes the frozen hem contact.'}
 if x['id'] in chosen:d.update(artistic_interpretation='Use terminal geometry to support an inspectable garment presentation.',transformation='Translate the abstract camera idea into specific floor margin and window alignment around the cape.',affected_dimensions=['framing' if x['id']==chosen[0] else 'composition'],prompt_evidence=ev[x['id']])
 dec.append(d)
c={'pack_id':pack['pack_id'],'composer':'agent','prompt_en':prompt,'negative_en':pack['negative_en'],'chosen_candidate_ids':chosen,'chosen_visual_concept_ids':[],'candidate_interpretations':[],'authorial_core_binding':{'source_authorial_core_sha256':core['canonical_sha256'],'source_intent_lock_sha256':lock['canonical_sha256'],'preserved_anchor_ids':[x['anchor_id'] for x in lock['semantic_anchors']],'preserved_evidence':['She wears a burgundy wool cape with clearly shaped shoulder seams','The cape front, shoulder construction, wool texture, lifted hem edge and complete trouser silhouette remain readable.','Tall ferry-terminal windows show a subdued sea horizon.'],'authorial_decisions':[{'dimension':'framing','decision':ev[chosen[0]],'rationale':'Keep grounded support and complete cape silhouette inspectable.'},{'dimension':'composition','decision':ev[chosen[1]],'rationale':'Architecture supports the garment outline without competing with its drape.'}]},'semantic_clarification_decisions':clar,'creative_augmentation_brief':{'decisions':dec},'embodiment_review':{'source_contract_sha256':pack['embodiment_preflight']['canonical_sha256'],'review':review}}
(p/'composed_prompt.json').write_text(json.dumps(c,ensure_ascii=False,indent=2)+'\n'); (p/'prompt.txt').write_text(prompt)
(p/'exposure-selection.json').write_text(json.dumps({'pack_id':pack['pack_id'],'new_mep_slots_exposed':[],'new_mep_profiles_exposed':[],'bundles_exposed':[],'visual_concepts_exposed':[x['id'] for x in pack['visual_concept_candidates']['candidates']],'chosen_visual_concept_ids':[],'chosen_candidate_ids':chosen,'new_data_exposure':'fail','new_data_selection':'none','reason':'The actual pack exposed no mep candidates; unrelated underarm and dress concepts rejected. New profile pixel qualification cannot be claimed.'},indent=2))
