import json,pathlib,hashlib,subprocess,datetime
p=pathlib.Path(__file__).parent.resolve(); pack=json.loads((p/'candidate_pack.json').read_text())[0]; c=json.loads((p/'composed_prompt.json').read_text()); r=json.loads((p/'runtime_request.json').read_text()); img=p/'generated_images/cape-lookbook.png'; sha=hashlib.sha256(img.read_bytes()).hexdigest()
obs={'embodiment_body_ownership':'pass|The two visible hands connect to the same cape-clad model; two trouser legs terminate in her two boots.','embodiment_joint_chain_and_reach':'pass|On screen left her right forearm runs naturally from the cape opening to the adjacent hem, with a relaxed wrist and small thumb-index pinch. Left forearm hangs beside her hip.','embodiment_support_and_balance':'pass|Both separated boot soles touch the concrete floor, with grounded contact shadows and the torso balanced above the stance.','embodiment_contact_and_space':'pass|The right thumb and index meet the burgundy edge, which curves back into the hanging cape. Both hand boundaries stay distinct and the chair frame is visibly separated from the boots.','embodiment_visibility_and_projection':'pass|The full-length frontal image includes fingers at the lifted hem, opposite hand, both complete boots and their floor contacts; cape cloth occlusion is locally legible.'}
rev={'schema_version':'moe-render-review/v1','contract_version':'photo-embodiment-preflight/v1','pack_id':pack['pack_id'],'reviewer':'independent_agent_arm_a','result_image':str(img),'result_sha256':sha,'review_scales':['overall frame','native 1086x1448 original image'],'hard_gates':{k:{'status':v.split('|')[0],'evidence':v.split('|')[1]} for k,v in obs.items()},'user_judgment':{'baseline_available':False,'genuinely_moe':'pending','better_than_baseline':'not_applicable','source':'not_yet_received','evidence':''}}
(p/'pixel-review.json').write_text(json.dumps(rev,indent=2))
supp={'evaluation':'partial_is_fail','result_image':str(img),'result_sha256':sha,'new_mep_profile_pixel_qualification':'not_exercised_no_profile_exposure_or_selection','focal_contract_coverage':'missing_typed_garment_aware_profile_or_assertion; supplemental frozen testcase only','checks':{'garment':{'status':'pass','evidence':'Burgundy cape, shoulder seam on screen left, wool surface, curved hem, charcoal trousers and black boots visible.'},'garment_aware':{'status':'pass','evidence':'Cape dominates the center, front and broad drape are readable and hand lift exposes edge behavior.'},'interaction':{'status':'pass','evidence':'Model right hand on screen left lightly pinches outer hem; shallow curved hanging fold visible.'},'body':{'status':'pass','evidence':'Both arms emerge from side openings; grounded boots and chair clearance visible.'},'setting':{'status':'pass','evidence':'Ferry Departures sign, terminal windows, sea, distant coast and a ferry make location clear.'},'light':{'status':'fail','evidence':'Cool window illumination and warm floor/wall light are visible, but a localized warm reflection on a garment edge is not distinct enough to pass the declared garment owner/scope.'},'reference':{'status':'pass','evidence':'Long dark wavy center-parted hair, eyes, oval facial shape and lip proportions visually correspond to the source portrait; this is visual comparison only.'}},'overall_testcase_status':'fail','user_judgment':'not_yet_received','limitations':['No mep profile was exposed or selected; neither generation nor existing slot selection qualifies new model-editorial data.','Strict focal semantic contract coverage is absent for agent-owned garment-aware keyword, recorded as a workflow gap; only embodiment has derived hard gates.','No controlled baseline comparison; cannot infer causal benefit of new data.','One image call only; no retry.']}
(p/'supplemental-pixel-review.json').write_text(json.dumps(supp,indent=2))
meta={'tool':'image_gen.imagegen','image_call_count':1,'native_source_path':'/Users/chasoik/.codex/generated_images/01a09536-240a-7180-82bc-4b4ffb87b9ab/exec-08dacd95-9c7e-4099-9ea7-ea03b05c8841.png','saved_result':str(img),'result_sha256':sha,'native_dimensions':[1086,1448]};(p/'image-result.json').write_text(json.dumps(meta,indent=2))
args=['.venv/bin/python','skills/photo-prompt-image-generator/scripts/record_image_run.py','--ts',datetime.datetime.now(datetime.timezone.utc).isoformat(),'--concept',json.loads((p/'request_envelope.json').read_text())['request_text'],'--prompt-en',c['prompt_en'],'--negative-en',c['negative_en'],'--seed','4078680847','--attempt','1','--status','success','--image-path',str(img),'--tool','image_gen.imagegen','--pack-id',pack['pack_id'],'--chosen-candidate-ids-json',json.dumps(c['chosen_candidate_ids']),'--chosen-visual-concept-ids-json','[]','--composer','agent','--audit-status','pass','--arm-id','arm-a','--worktree-id',str(p),'--skill-sha256',hashlib.sha256(pathlib.Path('skills/photo-prompt-image-generator/SKILL.md').read_bytes()).hexdigest(),'--source-ref','sha256:0715804477870cb410c752af4d4e5a6eabaee3822c7424795cbb15dcb32b4a82','--candidate-pack-version','v6','--authorial-core-sha256',pack['authorial_core']['canonical_sha256'],'--intent-lock-sha256',pack['authorial_core']['intent_lock']['canonical_sha256'],'--reference-sha256',r['references'][0]['sha256'],'--image-call-count','1','--independent-no-cross-arm-inputs','--manifest',str(p/'run_manifest.json'),'--ledger',str(p/'image_runs.ndjson')]
x=subprocess.run(args,text=True,capture_output=True);(p/'record-image-run-output.json').write_text(x.stdout); print('recorder',x.returncode,x.stderr,x.stdout[:1000])
print('image_sha256',sha)
