import json,pathlib,hashlib,shutil
p=pathlib.Path(__file__).parent
src=p.parent/'request_envelope.json'; assert hashlib.sha256(src.read_bytes()).hexdigest()=='781e27722b64802d0de2131949b23290a9c37bfda5185467264353d53f1ded9e'
shutil.copyfile(src,p/'request_envelope.json'); env=json.loads(src.read_text()); span=env['active_spans'][0]['text']
baseline='Photograph an adult fashion model in her late twenties, using the supplied portrait as the visual reference for her face and long dark wavy hair. Create a garment-aware fashion lookbook photograph in a quiet coastal ferry terminal. She wears a burgundy wool cape with clearly shaped shoulder seams and a curved lower hem over charcoal tapered trousers and polished black ankle boots. She stands upright with both boot soles planted on the dry concrete floor, feet comfortably apart, and her torso facing the camera. Her right hand emerges through the cape arm opening and gently pinches a small section of the right outer hem between thumb and index finger, holding it a few inches outward; the lifted cloth hangs in a shallow curved fold back toward her right thigh. Her left arm hangs naturally through the left arm opening with the hand visible beside her hip. The cape front, shoulder construction, wool texture, lifted hem edge and complete trouser silhouette remain readable. A single chrome folding chair stands beside her with a clear gap between its frame and her boots. Tall ferry-terminal windows show a subdued sea horizon. Cool skylight defines the burgundy wool, while a small warm side reflection touches one garment edge. Frame her full length with floor beneath both boots, balanced architecture, lifelike skin texture and a calm direct gaze. The photograph presents the actual drape and construction of the garment as its visual center.'
core={'contract_version':'photo-authorial-core/v3','provenance':'agent_prepack','source_request':env['request_text'],'interpreted_intent':'User requests independent randomized complex image test concepts, reference-based prompts, generation and literal pixel verification. This arm independently chooses a garment-aware cape lookbook in a coastal ferry terminal; randomized choices are agent-owned.','subject':'An adult model in her late twenties with face and long dark wavy hair visually referenced to the attachment','setting':'Quiet coastal ferry terminal with sea horizon and chrome folding chair','event':'Standing model gently lifts a small section of her cape hem to exhibit drape','visual_priorities':['Garment construction and drape stay readable','Reference face and long dark wavy hair remain visually recognizable','Plausible fingers, arm openings, planted boots and cloth contact'],'baseline_prompt_en':baseline,'user_definitions':[],'interpretation_provenance':[{'term':'independent randomized complex reference-image test','source_text':span,'basis':'request_context','resolution':'Independently design and freeze an agent-owned test concept, use the supplied image as visual reference, generate once and assess actual pixels.','sources':[]}],'unresolved_ambiguities':[],'user_exclusions':[],'runtime_forbidden_labels':[],'intent_lock':{'contract_version':'photo-intent-lock/v1','priority':'requesting_user','semantic_anchors':[{'anchor_id':'core_concept','source_text':span,'dimension':'concept','prompt_evidence':'Create a garment-aware fashion lookbook photograph in a quiet coastal ferry terminal.'},{'anchor_id':'core_subject','source_text':span,'dimension':'subject','prompt_evidence':'Photograph an adult fashion model in her late twenties'},{'anchor_id':'core_event','source_text':span,'dimension':'event','prompt_evidence':'Her right hand emerges through the cape arm opening and gently pinches a small section of the right outer hem between thumb and index finger'},{'anchor_id':'reference_use','source_text':span,'dimension':'reference_use','prompt_evidence':'using the supplied portrait as the visual reference for her face and long dark wavy hair'}],'locked_dimensions':['concept','subject','event','reference_use'],'open_dimensions':['framing','composition','lighting','camera']},'semantic_assertions':[],'request_lineage':None,'style':{'domain':'fashion photography','family':'garment-aware lookbook','evidence':['complete trouser silhouette','cape shoulder construction and wool drape']},'variation_key':'arm-a-4078680847'}
def review(prompt,provenance):
 vals={'body_ownership':('One model owns both hands, feet and the cape.',['Her right hand emerges through the cape arm opening','Her left arm hangs naturally through the left arm opening']), 'joint_chain_and_reach':('Right arm reaches an adjacent hem section with a small outward displacement, left arm rests.',['holding it a few inches outward','with the hand visible beside her hip']), 'support_and_balance':('Stationary upright stance has separated feet and both soles grounded.',['both boot soles planted on the dry concrete floor','feet comfortably apart']), 'contact_and_space':('Thumb and index contact the cape edge, cloth returns toward thigh, chair has clearance.',['between thumb and index finger','a clear gap between its frame and her boots']), 'visibility_and_projection':('Full-length frontal view exposes both hands and boots plus garment drape.',['her torso facing the camera','Frame her full length with floor beneath both boots'])}
 return {'contract_version':'photo-embodiment-review/v1','provenance':provenance,'prompt_sha256':hashlib.sha256(prompt.encode()).hexdigest(),'scope':'body_action','summary':'Adult human standing in grounded full-length pose, lightly pinching own cape hem with right hand.','checks':{k:{'status':'supported','reason':v[0],'prompt_evidence':v[1]} for k,v in vals.items()}}
files={'authorial_core.json':core,'embodiment_review.json':review(baseline,'agent_prepack'),'test-case.json':{'provenance':'agent_prepack','seed':4078680847,'keywords':['garment-aware fashion lookbook','burgundy wool cape','garment construction and readable drape','hem pinch','coastal ferry terminal','cool skylight and warm edge reflection','reference face and long wavy hair'],'required_pixel_checks':{'garment':'Burgundy wool cape, shaped shoulders, curved hem and charcoal tapered trousers visible together','garment_aware':'Framing and pose expose garment front, shoulder construction and drape; fashion presentation is visual center','interaction':'Right thumb and index visibly pinch small right outer hem section, shallow fold runs to right thigh, no implausible hand or cloth fusion','body':'Both hands correctly connected through cape openings; both boot soles on floor; chair clear of boots','setting':'Terminal architecture and window with visible sea horizon','light':'Cool broad illumination and localized warm garment-edge reflection','reference':'Face and long dark wavy hair visibly correspond to supplied reference; no authentication claim'},'evaluation':'partial_is_fail','user_judgment':'not_yet_received'}}
for n,x in files.items(): (p/n).write_text(json.dumps(x,ensure_ascii=False,indent=2)+'\n')
(p/'baseline_prompt.txt').write_text(baseline)
names=['request_envelope.json','authorial_core.json','embodiment_review.json','test-case.json','random-design.json','baseline_prompt.txt']
(p/'prepack-checksums.json').write_text(json.dumps({n:hashlib.sha256((p/n).read_bytes()).hexdigest() for n in names},indent=2)+'\n')
print((p/'prepack-checksums.json').read_text())
