from pathlib import Path
import json,hashlib,re,datetime,copy
v=Path(__file__).resolve().parent
raw=json.loads((v/'candidate_pack.json').read_text()); assert isinstance(raw,list) and len(raw)==1
p=raw[0]; core=p['authorial_core']; details=json.loads((v/'selected_candidate_details.json').read_text()); byid={r['id']:r['candidate'] for r in details['candidates']}
# Own previous contract shape is reused; all retest selections and source bindings are replaced.
c=json.loads((v.parent/'composed_prompt.json').read_text())
baseline=(v/'baseline_prompt.txt').read_text(); first=baseline.split('The main impression is')[0].rstrip()
finish='The main impression is a compact-digital snapshot. Here near subjects receive direct frontal flash: her cheek and satin folds have crisp bright edges, with a short sharp floor shadow behind her skates and a dimmer rink. Slow-sync flash freezes one sharp body while a faint continuous exposure trail follows her moving sleeve and wheels toward screen left. Small cyan LEDs in the skate wheels leave short horizontal light streaks toward screen left behind the flash-frozen wheels; fixed rails and counter edges stay still. Dark image regions carry digital noise across the wall and shadowed sleeves and chest folds of her slate jacket. Dark image regions contain irregular brightness speckle, fine random light/dark pixels visibly scattered over those jacket gradients. Small colored speckles appear within dark image regions, including tiny green and magenta flecks in the same shaded jacket folds; speckles remain separate from large object colors. The speckle remains an image-plane artifact overlaying satin, rather than a woven pattern. Keep jacket shadows open enough to read this noisy texture. Noise fades into the bright face; skin texture, satin reflections and floor contact remain readable.'
prompt=first+' '+finish; negative=p['negative_en']; sha=lambda s:hashlib.sha256(s.encode()).hexdigest()
chosen=['bundle:pe_bundle_compact_direct_flash','slot:grain_profile:pe_digital_luma_noise','slot:motion:pe_flash_core_shutter_trace','integration:environment_binding','integration:event_timing']
profiles=['visual-concept:pe_compact_flash_noisy_finish_relation','visual-concept:pe_digital_chroma_noise_relation','visual-concept:pe_digital_luma_noise_relation']
assert all(i in byid for i in chosen+profiles)
c.update(pack_id=p['pack_id'],prompt_en=prompt,negative_en=negative,chosen_candidate_ids=chosen,chosen_visual_concept_ids=profiles)
c['candidate_interpretations']=[
 {'candidate_id':chosen[0],'artistic_interpretation':'The farewell glance belongs to a nearby flash portrait with a dim rink and a shared digital shadow texture.','transformation':'Translate all four bundle components to the woman and rink wall, with sparse green and magenta pixels crossing her slate satin shadows.','prompt_evidence':'her cheek and satin folds have crisp bright edges, with a short sharp floor shadow behind her skates and a dimmer rink','component_evidence':{'component_1':'near subjects receive direct frontal flash: her cheek and satin folds have crisp bright edges','component_2':'Dark image regions carry digital noise across the wall and shadowed sleeves and chest folds of her slate jacket','component_3':'Small colored speckles appear within dark image regions, including tiny green and magenta flecks in the same shaded jacket folds','component_4':'speckles remain separate from large object colors'},'relation_evidence':{}},
 {'candidate_id':chosen[1],'artistic_interpretation':'The digital shadow field must visibly cross satin gradients rather than remain confined to a noisy wall.','transformation':'Specify random pixel brightness fluctuations on jacket shadows, alongside an image-plane ownership phrase that excludes a woven material reading.','prompt_evidence':'fine random light/dark pixels visibly scattered over those jacket gradients','relation_evidence':{'effect_owner':'The speckle remains an image-plane artifact overlaying satin, rather than a woven pattern'}},
 {'candidate_id':chosen[2],'artistic_interpretation':'A single flash-frozen skater remains distinct from earlier moving sleeve and wheel exposure.','transformation':'Retain the passed cyan wheel light streaks trailing toward screen left behind the sharp skate endpoints and stationary rink architecture.','prompt_evidence':'Small cyan LEDs in the skate wheels leave short horizontal light streaks toward screen left behind the flash-frozen wheels','relation_evidence':{'effect_owner':'Small cyan LEDs in the skate wheels leave short horizontal light streaks toward screen left behind the flash-frozen wheels; fixed rails and counter edges stay still'}},
 {'candidate_id':chosen[3],'artistic_interpretation':'The bright nearby subject shares the floor with her short cast shadow and a dimmer rink.','transformation':'Bind the frontal flash to the satin highlights and a specific shadow behind the grounded skates.','prompt_evidence':'a short sharp floor shadow behind her skates and a dimmer rink'},
 {'candidate_id':chosen[4],'artistic_interpretation':'This glance happens during the final lap and carries the farewell through her ongoing glide.','transformation':'Keep the authored return counter, slow forward momentum and spontaneous smile as the visible event phase.','prompt_evidence':'She glides left to right through her last slow lap, turning her head toward her rink-edge friend who is taking this photograph'}
]
vo={
 'pe_compact_flash_noisy_finish_relation':{'component_1_phrase':'near subjects receive direct frontal flash: her cheek and satin folds have crisp bright edges','component_2_phrase':'Dark image regions carry digital noise across the wall and shadowed sleeves and chest folds of her slate jacket'},
 'pe_digital_chroma_noise_relation':{'component_1_phrase':'Small colored speckles appear within dark image regions, including tiny green and magenta flecks in the same shaded jacket folds','component_2_phrase':'speckles remain separate from large object colors'},
 'pe_digital_luma_noise_relation':{'component_1_phrase':'Dark image regions contain irregular brightness speckle, fine random light/dark pixels visibly scattered over those jacket gradients','component_2_phrase':'The speckle remains an image-plane artifact overlaying satin, rather than a woven pattern'}
}
c['visual_obligation_evidence']=vo
c['coverage_assertions']={row['text']:[row['text']] for row in p['mandatory_intents']}
c['authorial_core_binding']={'source_authorial_core_sha256':core['canonical_sha256'],'source_intent_lock_sha256':core['intent_lock']['canonical_sha256'],'source_authorship_policy_sha256':p['authorial_composition']['authorship_policy']['canonical_sha256'],'preserved_anchor_ids':p['intent_preservation']['required_anchor_ids'],'preserved_evidence':[],'authorial_decisions':[
 {'dimension':'style','decision':'Expose fine luma and green/magenta chroma texture over both wall and shaded satin folds, with a quieter flash-bright face.','rationale':'The original advisory digital-noise test failed where jacket shadows stayed smooth; this intensifies visibility within its original style scope.','prompt_evidence':'Dark image regions contain irregular brightness speckle, fine random light/dark pixels visibly scattered over those jacket gradients'},
 {'dimension':'lighting','decision':'Keep jacket shadows open while retaining hard frontal flash and a dimmer rink.','rationale':'Readable shadow gradients expose image-plane noise without replacing satin reflections or floor shadows.','prompt_evidence':'Keep jacket shadows open enough to read this noisy texture'},
 {'dimension':'camera','decision':'Preserve cyan wheel light streaks behind the flash-frozen endpoints and stable counter and rails.','rationale':'This open-dimensional realization passed the original shutter-trace criteria and covers moving ambient light units.','prompt_evidence':'Small cyan LEDs in the skate wheels leave short horizontal light streaks toward screen left behind the flash-frozen wheels'}]}
selected_profile_ids={i.removeprefix('visual-concept:') for i in profiles}; clarification=[]
for row in p['semantic_clarification']['candidates']:
 active=row.get('required_in_final_prompt') or row.get('profile_id') in selected_profile_ids
 decision={'clarification_id':row['id'],'decision':'applied' if active else 'rejected','rationale':'Retain original requester-owned anchors and the explicitly selected authorial editing definition.' if active else 'This optional alternate visual proposition adds unrelated action, emphasis or genre to the frozen roller-rink test; keep the existing direction.'}
 if active: decision['prompt_evidence']=next(iter(vo[row['profile_id']].values())) if row.get('profile_id') else 'A photographic scene of a fictional adult woman in a candid moment'
 clarification.append(decision)
c['semantic_clarification_decisions']=clarification
c['creative_augmentation_brief']={'decisions':[{'candidate_id':r['id'],'decision':'rejected','rationale':'Keep the same whole-body skate-contact, readable reference-guided face and restrained farewell direction; this candidate adds no necessary improvement for the original three-effect retest.'} for r in p['creative_augmentation']['candidates']]}
ctx=json.loads((v/'contextual_candidate_details.json').read_text())['candidates']; contextual=[]
reason_map={
 'same_adult_target_coordinated_gaze':('relevant','The existing returned glance supports attention to her friend, but turning the entire body toward the camera weakens the ongoing rightward glide; retain baseline expression.','Retain the modest head turn, smile and forward skating stance without adopting a new axis candidate.'),
 'pfe_cleavage_candidate':('irrelevant','A central chest contour does not help the returning glance, flash/noise or wheel-trace test; subtle attraction is already carried by smile and satin swing.','Not adopted.'),
 'ctx_c096':('potential','A fitted T-shirt and jeans could carry ordinary warmth at sensual one, but replacing satin removes the common flash-and-shadow testing surface.','A future open wardrobe alternative could replace trousers and top with jeans and a fitted T-shirt while retaining a satin outer layer; this retest keeps the original wardrobe.'),
 'vulnerable_glamour':('potential','A quieter caught expression could support a close farewell at the same intensity, but the unguarded smile already serves the friend relationship.','A future expression-only refinement could soften the smile; retain the easy smile here.')}
for row in ctx:
 reading,reason,application=reason_map[row['id'].split(':')[-1]]; contextual.append({'candidate_id':row['id'],'reading':reading,'reason':reason,'proposed_application':application,'requirement_evidence':[]})
c['adult_appeal_brief']['contextual_review']=contextual
c['adult_appeal_brief']['contextual_comparison']='At the same sensual one/fetish zero strengths, coordinated gaze supports the head turn but full body rotation weakens the glide; T-shirt and jeans remove the reflective common test surface; vulnerable glamour shifts an easy farewell into a more directed register; chest-contour emphasis distracts from glance and motion. The original unguarded smile, satin swing and chest-height view remain coherent.'
# Physical action, agency and axis realization retain the exact same own baseline.
c['embodiment_review']['source_contract_sha256']=p['embodiment_preflight']['canonical_sha256']; review=c['embodiment_review']['review']; review['prompt_sha256']=sha(prompt)
for check in review['checks'].values():
 for phrase in check['prompt_evidence']: assert phrase in prompt, phrase
for i in chosen:
 assert byid[i].get('applicability',{}).get('status','eligible')=='eligible'
for name,obj in [('composed_prompt.json',c),('postcomposition_embodiment_review.json',review),('pack_normalized_core.json',core)]: (v/name).write_text(json.dumps(obj,ensure_ascii=False,indent=2)+'\n')
(v/'prompt.txt').write_text(prompt); (v/'negative.txt').write_text(negative)
case=json.loads((v/'pre_render_test_case.independent.json').read_text()); case.update({'revision':'v2','source_independent_case_sha256':hashlib.sha256((v/'pre_render_test_case.independent.json').read_bytes()).hexdigest(),'prepared_v2_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'pack_id':p['pack_id'],'pack_file_sha256':hashlib.sha256((v/'candidate_pack.json').read_bytes()).hexdigest(),'prompt_sha256':sha(prompt),'negative_sha256':sha(negative),'chosen_candidate_ids':chosen,'chosen_visual_concept_ids':profiles,'profile_activation_source':'Explicit composer_opt_in; all gates active; no invented requester obligations','selected_profile_contracts':[byid[i]['opt_in_contract'] for i in profiles],'generic_embodiment_required_checks':p['embodiment_preflight']['required_checks'],'binary_rule':'PARTIAL is FAIL. Original three effects and all selected profile/physical/reference criteria must pass. User acceptance remains pending.'})
(v/'pre_render_test_case.json').write_text(json.dumps(case,ensure_ascii=False,indent=2)+'\n')
exposed=[r for r in json.loads((v/'composer_view.json').read_text())['candidate_catalog'] if ':pe_' in r['id']]
(v/'editing_exposure.json').write_text(json.dumps({'revision':'v2','pack_id':p['pack_id'],'actual_emitted_packs':1,'snapshot_invocation_emitted_packs':0,'new_editing_exposed_ids':[r['id'] for r in exposed],'chosen_candidate_ids':chosen,'chosen_visual_concept_ids':profiles,'selected_profile_activation':'Explicit optional selection; bundle associated IDs do not activate profiles','selected_details_sha256':hashlib.sha256((v/'selected_candidate_details.json').read_bytes()).hexdigest()},ensure_ascii=False,indent=2)+'\n')
print('word_count',len(re.findall(r"[A-Za-z0-9]+(?:[-'][A-Za-z0-9]+)*",prompt))); print('prompt_sha256',sha(prompt)); print(prompt)
