from pathlib import Path
import json,hashlib,datetime
v=Path(__file__).resolve().parent
p=json.loads((v/'candidate_pack.json').read_text())[0]; c=json.loads((v/'composed_prompt.json').read_text()); a=json.loads((v/'composed_audit.json').read_text()); image=v/'generated_original.png'; image_sha=hashlib.sha256(image.read_bytes()).hexdigest(); reviewed=datetime.datetime.now(datetime.timezone.utc).isoformat()
region=lambda x,y,w,h:{'x':x,'y':y,'width':w,'height':h,'scale':'native','source_size':[1237,1272]}
physical={
 'embodiment_body_ownership':{'status':'pass','evidence':'One sharp adult body connects the visible head, shoulders, two arms and two trousered legs to two skate boots. The translucent exposure behind her outward sleeve remains attached to that same arm, with no detached extra limb.'},
 'embodiment_joint_chain_and_reach':{'status':'pass','evidence':'The returned head tilt connects continuously through neck and shoulders to the forward glide. Both knee chains bend above the staggered skate boots; the extended arm has a plausible shoulder-elbow-wrist chain.'},
 'embodiment_support_and_balance':{'status':'pass','evidence':'The near wheels of both quad skates touch the common polished floor, with tiny contact shadows and cyan reflections beneath them. Staggered skates under bent knees and a loose balancing arm support this slow coast.'},
 'embodiment_contact_and_space':{'status':'pass','evidence':'Boots, trucks and wheels have readable boundaries and meet the floor rather than float. The clear lane beside the rental counter offers forward space; the torso and hands do not intersect the counter.'},
 'embodiment_visibility_and_projection':{'status':'pass','evidence':'The image retains the full body, both skate structures and their floor contacts, while the turned face and balancing hand remain readable. Perspective scales the nearer skate naturally; leftward light trails remain beside stable rails and counter edges.'}}
noise_evidence='Tiny irregular brightness fluctuations and sparse green/magenta flecks are visible on the dark rear wall, shaded outer sleeve and jacket-front satin gradients. Similar fine speckles also cross the dark trouser and counter fields, while the flash-bright face is comparatively quieter.'
profile={
 'vo_pe_compact_flash_noisy_finish_relation_1':{'status':'pass','evidence':'The near woman has frontal cheek/nose sheen, bright short transitions on satin folds and a bright tank against the substantially dimmer rink. Both skates have crisp floor shadows extending a short distance behind the wheels.'},
 'vo_pe_compact_flash_noisy_finish_relation_2':{'status':'pass','evidence':noise_evidence},
 'vo_pe_digital_chroma_noise_relation_1':{'status':'pass','evidence':'The unscaled left-sleeve crop shows tiny green, magenta and other colored dots within its dark satin folds. The same small colored dots appear in dark wall and counter fields; bright facial regions have much fewer.'},
 'vo_pe_digital_chroma_noise_relation_2':{'status':'pass','evidence':'The sparse green/magenta flecks remain small isolated variations superimposed over the slate jacket and dark wall colors. They do not merge into the broad cyan wheel light streaks, violet stars, pink sign border or other large object colors.'},
 'vo_pe_digital_luma_noise_relation_1':{'status':'pass','evidence':'Native wall and sleeve crops show fine irregular light/dark flecks across otherwise smooth dark regions. The shaded sleeve bowl and jacket front contain this fine brightness texture while their larger folds and satin highlights remain independently readable.'},
 'vo_pe_digital_luma_noise_relation_2':{'status':'pass','evidence':'Fine irregular speckling is shared by unrelated dark image surfaces: rear wall, satin shadows, trousers and counter. It crosses satin gradients without regular woven direction and fades across the bright face, supporting a tonal image-plane reading rather than only textile weave or skin pores.'}}
reference={'gate_id':'b_face_hair_scope','status':'pass','scope':'Visible face/hair appearance guidance only','evidence':'The inspected source and fictional generated adult woman share a short dark bob, fine parted forehead bangs, softly rounded facial contour, dark eyes and naturally pink lips. The smile, head tilt, loose ends and camera distance vary with the authored rink moment. This qualifies appearance guidance only, never identity authentication.','reference_sha256':'06d6c6feeed0d2397ec9562d46113cd221ac54a0e190295f0aa7f7868c22ece7','regions':[region(520,20,250,300)]}
original_case=json.loads((v/'pre_render_test_case.independent.json').read_text())
effects=[
 {'gate_id':'b_direct_flash','status':'pass','component_results':[{'criterion':original_case['effects'][0]['criteria'][0],'status':'pass','evidence':'The cheek and nose show a frontal sheen; shiny satin ridges have short bright transitions against shadowed fold bowls.'},{'criterion':original_case['effects'][0]['criteria'][1],'status':'pass','evidence':'Both cyan-lit skates cast sharp short floor shadows behind their wheels. The large empty rink remains substantially dimmer than the nearby woman.'}],'regions':[region(520,20,250,300),region(215,410,370,270),region(290,920,640,320)]},
 {'gate_id':'b_slow_sync_trace','status':'pass','component_results':[{'criterion':original_case['effects'][1]['criteria'][0],'status':'pass','evidence':'One sharp principal woman, hands, face and skate boots remain readable.'},{'criterion':original_case['effects'][1]['criteria'][1],'status':'pass','evidence':'Translucent sleeve exposure trails extend continuously toward screen left behind the outward arm. Cyan wheel lights leave aligned leftward horizontal trails attached to the sharp wheel endpoints.'},{'criterion':original_case['effects'][1]['criteria'][2],'status':'pass','evidence':'Rental-counter lip, return lettering and distant rail edges remain stationary and readable rather than sharing the wheel streak direction.'}],'regions':[region(150,310,420,335),region(290,920,640,320),region(790,300,447,620)]},
 {'gate_id':'b_digital_noise','status':'pass','component_results':[{'criterion':original_case['effects'][2]['criteria'][0],'status':'pass','evidence':'Native wall and jacket crops show small irregular light/dark variations over the dark rear field, sleeve bowl and shaded jacket front. Fine speckle coexists with independently readable satin folds.'},{'criterion':original_case['effects'][2]['criteria'][1],'status':'pass','evidence':'Tiny sparse green and magenta colored flecks are visible in dark wall, extended sleeve shadows and jacket-front folds; they are distinct from satin sheen and large cyan/violet light features.'},{'criterion':original_case['effects'][2]['criteria'][2],'status':'pass','evidence':'The bright cheeks and forehead are visibly quieter than the peppered dark sleeve, trousers, rear wall and return-counter panels; facial structure and surface variation remain readable.'}],'regions':[region(250,105,225,200),region(215,410,370,270),region(475,310,285,300),region(520,20,250,300)]}
]
editing={'contract_version':'photo-editing-native-pixel-review/v1','revision':'v2','pack_id':p['pack_id'],'reviewer':'independent_arm_b_agent_native_pixel_review','reviewed_utc':reviewed,'result_image':str(image),'result_sha256':image_sha,'source_pre_render_case_sha256':hashlib.sha256((v/'pre_render_test_case.json').read_bytes()).hexdigest(),'original_three_effect_criteria_preserved':True,'assertion_origin':'Advisory authorial test choices, not requester-required scene assertions','partial_is_fail':True,'effects':effects,'reference_result':reference,'physical_result':physical,'selected_profile_result':profile,'strict_all_of':{'status':'pass','effect_pass_count':3,'effect_total':3,'selected_profile_pass_count':6,'selected_profile_gate_total':6,'generic_embodiment_pass_count':5,'generic_embodiment_gate_total':5,'reference_pass_count':1,'reference_total':1,'fail_count':0,'technical_outcome':'visual_technical_qualified_user_judgment_pending'},'limitations':['A native image can exhibit these visible effects but cannot establish actual camera hardware, ISO, sensor type, numeric shutter speed or editing/capture history.','Face/hair guidance does not establish identity, biometric equivalence, personal traits or body similarity.','Some larger satin mottling coexists with the fine visible speckle and weakens the clean satin impression; the tested fine brightness/chroma field remains readable.','No requesting-user acceptance or comparative preference has been received.']}
visual={'schema_version':'moe-render-review/v1','contract_version':'photo-visual-obligations/v1','pack_id':p['pack_id'],'reviewer':'independent_arm_b_agent_native_pixel_review','result_image':str(image),'result_sha256':image_sha,'reviewed_utc':reviewed,'review_scales':['native_1237x1272','whole_frame','unscaled_native_pixel_crops'],'effective_visual_contract_sha256':a['effective_visual_contract_sha256'],'hard_gates':{**profile,**physical},'user_judgment':{'source':'not_yet_received','baseline_available':True,'genuinely_moe':'pending','better_than_baseline':'pending','evidence':'The own v1 image is preserved, but no direct requesting-user acceptance or comparative preference has been received.'},'supplemental_editing_review_file':'editing_pixel_review.json','supplemental_reference_review':reference,'supplemental_whole_image_observation':{'label_free_initial_impression':'A close, brightly lit skater smiles back during a final glide through a dim rental rink. Blue wheel streaks pull left from a sharp body, while peppered dark fabric and wall surfaces make the digital finish conspicuous.','strengths':['The returning smile links the adult woman with the nearby off-frame photographer.','Both skate-floor contacts, continuous leftward wheel traces and attached sleeve exposure remain readable.','The rental skates and return counter locate the farewell moment.','Fine brightness/chroma texture now visibly crosses dark wall and shaded satin.'],'weaknesses':['Larger mottled patches coexist with fine noise on the satin sleeve and make the fabric look less clean.','The posed-looking front-facing smile and polished bright facial treatment soften the spontaneous compact-digital impression.'],'control_calibration':'The same subtle warmth and ordinary self-directed glide fit frozen sensual one/fetish zero. This qualitative visual reading is separate from measured intensity and user preference.'},'inspection_assets':[{'path':'native-review-jacket-sleeve.png','source_region':region(215,410,370,270)},{'path':'native-review-jacket-chest.png','source_region':region(475,310,285,300)},{'path':'native-review-dark-wall.png','source_region':region(250,105,225,200)},{'path':'native-review-skate-contact.png','source_region':region(290,920,640,320)}],'inspection_method':'View preserved original pixels and unscaled sips crops; no pixel-editing or image enhancement; original file byte hash retained.'}
for name,obj in [('editing_pixel_review.json',editing),('visual_pixel_review.json',visual)]: (v/name).write_text(json.dumps(obj,ensure_ascii=False,indent=2)+'\n')
print(json.dumps(editing['strict_all_of'],indent=2))
