from pathlib import Path
import json,hashlib,copy
p=Path(__file__).parent
pack=json.loads((p/'candidate_pack.json').read_text())[0]; core=pack['authorial_core']; lock=core['intent_lock']
prompt=core['baseline_prompt_en']+' Keep a narrow margin below both elbows so the lower frame reveals the full tray support. Shape the silver reflection into a long pale rectangle bounded by a darker edge, separating the cuff silhouette from her illuminated skin.'
clar=[]
for row in pack['semantic_clarification']['candidates']:
 req=row.get('required_in_final_prompt')
 clar.append({'clarification_id':row['id'],'decision':'applied' if req else 'rejected','rationale':'Preserves independently frozen jewelry subject reference and tray interaction.' if req else 'This optional concept changes the frozen jewelry photograph into unrelated staging or a medium effect.','prompt_evidence':'a product-led jewelry campaign photograph' if req else ''})
com={'pack_id':pack['pack_id'],'composer':'agent','prompt_en':prompt,'negative_en':pack['negative_en'],'chosen_candidate_ids':['slot:lighting:softbox','slot:subject_framing:upper_body_framing'],'chosen_visual_concept_ids':[],'candidate_interpretations':[{'candidate_id':'slot:lighting:softbox','artistic_interpretation':'The light modifier reveals the jewelry surface boundary instead of merely flattering the portrait.','transformation':'Shape one pale rectangular reflection beside a dark edge on the cuff.','prompt_evidence':'Shape the silver reflection into a long pale rectangle bounded by a darker edge'},{'candidate_id':'slot:subject_framing:upper_body_framing','artistic_interpretation':'The framing explains the tray support while giving the cuff a readable silhouette.','transformation':'Place a narrow margin under the connected elbows so wrist ownership remains visible.','prompt_evidence':'Keep a narrow margin below both elbows so the lower frame reveals the full tray support'}],'authorial_core_binding':{'source_authorial_core_sha256':core['canonical_sha256'],'source_intent_lock_sha256':lock['canonical_sha256'],'preserved_anchor_ids':[r['anchor_id'] for r in lock['semantic_anchors']],'preserved_evidence':['a product-led jewelry campaign photograph','one 28-year-old adult woman','lifting it a few centimeters above the tabletop'],'authorial_decisions':[{'dimension':'framing','decision':'Keep a narrow margin below both elbows so the lower frame reveals the full tray support.','rationale':'Showing support makes the hand mechanism assessable.'},{'dimension':'lighting','decision':'Shape the silver reflection into a long pale rectangle bounded by a darker edge.','rationale':'The tonal edge clarifies the actual cuff silhouette and material.'}]},'semantic_clarification_decisions':clar,'creative_augmentation_brief':{'decisions':[{'candidate_id':r['id'],'decision':'rejected','rationale':'The baseline already establishes product scale and precise hands; this optional idea does not materially improve that test.'} for r in pack['creative_augmentation']['candidates']]},'semantic_assertion_evidence':{'source_contract_sha256':pack['semantic_assertion_obligations']['canonical_sha256'],'evidence':{r['assertion_id']:r['frozen_evidence'] for r in pack['semantic_assertion_obligations']['obligations']}}}
review=copy.deepcopy(json.loads((p/'embodiment_review.json').read_text())); review['provenance']='agent_postcomposition';review['prompt_sha256']=hashlib.sha256(prompt.encode()).hexdigest(); review['summary']='Reread complete final prompt: baseline two-handed tray geometry retained; added elbow margin improves support visibility and controlled cuff reflection changes only lighting.'
com['embodiment_review']={'source_contract_sha256':pack['embodiment_preflight']['canonical_sha256'],'review':review}
(p/'composed_prompt.json').write_text(json.dumps(com,ensure_ascii=False,indent=2)+'\n')
(p/'prompt_en.txt').write_text(prompt)
(p/'adoption.json').write_text(json.dumps({'pack_id':pack['pack_id'],'new_mep_exposure':[],'bundles_exposed':[],'new_mep_selected':[],'other_visual_profiles_exposed':[r['id'] for r in pack['visual_concept_candidates']['candidates']],'chosen_visual_concept_ids':[],'chosen_candidate_ids':com['chosen_candidate_ids'],'finding':'new model/editorial product keywords not exposed; frozen baseline preserved; no forced injection'},indent=2)+'\n')
